### ISSUE TITLE
Support CodeSandbox?

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#8193] opened 2018-11-14 16:44 UTC
This involves adding a file `sandbox.config.json` to the new app / addon blueprints and ensuring that `app.css` exists (even if empty).

@mike-north Correct?

This would enable any app / addon to automatically run in codesandbox.io.

It would also enable people to use ember-cli/ember-new-output and/or ember-cli/ember-addon-output as a project starter blueprint in codesandbox.

Does this need an RFC written?

**Comment by mike-north** [comment] 2018-11-23 14:17
> @mike-north Correct?

Sort of. This work is already tracked, so we may not need another issue. The main things that are needed are

- [ ] #8172 - Ensure that https://github.com/ember-cli/ember-new-output #master represents the latest beta or stable release of ember-cli. It's currently possible for it to be in a wierd state, whenever a release is not accompanied by a new beta (I filed what I feel is a bug - #8168, but @Turbo87 @kellyselden may feel that the current behavior is as intended).
- [ ] #8081 - Ember-cli shouldn't fail to build in the absence of app/styles
- [x] https://github.com/codesandbox-app/codesandbox-importers/pull/16 - Ensure that the presence of `ember-cli` as a dependency indicartes that a CSB project is treated as a `node` sandbox
- [x] Livereload proxying fixes that are present in e-cli-inject-livereload v1.8

> Does this need an RFC written?

Doubt it, as there's exactly one clear path forward, and the hard work has already been done.

Once #8172 is resolved in a reasonable way, I can complete work on [`ember-twiddle-eject`](https://github.com/mike-north/ember-twiddle-eject) which will allow people to turn twiddles into full ember projects. These projects will inherently be supported by codesandbox.

**Comment by locks** [comment] 2020-04-12 20:28
Closing since the work is being tracked elsewhere as mentioned above!

**Closed by locks** 2020-04-12 20:28 UTC
Labels: enhancement
