### ISSUE TITLE
.coffee files no longer generated for components and routes

### ISSUE THREAD

**Issue by andorov** [ember-cli/ember-cli#5127] opened 2015-11-18 18:59 UTC
Just upgraded to `1.13.12` from `1.13.8`.  `ember g ...` now by default creates an `.emblem` file instead of `.hbs` (thank you!), but has reverted to creating `.js` files instead of `.coffee`.  This is only for components and routes - models and controllers still work.  In addition, it now also fails when trying to add a new route to the router -

    installing route
      create app/routes/blah.js
      create app/templates/blah.emblem
    ENOENT, no such file or directory '<my path>/app/router.js'
    Error: ENOENT, no such file or directory '<my path>/app/router.js'

Using -

    "ember-cli-coffeescript": "^1.13.0"

**Comment by stefanpenner** [comment] 2015-11-18 19:06
@trabus got a sec to take alook?

**Comment by trabus** [comment] 2015-11-18 20:48
Will take a look in a few, @andorov what commands were you running specifically?

**Comment by stefanpenner** [comment] 2015-11-18 21:01
@andorov can we also have a reproduction example in a public repo?

**Comment by andorov** [comment] 2015-11-18 22:44
Repo [here](https://github.com/andorov/ember-cli-test).  The only two packages I've added are `ember-cli-coffeescript` and `ember-cli-emblem`.  The `.coffee` (and `.hbs`) files are generated when only coffee is installed, but after I also add emblem I get `.js` and `.emblem` - although test files are `.coffee`.  I believe the only package version that changed when this behavior started was `ember-cli`.

    ember g route foo-bar/index
    ember g component foo-bar/index-item

Also I noticed that with `ember-cli-emblem` installed I can get away with `ember g component foo`.  It bypasses the warning about requiring a hyphen in component names.

**Comment by trabus** [comment] 2015-11-19 05:04
@androv I just created a new repo with ember-cli `1.13.13`, installed `ember-cli-coffeescript` and `ember-cli-emblem`, and was unable to reproduce the errors you reported. I would suggest upgrading to `1.13.13`. 

However, the issue with `.coffee` and `.js` files being generated is due to the two addons conflicting. The behavior you're seeing is due to `ember-cli-emblem`'s blueprint winning out over `ember-cli-coffeescript`. Currently there is no way to reconcile between the two, since they both override the default blueprints, only one can win.

We're working on making blueprints more composable, but in the mean-time, it may be necessary to create an alternate set of blueprints that combine the two.

**Comment by andorov** [comment] 2015-11-19 15:00
Makes sense.  I do see the same thing with `1.13.13`.

Thanks!

**Comment by trabus** [comment] 2015-11-21 05:59
I'm going to go ahead and close this for now, as it is technically just a side effect cause by limitations of the current state of blueprints.

**Closed by trabus** 2015-11-21 05:59 UTC
Labels: needs-implementation
