### ISSUE TITLE
Track broken appveyor

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#6735] opened 2017-01-30 20:22 UTC
It breaks on git checkout

```
Build started
git clone -q --branch=master https://github.com/ember-cli/ember-cli.git C:\projects\ember-cli
git checkout -qf 09742793e81a464609a97ba7b3b05ed0e484758e
The item was not found or does not exist.
```

**Comment by stefanpenner** [comment] 2017-01-30 23:27
very strange..

**Comment by Turbo87** [comment] 2017-01-31 21:09
@kellyselden can you contact the AppVeyor support? Last time they were quite responsive.

**Comment by stefanpenner** [comment] 2017-02-01 00:12
https://twitter.com/stefanpenner/status/826583864491417600

**Comment by FeodorFitsner** [comment] 2017-02-01 00:23
Could you drop a link corresponding to that build please? We'd need to check its webhook payload too (feel free to email it). Have you tried re-trying this commit from UI?

**Comment by FeodorFitsner** [comment] 2017-02-01 00:32
Looking at the error I'd think it's not `git` command that generates it, but rather the thing going next to it - build cache.

Can you try disabling build cache and see if that helps?

**Comment by Turbo87** [comment] 2017-02-01 00:39
@FeodorFitsner are you talking about https://github.com/ember-cli/ember-cli/blob/master/appveyor.yml#L24-L26?

**Comment by FeodorFitsner** [comment] 2017-02-01 00:40
yep

**Comment by Turbo87** [comment] 2017-02-01 20:14
@FeodorFitsner that seems to "solve" the issue, but it would be unfortunate to lose the ability to use caching... 😕

**Comment by FeodorFitsner** [comment] 2017-02-01 20:19
Sure. Now try bringing cache back, but this time with dependencies, like:

```yaml
cache:
  - '%LOCALAPPDATA%\Yarn' -> yarn.lock
  - '%APPDATA%\Roaming\bower' -> package.json
```

**Comment by Turbo87** [comment] 2017-02-01 20:26
https://ci.appveyor.com/project/embercli/ember-cli/build/11780/job/x9we74almdk9p4cr

nope...

testing this in https://github.com/ember-cli/ember-cli/issues/6740 in case you hadn't seen yet

**Comment by FeodorFitsner** [comment] 2017-02-01 20:48
Can you please try putting bower cache only?

**Comment by FeodorFitsner** [comment] 2017-02-01 20:57
Also, please try cleaning up project cache via REST API: https://www.appveyor.com/docs/build-cache/#rest-api

**Comment by Turbo87** [comment] 2017-02-01 21:03
> Can you please try putting bower cache only?

well, the problem is that we don't actually have a `bower.json` file and I have to admit I'm not quite sure why we're actually the Bower stuff.

**Comment by FeodorFitsner** [comment] 2017-02-01 21:05
OK, then leave yarn cache only, but clean up project cache via API before trying it again.

**Comment by Turbo87** [comment] 2017-02-01 21:28
@FeodorFitsner I've deleted the cache now using the REST API and restarted the failed build above, but I'm seeing the same error as before.

**Comment by FeodorFitsner** [comment] 2017-02-01 23:29
OK, I've just cleared the cache from here. Can you try once again please?

**Comment by Turbo87** [comment] 2017-02-01 23:39
@FeodorFitsner seems to be running, thanks

**Comment by FeodorFitsner** [comment] 2017-02-01 23:41
OK then. Let's see if that happens again. Might have been some temp glitch.

**Comment by Turbo87** [comment] 2017-02-01 23:43
Thanks for your help! I'll close this issue for now and will reopen if we should hit the same problem again.

**Closed by Turbo87** 2017-02-01 23:43 UTC
