### ISSUE TITLE
Custom command line args passed to blueprint generation not in options object as expected

### ISSUE THREAD

**Issue by JonForest** [ember-cli/ember-cli#7125] opened 2017-06-13 06:11 UTC
The docs (https://ember-cli.com/api/classes/Blueprint.html#method_locals) specify that custom command line args passed to blueprint generate will appear in the `{entity: {options: {customArg: value}}}` object.

E.g.
```
ember generate controller foo --type=array --dry-run
```
generates
```
{
  entity: {
    name: 'foo',
    options: {
      type: 'array'
    }
  },
  dryRun: true
}
```
Inside of the `locals` hook `options` argument.

However, when developing my own blueprint, I get the following output:
```
> ember g model-crud bob --model=person
The option '--model' is not registered with the generate command. Run `ember generate --help` for a list of supported options.
installing model-crud
{ target: '/Users/jonathanh/mediasuite/tmp/my-first-blueprint',
  entity: { name: 'bob', options: {} },
  ....
  model: 'person'
}
```

So the information is still available, but is not in the location the docs would suggest.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.12.0
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
zsh: command not found: yarn
```

**Comment by locks** [comment] 2020-03-31 16:17
Duplicate of https://github.com/ember-cli/ember-cli/issues/8200. Thanks!

**Closed by locks** 2020-03-31 16:17 UTC
