### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#5040] opened 2015-11-05 07:59 UTC
Hi 

Getting the following:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:7357/testem.js' with computed SHA-256 integrity 'lh8NuSGzYSb6XpdfBYsEglnfxBdd6LpuYybvxZC97fM='. The resource has been blocked.
```

With:

```
DEBUG: -------------------------------
ember.debug.js:5240 DEBUG: Ember             : 2.1.0
ember.debug.js:5240 DEBUG: Ember Data        : 2.1.0
ember.debug.js:5240 DEBUG: jQuery            : 1.11.3
ember.debug.js:5240 DEBUG: Ember Simple Auth : 1.0.0
ember.debug.js:5240 DEBUG: -------------------------------
```

Have searched the open bugs and not found anything pertaining to this.

Is anyone aware of an issue here?

Cheers

**Comment by rwjblue** [comment] 2015-11-05 11:38
This is fixed on master, but you can add 

    integrity=""

To the script tag loading testem.js in tests/index.html

**Closed** 2015-11-05 14:47 UTC

**Comment by blazeeboy** [comment] 2016-01-05 00:32
@stefanpenner May i ask why this bug is closed? i faced it in my app blazeeboy/devtools#26 
i made a workaround by adding `integrity=""` but i can't find the root cause or a related commit that solved it, any hints?

**Comment by stefanpenner** [comment] 2016-01-05 02:05
> i made a workaround by adding integrity=""

this is the solution, and new ember apps ship with on testem.js script tag.

**Comment by sheriffderek** [comment] 2016-04-03 05:47
Just for the record - and for people upgrading or still hitting this:  Recently upgraded an app from 2.0 to 2.4. Ran into this error. testem.js already had the `integrity=""` though. There was an SHA-256 string in the `/assets/my-app.js` `integrity ='asdfsa'` though... and when I removed the string the app would load.

**Comment by borisrorsvort** [comment] 2016-04-17 19:59
Its happening again indeed. Ember version 2.4.1

**Comment by stefanpenner** [comment] 2016-04-17 20:22
> Its happening again indeed. Ember version 2.4.1

I do not believe to be the case (having just upgraded several apps, without issue), have you followed the instructions?

**Comment by borisrorsvort** [comment] 2016-04-17 20:25
I mean its working with integrity="". But is it the solution ?

**Comment by stefanpenner** [comment] 2016-04-17 20:41
> I mean its working with integrity="". But is it the solution ?

yes

**Comment by ziali088** [comment] 2016-07-05 10:08
I've ran into this issue when building my application in production mode, the contents of `dist/index.html` show that the sri hashes were generated for all the javascript/css files, eg

`<script src="assets/vendor-9d6efb5c3b35b8a645637f53779d1d7c.js" integrity="sha256-EtU1Rm2XQeNj0QMonA9FMqK26HZYnKb4TkyZfvSWQ= sha512    -C40xcfgWFRIEi0RbQhA/2WMo6ripG2fJksLw9noG5+khSL+a8nWVPwOKKmBWdGmvOXY99HecZvpu/SGtSGhxrQ==" ></script>`

I'm using
Ember 2.6.0
Ember-CLI 2.4.2
Ember-CLI-SRI 2.1.0

**Comment by nathanhammond** [comment] 2016-07-05 20:52
@ziali088 I don't think that you're talking about the same issue. If you still believe what you're encountering is a bug open a new issue and explain your problem from the beginning (including expected behavior and actual results). I suspect however that you're not triggering a bug and you'd be better served by dropping by [#-ember-cli](https://embercommunity.slack.com/archives/-ember-cli).

**Comment by The-Don-Himself** [comment] 2017-01-06 02:37
@ziali088 Don't know if you ever solved your issue but I also ran into the same error messages while in production I'm on the latest Chrome (Version 55). Took a while but the problem was due to having Cloudflare settings Auto-minify css and js on, which is the default. Turning those off solved the issue, since my resources were already minified at source anyway.

@nathanhammond @rwjblue should this be documented/pointed out that external elements could also lead to this exact issue other that integrity="" ?

**Comment by miolae** [comment] 2017-06-20 13:39
I've got the same issue except a bit. I've generated the code with `ember build -prod` and placed it to the hosting.
Now I can visit the site with Chrome Desctop, but there is the error when I'm visiting the site with Chrome Mobile. How shoul I generate production version which will work in all modern browsers?
