### ISSUE TITLE
ENOENT, no such file or directory '/home/kana/dev/update_111/tmp/concat_with_maps-input_base_path-UkLqV7Bb.tmp/0/bower_components/web-animations-js/src/scope.js'

### ISSUE THREAD

**Issue by Kanabanarama** [ember-cli/ember-cli#6517] opened 2016-12-03 02:52 UTC
I'm getting an ENOENT error in ember serve after updating web-animations-js from 1.0.6 to 1.0.8. I included it in ember-cli-build.js:
```
app.import('bower_components/web-animations-js/web-animations-next.min.js');
```
The error I'm seeing is:

```
Error: ENOENT, no such file or directory '/home/kana/dev/update_111/tmp/concat_with_maps-input_base_path-UkLqV7Bb.tmp/0/bower_components/web-animations-js/src/scope.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at SourceMap.<anonymous> (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:282:29)
    at Array.map (native)
    at SourceMap._resolveSourcesContent (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:275:27)
    at SourceMap._assimilateExistingMap (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:248:63)
    at SourceMap.<anonymous> (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:219:12)
    at SourceMap._cacheEncoderResults (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:125:16)
    at SourceMap._addMap (/home/kana/dev/update_111/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:218:10)
```

Output from `ember version --verbose && npm --version`:
```
version: 1.13.15
http_parser: 2.3
node: 0.12.17
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1u
npm: 2.14.10
os: linux x64
2.15.1
```

What could be the problem here?

**Comment by nathanhammond** [comment] 2016-12-03 07:01
I believe that you don't need to prefix this with `bower_components`. Also, the file location may have changed inside of the bower package.

I'm closing this issue as very likely not a bug (otherwise there would be tremendous outcry). In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. Also, we would require you to upgrade to the most recent version of Ember CLI and get a reproduction there as we're not releasing any additional patch releases for the 1.13 series.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) for help with things like this! We've got a lot of wonderful people who can help with configuration. 😄

**Closed by nathanhammond** 2016-12-03 07:01 UTC
