### ISSUE TITLE
Using both LESS and SASS?

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli#6328] opened 2016-10-07 17:28 UTC
I'm running into a problem of using both LESS and SASS.

The app is trying to use 2 addons: one uses LESS and other uses SASS. Both are trying to write to `app.css` via `app.less` and `app.scss`. This creates a conflict when both of them tries to write to `app.css`.

**Comment by nathanhammond** [comment] 2016-10-07 19:49
We don't recommend or have a way to default make this play nicely inside of Ember CLI. This functionality is provided by addons which register preprocessors and must be updated to be aware of each others' existence so that they don't clobber each others' output.

This isn't an Ember CLI concern except that we should have better APIs to make this easier for addons to accomplish. Efforts for that are already underway.

I'm closing this issue as not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Ember CLI issues are not a good support forum. Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) for things like this and ask what people in the community are doing to work around things like this.

**Closed by nathanhammond** 2016-10-07 19:49 UTC

**Comment by stefanpenner** [comment] 2016-10-07 20:09
@ming-codes I suspect we can't support this out of the box, in-theory a custom little broccoli method or two could do this manually....

**Comment by ming-codes** [comment] 2016-10-07 20:40
> in-theory a custom little broccoli method or two could do this manually....

@stefanpenner Yea, I suspected that as well. I thought I could just string `ember-cli-less` and `ember-cli-sass` together and it would work, but turns out I need to build my own plugin.
