### ISSUE TITLE
EBUSY: resource busy or locked, symlink

### ISSUE THREAD

**Issue by parivajk** [ember-cli/ember-cli#7574] opened 2018-01-24 09:11 UTC
Hi, I created a brand new Ember project with no manual changes in either generated files.
What I did:
ember new myprojectname
cd myprojectname
npm install
ember build
I am running this a company pc so I have elevated privileges and I am running the cmd as such user.
Can someone please advice how to address this issue under windows 7.

---

Output from `ember version --verbose && npm --version && yarn --version`:
ember-cli: 2.17.2
http_parser: 2.7.0
node: 6.12.3
v8: 5.1.281.111
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2n
os: win32 x64
3.10.10
```
Build failed.
Build Error (Funnel)

EBUSY: resource busy or locked, symlink 'C:\myprojectfolder\tmp\broccoli_persistent_filterbabel__babel_ember_data-output_path-1OYPVy
4s.tmp' -> 'C:\myprojectfolder\tmp\funnel-output_path-KMQ1M9nA.tmp\modules'
```

**Comment by rwjblue** [comment] 2018-02-04 20:37
I'm not familiar with this specific error, but some quick research shows that it generally points to some sort of other system issue (e.g. out of space).

**Comment by rwjblue** [comment] 2018-02-04 20:38
I am also fairly confused why you opened a new issue, when the previous issue you opened for this is still open...

Closing as a duplicate of #7544

**Closed by rwjblue** 2018-02-04 20:38 UTC
