### ISSUE TITLE
Ember CLI prints stack trace on fresh clone (with no node_modules)

### ISSUE THREAD

**Issue by wycats** [ember-cli/ember-cli#6168] opened 2016-08-10 18:06 UTC
Running `ember s` on a freshly cloned repo, before running npm install, produces:

```
$ ember s
Could not require 'ember-cli-build.js': Cannot find module 'broccoli-merge-trees'
Error: Could not require 'ember-cli-build.js': Cannot find module 'broccoli-merge-trees'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Code\spec\ember-cli-build.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I think, it should print a nicer error, instructing the user to run `npm install`.

**Comment by rwjblue** [comment] 2016-08-10 18:13
Hmm. If no node_modules is present (like when you freshly clone) we do emit a much more friendly error. Was your node_modules partially populated? Can you provide specific steps to reproduce?

**Comment by Turbo87** [comment] 2016-08-11 12:00
closing this as a duplicate of https://github.com/ember-cli/ember-cli/issues/5711

**Closed by Turbo87** 2016-08-11 12:00 UTC
