### ISSUE TITLE
Question: How to turn off SourcemapConcat?

### ISSUE THREAD

**Issue by bucaran** [ember-cli/ember-cli#4520] opened 2015-07-24 08:51 UTC
I would like to turn off `SourcemapConcat`, but I have no idea where this can be done.

Due to the lack of instrumentation at the `ember-cli`, `broccoli` or plugin level (don't know where to look really) I can't explain why my team are having horribly long 30s to 1 minute delay gaps between "tasks" (like concat, babel, linting, merge trees, etc.) so I would like to turn this feature off to help me on my hunt.

Thanks

**Comment by kennethkalmer** [comment] 2015-07-27 07:04
Possible duplicate of #4460? This is driving me nuts as well.

**Comment by bucaran** [comment] 2015-07-27 09:56
@kennethkalmer Both issues are related, but this is not a duplicate, I just want to know the magical instruction that turns them off.

This is just sourcemaps:

```js
emberCliConfig.sourcemaps = { enabled: false, extensions: ['js','css'] }
```

**Comment by stefanpenner** [comment] 2015-07-27 17:05
@bucaran the related docs are [here](http://www.ember-cli.com/user-guide/#asset-compilation)

> Due to the lack of instrumentation at the ember-cli, broccoli or plugin level (don't know where to look really) I can't explain why my team are having horribly long 30s to 1 minute delay gaps between "tasks" (like concat, babel, linting, merge trees, etc.)

Ya this is rough, I have attempted to explain in the [previous issue](https://github.com/ember-cli/ember-cli/issues/4460). I am likely explaining poorly, but have been making progress eliminating the issue (stay tuned: I am actively working to continue to upstream all my fixes).

If all works out well, shortly you wont need to explain at all. :)

> so I would like to turn this feature off to help me on my hunt.

Unfortunately, disabling the feature will likely not result in improvements

**Comment by stefanpenner** [comment] 2015-07-30 16:21
I believe the question was [answered](http://www.ember-cli.com/user-guide/#source-maps).

Future questions should likely be directed to StackOverflow, as it is a much better venue for Q/A interactions.

**Closed by stefanpenner** 2015-07-30 16:21 UTC
