### ISSUE TITLE
ember addon foo-bar -- Generates incorrect Brocfile.js

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#2893] opened 2015-01-05 21:40 UTC
The `Brocfile.js` that is generated is actually from the `app` blueprint not `addon`.

**Comment by stefanpenner** [comment] 2015-01-12 16:20
@rwjblue got time to fix?

**Comment by stefanpenner** [comment] 2015-01-12 20:45
appears fixed on master.

**Closed** 2015-01-12 20:45 UTC
Labels: bug

**Comment by stefanpenner** [comment] 2015-01-12 20:49
although i am unsure when or how it was fixed...

@rwjblue @jakecraige @abuiles any one remember what fixed this?

**Comment by jakecraige** [comment] 2015-01-13 15:07
I have no clue, but I also just tested and it's broken in 0.1.6 but fixed on master.

**Comment by jakecraige** [comment] 2015-01-13 15:13
I was going to bisect it but I can't even reproduce it. Tried checking out and nom'ing 0.1.5 and 0.1.6, it always works for me...

**Comment by john-griffin** [comment] 2015-01-13 15:26
Had this problem too. Tried nom'ing 0.1.6. Generated addon with fresh 0.1.6. `Brocfile.js` is still from app blueprint and the addon folders are still missing.

**Comment by jakecraige** [comment] 2015-01-13 15:44
Lol this isn't terribly useful. But here's the results of my bisect.. 

![1__tmux](https://cloud.githubusercontent.com/assets/3799709/5723301/a97fa70a-9b08-11e4-9001-450dbfab1f5b.png)

my test was this

```
ember addon my-addon
ember s
```

and having `ember s` not error out. The majority of the time it was the assertion error

**Comment by john-griffin** [comment] 2015-01-14 11:53
I still get the problem in 0.1.7.

**Comment by rwjblue** [comment] 2015-01-14 12:00
@john-griffin - Can you `npm uninstall -g ember-cli && npm cache clear && npm install -g ember-cli`  and try again?

**Comment by john-griffin** [comment] 2015-01-14 12:09
@rwjblue I still have the issue after using that exact command.

**Comment by rk1** [comment] 2015-01-14 13:02
I am still getting this problem with 0.1.7 as well. Tried cleaning the cache, reinstalling ember-cli, even a different machine.

It seems to work on master though. After I cloned & linked it, I created a new addon - got the correct Brocfile, directory structure and was able to serve it.

    version: 0.1.7-master-2e0a0e88dc
    node: 0.10.35
    npm: 2.1.8

**Comment by jakecraige** [comment] 2015-01-14 14:07
lets track this over in #2980
