### ISSUE TITLE
Can't name route `components` anymore

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#5744] opened 2016-04-05 14:26 UTC
I have an private ember add-on which runs ember `1.13.x`. I tried to upgrade it to `2.4.x`.

The add-on uses pods and has the following component:

```
addon/components/my-component/template.hbs
addon/components/my-component/component.js
```

The add-on uses pods and has a dummy app. The dummy app has a route named `/components/my-component` to showcase the component. The following files are needed:

```
dummy/components/my-component/template.hbs
dummy/components/template.hbs
```

Back in `1.13.x` this was supported OK.
Switching to `2.4.x` result in my add-on dummy app to break (the tests also break)

**Comment by stefanpenner** [comment] 2016-04-05 15:16
I don't believe this is an ember-cli issue, rather something in ember or the resolver. Ultimately though, im not entirely sure the root cause.

Also, as per the CONTRIBUTING.md (which is link provided by the big yellow banner when you submit an issue), you should provide additional information yet. So someone who is debugging this can more quickly isolate the issue

@rwjblue any quick ideas off the top of your head?

**Comment by olivierlesnicki** [comment] 2016-04-05 15:32
@stefanpenner feel free to close and/or de-prioritize this issue if you believe it violates the contribution rules. I've proceeded to re-name all my routes to avoid the naming clash anyway.

**Comment by rwjblue** [comment] 2016-04-05 16:18
In general, I believe this should work.  I'd need more detailed error information (and likely a reproduction) to be able to dig in further...

**Comment by stefanpenner** [comment] 2016-04-05 16:21
@olivierlesnicki i don't think this violates the rules, just that some addition info, and a reproduction would be perfect.

**Comment by olivierlesnicki** [comment] 2016-04-05 16:51
https://github.com/olivierlesnicki/ember-cli-issue-5744
Try to navigate to `/components/my-component`

![image](https://cloud.githubusercontent.com/assets/1705944/14290453/0b596ff6-fb57-11e5-9349-4630d7a778bb.png)

**Comment by stefanpenner** [comment] 2016-04-05 17:40
@olivierlesnicki thank you very much for the reproduction, this will help us debug.

**Comment by stefanpenner** [comment] 2016-04-24 23:22
> @olivierlesnicki thank you very much for the reproduction, this will help us debug.

will reopen if ^ is provided

**Comment by olivierlesnicki** [comment] 2016-04-25 08:58
@stefanpenner I don't understand... The reproduction has been provided already... https://github.com/olivierlesnicki/ember-cli-issue-5744

**Comment by nathanhammond** [comment] 2016-10-31 06:32
@olivierlesnicki I'm closing this issue as we're no longer actively supporting pods as we instead head in the direction of the Module Unification RFC. Thank you for the work in tracking this down as it will likely still help people discover an edge case we don't support!

**Closed by nathanhammond** 2016-10-31 06:32 UTC
Labels: Needs Bug Verification
