### ISSUE TITLE
ember test; Building; Hangup;

### ISSUE THREAD

**Issue by holtalanm** [ember-cli/ember-cli#6099] opened 2016-07-22 15:18 UTC
Exact output from running "ember test":
```
Could not start watchman; falling back to NodeWatcher for file system events. Visit http://ember-cli.com/user-guide/#watchman for more info. â ¦ BuildingHangup
```
Project builds fine, but right after, all it says is "Hangup" and that is all. No stack trace, nothing.

Running: Ember: 2.6.3
Node: 6.2.2
Phantomjs: 2.1.1
Ubuntu: 14.04 (crouton)

I honestly have no idea what the heck is going on since there is literally no more information given to me when I try to run "ember test". If I run "ember server" it runs without ANY issue.

---

Output from ember version --verbose:
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64

```

**Comment by stefanpenner** [comment] 2016-07-22 17:23
Most likely an issue with phantomjs and testem (in your setup).

Something verbose (so share via gist) would be to run the same thing but with `DEBUG=* ember test` it may hint at something.

**Comment by holtalanm** [comment] 2016-07-22 18:03
Ran DEBUG=* ember test.  You are correct in the statement that it is verbose :)

https://gist.github.com/holtalanm/241e500e04cf645f11319d123ff55bbe

**Comment by holtalanm** [comment] 2016-07-22 18:03
accidentally closed and commented instead of just commenting.  my bad.

**Comment by stefanpenner** [comment] 2016-07-22 18:16
the file in question does not appear to contain the word `hangup`

**Comment by aholtventuretech** [comment] 2016-07-22 18:18
you know what, I think i screwed up the pipe for directing the output to file.  one minute.

**Comment by holtalanm** [comment] 2016-07-22 18:19
I think I screwed up the pipe for directing the output to file. one minute.   I'll update the gist.

**Comment by stefanpenner** [comment] 2016-07-22 18:31
ya, unfortunately that logging is insufficient likely something in testem or phantom is dying :S

**Comment by stefanpenner** [comment] 2016-07-22 18:31
@johanneswuerbach do you have any quick thoughts on this?

**Comment by lbdm44** [comment] 2016-07-23 22:39
For another datapoint, I am also seeing this same behavior when running `ember test`

```
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by mike-north** [comment] 2016-07-24 13:44
@holtalanm - any chance you're using fastboot? I have to ask because a release was cut which introduced a very similar sounding problem 1 day before you opened this ticket

**Comment by jasonmit** [comment] 2016-07-25 00:18
Confirmed as a bug in fastboot, lets use https://github.com/ember-fastboot/ember-cli-fastboot/issues/232 for tracking.

A PR is opened that should fix the issue: https://github.com/ember-fastboot/ember-cli-fastboot/pull/233

**Comment by holtalanm** [comment] 2016-07-25 14:21
Yes, I had the fastboot addon installed in my project.  Had no idea it would affect running the tests though.  Interesting.  I'm currently not even using it due to compatibility between fastboot at simple-auth, so I'll just remove it.   Good to know.  Thanks guys!

**Comment by nathanhammond** [comment] 2016-07-26 18:07
As this is an addon-only bug I'm going to close it here.

**Closed by nathanhammond** 2016-07-26 18:07 UTC
Labels: Needs Dependency Fix
