### ISSUE TITLE
config changes not picked up by development server

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli#8782] opened 2019-08-12 06:28 UTC
Likely duplicate of #8478, which has more information and a potential PR

1. Generate an ember app
1. Run `FOO=bar ember s`
1. Go to `https://localhost:4200/`
1. Run in the console `require("my-app/config/environment").default.FOO` => `undefined`
1. Add `ENV.FOO = process.env.FOO;` to `config/environment.js`
1. The file _is_ being watched, and it looks like the server rebuilt the app as expected
1. Refresh `https://localhost:4200/` (it was refreshed automatically after the build anyway)
1. Run in the console `require("my-app/config/environment").default.FOO` => still `undefined`
1. Restart the server, passing `FOO=bar` again
1. Go to `https://localhost:4200/`
1. Run in the console `require("my-app/config/environment").default.FOO` => `"bar"` as expected

It seems like this is not related to reading `FOO` from `process.env`. Changing the line to `ENV.FOO = 'bar'` seems to have the same issue.

**Comment by chancancode** [comment] 2019-09-20 08:56
Asked @rwjblue on discord, he seems to think this is a bug!

**Comment by chancancode** [comment] 2019-09-26 18:00
I think @rwjblue had confirmed that this is a bug, and it does look like it's probably the same as #8478, and it happens on OS X as well. This is affecting the tutorial, specifically [this chapter](https://octane-guides-preview.emberjs.com/release/tutorial/07-reusable-components/). When this is fixed, we can remove a bunch of steps from there.

**Comment by bertdeblock** [comment] 2024-12-16 17:33
This is still a valid issue, but I'm going to close this one as it's a duplicate of https://github.com/ember-cli/ember-cli/issues/8782 indeed.

**Closed by bertdeblock** 2024-12-16 17:33 UTC
Labels: bug, help wanted
