### ISSUE TITLE
Unknown blueprint: route

### ISSUE THREAD

**Issue by deepan83** [ember-cli/ember-cli#6116] opened 2016-07-28 08:43 UTC
ember g route post 

fails with the following,

installing route
Unknown blueprint: route

Also fails for components but works for models and mixins from a quick test

---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
os: darwin x64
```

**Comment by nathanhammond** [comment] 2016-07-28 22:29
@deepan83 It is very unlikely that this is broken otherwise we would have hundreds of bug reports by now. As a result I suspect that you have a broken npm installation and this issue is specific to your machine. Please try resetting all of your node and npm setup and start over with a brand new project.

I'm closing this issue as likely not a bug but _please feel encouraged to reopen it_ if upon further investigation on your side you discover that it may in fact be a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community.

**Closed by nathanhammond** 2016-07-28 22:29 UTC

**Comment by musaffa** [comment] 2016-08-06 16:36
@deepan83 The issue is probably related to ember-cli-emblem. See https://github.com/Vestorly/ember-cli-emblem/issues/41
