### ISSUE TITLE
Files imported via app.import are not included in production build

### ISSUE THREAD

**Issue by MartinMalinda** [ember-cli/ember-cli#6829] opened 2017-03-06 18:23 UTC
node: 7.5.0
os: darwin x64
ember-cli: 2.12.0-beta.1

Maybe but I'm missing something but imported files are only available in development build but not in production build.

```
  app.import('./bower_components/magnific-popup/dist/jquery.magnific-popup.min.js'); //not included in production build
  app.import('./vendor/plain.js'); //not included in production build

  app.import({
    production: './vendor/plain.js', //not included in production build
    development: './vendor/plain.js'
  });
```

Reproduction repo: https://github.com/MartinMalinda/ember-cli-import-issue

**Comment by Turbo87** [comment] 2017-03-07 17:42
@MartinMalinda does that happen only on the 2.12 beta or in other releases too?

**Comment by rwjblue** [comment] 2017-03-07 18:02
Does the same issue exist when you strip the leading `./` from the paths?

**Comment by MartinMalinda** [comment] 2017-03-07 18:39
@rwjblue It works correctly without `./`. It is strange that it works for dev though, It can lead to sneaky production bugs.
@Turbo87 It also does not load on 2.11, should I test on older releases as well?

I looked a few online code examples and official docs and none of them mention using `./`. But still it is quite intuitive to put the `./` there as it's also supported syntax in module importing.

**Comment by stefanpenner** [comment] 2017-03-07 18:48
@MartinMalinda thanks to checking, that def sounds like a bug then. Although a strange one...

**Comment by stefanpenner** [comment] 2017-03-07 18:48
@rwjblue should we disallow relative paths? I am quite surprised they actually work, that isn't intended...

**Comment by rwjblue** [comment] 2017-03-07 19:10
@stefanpenner - I was also very surprised that relative paths worked here.  IMO, relative paths "break" the mental model that we want folks to have which is that you are importing from some ephemeral tree that is reified just prior to final concatenation.

**Comment by rwjblue** [comment] 2017-03-07 19:10
But I totally think its a bug that we somehow treat relative paths differently between `ember b` and `ember b -prod`.

**Comment by n1ru4l** [comment] 2017-06-02 15:25
I can confirm this.
```code
ember-cli: 2.14.0-beta.2
node: 7.9.0
os: darwin x64
```

I am importing a file with an **absolute path** in an addon. With `ember build` everything is okay. When using `ember build -prod` the file is not added to the bundle.

**Comment by pzac** [comment] 2017-07-06 14:22
I'm getting the same issue with absolute paths. Is there any workaround?

**Comment by palamike** [comment] 2017-07-11 03:56
I use "./" (relative path) and it work perfectly for both dev and prod.

**Comment by afreem66** [comment] 2017-07-13 18:02
I had this same issue as well when upgrading to ember-cli 2.12.3, removing the relative path solved it though. Thanks!

**Comment by pzac** [comment] 2017-07-14 07:45
We gave up and basically replaced `App.import(foo)` with `import npm:foo`

**Comment by Turbo87** [comment] 2017-07-14 07:47
FWIW the `import()` method was only ever designed to work with paths starting with either `vendor/` or `bower_components/`. Everything else shouldn't have worked and shouldn't be used. Note though that starting in Ember CLI 2.15 it will also allow and work with `node_modules/` too.

**Comment by Turbo87** [comment] 2017-07-14 07:48
I'm closing this issues as it seems to be working as intended

**Closed by Turbo87** 2017-07-14 07:48 UTC
Labels: Bug

**Comment by pzac** [comment] 2017-07-14 08:06
It would be nice if the documentation made this clear, this issue drove us crazy

**Comment by Turbo87** [comment] 2017-07-14 08:41
@pzac pull requests welcome 😉
