### ISSUE TITLE
Kill `<base>` tag

### ISSUE THREAD

**Issue by wagenet** [ember-cli/ember-cli#2633] opened 2014-12-02 23:04 UTC
The `<base>` tag has a number of unexpected side-effects. For instance it prevents SVG urls from working correctly. We should not use them by default.

**Comment by jayphelps** [comment] 2015-01-28 21:39
Just chiming in to confirm I lost quite a few cycles trying to figure out why my svg `clip-path: url(#some-id);`'s weren't working, which it turns out is because of the `<base>`..Here's Angular's pain thread https://github.com/angular/angular.js/issues/8934

(Hopefully me adding these keywords will save someone time finding the cause)

**Comment by rwjblue** [comment] 2015-01-28 21:48
All the pieces are in place (I believe) to remove the base tag via an addon using broccoli-asset-rewrite (which was extracted from broccoli-asset-rev).  I'm happy to pair with someone on a spike if they can bring it to completion...

**Comment by jdmarshall** [comment] 2015-01-30 08:07
This is causing a great deal of trouble for me on an SVG project.  I've got symbols behaving but I can't convince Chrome to use fills no matter what.

**Comment by stefanpenner** [comment] 2015-01-30 12:45
> This is causing a great deal of trouble for me on an SVG project. I've got symbols behaving but I can't convince Chrome to use fills no matter what.

you can remove it, and manually update the urls in index.html and tests/index.html to reflect the explicit path you need.

But we do want to kill it with fire asap

**Comment by rwjblue** [comment] 2015-01-30 12:46
> But we do want to kill it with fire asap


CONFIRM

**Comment by rwjblue** [comment] 2015-01-30 17:51
To reiterate, I would love to help someone bring this home.  We could pair out the basic solution in an hour or two I think...

WE MUST KILL IT WITH :fire:

![fire](http://i.imgur.com/eN514xh.gif)

**Comment by jayphelps** [comment] 2015-01-30 17:59
I'm down to pair tonight or this weekend.

**Comment by stefanpenner** [comment] 2015-01-30 19:21
@jayphelps ill be online all weekend

**Comment by rickharrison** [comment] 2015-01-30 21:35
Let me know if you need any help with `broccoli-asset-rewrite` or something isn't working as expeted.

**Comment by rwjblue** [comment] 2015-01-30 21:46
@rickharrison - Thank you!  We definitely will keep you in the loop...

**Comment by brian-gates** [comment] 2015-02-10 20:27
Any news on this or a workaround?  I'm running into svg filter issues as well.

**Comment by stefanpenner** [comment] 2015-02-10 21:57
@brian-gates remove te base tag, and prefix paths manually

**Comment by jdmarshall** [comment] 2015-02-15 23:34
@brian-gates I'm using ember-cli, and I removed the base properties from my configuration file and svg
worked fine, except gradients.  I'm not sure if that's ember's fault or mine (learning ember and SVG at the same time turned out to be a very bad idea) so I'll leave it there.

Of course, I then discovered I had some hrefs wrong in other parts of the app and had to fix those.

**Comment by ulisesrmzroche** [comment] 2015-03-04 20:47
How do I remove base tag? I haven't found any leads on how to do it yet.

**Comment by ulisesrmzroche** [comment] 2015-03-04 20:52
Link to SO: http://stackoverflow.com/questions/28864699/how-do-i-remove-the-base-tag

**Comment by ulisesrmzroche** [comment] 2015-03-04 21:14
Ok, I just read the tests. Yeah, this needs to die today. I'll open a PR and go from there.

**Comment by chopper** [comment] 2015-03-19 17:12
We are having the same problem with an SVG project - any updates on how to best solve this?

**Comment by stefanpenner** [comment] 2015-03-19 17:19
> We are having the same problem with an SVG project - any updates on how to best solve this?

remote base href entirely, and hard-code relative paths in you index.html

**Comment by chopper** [comment] 2015-03-21 03:08
Thanks, @stefanpenner, that worked like a charm. The only thing I had to do in addition to that is update all <img> src to be absolute paths, too.

**Comment by blesh** [comment] 2015-04-10 20:20
> remote base href entirely, and hard-code relative paths in you index.html

We just tried this for a set of examples we're trying to host on GitHub pages, and We get a funky error:

```sh
Uncaught UnrecognizedURLError: /ember-nf-graph-examples/dist/
```

attn @stefanpenner

**Comment by blesh** [comment] 2015-04-10 20:21
this is for https://github.com/netflix/ember-nf-graph-examples

which should have an app at: https://netflix.github.io/ember-nf-graph-examples/dist

**Comment by Patsy-issa** [comment] 2015-04-21 22:31
2hours and a broken keyboard later I stumbled upon this issue x.x, the clip mask only shows when i m at `/` anytime i navigate away from it and tadaa it's broken, any chance to get this resolved without using hard-coded urls?

**Comment by stefanpenner** [comment] 2015-04-21 22:32
> any chance to get this resolved without using hard-coded urls?

i believe that is the only solution.

**Comment by Patsy-issa** [comment] 2015-04-21 22:39
The svg is in a component that's used all over the placed =/

**Comment by justin-hackin** [comment] 2015-04-23 14:02
Also struggling with SVG urls and base tag.  Like @blesh I am attempting to delete base tags and  hardcode urls after compiling, using a (non-root) baseURL in environment.js and get a UnrecognizedURLError.  This appears to be a game-stopper for deployment :(  Any advice on workarounds appreciated.

**Comment by kieran** [comment] 2015-04-23 16:30
:+1:

**Comment by NoiseEee** [comment] 2015-04-28 15:09
Has this issue just fallen by the wayside hoping to be forgotten? @rwjblue is this still something you are pursuing?  Real bummer to be working for 12+ weeks on something that works fine in dev but is just useless in actual deployment. Super bad taste in the mouth.

**Comment by Patsy-issa** [comment] 2015-04-28 15:14
@NoiseEee  the way we dealt with it is by disabling the base tag and using absolute urls, it's an acceptable workaround until someone gets the free time to invest in this.

On a side note would a PR adding comments next to `base` in `environment.js` be welcomed? Could save time for others that run into this issue without knowing what might have caused it (the base tag was the last thing that I thought of that was the cause).

**Comment by stefanpenner** [comment] 2015-04-28 15:20
@NoiseEee no we are well aware. The work-around although crappy works, and as we still have some bigger fish to fry, this isn't hasn't been tackled yet.

At some point, hopefully soon, we will circle back.

Until then, much conversation and proposed solutions have come up. A valiant community member who's itch this scratches could use this knowledge to solve the problem much sooner.

**Comment by stefanpenner** [comment] 2015-04-28 15:21
@Patsy-issa sounds very reasonable

**Comment by justin-hackin** [comment] 2015-04-28 16:54
After hours of struggling, I finally figured out that rootURL seems to be useless without baseURL in environment.js .  Anyone attempting to use a non-root url + no base tag, I found out that specifying rootURL in the router.js to be the ticket to success.  It is rather hackish though because I need to toggle comment it out between dev and production builds @blesh

**Comment by jdmarshall** [comment] 2015-04-28 20:47
@justin-hackin And that works with SVG?

**Comment by justin-hackin** [comment] 2015-04-29 15:28
@jdmarshall, yes, my project is SVG and depends heavily on clip paths' relative urls.  

I also found out that to remedy the pain in the behind in changing your absolute URLS in index.html (for non-root url apps) between prod/dev, you can use this: https://www.npmjs.com/package/ember-cli-replace

I found the regex searches didn't work properly though so I had to do "@@assets/.... in index.html along with in Broccfile.js
```
var config = require('./config/environment')(process.env.EMBER_ENV) ;

var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var app = new EmberApp({
  replace: {
    files: [
      'index.html'
    ],
    patterns: [{
      match: 'assets',
      replacement: config.rootURL + 'assets' // replaces "@@foo" to "bar"
    }]
  }
});
```

**Comment by skylar** [comment] 2015-07-02 08:06
+1 for this one. Since my app is embedded in a rails app, not having a base tag really tripped me up for quite a while.

Related: https://github.com/rwz/ember-cli-rails/issues/98

**Comment by lightblade** [comment] 2015-07-10 22:47
Does the `<base>` tag still have any use after the app gets loaded (but before booting)?

I found that resources that's already loaded after `<base>` tag is removed does not get reloaded with new path. But new DOM nodes added after `<base>` tag is removed uses new path.

So as a possible workaround, we can do something like this:

```javascript
Ember.Component.extend({
  tagName: 'svg',

  init() {
    this._super(arguments);

    Ember.$('head base').remove();
  }
});
```

The downside to this is if you have additional resources that needs to be loaded after the `<base>` tag is removed, it'll use the incorrect path.

**Comment by jlarkin85** [comment] 2015-09-28 16:12
<img width="993" alt="screen shot 2015-09-28 at 12 10 49 pm" src="https://cloud.githubusercontent.com/assets/14295994/10141342/fc891b2e-65d9-11e5-9858-44bbc153edf5.png">

**Comment by ianpetzer** [comment] 2015-12-08 06:14
I managed to get my SVG's working by using the ideas at https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2

Basically I prepend the base url to the id in the svg use tag:

    <svg class="svg-icon-dims">  
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://localhost:4200/trip/delta-explorer#category--icon"></use>
    </svg>

**Comment by KennedyTedesco** [comment] 2015-12-21 16:14
Please, kill this tag. =(

**Comment by superlou** [comment] 2016-02-29 02:10
Chiming in for another project having to decide between working SVGs or working dynamic routes.

**Comment by BryanHunt** [comment] 2016-03-07 05:22
I tried working around this problem by using the fully qualified URL for the clip-path and that worked as long as locationType: auto.  When you app is using locationType: hash, the fully qualified URL no longer works.

**Comment by BryanHunt** [comment] 2016-03-07 15:03
Got it to work like this:
```javascript
  attributeBindings: ['transform', 'clip-path'],

  'clip-path': computed('parentView.clipPath', function() {
    return `url(${window.location.href.replace(window.location.hash, "")}${this.get('parentView.clipPath')})`;
  })
```

**Comment by misteroh** [comment] 2016-04-09 00:44
@ianpetzer that kind of works, but is broken in IE10 for me.

Does anyone know what's going on with this?

**Comment by mikeazo** [comment] 2016-04-11 13:41
Anyone aware of a good workaround for [this example JSfiddle](https://jsfiddle.net/j8ppcwp1/3/)? There should be text along the path like there is [here](https://jsfiddle.net/j8ppcwp1/1/) where the `<base>` tag is removed. Some of the suggestions above like using the full URL don't appear to work with the `textPath`.

I could remove the `<base>` tag, as is suggested, but I'm looking or other options.

**Comment by ming-codes** [comment] 2016-04-11 17:11
@mikeazo Works for me. As far as I know, `xlink:href` is not effected by this issue. Only inlined CSS styles that uses `url(...)` is effected.

**Comment by mikeazo** [comment] 2016-04-11 17:13
@ming-codes the [JSfiddle](https://jsfiddle.net/j8ppcwp1/3/) I linked to shows text on the path? What browser are you in? In Chrome 49 and Firefox 45, it doesn't. It does work in IE and Edge, AFAIK. It also works in Chrome 48.

**Comment by jdmarshall** [comment] 2016-04-11 17:16
@BryanHunt Unfortunately that solution is DOA if you are using virtual hosts, which is a major 1.1 feature for my project.

I am sadly coming to a crossroads where I may have to switch off Ember due to lack of traction on this issue.  That and the giant initial download (which isn't on the 2016 roadmap, which IMO is huge mistake)

**Comment by JackCA** [comment] 2016-04-11 17:20
@ivanvanderbyl was your solution to this generic enough that it could be shared?

**Comment by ming-codes** [comment] 2016-04-11 17:22
@mikeazo Yes, I see the problem now. I see it working in Safari and Mobile Safari.

**Comment by morganick** [comment] 2016-04-12 21:24
It took me 2 days to find this issue. Please nuke `<base href="..." />` from orbit. No SVGs load in Chrome or Firefox when SVG defs are embedded in HTML. Safari has no issue displaying them.

**Comment by ivanvanderbyl** [comment] 2016-04-13 20:52
@JackCA definitely. Here's a gist of roughly what I did https://gist.github.com/ivanvanderbyl/4b1c2ab7904542aa08f7ef1b83bdb342

**Comment by ivanvanderbyl** [comment] 2016-04-13 20:53
Basically if you remove `baseURL` from your environment.js, Ember will stop rendering the tag. But you need to update the asset paths so it doesn't break all the other things.

**Comment by JackCA** [comment] 2016-04-14 21:25
@ivanvanderbyl awesome, thanks for sharing! Looks like @Turbo87 jumped on this with #5792 moments after you shared. However, your implementation could be an intermediary fix...

**Comment by rwjblue** [comment] 2016-04-14 21:33
@JackCA - FWIW, the fix in #5792 is roughly the same as what @ivanvanderbyl had in the gist (though there are a few additional steps we will be doing internally to ensure proper warnings/deprecations/etc happen).

**Comment by JackCA** [comment] 2016-04-14 21:38
@rwjblue awesome! Nice work everyone

**Comment by ianpetzer** [comment] 2016-04-20 11:09
@Turbo87 We are running our ember-cli build off your branch and it has fixed our svg issues. Amazing! Thanks so much to everyone that contributed.

So our use elements now looks like:
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo--logo"></use>

ie: Just a relative identifier for embedded svg's
Previously we had to include the page url to make the svg's work but it was becoming a nightmare with changing query params

**Comment by Turbo87** [comment] 2016-04-20 11:28
@ianpetzer awesome, thanks for the feedback!

**Closed** 2016-04-27 13:03 UTC
Labels: Blocking, Bug
