### ISSUE TITLE
livereload requires toggling extension twice in google chrome to work

### ISSUE THREAD

**Issue by alanzheng88** [ember-cli/ember-cli#6356] opened 2016-10-17 13:38 UTC
Output from `ember version --verbose && npm --version`:
```
ubuntu@ubuntu-xenial:~/project/webroot$ ember version --verbose && npm --version
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.7.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: linux x64
3.10.8
```
Steps to reproduce issue:
1. Open any ember.js project
2. Enable liveReload in .ember-cli file
        ```
        {
          "liveReload": true,
          "watcher": "polling"
        }
        ```
3. Start ember server in vagrant vm
4. Go to Google Chrome on host and access a project page
5. Make changes to the project page in step 4
6. Note changes are not reflected in browser

I noticed that by toggling LiveReload Google Chrome extension twice, it appends the following script tag to the body of the webpage, and when I make changes to the page, it is reflected in the browser.
        ```
        <script src="http://127.0.0.1:35729/livereload.js?ext=Chrome&amp;extver=2.1.0"></script>
        ```
However, on the initial page load, the following is appended inside the head and not the body and when I make changes to the page, it is not reflected in the browser.
        ```
        <script type="text/javascript" src="http://localhost:49152/livereload.js?snipver=1"></script>
        ```

**Comment by alanzheng88** [comment] 2016-10-17 14:04
I realized I forgot to forward the port 35729 in the VM

**Comment by alanzheng88** [comment] 2016-10-17 14:13
I initially thought that forwarding port 49152 would resolve the issue but it didn't which leads me to believe that
        ```
         <script type="text/javascript" src="http://localhost:49152/livereload.js?snipver=1"></script>
        ```
needs to be displayed in the body on its initial load for livereload to work.

**Comment by nathanhammond** [comment] 2016-10-17 15:41
1. We insert the livereload handling for you and it doesn't require a browser extension. I suspect that conflicts there are the problem. We know that the baseline behavior works (otherwise we'd be hearing about it often), so this is likely a local configuration problem.

2. We've moved on to Ember CLI 2.8 with 2.9 releasing today. Please upgrade to a newer version and see if the issue persists. 

I'm closing this issue as likely not a bug but if upon further investigation on your side you discover that it may in fact be a bug keep us up-to-date here–we will still continue to receive notifications from any followup comments on this issue. Being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you want help figuring it out. :smile:

**Closed by nathanhammond** 2016-10-17 15:42 UTC
