### ISSUE TITLE
"server.shutdown()" wants to be removed with "ember init" but is present when run "ember new"

### ISSUE THREAD

**Issue by notmessenger** [ember-cli/ember-cli#6217] opened 2016-08-30 16:08 UTC
I recently upgraded an application from Ember CLI 2.4.3 to 2.7.0 by upgrading to each version in-between and running `ember init`.  In each instance of doing so, for each version of Ember CLI, the following change was wanting to be made:

```
// tests/helpers/destroy-app.js

import Ember from 'ember';

export default function destroyApp(application) {
   Ember.run(application, 'destroy');
-  server.shutdown();
}
```

However, if I run `ember new` against Ember CLI 2.7.0 the *tests/helpers/destroy-app.js* file is created with the `server.shutdown();` line contained within it.

So it seems either the diff is incorrect or the contents of this file on creation is not correct.

**Comment by nathanhammond** [comment] 2016-08-30 16:25
I suspect that you you have an old version of Ember CLI installed globally.

The blueprint doesn't include the `server.shutdown()` line and hasn't for exactly one year: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/destroy-app.js

I'm closing this issue as not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. If you can confirm that your global install is old that would be wonderful. 😄

**Closed by nathanhammond** 2016-08-30 16:25 UTC

**Comment by notmessenger** [comment] 2016-08-30 16:39
Info when run `ember -v` not in an app folder (global version)

```
[jeremy@Jeremys-MacBook-Pro ~]$ pwd
/Users/jeremy
[jeremy@Jeremys-MacBook-Pro ~]$ ember -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
node: 6.3.0
os: darwin x64
```

Info when run `ember -v` from within an app:

```
[jeremy@Jeremys-MacBook-Pro ~]$ cd Desktop/throwAway/authTest/
[jeremy@Jeremys-MacBook-Pro authTest (master)]$ ember -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
node: 6.3.0
os: darwin x64
```

Then ran

* `npm uninstall -g ember-cli`
* `npm cache clean`
* `bower cache clean`
* `npm install -g ember-cli@2.7.0`

`ember -v` info:

```
[jeremy@Jeremys-MacBook-Pro ~]$ ember -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
node: 6.3.0
os: darwin x64
```

**VERDICT:** The line is gone from the file.  This is interesting but I'm glad it is explained and I could provide resolution for this issue.

**Comment by nathanhammond** [comment] 2016-08-30 16:47
Very strange. I'm not entirely sure why that happened, but it's good to know that you were able to get it sorted out. Thanks for posting all of the information for future travelers, @notmessenger!
