### ISSUE TITLE
Test failure in browser on clean ember-cli 2.8.0 install

### ISSUE THREAD

**Issue by pgengler** [ember-cli/ember-cli#6247] opened 2016-09-09 14:07 UTC
With a fresh app generated with `ember new` with ember-cli 2.8.0, tests run in the browser (http://localhost:4200) have a failure. (When running the tests via `ember test` or `ember test --serve`, the failure does not happen.)

Steps to reproduce:
1. Generate a new Ember app: `ember new test-failure`
2. Start the server for the new app: `cd test-failure && ember s`
3. Visit http://localhost:4200/tests in a browser

Result: eight passing JSHint tests (as expected) and a failure (unexpected) "Uncaught Error: Called start() outside of a test context while already started"

<img width="1379" alt="screen shot 2016-09-09 at 10 04 45 am" src="https://cloud.githubusercontent.com/assets/193435/18389650/eee01d40-7674-11e6-81b6-9ad049147177.png">

---

Output from `ember version --verbose && npm --version`:
```
$ ember version --verbose && npm --version
ember-cli: 2.8.0
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: darwin x64
3.3.12
```

**Comment by kellyselden** [comment] 2016-09-09 16:33
@pgengler I'm glad someone else stumbled on this. I was upgrading my app as well and got this. I thought it was my complicated tests not playing well with the new release, but I guess it's simpler than that. Thanks!

**Comment by stefanpenner** [comment] 2016-09-09 16:40
cc @trentmwillis

**Comment by trentmwillis** [comment] 2016-09-09 18:12
Hmm, I can dive into this sometime over the weekend. We didn't move ember-cli-qunit at all with this last release though, did we?

**Comment by kellyselden** [comment] 2016-09-09 18:25
@trentmwillis it went from "^2.0.0" to "^2.1.0" in the blueprint, so even though it was covered, I hadn't run the tests in a while so a newer version could have caused it.

**Comment by nathanhammond** [comment] 2016-09-09 19:57
@trentmwillis It appears that this code is now running too late and that the tests actually _have_ already been started:

https://github.com/ember-cli/ember-cli-qunit/blob/884a35c078a372e538d82bd95aabc5613e99c9e5/vendor/ember-cli-qunit/test-loader.js#L67-L76

By the time this is run eight tests have been completed.

**Comment by trentmwillis** [comment] 2016-09-09 20:17
Hmm, likely has something to do with the changes to not use jQuery for `ready`.

**Comment by rwjblue** [comment] 2016-09-09 20:26
Possibly, but if jQuery is present we still use it.

**Comment by trentmwillis** [comment] 2016-09-10 17:15
So I spent some time debugging this and narrowed it down to an issue between Ember 2.7 and 2.8. The root issue is that `QUnit.load` (scheduled via `window.load`) executes prior to the ember-cli-qunit callback (scheduled via `$.ready`), but when using Ember 2.7 that doesn't happen. I think the error is due to a change in `$.ready` since Ember 2.8 uses jQuery 3 and Ember 2.7 uses jQuery 2.

That's as far as I have gotten, unsure how to fix really.

**Comment by kellyselden** [comment] 2016-09-10 21:07
I'm also seeing this error in our own CI https://ci.appveyor.com/project/embercli/ember-cli/build/9646/job/ao7rsmun44y2e3bj "Called start() outside of a test context while already started"

Don't know if that helps.

**Comment by nathanhammond** [comment] 2016-09-10 22:55
Updates:
- Ember.js 2.8.0 with jQuery 2.X works.
- Ember.js 2.8.0 with jQuery 3.X doesn't work.

I've not traced more than that.

**Comment by tragiclifestories** [comment] 2016-09-11 16:31
@nathanhammond That fixed it for me, thanks. Just in addition: I noticed that this seems to be a phantomjs-specific thing - tests were running fine in Chrome for me.

**Comment by rwjblue** [comment] 2016-09-11 16:33
Likely related to this note in the jQuery 3.x [upgrade guide](https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous).

> Breaking change: document-ready handlers are now asynchronous

**Comment by rwjblue** [comment] 2016-09-11 16:57
I believe that https://github.com/ember-cli/ember-cli-qunit/pull/145 and https://github.com/ember-cli/ember-cli-qunit/pull/146 should resolve this.

Would love for someone to test and confirm before landing and releasing another 2.x  ember-cli-qunit...

**Comment by tragiclifestories** [comment] 2016-09-11 17:18
They look good to me.

**Comment by nathanhammond** [comment] 2016-09-11 17:26
Confirmed and merged, just need releases.

**Comment by rwjblue** [comment] 2016-09-11 17:49
ember-cli-qunit@2.2.2 and ember-cli-qunit@3.0.1 have been released (also added @nathanhammond to npm owners).

Closing this for now (can reopen if that doesn't resolve).

**Closed by rwjblue** 2016-09-11 17:49 UTC
Labels: Bug, Regression
