### ISSUE TITLE
SASS import works in engines, but not addons

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#6943] opened 2017-04-04 13:24 UTC
I found an issue where the exact same sass setup in engines and addons behaves differently. I have an import that works in engines, but fails in addons. I created a repo that can be used to reproduce the issue https://github.com/rwwagner90/cli-sass-issues

Happy to help figure this out, if people can help nudge me in the right direction.

**Comment by rwjblue** [comment] 2017-04-04 15:25
Thank you for the detailed reproduction!

The issue here is that the `component-lib` exports its styles in the `app` tree. The purpose of the app tree is that it is merged with the "host".  In the case of a normal addon, the host is the actual host app (`tests/dummy` in an addons repo).  In the case of an engine the engine itself is the host (e.g. it is the thing that "owns" the namespace).

I agree that the behavior is not obvious and we have generally done a poor job of explaining how folks should think of this, but I do think it is consistent with the mental model above.

**Comment by rwwagner90** [comment] 2017-04-04 15:48
@rwjblue thanks for that explanation! 

Is there a way to have a common addon that holds all the SASS variables, mixins, etc and be able to `@import` it into both other addons and engines?

If we use the `addon` tree in `component-lib` then we cannot access the variables and mixins and such from other addons, since it just all gets converted to CSS and dropped in the vendor tree.

**Comment by pangratz** [comment] 2017-09-26 08:14
@rwwagner90 it seems that your reproduction repo is not available anymore. Any chance you still have this around? I am investigating issues within our sass + addon + engine setup and maybe your repo could help... Thanks!

**Comment by rwwagner90** [comment] 2017-09-26 18:44
@pangratz I believe I deleted it because I thought I had no need for it anymore. What issue are you encountering?

**Comment by pangratz** [comment] 2017-09-28 12:55
The issue is no more. Thanks @rwwagner90 for getting back to me!

For the future reader, this https://github.com/aexmachina/ember-cli-sass/issues/107#issuecomment-332821531 fixed the problem of not being able to import SASS from an in-repo addon into an in-repo engine.

**Closed** 2017-09-30 13:29 UTC

**Comment by rwwagner90** [comment] 2017-09-30 14:16
@pangratz perhaps we should add some docs somewhere detailing the fix you found? That way it is not lost in issues forever.
