### ISSUE TITLE
index.html not updating in builds with 2.3.0-beta.2

### ISSUE THREAD

**Issue by Soliah** [ember-cli/ember-cli#5445] opened 2016-02-09 23:03 UTC
To reproduce:

- `ember new foo`
- `ember build --environment production`
- Observe that `index.html` does not have the prepend set for assets
- Add a setting to ember-cli-build.js prepend for a CDN:

```
    fingerprint: {
      enabled: true,
      prepend: 'https://xxxxxxxx.cloudfront.net/'
    },
```

- `ember build --environment production`
- Observe that `index.html` hasn't updated references

`prepend` options was just an example. This seems to also be the case when code (and hence the fingerprints) have changed, the new fingerprints aren't reflected either.

--

Work around is to delete `tmp` before building.

**Comment by Soliah** [comment] 2016-02-09 23:03
Maybe related to #5370?

**Comment by stefanpenner** [comment] 2016-02-09 23:23
likely a bug in broccoli-asset-rev

**Comment by raido** [comment] 2016-02-10 11:30
It happens with environment config too. It just won't update the index at all. Timestamp on index stays the same between builds.

**Comment by rwjblue** [comment] 2016-02-10 21:16
Might be related to #5370 (it was just included in 2.3.0-beta.2)...

**Comment by stefanpenner** [comment] 2016-02-10 21:54
I'm unsure, if it is I suspect is is more likely just uncovering some underlying issue.

**Comment by jpadilla** [comment] 2016-02-11 20:18
Ran into this as well on 2.3.0-beta.2. Noticed that removing `dist` and building again resulted in correct fingerprints in `index.html`. If I then modified `styles/app.css` and rebuild fingerprints in `index.html` didn't update. Turned off fingerprints, rebuild, assets no longer have fingerprints, `index.html` didn't update. Seems similar to what was going on in https://github.com/tildeio/ember-cli-fastboot/pull/112

**Comment by stefanpenner** [comment] 2016-02-11 20:28
my guess is this is an bug in asset-rev, but introduced by more efficient dist management. (previously, asset-rev relied on everything changing everytime, or something)

**Comment by varoot** [comment] 2016-02-12 02:35
It seems the issue is that the content in the output folder does not get replaced if filename remains the same.

For example, run `ember build`. Then go to `dist` folder, change content of some files (`index.html`, `robots.txt`, etc), then run `ember build` again. In **2.3.0-beta.1**, the files are replaced with the correct content, in **2.3.0-beta.2**, they aren't. This breaks other addons that modify output folder like `ember-cli-deploy-gzip` (#5454)

**Comment by stefanpenner** [comment] 2016-02-12 02:43
> This breaks other addons that modify output folder like ember-cli-deploy-gzip (#5454)

really, addons should not be modifying the output folder.

**Comment by ghedamat** [comment] 2016-02-15 00:37
I just hit this issue in a brand new project

it seems to be happening even without touching the dist result (which I agree is less than ideal)

repro (pretty much the same as what @Soliah reported)
1) create a new ember project
2) build with env production
3) change fingerprinting config to i.e use `prepend`
4) build again

expected
index.html should be updated

result
index.html is NOT updated

happens in 2.3.0-beta.2
works in 2.3.0-beta.1

**Comment by ghedamat** [comment] 2016-02-15 13:34
just tried on current ember-cli master

even running `ember build` followed by `ember build --environment=production` leads to NOT getting an updated `index.html`

**Comment by achambers** [comment] 2016-02-15 13:48
@stefanpenner said:
> really, add-ons should not be modifying the output folder.

Agreed, so we should look at how the ember-cli-deploy-gzip plugin works. However, I think this issue it broader than that.

I'm pretty sure this is related to #5379, like Soliah mentioned, as (my understanding is that) the `tree-sync` package now essentially updates the output dir based on a diff, but it is using file names to work out this diff. For files that are not fingerprinted, such as index.html, robots.txt etc, once they are modified, they are not going to be updated as tree-sync thinks that the file already exists in the output dir.

**Comment by rwjblue** [comment] 2016-02-15 15:16
Steps to reproduce without asset-rev (or a production build):

```
ember new foo
cd foo
ember build
# update <title> in app/index.html to some other value
ember build
# dist/index.html contains old title
```

Output from `DEBUG=tree-sync ember build` on the second build:

```
version: 2.3.0-beta.2
Building..  tree-sync initializing TreeSync:  /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/tmp/broccoli_merge_trees-output_path-NbROv01s.tmp -> /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/dist +0ms
  tree-sync syncing /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/tmp/broccoli_merge_trees-output_path-NbROv01s.tmp -> /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/dist +1ms
  tree-sync walked /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/tmp/broccoli_merge_trees-output_path-NbROv01s.tmp 21ms and  /Users/rjackson/Source/sandbox/ember-cli/sample-2-3-0-beta-2/dist 21ms +1ms
  tree-sync calc operations 0 +2ms
  tree-sync applied patches: 0 +0ms
Built project successfully. Stored in "dist/".
```

Still digging a bit to see why no operations are detected...

**Comment by rwjblue** [comment] 2016-02-15 16:14
https://github.com/stefanpenner/tree-sync/pull/1 is a failing test in the tree-sync repo for this, I am working on a fix...

**Comment by achambers** [comment] 2016-02-15 17:02
:+1:

**Comment by ghedamat** [comment] 2016-02-15 17:05
thanks as usual @rwjblue !!

**Comment by rwjblue** [comment] 2016-02-15 19:34
This should be fixed now with `tree-sync@1.0.2`. A `rm -rf node_modules && npm install` should get the updated version.

**Closed by rwjblue** 2016-02-15 19:34 UTC

**Comment by ghedamat** [comment] 2016-02-15 21:50
confirm @rwjblue ! thanks a lot!

**Comment by stefanpenner** [comment] 2016-02-15 21:53
Thanks @rwjblue
