### ISSUE TITLE
Config is encoded to meta tag with deprecated `escape` method

### ISSUE THREAD

**Issue by JackieChiles** [ember-cli/ember-cli#6598] opened 2016-12-21 15:50 UTC
The relevant line is here in [lib/broccoli/ember-app.js](https://github.com/ember-cli/ember-cli/blob/bdf9aa0afacd8243180e4a0c14351d7072d0a62d/lib/broccoli/ember-app.js#L1757). Calling `decodeURIComponent` on this config string can fail if UTF-8 characters are used. The `encodeURIComponent` method should be used instead.

I will gladly PR a fix but wanted to open an issue first as this is a breaking change that will modify the formatting of the escaped meta config string.

**Comment by nathanhammond** [comment] 2016-12-22 10:26
@JackieChiles You've also identified why we can't exactly make a change to this. I'd add this to the list for https://github.com/ember-cli/rfcs/issues/72.

Thoughts @ember-cli/core?

**Comment by kellyselden** [comment] 2016-12-22 19:11
I'm cool with this.

**Comment by stefanpenner** [comment] 2016-12-22 20:11
sounds reasonable, is there a catch?

**Comment by nathanhammond** [comment] 2016-12-23 14:57
@kellyselden @stefanpenner Y'all's comments aren't particularly clear. 😛 The problem is this:

```javascript
var config = "{'å': 'å'}";
config === decodeURIComponent(escape(config));
// => URIError: malformed URI sequence

unescape(encodeURIComponent(config))
// => "{'Ã¥': 'Ã¥'}"
```

- For: [we control the end-to-end usage inside of config here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/app-config-from-meta.js#L6).
- Against: we break any existing things which manually grab things out of the `meta`.

I don't have strong opinions either way.

**Comment by stefanpenner** [comment] 2016-12-23 17:55
> Against: we break any existing things which manually grab things out of the meta.

I am OK with this, as long as we send it through the regular release train.

I don't believe we made public API the serialization scheme itself. Although I could accept some power-users have gained access. If they have, I would love to work with them on making read/write to these meta objects a more formalized public API.

**Comment by kellyselden** [comment] 2016-12-23 18:04
I was agreeing with the call to add to the 3.0 breaking changes list. I'm also ok with @stefanpenner's normal release justification.

**Comment by JackieChiles** [comment] 2017-01-04 13:16
Adding to the 3.0 list sounds good to me. @stefanpenner In our case we pull down the HTML via AJAX, parse the meta values, and use that to determine if the server has a newer version of the app than is currently running. Our fix for now is just to use `unescape` to decode rather than `decodeURIComponent`.

**Comment by Turbo87** [comment] 2017-02-20 10:30
FWIW I also agree that this should likely not be considered a breaking change and can be part of the usual release cycle.

**Comment by efx** [comment] 2017-12-19 14:38
This issue could probably get a label `has-pending-pr` or something to avoid subsequent folks thinking it still needs to be fixed.

**Comment by raido** [comment] 2018-12-21 04:48
I rebased PR #6867 on master.

**Comment by acorncom** [comment] 2019-01-28 19:50
Looks like this can be closed, the referenced PR has been merged

**Closed** 2019-01-28 19:54 UTC
Labels: Internal, Ready for PR, good first issue
