### ISSUE TITLE
ember-cli build times w/ broccoli-viz

### ISSUE THREAD

**Issue by snewcomer** [ember-cli/ember-cli#6221] opened 2016-09-01 18:40 UTC
Having some serious troubles with `ember s`, so I included the results of the `broccoli-viz` output and having trouble remediating the problem.  ~50-60sec is the norm.  Looks like Babel is quite the culprit and seems like it is eating up most of that time.  Any thoughts or potential solutions?  Really a downer on productivity :)

**graph.0.dot && graph.0.json**
https://gist.github.com/snewcomer/92e6b89efe206e960854099b53caa4d8

**package.json and bower.json**
https://gist.github.com/snewcomer/260bc762fbb818d1173a2dbb75130adf

**Comment by nathanhammond** [comment] 2016-09-02 06:19
At risk of being a smartass (which I am 😜) [this is your problem](https://gist.github.com/snewcomer/260bc762fbb818d1173a2dbb75130adf#file-package-json-L23-L84).

1. How is performance on rebuilds? Slow rebuilds implies "unstable" broccoli plugins doing too much invalidation. If rebuilds are snappy then...
2. Your problem is the sheer amount of JavaScript. How large is app.js and vendor.js? I suspect that they're huge.

Addons are fantastic, but knowing when to pull in an addon versus writing bespoke code is a fine balance.

Node 427, Babel, self time (10057ms) is babelifying all of your addons `addon` folders.
Node 552, Babel, self time (15547ms) is babelifying all of your addons `app` folders plus your own app code (though mostly your addons).

You need fewer files for first build to be quick. I'm _more_ interested in rebuild times because that's something we can actually work on to make sure things are stable if they're not.

I'm closing this issue as not a bug but in the mean time we can continue to have conversation on this thread. We will still continue to receive notifications from any followup comments; being closed doesn't mean that we're ignoring the thread.

**Closed by nathanhammond** 2016-09-02 06:19 UTC

**Comment by snewcomer** [comment] 2016-09-03 05:15
Thank you.  Yeah was mainly concerned if somehow I introduced a bug if said build times were abnormal.  Rebuild times are great!

**Comment by nathanhammond** [comment] 2016-09-03 17:49
It is abnormal because most people don't end up with applications of that size. However it's nonetheless expected.
