### ISSUE TITLE
Add a clean way to get access to build timing

### ISSUE THREAD

**Issue by mdebbar** [ember-cli/ember-cli#6349] opened 2016-10-14 20:58 UTC
Right now, the only way to get the build time information is by creating an addon and monkey patching `project.cli.analytics.trackTiming` like so:

``` javascript
module.exports = {
  name: 'build-time-tracker',
  init: function() {
    this._super.init && this._super.init.apply(this, arguments);

    var analytics = project.cli.analytics;
    var original = analytics.trackTiming;

    analytics.trackTiming = function(info) {
      original.apply(this, arguments);
      // Access `info` which contains meta data about current build, including build time.
    };
  },
};
```

It would be great to have a clean API to listen to build time info. Something as simple as this could work:

``` javascript
project.cli.onBuildComplete(function(info) {
  // Access the build info here..
});
```

Any thoughts?

**Comment by hjdivad** [comment] 2016-10-17 09:42
@mdebbar have you looked at the json output from using [`BROCCOLI_VIZ`](https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md#broccoli-viz).

You can see some examples of this being processed in [broccoli-slow-trees](https://github.com/rwjblue/broccoli-slow-trees/blob/master/calculate-summary.js#L20-L63).

What's your specific goal for which you want to monitor build times?

**Comment by mdebbar** [comment] 2016-10-18 17:59
I didn't know about that, thanks for the pointer. I tried it but I don't think I'll use broccoli viz, simply because it generates huge json and dot files (40+ MB) that I don't need. I just need the build time.

I found out that I can do`builder.on('start', function() { ... })` and `builder.on('end', function() { ... })` and capture `Date.now()` in both. Then calculate the build time as the difference.

My goal is to start tracking build times on all developers' machines. Then we can measure build time improvements more accurately.

**Comment by stefanpenner** [comment] 2016-10-18 18:01
we already have this tracking, but its likely not publicly augmentable. 

@twokul got any suggests on how to make leak pluggable here?

**Comment by mdebbar** [comment] 2016-10-18 18:44
@hjdivad, @stefanpenner in the future, we are planning to track the timing of sub-tasks (e.g. css compilation, babel, rollup, etc). Basically, the same info that's displayed as `Slowest Trees` by ember-cli. Is there a way to access that information without generating the gigantic broccoli-viz files?

**Comment by stefanpenner** [comment] 2016-10-19 07:13
@mdebbar I would recommend looking at where the slow tress are calculated today, that should most likely give you want you want.

**Comment by twokul** [comment] 2016-10-19 21:08
@stefanpenner let me think about it. it might require some changes to ember cli

**Comment by nathanhammond** [comment] 2016-10-30 05:52
Hey @mdebbar et al.!

@twokul and I are looking at this right now: what exactly is your concern about the JSON files? that you don't wish to push that much data across the network to a central analytics server at build complete? Everything else in this comment assumes that context.

---

I'm not a fan of trying to provide coarse information via custom code inside of Ember CLI which is unaware of Broccoli. We would have to inject that code at numerous places inside of Ember CLI and  the results would be highly subject to change scope as we refactor code. Doing this at the Broccoli level makes a lot more sense, and is something that we already mostly track end-to-end with Heimdall.

I believe (with limited familiarity) that our goal should be to fully adopt Heimdall and let the application specify "queries" which we can run on the collected data post-build which we decide are interesting. This is approximately similar to what exists in [`broccoli-slow-trees`](https://github.com/rwjblue/broccoli-slow-trees/blob/master/calculate-summary.js#L20-L63) already linked by David.

So given that, we'd still generate the large data sets, but then process them _before_ shipping them off. That would be a much more palatable API as it isn't nearly as invasive into Ember CLI and is something we've already proven works.

@hjdivad @runspired @stefanpenner is that something that sounds reasonable? What exactly is the state of [heimdall-query](https://github.com/heimdalljs/heimdall-query)?

**Comment by stefanpenner** [comment] 2016-10-30 14:13
The files we produce now, are extremely high fidelity (thus large) because they are intended to be the entry point to other tooling.  An example tool, would be one that submits summaries to some analytic service.

It seems 2 choices exist:

* summarize the larger files, into smaller datasets before sending them to an analytics service (easiest)
* expand broccoli-slow-trees to allow for the needed summarization (more work)

**Comment by hjdivad** [comment] 2016-11-02 18:51
> I believe (with limited familiarity) that our goal should be to fully adopt Heimdall and let the application specify "queries" which we can run on the collected data post-build which we decide are interesting. This is approximately similar to what exists in broccoli-slow-trees already linked by David.
> 
> So given that, we'd still generate the large data sets, but then process them before shipping them off. That would be a much more palatable API as it isn't nearly as invasive into Ember CLI and is something we've already proven works.

big +1.  I think this is exactly what we want to do.

**Comment by stefanpenner** [comment] 2016-11-20 20:57
just a heads-up, @chadhietala added a feature for this specifically for linkedin in 2014 https://github.com/ember-cli/ember-cli/pull/2817  Is this sufficient?

**Comment by mdebbar** [comment] 2016-11-21 18:28
@stefanpenner unfortunately, that's not enough in our case. What we need is a way to get the leek data locally (through an event listener or similar). The server expects requests to be sent in a specific structure (and potentially with specific http headers), while @chadhietala's PR allows flexibility only in the URL.

Also, what would be the best way to get more detailed info about the build (e.g. the type of file that triggered the rebuild, the breakup of build time by tree: babel/rollup/eyeglass/etc)? Would that be something doable with Leek?

**Comment by stefanpenner** [comment] 2016-11-21 18:47
@mdebbar right now, detailed information comes from those detailed graphs produced for the viz debugging.

My recommendation is for you to provide a detailed list/schema of the information you need. And we can work together to make sure the information is easily accessible.

**Comment by twokul** [comment] 2016-11-21 20:16
@mdebbar so just to be clear. `leek` was originally created to gather analytics **only** internal to ember-cli (and, imo, it should stay this way). it seems to me the avenue we should walk is to provide a nice interface on top the viz and heimdalljs to gather data about ember-cli app locally.

I'll be happy to chat with you and talk through some of the scenarios you surfaced and RFC it.

**Comment by mdebbar** [comment] 2016-11-21 20:22
Ok, I'm starting to get confused now. Different people are suggesting different ways to collect build info. First thing we should do is agree on **_one_** way to expose that data, either leek, heimdall or viz. I'll follow up offline with @twokul

**Comment by stefanpenner** [comment] 2016-11-21 20:28
@mdebbar I believe the confusion stems from:

1. existing public API's are insufficient, but it is unclear why they are
2. this leads people to share ideas on how to get various pieces of information, but not a unified/cohesive story.

I think for this to be successful, we need to know exactly what information is required. Then we can figure out how to provide that information.

**Comment by mdebbar** [comment] 2016-11-21 22:00
I'll try to summarize my discussion with @twokul:

We need to gather more granular data to help us focus our effort on the main build-perf bottlenecks:
1. Track which files are triggering each rebuild.
2. Break down the build time by tree: e.g. babel, rollup, eyeglass, etc.

We need other information (e.g. machine cpu power, available memory, etc) but those aren't related to ember-cli and should be collected independently.

The following structure of info could work:
```javascript
{
  task: 'build', // or 'rebuild'
  totalTime: 47144000,

  // If it's a rebuild, include a list of files that triggered it.
  files: [
    'core/jobs/addon/components/some-component.js',
    ...
  ],

  // Break-down of trees, ideally sorted by slowest.
  trees: [
    { name: 'EyeglassCompiler', time: 4210000 },
    { name: 'Babel', time: 3488000 },
    ...
  ]
}
```

Having a local dashboard running inside the ember app won't work. The dashboard needs to be remote and accessible by everyone and contains aggregated data from all developers' machines.

I hope that helps clarify things up.

**Comment by MiguelMadero** [comment] 2016-11-21 23:34
We have a pretty similar use case. However, the way I'm thinking about it is: 

1. Get aggregate data, company-wide so we can catch regressions or make sure that we hit certain internal SLAs. For example, we want to make sure the 90th percentile rebuild time is 4 seconds or faster (sounds bad, but it would be an improvement for us). 
2. When we're looking for explanations we can dive deeper, at the analytics level to see if there is anything in common amongst worst performers (e.g. a slower machine or watchman 4.7, etc) or the worst types of builds (e.g. is hbs, js or scss slow, is it for a specific engine or addon change, etc). 
3. Finally, once we can use viz and other debugging tools to get even richer information. 

The structure @mdebbar posted sounds like a reasonable start.

**Comment by stefanpenner** [comment] 2016-11-21 23:37
Yup sounds perfectly reasonable, we have all the data. Requires public api design / implementation effort next likely. RFC may be appropriate for whomever takes this.

**Comment by twokul** [comment] 2016-11-24 10:10
working on RFC for this feature

**Comment by MiguelMadero** [comment] 2016-11-28 03:53
@twokul do you have a link to the RFC?

**Comment by twokul** [comment] 2016-11-29 01:23
@MiguelMadero in progress. will link today/tomorrow.

**Comment by MiguelMadero** [comment] 2016-11-29 01:44
thanks, no pressure, just curious. Looking forward to reading this.

**Comment by twokul** [comment] 2016-12-01 15:53
update on this: there are several way to implement it, I'll raise this question during ember cli core meeting and provide an update on the decided direction.

**Comment by stefanpenner** [comment] 2016-12-03 09:07
@twokul please share a link to the RFC when you have it.

**Comment by stefanpenner** [comment] 2016-12-07 17:55
Not sure whats-up with the RFC. But @hjdivad and myself are tasked with addressing this at work, as it is blocking our effort, so we are moving it forward.

Our current high level plan:

- [ ] summarize heimdall gather data to answer actionable important questions about the build.
- [ ] how to automatically share said information.

**Comment by mdebbar** [comment] 2016-12-07 19:03
Few days ago, I discussed with @hjdivad the possibility of using `BROCCOLI_VIZ` to collect build data. Here's a list of questions/concerns that if answered, we might be able to use `BROCCOLI_VIZ`:
- How do we know when `BROCCOLI_VIZ`'s output files are ready?
- How can we reliably tell which file corresponds to the current build/rebuild?
- Is it possible to generate those files inside a subfolder instead of root folder?
- How should we cleanup those files so they don't keep piling up forever?
- How can we get the list of changed/added/removed files that triggered the rebuild?

I noticed that in recent versions of ember-cli, we are using `heimdall` to generate the `broccoli-viz` files. So it seems like it makes more sense now to somehow expose heimdall data directly instead of getting that data from the `broccoli-viz` files. And I'm glad that that's the direction we are heading according to @stefanpenner's comment above.

**Comment by stefanpenner** [comment] 2016-12-07 19:38
@mdebbar those questions are why we cannot rely on those outputfiles reliable for "autmoatically sharing" this information.

Which we will address with the 2nd "work item" above. this will most likely be, adding a hook internally that either does the broadcasting or enables someone to listen /broadcast themselves.

**Comment by locks** [comment] 2022-04-19 20:18
I believe significant progress was made in this area? Closing as at least partially addressed.

**Closed by locks** 2022-04-19 20:18 UTC
Labels: enhancement
