### ISSUE TITLE
app.import support compilation of multiple files

### ISSUE THREAD

**Issue by yeelan0319** [ember-cli/ember-cli#4221] opened 2015-06-03 14:16 UTC
I am working on a project that have many dependency libraries. The project was based on ember appkit but we are recently moving forward to ember-cli and try to hand over the compilation to ```ember build```, but we need to add all dependencies line by line using ```app.import```.  There is also a [similar question](http://stackoverflow.com/questions/27628976/import-many-javascript-files-in-a-directory-into-ember-cli) posted on stackoverflow several month ago.

I wonder if it is possible to make ```app.import``` support similar syntax like brocolli-funnel? For example,

    app.import('vendor/js, {
        srcDir: '/',
        include: ['*.js'],
        exclude: ['some-js-for-dev-only.js'],
        destDir: 'assets'
    });

The problem with using brocolli-funnel is it just move the file so we still need gulp to do all the minification and uglification, which ember is not aware of. It seems now ember-cli already support ```destDir```, which is great. I wonder if we can go further and make ```app.import``` more powerful. What's the major concerns for this feature? Thanks!

**Comment by stefanpenner** [comment] 2015-06-03 14:39
app.import is merely slight sugar over the concept of `script src` 1 file in.

if you wish to do more, you;ll have to use broccoli directly.  A good place to start is broccoli-stew's `find` https://github.com/stefanpenner/broccoli-stew/blob/master/lib/find.js

**Comment by yeelan0319** [comment] 2015-06-03 17:08
Thanks @stefanpenner . Once I find the files I needed, how can I let ember aware of those files and using ember build-in minification tools? I am not yet familiar with building process for ember, can you give me some clue for that?

**Comment by stefanpenner** [comment] 2015-06-03 17:23
module.exports = stew.find({
  app.toTree(),
  stew.find('path/to/other/files/**/*')
])

**Comment by stefanpenner** [comment] 2015-06-03 17:23
this is a better question for SO, closing as it is not a bug.

**Closed by stefanpenner** 2015-06-03 17:23 UTC

**Comment by yeelan0319** [comment] 2015-06-03 17:32
Oh sure @stefanpenner , I just want to propose a feature request instead of reporting a bug. I mean, I can also use brocolli-funnel to achieve the same result, but in that case, ember won't help me concat the dependencies into one file, so I need to rely on other build tools to do so. Correct me if I understand it wrong:)
