### ISSUE TITLE
[BETA] start app test helper causes lots of deprecation warnings

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#5816] opened 2016-04-18 13:57 UTC
These lines:
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/start-app.js#L8-L9

```
  let attributes = Ember.merge({}, config.APP);
  attributes = Ember.merge(attributes, attrs); // use defaults, but you can override;
```

cause a large number of deprecation warnings due to Ember.merge being deprecated in Ember 2.5

---

Output from ember version --verbose:
```
ember-cli: 2.6.0-beta.1
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
os: darwin x64

ember: 2.5.0
ember-data: 2.5.1
```

**Comment by rwjblue** [comment] 2016-04-18 14:02
Duplicate of:

* https://github.com/ember-cli/ember-cli/pull/5811
* https://github.com/ember-cli/ember-cli/pull/5808
* https://github.com/ember-cli/ember-cli/pull/5803

**Comment by rwjblue** [comment] 2016-04-18 14:03
As mentioned in those issues, the `Ember.merge` deprecation was premature and will be removed in Ember 2.5.1 (which should be released today or tomorrow).

**Closed by rwjblue** 2016-04-18 14:02 UTC
