### ISSUE TITLE
Incorrect layout path in generated components when using pods.

### ISSUE THREAD

**Issue by lpaluszk** [ember-cli/ember-cli#3509] opened 2015-03-11 22:19 UTC
The component js file generated from a blueprint references an incorrect template path when using pods.

![screenshot](https://cloud.githubusercontent.com/assets/3707675/6608137/6bbd1a4a-c83c-11e4-8f42-bcd3bbd95688.png)

https://github.com/ember-cli/ember-cli/blob/90dd165ee5732b272d498eeefcc98f3b29a9ccd8/blueprints/component/index.js#L50

**Comment by rwjblue** [comment] 2015-03-12 00:27
Duplicate of: https://github.com/ember-cli/ember-cli/issues/3472
Fixed in: https://github.com/ember-cli/ember-cli/pull/3481

**Closed by rwjblue** 2015-03-12 00:27 UTC
