### ISSUE TITLE
ember install doesn't update yarn.lock

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#9069] opened 2020-02-28 00:32 UTC
Running `ember install some-addon` on a brand new addon project generated with the `--yarn` option updates `package.json` but not `yarn.lock`. Conversely, new projects generated without `--yarn` will see `ember install` reflect changes in their `package-lock.json`, indicating that there is a gap in the yarn behavior. Here's an example of repro steps:

```
ember addon my-addon --yarn
cd my-addon
ember install ember-modifier
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.16.0
node: 12.16.1
v8: 7.8.279.23-node.31
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
os: darwin x64
6.13.4
1.22.0
```

Also potentially of note, I'm using volta v0.7.2 to manage my node/yarn/ember-cli versions.

**Comment by locks** [comment] 2020-03-31 15:57
Could not reproduce:

```
 ~/s/ember-3-16-yarn git:(master)
$ ember install ember-modifier

🚧  Installing packages... This might take a couple of minutes.
Yarn: Installed ember-modifier
Installed addon package.
 ~/s/ember-3-16-yarn git:(master) ✗
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package.json
	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
 ~/s/ember-3-16-yarn git:(master) ✗
$ volta --version
0.7.2
 ~/s/ember-3-16-yarn git:(master) ✗
$ ember --version
ember-cli: 3.16.1
node: 12.15.0
os: darwin x64
```

**Comment by locks** [comment] 2020-03-31 16:02
Couldn't repro on a fresh addon either :/

```
$ ember install ember-modifier

🚧  Installing packages... This might take a couple of minutes.
Yarn: Installed ember-modifier
Installed addon package.
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package.json
	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
$ ember --version
volta --vember-cli: 3.16.1
node: 12.15.0
os: darwin x64                                                                                                                                                                                                                            
$ volta --version
0.7.2

**Comment by rwjblue** [comment] 2020-04-01 18:16
Going to close for now then, definitely happy to reopen if we can repro...

**Closed by rwjblue** 2020-04-01 18:16 UTC
