### ISSUE TITLE
Error during 'Installing packages for tooling via npm'

### ISSUE THREAD

**Issue by LidaDimitriadi** [ember-cli/ember-cli#5529] opened 2016-02-27 10:58 UTC
I' getting this error after trying to create a new ember app:

Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Roaming\npm
-cache\underscore.string\2.3.3\package\package.json.9dd05c1acf548a1637405b19531a
b8cb' -> 'C:\Users\username\AppData\Roaming\npm-cache\underscore.string\2.3.3\packag
e\package.json'
    at Error (native)

I am on Windows 8 and I tried already uninstalling and reinstalling node, npm-bower cache clean and reinstalling ember-cli. Everything I tried so far failed. Any ideas? Thanks

**Comment by stefanpenner** [comment] 2016-02-27 14:46
When reporting an issue please be sure to read CONTRIBUTING.MD (you may notice a big banner when creating the issue that tells submitters this). Specifically [how to report an issue](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#reporting-a-bug) which requests additional information like OS/npm/ember version and clear steps for reproduction.

----

i think this is an upstream issue in NPM or maybe some funky permissions, as such I'm going to close this issue. If it turns out to actually be an ember-cli issue we can reopen.

some thoughts that may help:

this issue seems related: https://github.com/npm/npm/issues/9696 and it appears to have been "fixed" by https://github.com/npm/npm/commit/e982858d9bed65cede9cbb12df9216a4bb9e6fc9 which should have landed in npm v3.8.0.

I would suggest trying to update npm to 3.8+ and clearing the `'C:\Users\username\AppData\Roaming\npm-cache` directory.

**Closed by stefanpenner** 2016-02-27 14:46 UTC
Labels: Needs Bug Verification, Windows
