### ISSUE TITLE
"ReferenceError: a53113 is not defined" error in the production build

### ISSUE THREAD

**Issue by devdemi** [ember-cli/ember-cli#7526] opened 2017-12-26 15:14 UTC
Today after executing `ember build --environment=production`. I got the error:
```
ReferenceError: a53113 is not defined
    at /usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:8894:1
    at Object.e.default [as initialize] (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:8894:391)
    at /usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1914:108
    at e.each (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1860:28)
    at e.walk (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1851:6)
    at e.each (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1841:157)
    at e.topsort (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1841:203)
    at o._runInitializer (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1918:3)
    at o.runInitializers (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1914:6)
    at o._bootSync (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1884:10)
    at o.boot (/usr/src/fastboot/dist/assets/vendor-9d95620595ed8adf5e5e8840c9cdc065.js:1882:10)
    at EmberApp.buildAppInstance (/usr/src/fastboot/node_modules/fastboot/src/ember-app.js:225:21)
    at EmberApp.visitRoute (/usr/src/fastboot/node_modules/fastboot/src/ember-app.js:252:17)
    at EmberApp.visit (/usr/src/fastboot/node_modules/fastboot/src/ember-app.js:321:17)
```
My application starts with FastBoot `fastboot-app-server`.
I go to `vendor-9d95620595ed8adf5e5e8840c9cdc065.js` and there is this code:
```javascript
define("ember-data/setup-container", ["exports", "ember-data/-private", "ember-data/serializers/json-api", "ember-data/serializers/json", "ember-data/serializers/rest", "ember-data/adapters/json-api", "ember-data/adapters/rest", "ember-data/transforms/number", "ember-data/transforms/date", "ember-data/transforms/string", "ember-data/transforms/boolean"], function(e, t, n, r, i, o, s, a, l, u, c) {
    "use strict"
    Object.defineProperty(e, "__esModule", {
        value: !0
    }), e.default = function(e) {
        p = e, 
        p.register("data-adapter:main", t.DebugAdapter), d = e, d.register("transform:boolean", c.default), d.register("transform:date", l.default), d.register("transform:number", a.default), d.register("transform:string", u.default),
            function(e) {
                var t = e.inject || e.injection
                t.call(e, "controller", "store", "service:store"), t.call(e, "route", "store", "service:store"), t.call(e, "data-adapter", "store", "service:store")
            }(e),
            function(e) {
                var a, l
                a53113.call(e, "serializer", {
                    singleton: !1
                }), a53113.call(e, "adapter", {
                    singleton: !1
                }), e.register("serializer:-default", r.default), e.register("serializer:-rest", i.default), e.register("adapter:-rest", s.default), e.register("adapter:-json-api", o.default), e.register("serializer:-json-api", n.default), l = "service:store", ((a = e).has ? a.has(l) : a.hasRegistration(l)) || e.register("service:store", t.Store)
            }(e)
        var d
        var p
    }
})
```
Something wrong with initializers. But how to localize the error? Please advise ways to find out reasons of this error.

My package.json file:
```json
{
  "name": "my app",
  "version": "0.0.0",
  "description": "Small description for my app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "fastbootDependencies": [
    "ember-moment",
    "moment-timezone",
    "ember-cli-cookie",
    "ember-network"
  ],
  "devDependencies": {
    "babel-plugin-transform-es2015-block-scoping": "^6.24.0",
    "bootstrap-sass": "^3.3.7",
    "broccoli-asset-rev": "^2.6.0",
    "ember-ajax": "^3.0.0",
    "ember-bootstrap": "^1.0.0-rc.2",
    "ember-bootstrap-datepicker": "^2.0.3",
    "ember-cli": "^2.16.2",
    "ember-cli-app-version": "^3.1.0",
    "ember-cli-babel": "^6.9.0",
    "ember-cli-daterangepicker": "^0.5.1",
    "ember-cli-dependency-checker": "^2.0.1",
    "ember-cli-fastboot": "^1.0.5",
    "ember-cli-flash": "^1.4.3",
    "ember-cli-htmlbars": "^2.0.3",
    "ember-cli-htmlbars-inline-precompile": "^1.0.2",
    "ember-cli-inject-live-reload": "^1.7.0",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-meta-tags": "^4.0.0",
    "ember-tag-input": "^1.2.1",
    "ember-cli-moment-shim": "^3.4.0",
    "ember-cli-qunit": "^2.2.6",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^7.0.0",
    "ember-cli-shims": "1.1.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-stripe": "^1.0.1",
    "ember-cli-test-loader": "^2.2.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-cookies": "0.1.1",
    "ember-cp-validations": "^3.4.0",
    "ember-data": "^2.14.10",
    "ember-data-save-relationships": "0.0.5",
    "ember-export-application-global": "^1.0.5",
    "ember-file-upload": "^2.2.0",
    "ember-i18n": "^5.0.2",
    "ember-i18n-cp-validations": "^3.0.2",
    "ember-load-initializers": "^1.0.0",
    "ember-math-helpers": "^2.2.2",
    "ember-moment": "^7.4.1",
    "ember-fetch": "^3.4.3",
    "ember-page-title": "^3.2.2",
    "ember-radio-button": "^1.1.1",
    "ember-resolver": "^4.5.0",
    "ember-route-action-helper": "^2.0.6",
    "ember-simple-auth": "^1.4.0",
    "ember-welcome-page": "^3.1.1",
    "fastboot-transform": "^0.1.2",
    "loader.js": "^4.6.0",
    "moment-timezone": "^0.5.13",
    "pagination-pager": "^3.0.0",
    "torii": "^0.9.6",
    "ember-cli-facebook-js-sdk": "^2.0.1"
  },
  "dependencies": {
    "ember-cookies": "0.1.1"
  }
}
```

My versions:
```
ember-cli: 2.17.1
npm: 5.5.1
yarn: 1.3.2
```

I found old vendor-**.js and there is another code:
```javascript
 define("ember-data/setup-container", ["exports", "ember-data/-private", "ember-data/serializers/json-api", "ember-data/serializers/json", "ember-data/serializers/rest", "ember-data/adapters/json-api", "ember-data/adapters/rest", "ember-data/transforms/number", "ember-data/transforms/date", "ember-data/transforms/string", "ember-data/transforms/boolean"], function(e, t, n, r, i, o, s, a, l, u, c) {
    "use strict"
    Object.defineProperty(e, "__esModule", {
        value: !0
    }), e.default = function(e) {
        (function(e) {
            e.register("data-adapter:main", t.DebugAdapter)
        })(e),
        function(e) {
            e.register("transform:boolean", c.default), e.register("transform:date", l.default), e.register("transform:number", a.default), e.register("transform:string", u.default)
        }(e),
        function(e) {
            var t = e.inject || e.injection
            t.call(e, "controller", "store", "service:store"), t.call(e, "route", "store", "service:store"), t.call(e, "data-adapter", "store", "service:store")
        }(e),
        function(e) {
            var a = e.registerOptionsForType || e.optionsForType
            a.call(e, "serializer", {
                    singleton: !1
                }), a.call(e, "adapter", {
                    singleton: !1
                }), e.register("serializer:-default", r.default), e.register("serializer:-rest", i.default), e.register("adapter:-rest", s.default), e.register("adapter:-json-api", o.default), e.register("serializer:-json-api", n.default),
                function(e, t) {
                    return e.has ? e.has(t) : e.hasRegistration(t)
                }(e, "service:store") || e.register("service:store", t.Store)
        }(e)
    }
})
```

**Comment by devdemi** [comment] 2017-12-26 16:32
When I added to `ember-cli-build.js`:
```javascript
      'ember-cli-uglify': {
          enabled: false
      },
```
It starts to work well. So I go to `ember-cli-uglify` and it doesn't have new releases then I go to `broccoli-uglify-sourcemap` it also doesn't have new releases and it depends on `"uglify-es": "^3.1.3"`. And `uglify-es` has new release today. I think problem in new `uglify-es`

**Comment by rwjblue** [comment] 2017-12-26 16:47
Possibly. Did you double check if it is reported? If not, it would be a good idea to make a minimal reproduction to help track down the cause...

**Comment by kellyselden** [comment] 2017-12-26 19:26
We just started seeing this as well in one of our systems that doesn't respect the lockfile:

```
jQuery.Deferred exception: a29046 is not defined ReferenceError: a29046 is not defined
    at http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:6153:1
    at Object.e.default [as initialize] (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:6153:391)
    at http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1630:108
    at e.each (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1576:28)
    at e.walk (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1567:6)
    at e.each (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1557:157)
    at e.topsort (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1557:203)
    at o._runInitializer (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1634:3)
    at o.runInitializers (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1630:6)
    at o._bootSync (http://localhost:37375/dustbunny/assets/vendor-d09a11448bce4b24ff42f99908aa66c7.js:1600:10) null
```

I would say probably related and probably related to a floating dependency update.

**Comment by jdurand** [comment] 2017-12-27 03:10
This issue also hit me today. There's an issue with Uglify's `unused` rule. It seems like it mistakenly sees a variable (`var registerOptionsForType`) as unused in ember-data's `initializeStore` method.

This keeps most of the compression working while avoiding the issue with `unused`
```javascript
'ember-cli-uglify': {
  uglify: {
    compress: {
      unused: false
    }
  }
}
```

Here's the detail : 

```javascript
// source: ember-data 2.17.0
// ember-data/setup-container
function initializeStore(registry) {
  // registry.optionsForType for Ember < 2.1.0
  // application.registerOptionsForType for Ember 2.1.0+
  let registerOptionsForType = registry.registerOptionsForType || registry.optionsForType;
  registerOptionsForType.call(registry, 'serializer', { singleton: false });
  registerOptionsForType.call(registry, 'adapter', { singleton: false });

  registry.register('serializer:-default', JSONSerializer);
  registry.register('serializer:-rest', RESTSerializer);
  registry.register('adapter:-rest', RESTAdapter);

  registry.register('adapter:-json-api', JSONAPIAdapter);
  registry.register('serializer:-json-api', JSONAPISerializer);


  if (!has(registry, 'service:store')) {
    registry.register('service:store', Store);
  }
}


// build: unmangled with `unused: true`
function(registry) {
  var applicationOrRegistry, fullName
  registerOptionsForType.call(registry, "serializer", {
    singleton: !1
  }),
  registerOptionsForType.call(registry, "adapter", {
    singleton: !1
  }),
  registry.register("serializer:-default", _json.default),
  registry.register("serializer:-rest", _rest.default),
  registry.register("adapter:-rest", _rest2.default),
  registry.register("adapter:-json-api", _jsonApi2.default),
  registry.register("serializer:-json-api", _jsonApi.default),
  fullName = "service:store",
  ((applicationOrRegistry = registry).has ? applicationOrRegistry.has(fullName) : applicationOrRegistry.hasRegistration(fullName)) || registry.register("service:store", _private.Store)
}


// build: unmangled with `unused: false`
function initializeStore(registry) {
  var registerOptionsForType = registry.registerOptionsForType || registry.optionsForType
  registerOptionsForType.call(registry, "serializer", {
    singleton: !1
  }),
  registerOptionsForType.call(registry, "adapter", {
    singleton: !1
  }),
  registry.register("serializer:-default", _json.default),
  registry.register("serializer:-rest", _rest.default),
  registry.register("adapter:-rest", _rest2.default),
  registry.register("adapter:-json-api", _jsonApi2.default),
  registry.register("serializer:-json-api", _jsonApi.default),
  has(registry, "service:store") || registry.register("service:store", _private.Store)
}
```

**Comment by devdemi** [comment] 2017-12-27 09:00
@jdurand did you report bug to https://github.com/mishoo/UglifyJS2 ? Your example helps guys to fix it.

**Comment by paulyoder** [comment] 2017-12-27 13:43
I reproduced this issue by running the following commands on ember-cli 2.17.2
```
ember new --yarn new-app
cd new-app
ember s --environment=production
```

**Comment by rwjblue** [comment] 2017-12-27 16:10
If this is an uglify issue, we need to reproduce as minimally as possible (e.g. without ember-cli) and report to https://github.com/mishoo/UglifyJS2.

Another possibly related issue is actively being tracked in https://github.com/mishoo/UglifyJS2/issues/2663, someone should dig in to see if it is the same general problem...

**Comment by jdurand** [comment] 2017-12-27 18:06
Yes, it's the same issue and it looks like @alexlamsl has plenty of examples to reproduce and fix this.

**Comment by ballPointPenguin** [comment] 2017-12-28 08:07
just ran into this today on both Windows and Linux machines, with latest node and npm and ember-cli packages.

**Comment by ronaldsuwandi** [comment] 2017-12-28 09:16
I think @ballPointPenguin is right, on our linux production machine this also breaks but works fine on a Mac

**Comment by kellyselden** [comment] 2017-12-28 15:40
At this point, there is no reason to keep this thread open. It has been fixed in uglifyjs and awaiting release. For those that missed it, the workaround mentioned by @jdurand is:

```js
'ember-cli-uglify': {
  uglify: {
    compress: {
      unused: false
    }
  }
}
```

You will have a slightly larger build size until the fix is released.

**Closed by kellyselden** 2017-12-28 15:40 UTC

**Comment by rwjblue** [comment] 2017-12-28 17:01
Alternatively, you can lock uglify-es to a known good version.

Also, all those that were affected should really look into setting up their projects with a lock file. The lockfiles used by either yarn or npm@5 would have prevented projects from getting the newer (and broken) version of uglify-es. When using lock files, this type of version drift only happens when _intentionally_ updating package versions (e.g. you submit a pull request to update deps to their latest versions).

**Comment by RuslanZavacky** [comment] 2018-01-07 19:09
I was hit hard by this issue as well, but kinda hard to reproduce with minimal setup.
