### ISSUE TITLE
Following the getting started throws error

### ISSUE THREAD

**Issue by luizkowalski** [ember-cli/ember-cli#6140] opened 2016-08-02 13:43 UTC
`ember version --verbose`

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

I just created an app and when run `ember s` I get the following

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: modules/ember-inflector/index.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/ember-inflector/index.js: Unknown option: /Users/luizeduardo/.babelrc.presets
    at Logger.error (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/luizeduardo/js_dev/super-rentals/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-babel-transpiler/index.js:94:21)
    at Babel.processString (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-babel-transpiler/index.js:123:25)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-persistent-filter/index.js:39:10)
    at new Babel (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/Users/luizeduardo/js_dev/super-rentals/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/Users/luizeduardo/js_dev/super-rentals/node_modules/ember-cli-babel/index.js:23:52)
    at /Users/luizeduardo/js_dev/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/luizeduardo/js_dev/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/luizeduardo/js_dev/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at CoreObject.extend.preprocessJs (/Users/luizeduardo/js_dev/super-rentals/node_modules/ember-cli/lib/models/addon.js:818:25)

```

**Comment by stefanpenner** [comment] 2016-08-02 14:00
babel is not backwards compatible with its .babelrc, and it seems for some reason the global RC file affects dependencies builds. Which sounds like a second babel bug.

Given:

```
Unknown option: /Users/luizeduardo/.babelrc.presets
```

I suspect removing that file will resolve the error.

Babel falling back to these global rc files, will result in potentially unexpected build outputs, or in cases such as these prevents builds from completing at all.

**Comment by stefanpenner** [comment] 2016-08-02 14:01
This should most likely also be raised to the babel folks, as it results in babel being a poor citizen when used within a dependency at build time.

cc @hzoo

**Comment by luizkowalski** [comment] 2016-08-03 08:30
you were right, deleted that file and worked
Thanks!

**Comment by stefanpenner** [comment] 2016-08-03 15:02
I'm going to keep this open, because I believe this to be part of a larger babel interopt issue.

**Comment by codered** [comment] 2016-08-30 19:09
I am having the same issue. 

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.5.0
v8: 5.1.281.81
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64

**Comment by codered** [comment] 2016-08-31 06:48
I have resolved this issue on my system (Mac OS)

The solution is as follows. 

1. Change the permission on your system as follow: **sudo chown -R $USER /usr/local** 
2. Re-install node using node package (dmg file)
3. Install ember using the quick start guide (**npm install -g ember-cli@2.7**) 

I do not get the error anymore and it works! 

**If someone else can verify this, we can close this ticket. I also thought it was an issue with Babel but it is only a permission error.**

**Comment by kamilogorek** [comment] 2016-09-06 11:43
@stefanpenner @codered I can confirm that this one is fixed and work as expected.

```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.4.0
v8: 5.0.71.60
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by nathanhammond** [comment] 2016-09-06 16:03
@codered @kamilogorek I suspect that the issues you're discussing are distinct from the original issue filed. No change has been made in our Babel setup.

**Comment by kamilogorek** [comment] 2016-09-06 19:00
@nathanhammond but there were changes to `broccoli-babel-transpiler` and `babel` itself. And because `ember-cli` is using `^` as semver range for `broccoli-babel-transpiler` it could be fixed along the way in mentioned lib.

**Comment by Turbo87** [comment] 2016-12-01 20:38
since the original issue apparently has been resolved and we're tracking Babel 6 compat in https://github.com/ember-cli/ember-cli/issues/5015 I'm going to close this issue

**Closed by Turbo87** 2016-12-01 20:38 UTC
Labels: Needs Dependency Fix

**Comment by hzoo** [comment] 2016-12-01 21:08
Let me know if need help with porting to Babel 6 @Turbo87 (or ping on our [slack](slack.babeljs.io))

**Comment by Turbo87** [comment] 2016-12-01 21:39
@hzoo we would definitely like help with that, although I have to admit that the main issues with that are currently on the Ember CLI side. specifically we need to handle the cases where some addons in an Ember app are using Babel 5 and some are using Babel 6. this might be easier to solve than I think, but last time I looked at it, it seemed like a non-trivial task.

as you can see in https://github.com/ember-cli/ember-cli/issues/5015 most of our custom Babel addons are already ported to Babel 6, but are currently unused due to the stuff mentioned above.

**Comment by hzoo** [comment] 2016-12-01 22:15
Hmm ok - yeah was hoping it was just a plugin 5->6 issue or something haha but let us know.
