### ISSUE TITLE
Nested Addons don't seem to add to Host App Filestructure

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#3884] opened 2015-04-11 21:24 UTC
Hi All!

I'm working on an addon system with mini-addons that can be used separately, but also are dependancies of one master addon.

Ie:

**Host App** >--depends on--> `master-addon`

`master-addon` >--depends on--> `mini-addon-1` & `mini-addon-2`

`mini-addon-1` and `mini-addon-2` both have Initializers in their `/app` directories

These initializers run when I serve `master-addon`'s dummy app, but don't run when I serve the **Host App**.

It appears that nested addons don't have their `/app` directory combined with the top level **Host App**.

Is there a way to achieve this?  I've searched through the issues and addon hooks and I can't seem to find anything...

Thankyou!

**Comment by stefanpenner** [comment] 2015-04-11 21:25
this is currently by design.

**Comment by stefanpenner** [comment] 2015-04-11 21:25
dupe of: https://github.com/ember-cli/ember-cli/issues/3718

**Closed by stefanpenner** 2015-04-11 21:25 UTC

**Comment by hhff** [comment] 2015-04-11 21:45
ok, thanks stef

**Comment by hhff** [comment] 2015-04-11 23:39
FWIW, to get around this, I moved my nested addons from "devDependencies" to "dependencies", in my master added, I manually invoke the `included` hook of the addon, like so:

```js
module.exports = {
  name: 'master-addon',

  included: function(app) {
    this.addons.forEach(function(addon){
      if (addon.name === "mini-addon") {
        addon.included.apply(addon, [app]);
      }
    });
  }
};
```

Not the nicest solution - but I thought it might help someone.
