### ISSUE TITLE
codemods removed comments from tests

### ISSUE THREAD

**Issue by larryh** [ember-cli/ember-cli#8758] opened 2019-07-16 13:15 UTC
Running the codemods removed a lot of comments from my QUnit tests. It appears the "rule" was to remove anything directly above a `module` statement.

Needless to say, codemods should leave comments alone.

BTW: Thanks for all of your work!

```
larry@larry-lap:~/RubyMine/BNC$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.11.0
node: 11.9.0
v8: 7.0.276.38-node.16
uv: 1.25.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
os: linux x64
6.9.0

Command 'yarn' not found, but can be installed with:

sudo apt install cmdtest

```

**Comment by rwjblue** [comment] 2019-07-22 22:19
Thanks for reporting! This is indeed bad 😢, would you mind helping us reproduce the issue (so we can get it fixed)?  I think the easiest way to help us track this down would be to submit a new test case for https://github.com/ember-codemods/ember-qunit-codemod.

Over in that repo, if you do:

```
git clone git@github.com:ember-codemods/ember-qunit-codemod
cd ember-qunit-codemod
yarn
yarn codemod-cli generate fixture convert-module-for-to-setup-test (with-leading-comments)
```

Then edit the new `transforms/convert-module-for-to-setup-test/__testfixtures__/with-leading-comments.input.js` and `transforms/convert-module-for-to-setup-test/__testfixtures__/with-leading-comments.output.js` files to have some resemblance to your content (I think any leading comment above an older style test may cause the issue?).

**Comment by larryh** [comment] 2019-07-25 22:04
Hi,

I was unable to clone the repository - I have attached the error message that I got. I've Googled around and tried stuff, but nothing has worked. I'm pretty sure it's an SSH issue, which is an area that I'm not up on, and only read about when I have to (kinda like regular expressions ;-), so I think it would take me a fair bit of time to figure out what is going on.

Unfortunately, I am waaaay behind on other work. (Aren't we all?) But, FWIW, that work is unpaid for a site that is intended to help others (without making any money) => I don't feel bad about bailing with just some images that I hope will help you.

The reason I mention the "unpaid/helping" work above is that I know a LOT of ember folks donate their time to help the ember cause, and I think it's kind of crappy to just expect them to do so without pitching in yourself.

So maybe the fact that I am "pitching in to help" elsewhere just alleviates some guilt on my part - I don't know.

Regardless, I have attached a bunch of images. A clone-failed one that shows my inability to clone the project, and 5 sample ones which clearly illustrate the problem: they are  basically a "diff" of the code, with the left pane showing the original, and the right pane showing the result of running the _ember-qunit-codemod_. I figure (hope) you should be able to re-create a sample failing test from this  in just a few minutes. 

Thanks for all of the work you do for Ember.


![clone_failed](https://user-images.githubusercontent.com/89646/61911610-974ee600-aefd-11e9-9a87-9028955c4522.png)
![sample_1](https://user-images.githubusercontent.com/89646/61911629-a33aa800-aefd-11e9-9be8-65fb8c2cf19f.png)
![sample_2](https://user-images.githubusercontent.com/89646/61911630-a6359880-aefd-11e9-8804-d8f08cca62e2.png)
![sample_3](https://user-images.githubusercontent.com/89646/61911633-a897f280-aefd-11e9-9c6b-277f52971462.png)
![sample_4](https://user-images.githubusercontent.com/89646/61911638-aafa4c80-aefd-11e9-84c8-072c11d4e5ee.png)
![sample_5](https://user-images.githubusercontent.com/89646/61911642-ad5ca680-aefd-11e9-8e64-ad5b1f615f88.png)

**Comment by locks** [comment] 2022-02-10 02:14
Thank you for all the detailed information! Following the breadcrumbs, this issue seems to be tracked at https://github.com/ember-codemods/ember-qunit-codemod/issues/198, and there is a linked PR with a fix that has been merged so I'm closing the issue.

**Closed by locks** 2022-02-10 02:14 UTC
