### ISSUE TITLE
ENOTEMPTY error on Windows

### ISSUE THREAD

**Issue by dwickern** [ember-cli/ember-cli#5067] opened 2015-11-11 21:10 UTC
Starting yesterday, my build fails 100% of the time on Windows CI.

Here's the error:
```
ENOTEMPTY: directory not empty, rmdir 'C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-output_path-SwhUQo8y.tmp'
Error: ENOTEMPTY: directory not empty, rmdir 'C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-output_path-SwhUQo8y.tmp'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at rmkidsSync (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\quick-temp\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at Function.rimrafSync [as sync] (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at Object.remove (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\quick-temp\index.js:26:12)
    at ReadCompat.cleanup (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-plugin\read_compat.js:69:13)
    at ConcatWithMaps.Plugin.cleanup (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-plugin\index.js:113:49)
    at cleanupTree (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:147:17)
Build failed.
ENOENT: no such file or directory, open 'C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-input_base_path-vEFR6ibn.tmp\0\C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-input_base_path-vEFR6ibn.tmp\0\ember-cli-active-link-wrapper\components\active-link.js'
Error: ENOENT: no such file or directory, open 'C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-input_base_path-vEFR6ibn.tmp\0\C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\tmp\concat_with_maps-input_base_path-vEFR6ibn.tmp\0\ember-cli-active-link-wrapper\components\active-link.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.addFile (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\fast-sourcemap-concat\lib\source-map.js:68:19)
    at ConcatWithMaps.<anonymous> (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\concat-with-maps.js:96:17)
    at Array.forEach (native)
    at ConcatWithMaps.addFiles (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\concat-with-maps.js:93:9)
    at ConcatWithMaps.build (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\concat-with-maps.js:65:8)
    at C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
```

Someone on SO may have found the cause:
http://stackoverflow.com/questions/33657172/ember-cli-cleanup-error-when-building

**Comment by kellyselden** [comment] 2015-11-11 21:16
duplicate of #5055, should be fixed now if you clear your node_modules.

**Closed by kellyselden** 2015-11-11 21:16 UTC
