### ISSUE TITLE
Travis builds fail with node 6 and yarn

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#8360] opened 2019-01-11 15:51 UTC
It seems that ip-regex sets an engine that is not compatible with node 6, which we use for travis tests.

`error ip-regex@3.0.0: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.16.0"`

Should we add `--ignore-engines` to the yarn install to avoid this sort of thing in the future? If so, I am happy to open a PR.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.7.1
node: 11.6.0
v8: 7.0.276.38-node.13
uv: 1.24.1
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
os: darwin x64
6.5.0-next.0
1.13.0
```

**Comment by rwjblue** [comment] 2019-01-11 15:55
Can you say more? Do you mean that ember-cli itself is failing, apps are failing, addons are failing, etc?

**Comment by rwjblue** [comment] 2019-01-11 16:31
In one of the affected systems can you `npm ls ip-regex`? Who is pulling it in as a dependency?

**Comment by rwwagner90** [comment] 2019-01-11 16:55
@rwjblue the output from that seems to be empty, so no idea 😂 

You can see the error in the build here https://travis-ci.org/shipshapecode/ember-math-helpers/jobs/478394676

Something in travis specifically must be pulling it in. It's not in my local yarn.lock

**Comment by rwjblue** [comment] 2019-01-11 17:32
I believe that this is the same issue that @pzuraq and I were chatting about last night. Basically a nested dependency of `ember-cli-addon-docs` (ember-cli-addon-docs > jsdom > tough-cookie > ip-regex) is now bringing in `ip-regex` which is not Node 6 compatible.

See https://github.com/ember-decorators/ember-decorators/pull/375 for a handy work around.

**Comment by Turbo87** [comment] 2019-01-12 13:31
this is caused by https://github.com/salesforce/tough-cookie/issues/140

**Comment by rwjblue** [comment] 2019-01-20 16:08
Closing here as there isn't much we can do about it in ember-cli itself...

**Closed by rwjblue** 2019-01-20 16:08 UTC

**Comment by rwwagner90** [comment] 2019-01-21 14:19
@rwjblue I was thinking we could add `--ignore-engines` to the default yarn blueprint to fix it. Thoughts?

**Comment by rwjblue** [comment] 2019-01-21 14:46
I'm not really in favor 🤔. Hiding the failure doesn't actually fix it...

**Comment by rwwagner90** [comment] 2019-01-21 15:41
@rwjblue sure thing. I think, in a lot of cases, engines are somewhat arbitrary though, and things really work still, but I suppose it's safer to not ignore the failure, so never mind 😃
