### ISSUE TITLE
"this" is undefined in preBuild & included hooks for addon

### ISSUE THREAD

**Issue by nullrocket** [ember-cli/ember-cli#7220] opened 2017-07-13 05:44 UTC
**this** seems to be undefined in the **preBuild** and **included** hook for addons. The **init** hook seems fine.

```
ember-cli: 2.15.0-beta.1
```

**Comment by stefanpenner** [comment] 2017-07-14 03:01
@nullrocket oh strange, mind providing a quick reproduction? Maybe a GH repo.

**Comment by trentmwillis** [comment] 2017-07-14 03:42
Unsure about `included`, but looks like `preBuild` just needs a context when invoked [during `processAddonBuildSteps`](https://github.com/ember-cli/ember-cli/blob/816b540e741345eeb54756c9f5c7a5304d6108da/lib/models/builder.js#L136-L138).

**Comment by stefanpenner** [comment] 2017-07-14 03:47
@bekzod looks like a regression introduced by https://github.com/ember-cli/ember-cli/commit/6650df901e75050fba5840459f60588d95a80a84  mind taking a look?

**Comment by bekzod** [comment] 2017-07-14 03:48
@stefanpenner sure

**Comment by nullrocket** [comment] 2017-07-14 03:49
Sure,
With ember-cli 2.14.0 I added a console.log to preBuild in index.js and get a this context.
[https://github.com/nullrocket/hasthis.git](https://github.com/nullrocket/hasthis.git)

With ember-cli 2.15.0-beta.1 same console.log in preBuild gets undefined.
[https://github.com/nullrocket/nothis.git](https://github.com/nullrocket/nothis.git)

**Comment by nullrocket** [comment] 2017-07-14 03:49
@stefanpenner  I was only a little slow :)

**Comment by bekzod** [comment] 2017-07-14 03:57
@stefanpenner this should fix it https://github.com/ember-cli/ember-cli/pull/7224 sorry for missing it before

**Comment by locks** [comment] 2020-03-31 16:14
The mentioned PR was merged at the time, so this should be addressed. Thank you!

**Closed by locks** 2020-03-31 16:14 UTC
Labels: bug
