### ISSUE TITLE
Vendor empty if ember-cli can't find an import

### ISSUE THREAD

**Issue by jrhe** [ember-cli/ember-cli#2914] opened 2015-01-07 00:37 UTC
If I have a file which ember-cli can't find in the styles tree it carries on silently and outputs an empty vendor.css

**Comment by stefanpenner** [comment] 2015-01-07 00:38
related  + partial dupe of: https://github.com/ember-cli/ember-cli/issues/2877

**Closed by stefanpenner** 2015-01-07 00:38 UTC
