### ISSUE TITLE
new my-app fails trying to open non-extant package.json in working dir (not app dir)

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [ember-cli/ember-cli#4320] opened 2015-06-22 16:55 UTC
This is on OS X 10.9.5 (Mavericks) with node 0.12.4, npm 2.11.3, ember 0.2.7.

The Installing Ember topic has a section called "Testing Your Installation". If those instructions are followed then after entering the command "ember new my-app", I see the following error:

```
~/trash/ember$
ember new my-app
version: 0.2.7
0.2.7

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
ENOENT, open '/Users/datihein/trash/ember/package.json'
Error: ENOENT, open '/Users/datihein/trash/ember/package.json'
    at Error (native)
```
I suspect that the path **should have been** `/Users/datihein/trash/ember/my-app/package.json`.

If I push past that and enter the command "ember server", I get the following error.

```
~/trash/ember/my-app$
ember server
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/datihein/trash/ember/my-app/Brocfile.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I worked around that (after some Googling) by installing bower (`npm install -g bower`) and then, in the `my-app` directory, doing an `npm install` and a `bower install`.

This is on OS X 10.9.5 (Mavericks) with node 0.12.4, npm 2.11.3, ember 0.2.7, and bower 1.4.1.

Perhaps if the first defect hadn't happened, then the second would also not have happened. 

Also, nothing in the install guide mentions bower, so I"m not sure whether I needed to install bower (i.e. if `ember new my-app` had worked, perhaps bower would have been installed automatically).

**Comment by dukex** [comment] 2015-06-22 19:46
Need be investigate why ember tried get package.json from the wrong path.

The problem with ```ember server``` it's about the missing ```npm install```, normally the ```ember new``` run it, but in your case the command ```new``` fail

**Comment by acorncom** [comment] 2015-06-22 20:44
Duplicate of #3776 ?

**Comment by stefanpenner** [comment] 2015-06-22 21:54
Seems like you have the wrong permissions set? Did you install npm with sudo?

**Comment by JeNeSuisPasDave** [comment] 2015-06-23 12:50
@acorncom It is very similar to #3776, except that the problem happens consistently ... it doesn't go away after a one-time or first-time failure.

**Comment by JeNeSuisPasDave** [comment] 2015-06-23 13:05
@stefanpenner I did install npm with sudo.

I have two accounts on the OS X machine, one is an admin account that I use for installing software and other privileged tasks. That account can sudo, and that is what I use to install node, npm and do any `npm install -g` tasks.

The other account is a standard user account and it cannot sudo. I use that account for all my normal work, including software development.

That standard user account is what I used to executed the `ember new my-app` command.

So I tried using the admin user to do `ember new my-app` and got an error while "Installing packages for tooling via npm". The error was thrown from ember-cli/node_modules/npm/lib/utils/locker.js:66 and was an error attempting to unlock "ember-cli-babel, which hasn't been locked".  Top of the stack was ember-cli/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:63:22


So next I did `sudo ember new my-app`. This time everything worked.

I then deleted my-app and tried again, still with the admin account but without sudo, just `ember new my-app`. Failed again with the unlock but not locked failure.

So there is definitely a privilege issue. It seems that I can only use ember-cli if I run with sudo.

**Comment by acorncom** [comment] 2015-06-23 13:17
@JeNeSuisPasDave I've been watching Ember CLI for a while and regularly see @stefanpenner mention that sudo installs of npm cause him a ton of problems. The third header under common issues here (http://www.ember-cli.com/#commonissues) lists ways to get Ember-CLI installed without sudo. Might be a good place to start ...

**Comment by stefanpenner** [comment] 2015-06-23 14:22
Please don't use sudo when working with node and npm, you will just have much pain :(

Chowning the location of node to a common group and user should enable this nicely

**Comment by JeNeSuisPasDave** [comment] 2015-06-24 03:05
@stefanpenner, @acorncom,

OK, I removed my existing node install (which was installed the naive way, using the pkg installer from the nodejs.org home page).

I did a local install of node and npm in my standard user account ... no admin user or sudo involved. After that I was able to do `ember new my-app` and `server my-app` without any errors.

*I don't understand whether the permissions thing is a node issue or an ember-cli issue. Given that the standard node install kit sticks node in a location that requires root privileges to modify, it seems that ember-cli needs to learn how to work under that configuration (where node was installed using sudo or
equivalent).*

FYI, to install node/npm I created an install script using inspiration from one of the gists at https://gist.github.com/isaacs/579814. The script looks like this:

```
#! /bin/bash
#

# Install node and npm from github.
#
# make sure the ~/local/bin directory exists and is in the path
# BEFORE you run this script
#
git clone git://github.com/joyent/node.git
cd node
git checkout tags/v0.12.5
./configure --prefix=/Users/datihein/local
make install
cd ..
#
git clone git://github.com/npm/npm.git
cd npm
git checkout tags/v2.12.0
make install
#
```

**Comment by stefanpenner** [comment] 2015-06-24 03:09
> Given that the standard node install kit sticks node in a location that requires root privileges to modify

this is a mistake

> it seems that ember-cli needs to learn how to work under that configuration (where node was installed using sudo or
> equivalent).

ember-cli should not run at privileges beyond that of the current user.

**Comment by stefanpenner** [comment] 2015-06-24 03:10
https://github.com/creationix/nvm or https://github.com/isaacs/nave are other options.

**Closed by stefanpenner** 2015-06-24 03:10 UTC
