### ISSUE TITLE
How to generate proper ES6 -> ES5 sourcemaps in final output file.

### ISSUE THREAD

**Issue by ankeshdave** [ember-cli/ember-cli#6066] opened 2016-07-13 17:12 UTC
I am trying to setup a dev environment for my team.
I am trying to debug `ember-cli application` using `Visual Studio Code` (Using Chrome debugging protocol)
The [Microsoft/vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug/) is able to connect to chrome tab(running the application) and its able to read the sourcemaps and i am able to setup breakpoints in actual source (`/app/` folder).

Issue is the source map to source (Actual ES6 source- `/app/`) mapping is not correct hence the debugger is not able to step through on proper lines. ( See issue Microsoft/vscode-chrome-debug#193 for detail discussion).

[This is my repository](https://github.com/ankeshdave/vsc-debug-embercli-repo) which has the proper setup/configuration to connect to VS code and debug.

Is there any configuration i am missing in `ember-cli-build.js` to generate proper sourcemaps relative to ES6 source files in `/app/` folders.
Is there any why to generate proper sourcemaps  by using a different plugin/transpiler/modifying pipeline etc...

---

Output from ember version --verbose:

```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64
```

**Comment by nathanhammond** [comment] 2016-07-13 17:55
@ankeshdave Have you been able to step through your source maps correctly inside of the Chrome inspector? I'd like to make sure that this is an issue with our generated source maps and not just inside of VS Code.

**Comment by nathanhammond** [comment] 2016-07-13 17:58
Also, it'd be easier for us to debug this if you used `ember new my-demo-app` so that we could identify exactly what changed in your version.

**Comment by Turbo87** [comment] 2016-07-13 18:01
@nathanhammond I think the issue is simply that we don't use sourcemaps at the moment due to performance reasons. From what I understand that is basically the reason why we are working on [fast-source-map](https://github.com/krisselden/fast-source-map/), to improve the performance impact and enable us to use sourcemaps.

**Comment by ankeshdave** [comment] 2016-07-13 19:57
@nathanhammond 
The source displayed in chrome is `similar` but not same as of the actual `ES6 File`. Hence I believe the transpiled file (from ES6--> ES5)has a different sourceMap.

Also i did not get your comment about the `Tommster Commit`. As for the change in the demo project ([My Repo](https://github.com/ankeshdave/vsc-debug-embercli-repo))

1. removed the `getting-started` node module from `package.json`
2. create a component `random-comments.js/.hbs`
3. Used this configuration to build the app ->[ember-cli-build.txt](https://github.com/ember-cli/ember-cli/files/362333/ember-cli-build.txt)

@roblourens Can you share your finding about how the sourceMaps are different (Issue Microsoft/vscode-chrome-debug#193)

**Comment by stefanpenner** [comment] 2016-07-13 20:00
@ankeshdave as mentioned above, we basically explicitly disable those very granular source-maps for performance reasons. We hope to enable them in the future, but the hit was sufficiently high that we decided not to subject our community to it yet. Although we do have WIP to attempt to address.

**Comment by msmyers** [comment] 2016-09-01 18:45
I would like to know the special sauce to opt-in to ES6 source maps. I understand that you have decided that they are too slow, but I'd like to make that decision for myself.

I have spent about 2 hours searching and trial/error for this config, and I have been unsuccessful.

**Comment by nathanhammond** [comment] 2016-09-02 05:53
@msmyers For which of the three JS transforms we do do you want source maps? There are a tremendous number of moving pieces in this to get _just_ right and being kinda wrong was worse than not trying.

https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L256

**Comment by msmyers** [comment] 2016-09-02 17:03
First of all, thank you so much for your response. Upon reading my message the next day, I realize that I was having a particularly frustrating day attempting to get my development environment and I came across more negatively than intended.

My ultimate goal is to have ES6 modules in chrome debugging. I've been able to get sourcemaps loaded as requirejs modules, but they are not in ES6.

I'd like to see a correlation between my ember-cli source code and chrome debuggable breakpoints.

`
//ember-cli-build.js
new EmberApp({

...


        babel: {
            compileModules: true,
            sourceMaps: true,
            whitelist: ['es6']},

        sourcemaps: {
            enabled: true,
            compileModules: true,
            extensions: ['js']
        },

        minifyJS: {
            options: {
                mangle: false,
                compress: false,
                compileModules: true,
                sourceMapIncludeSources: true, // defaults to true
                exclude: ["**/vendor.js"],
                sourceMapConfig: {
                    enabled: true,
                    compileModules: true,
                    extensions: ['js'] // defaults to [ 'js' ]
                }
            }
        }

...
});
`

**Comment by nathanhammond** [comment] 2016-09-02 17:12
We don't actually have the ability to trace through all of our transforms right now to give you a single correct source map. Not to mention that it's slow. You're going to be hamstrung either way; I recommend just becoming familiar with doing the mental transformation back out. (It doesn't take too long before you stop noticing–I don't anymore.)

Not to say we don't want to make this better, but this is below my radar until we start updating our build process wherein we will revisit this story.

**Comment by msmyers** [comment] 2016-09-02 17:14
I do not know how to contact you directly

I would like to donate these websites/domains to ember-cli:

www.emberjs.feedback
www.ember.feedback
www.ember-cli.feedback

**Comment by msmyers** [comment] 2016-09-02 17:18
Thanks for your response.

This is not the response I was hoping for, but I understand, accept it, and move on. 

Thank you for your time.

**Comment by nathanhammond** [comment] 2016-09-02 18:09
@msmyers But of course! Note that my "revisit this build story" is currently scheduled to start 10/1. We don't provide delivery dates for anything because open source, but investigation is starting soon™.

**Comment by Turbo87** [comment] 2017-02-16 10:28
@dwickern was this resolved by your PR?

**Comment by dwickern** [comment] 2017-02-16 16:59
This is fixed in ember-cli `v2.12.0-beta.1`

To enable babel sourcemaps, add the following to your `ember-cli-build.js`:
```
var app = new EmberApp(defaults, {
    babel: {
      sourceMaps: 'inline'
    },
});
```

**Closed** 2017-02-16 17:01 UTC
Labels: Needs Dependency Fix

**Comment by joukevandermaas** [comment] 2017-03-08 08:25
For anyone else trying to find the PR referenced above, it's #6458.

**Comment by peabnuts123** [comment] 2017-05-18 21:44
I'm not seeing any change with `babel: { sourceMaps: 'inline' }` in my `ember-cli-build` (as suggested above). On `ember-cli#2.13.0`. function generator I am trying to debug is still a giant switch-case state machine. Am I missing something? `ember-cli-build` is pretty vanilla as far as I can tell. Have restarted `ember server` and things.

**Comment by bjornharrtell** [comment] 2017-06-15 08:37
Also unable to verify this and I'm getting sourcemap to the transformed source as reported by @peabnuts123 regardless of the `sourceMaps: 'inline'` setting. My ember -v output is:

```
ember-cli: 2.13.2
node: 6.11.0
os: linux x64
```

@Turbo87 would you consider reopening this issue?

**Comment by dwickern** [comment] 2017-06-19 16:29
@peabnuts123 @bjornharrtell The option was broken in the switch to ember-cli-babel which happened around ember-cli 2.12 or 2.13. I opened a fresh PR to fix it again babel/ember-cli-babel#158

**Comment by Turbo87** [comment] 2017-09-17 09:55
@dwickern I'm not sure what exactly is happening but this still (or again?) doesn't seem to work properly for me 🤔 

```
"ember-cli": "^2.15.0",
"ember-cli-babel": "^6.8.2",
```

I'm still seeing the default sourcemaps even though I've set `sourceMaps: 'inline'`

**Comment by bjornharrtell** [comment] 2017-09-17 11:01
Same for me as for @Turbo87. Assumed I was doing something wrong but perhaps not.

**Comment by dwickern** [comment] 2017-09-17 18:05
Same issue here. I tracked it down to https://github.com/ef4/fast-sourcemap-concat/issues/39

**Comment by Turbo87** [comment] 2017-09-17 18:31
😞 

thanks for tracking this down though!

**Comment by rstudner** [comment] 2018-01-16 14:11
What is the functional difference in doing the above
```
    babel: {
      sourceMaps: 'inline'
    },
```
and the old canonical:
```
    'sourcemaps': {
      // enabled: EmberApp.env() !== 'production',
      enabled: true,
      extensions: ['js'],
    }
```

**Comment by erichonkanen** [comment] 2018-04-23 16:28
I too am wondering what is the difference between the two declarations that @rstudner has described?

**Comment by octo-topi** [comment] 2020-09-02 13:37
> I too am wondering what is the difference between the two declarations that @rstudner has described?

See [ember-cli](https://github.com/ember-cli/ember-cli/blob/c9320aeb9fb521887bd8fec8f722bef0608c9fe5/docs/sourcemaps.md) doc
> There are broadly two ways a source file will have sourcemaps attached.
    - Via an external map file
    - Inline, in Base64.
