### ISSUE TITLE
ember g acceptance-test in addon

### ISSUE THREAD

**Issue by fsmanuel** [ember-cli/ember-cli#3943] opened 2015-04-21 17:41 UTC
When i `ember g acceptance-test lazy-images` in an addon i get:
```bash
version: 0.2.3
The 'acceptance-test' blueprint does not support generating inside addons.
```

Is that expected behavior? Would be nice to have it in an addon as well.

**Comment by clekstro** [comment] 2015-04-21 23:16
I think this is a duplicate of https://github.com/ember-cli/ember-cli/issues/3860.

**Closed** 2015-04-21 23:30 UTC
