### ISSUE TITLE
ember-cli crashes whenever there is an error and you try to load a page in the browser.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9586] opened 2021-07-18 21:22 UTC
reproduction:

- classic build / no embroider
- `await import(someVariable)`  <- auto import forbids non-static await imports
- `ember s`
- load localhost:4200
- `ember s` crashes

Output from `ember version --verbose && npm --version && yarn --version`:
```
❯ ember version --verbose && npm --version && yarn --version
ember-cli: 3.27.0
node: 14.17.3
v8: 8.4.371.23-node.67
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: linux x64
7.7.5
1.22.10

```

**Comment by NullVoxPopuli** [comment] 2021-09-13 12:53
Having a template syntax error also causes this, like mismatched tags.

**Comment by Alonski** [comment] 2021-11-10 11:53
This is happening to me too.
This could be related: https://github.com/ember-cli/ember-cli/issues/9584

**Comment by locks** [comment] 2022-02-03 15:48
@NullVoxPopuli is this still happening?

**Comment by NullVoxPopuli** [comment] 2022-02-03 15:54
yes. quite obnoxious.
Wish I had time to fix.

**Comment by ef4** [comment] 2022-08-10 18:02
I cannot reproduce this. 

Made a newly-generated app with ember-cli 4.6. Tried it under node 14, 16, and 18.

Introducing a template syntax error never crashes the process.

**Comment by ef4** [comment] 2022-08-10 18:06
Nevermind, I figured out the reproduction. I was missing the part where it's not the rebuild that crashes, it's the HTTP request after the rebuild.

**Comment by kategengler** [comment] 2022-08-17 17:31
I believe this fixed by https://github.com/ember-cli/ember-cli/pull/9987/

**Closed** 2022-08-17 17:31 UTC

**Comment by NullVoxPopuli** [comment] 2022-08-17 18:14
hasn't been released yet tho?

**Comment by kategengler** [comment] 2022-08-17 18:41
@kellyselden is working on releases; we typically close issues upon merge of fixes
