### ISSUE TITLE
Ember-cli module resolution fails in beta and canary

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#4633] opened 2015-08-09 12:43 UTC
`Ember-split-view` addon component tests work in `ember-release` but fail in `ember-beta` and `ember-canary`

`
not ok 15 PhantomJS 1.9 - SplitViewComponent: it renders
    ---
        actual: >
            null
        message: >
            Error: Could not find module 'ember-split-view/components/split-view' imported from 'dummy/components/split-view'
        Log: |
    ...
`

All deprecations appear to be fixed, so is this a regression?

**Comment by hhff** [comment] 2015-08-09 12:47
jah i get this alot too - still unsure why this happens in beta / canary.

**Comment by BryanCrotaz** [comment] 2015-08-09 12:47
Here's my latest commit
https://github.com/BryanCrotaz/ember-split-view/commit/ff843687aedc74cdbceb9828824ebfd171ce0eba

**Comment by stefanpenner** [comment] 2015-08-09 16:47
Can someone put up a reproduction?

**Comment by BryanCrotaz** [comment] 2015-08-09 16:49
The commit I link to above shows this (only has about 5 tests) ember try:testall shows the problem in under 2 minutes

**Comment by stefanpenner** [comment] 2015-08-09 16:51
Thanks

**Comment by BryanCrotaz** [comment] 2015-08-09 16:52
and here's the build information: https://travis-ci.org/BryanHunt/ember-split-view/builds/74788320

**Comment by stefanpenner** [comment] 2015-08-09 16:59
I suspect something in your vendor is crashing. Likely some incompatible dependency. Preventing this addons modules from getting included.


There is an issue open to fix testem to display this error.

**Comment by BryanCrotaz** [comment] 2015-08-09 17:03
Without the fix in testem, how do we go about finding which dependency?

**Comment by stefanpenner** [comment] 2015-08-09 17:27
Running the test in the browser and looking at the console

**Comment by BryanCrotaz** [comment] 2015-08-09 17:37
What's the magic phrase I'm looking for there to tell me which module is causing the problem?

**Comment by stefanpenner** [comment] 2015-08-09 21:11
@BryanCrotaz errors in the console

**Comment by BryanCrotaz** [comment] 2015-08-09 21:54
`
import { keysFunc, create } from "ember-data/system/object-polyfills";

var EmberError = Ember.Error;  <==== Error here
var forEach = Ember.ArrayPolyfills.forEach;
var SOURCE_POINTER_REGEXP = /^\/?data\/(attributes|relationships)\/(.*)/; /**
`

Error is `Uncaught TypeError: Cannot read property 'forEach' of undefined` - does this mean the error is in ember-data?

**Comment by BryanCrotaz** [comment] 2015-08-09 22:07
Which testem issue are you referring to? I can't find one that's relevant. I've made a few contributions to testem ci mode, maybe I can have a go at it.

**Comment by stefanpenner** [comment] 2015-08-09 22:50
> Error is Uncaught TypeError: Cannot read property 'forEach' of undefined - does this mean the error is in ember-data?

you have an old version of ember-data, upgrade it and the problem will go away.

**Comment by stefanpenner** [comment] 2015-08-09 22:51
> @stefanpenner Which testem issue are you referring to? I can't find one that's relevant. I've made a few contributions to testem ci mode, maybe I can have a go at it.

don't recal which #, but basically we need to re-order the test files to testem can hook in earlier.

**Comment by BryanCrotaz** [comment] 2015-08-09 22:54
It's the one that's used by ember-cli! The addon doesn't use ember-data

**Comment by stefanpenner** [comment] 2015-08-09 23:39
> It's the one that's used by ember-cli!

ember-cli does not depend on ember-data

**Comment by stefanpenner** [comment] 2015-08-10 02:27
I don't believe this is an ember-cli issue, rather a bug in ember-data.

Closing for now.

**Comment by miguelcobain** [comment] 2015-08-11 19:56
> Can someone put up a reproduction?

This: https://github.com/miguelcobain/ember-select

If you comment `app.import('bower_components/syn/dist/syn.js');` in `ember-cli-build.js` the problem goes away.
What on earth could that import be doing? :confused:

**Comment by stefanpenner** [comment] 2015-08-11 20:03
i'll take a look at your example in abit @miguelcobain

**Comment by miguelcobain** [comment] 2015-08-11 20:06
Upgrading my ember-cli to 1.13.8 to see if the problem persists (hotel wi-fi :snail: ).

**Comment by miguelcobain** [comment] 2015-08-11 20:19
I can confirm that the problem persists in 1.13.8. Want me to push this updated version?

**Comment by xcambar** [comment] 2015-09-07 15:08
I've experienced it today:  Release, Beta and Canary builds failed for an ember-cli 1.13.8 app. If this helps, here's a pretty simple repo to reproduce https://github.com/xcambar/ember-cli-self-update/tree/v0.1.0. No external dep apart from `mockjax`, used solely in testing.

Removing ember-data (see this commit: https://github.com/xcambar/ember-cli-self-update/commit/db9b4508f3f9d0c54c603a75a45cf7b2603053f4) fixes the build.

---

> ember-cli does not depend on ember-data, if its in package.json of your addon or app then its your addon or app that depends on it.

@stefanpenner Using ember-cli 1.13.8, on a fresh app, `package.json` and `bower.json` __both__ include an entry `ember-data: 1.13.8`. Reproduction is as simple as `ember new et-voila`.

The blueprint agrees: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json and https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json

**Comment by rwjblue** [comment] 2015-09-07 15:13
@xcambar - You cannot use Ember Data 1.13.8 with Ember 2.x.  Updating to Ember Data 1.13.11 or latest 2.0.x should solve this issue.

**Comment by xcambar** [comment] 2015-09-07 15:23
@rwjblue This explains everything!

As the blueprints of ember-cli (1.13.8) include ember-data (1.13.8), then obviously, the release/beta/canary channels will fail because `ember-try` only updates ember and "forgets" ember-data.

This is certanly going to hurt us again, even if the the transition 1.13.x => 2.0.x is edgy.

What do you think should be done:
* nothing? _(meh...)_
* removing ember-data from ember-cli blueprints? _(yay!)_
* updating `ember-try.js` so ember-data and ember stay compatible? _(more sync, more work)_

**Comment by stefanpenner** [comment] 2015-09-07 15:48
why not just bump both ember and ember-data. This is working fine for many other addons.

**Comment by rwjblue** [comment] 2015-09-07 16:12
@stefanpenner - I believe that the point @xcambar is making is that a newly created addon (using latest published ember-cli version and addon blueprint) does not pass a Travis run, because we set it up to run against `release`, `beta`, and `canary` via `ember-try` (essentially `ember try:testall` split up amongst a few parallel builds in Travis).  All of the Ember channels we test against are 2.x, but ED is hard coded to 1.13.8 which definitely does not work with Ember 2.x.

As an aside, I think we should allowed drift within patch version for Ember and Ember Data. So that we don't have to release a new version of Ember CLI just for bumping to a patch version (in this case ED 1.13.11 does work with Ember 2.x so this would have solved it).

**Comment by stefanpenner** [comment] 2015-09-07 16:27
> newly created addon

ah, well then. addons depending on ember-data seems funky, I suspect this is an extremely rare case.

**Comment by BryanCrotaz** [comment] 2015-09-07 16:37
The ember-cli addon blueprint includes ember-data in the dependencies. This caught me out too.

**Comment by rwjblue** [comment] 2015-09-07 16:38
@stefanpenner - This is what we create by default.  Steps to reproduce:

```
ember addon foo-bar
cd foo-bar
ember try:testall
```

:boom:

**Comment by stefanpenner** [comment] 2015-09-07 16:40
@rwjblue i was saying, it is funky that they include it. We shouldn't include it by default.

**Comment by rwjblue** [comment] 2015-09-07 16:41
Ahh, gotcha. Yes, I agree.

**Comment by xcambar** [comment] 2015-09-07 16:57
If I may, I would say that Ember-Data being opt-out is funky.
And it is currently the case for both apps and addons.

**Comment by stefanpenner** [comment] 2015-09-07 17:55
> And it is currently the case for both apps

disagree

> addons.

agree

**Comment by stefanpenner** [comment] 2015-12-22 04:43
I suspect this is fixed, if not I will reopen if a repro on latest is provided

**Closed by stefanpenner** 2015-12-22 04:43 UTC
Labels: needs-investigation
