### ISSUE TITLE
"app.import()" fails in "included()" hook of addon -> addon relationship

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5747] opened 2016-04-06 11:51 UTC
I wanted to develop a new addon that provides a set of API adapters including `ember-simple-auth` authenticators. I've tried to add `ember-simple-auth@1.0.1` as a `dependency` to my `package.json`, but if I run `ember serve` now I get the following error:

```
app.import is not a function
TypeError: app.import is not a function
    at Class.module.exports.included (.../node_modules/ember-simple-auth/index.js:10:15)
```

the `ember-simple-auth/index.js` file looks like this: 

```js
module.exports = {
  name: 'ember-simple-auth',

  included: function(app) {
    this._super.included(app);
    app.import('vendor/ember-simple-auth/register-version.js');
  }
};
```

It seems that the `app` parameter that is passed to the `included()` hook doesn't have an `import()` method defined.

```
$ ember version
ember-cli: 2.4.3
node: 5.8.0
os: darwin x64
```

/cc @marcoow

**Comment by Turbo87** [comment] 2016-04-06 11:54
note that it works fine when `ember-simple-auth` is mentioned in `devDependencies`. it only breaks when it's in the `dependencies` hash.

**Comment by Turbo87** [comment] 2016-04-06 12:45
seems to be a duplicate of #3718

**Comment by rwjblue** [comment] 2016-04-06 12:48
See also recent RFC (number not handy :()

**Comment by Turbo87** [comment] 2016-04-06 12:53
looks like the following code currently can work around the issue:
```js
included: function(app) {
  this._super.included.apply(this, arguments);

  if (typeof app.import !== 'function' && app.app) {
    app = app.app;
  }

  app.import('...');
}
```

**Comment by nathanhammond** [comment] 2016-04-06 23:45
I'd say that this gets addressed in @kellyselden's future install/uninstall RFC. This is indeed functoining as intended and workarounds like this are still the suggested way of doing things.

**Comment by zackthehuman** [comment] 2016-04-07 02:34
Checking for `app.app` works great if your addon is the child of an addon which is the child of an app. If it's 3 layers deep, however, then you need to get `app.app.app`, etc. So YMMV with simply checking `app.app`.

**Closed** 2016-04-13 15:52 UTC
