### ISSUE TITLE
app.legacyFilesToAppend.push deprecation

### ISSUE THREAD

**Issue by Hirtenknogger** [ember-cli/ember-cli#5589] opened 2016-03-07 12:09 UTC
Regarding Issue #5537 which should cause a deprecation warning since 2.4.1 #5545 does not work.
![issue](https://cloud.githubusercontent.com/assets/9415779/13568892/e116164e-e464-11e5-849b-4d1c73ce98c9.png)
It says "Build successful" but it is not successful because the page is empty and does not load.

I use ember-material-lite in my package.json and it uses app.legacyFilesToAppend.push function to import vendor javascript. (https://github.com/mike-north/ember-material-lite/blob/master/index.js)

**Comment by zoot123** [comment] 2016-03-07 12:18
+1

**Comment by rwjblue** [comment] 2016-03-07 12:19
Please provide a simple demo project that we can use to track down what additional changes may be necessary.

**Comment by Hirtenknogger** [comment] 2016-03-07 12:27
Add "ember-material-lite": "0.1.14" in any project to your package.json and you see what i mean.

**Comment by ro0gr** [comment] 2016-03-07 19:55
@Hirtenknogger Actually demo project would be very handy here cause `ember-material-lite` requires to manually run `ember g ember-material-lite` in order to update bower and npm deps.

As for this issue, looks like the problem is that `componentHandlerShim` is merged after the rest of material lite components [vendor-with-material-lite.js](https://gist.githubusercontent.com/ro0gr/0672b30a8cf67b162c0e/raw/434563bae01bb983777f0df414555906ee7b1fd0/gistfile1.txt):

```javascript
...
      MaterialTooltip.prototype.mdlDowngrade;

  // The component registers itself. It can assume componentHandler is available
  // in the global scope.
  componentHandler.register({
    constructor: MaterialTooltip,
    classAsString: 'MaterialTooltip',
    cssClass: 'mdl-tooltip'
  });
})();

;(function () {
  'use strict';
  window._materialLiteRegistrations = [];
  window.componentHandler = {
    register: function (config) {
      window._materialLiteRegistrations.push(config);
    }
  }
...
```
Working on a fix now. 
Thank you for catching and reporting this issue.

**Comment by ro0gr** [comment] 2016-03-07 20:14
demo project with bug https://github.com/ro0gr/material-lite-test

**Comment by rwjblue** [comment] 2016-03-07 23:03
IMHO, the issue here is with ember-material-lite. The interspersing of app.import and array pushes is really bizarre, and I'm not sure how we can preserve that behavior.

**Closed** 2016-03-11 07:32 UTC
Labels: Bug
