### ISSUE TITLE
Ember hangs on JavaScript syntax error

### ISSUE THREAD

**Issue by khaled-s** [ember-cli/ember-cli#9826] opened 2022-03-24 04:03 UTC
ember server stuck on 
"building... [Babel: project > applyPatches]"
this happens when a JavaScript syntax error 

I have created a new project and I'm getting the same problem
things I tried to do:
1. delete watchman
2. reinstall package.json
3. upgrade to newer version
4. delete package-lock.json and node_module and reinstall
5. update nodejs, update npm

and nothing work, this problem started when I did "npm update" , my old projects still working but the new ones are not

ember: 3.28.5
node: 14.19.1
npm: 6.14.16

I'm using nodenv for nodejs

and this is the last few lines of debug log

```
 ember-auto-import:analyzer updating imports for secondproject/components/upload-fi/component.js, 179 +1m
  ember-auto-import:analyzer Ignoring an unparseable file +10ms
  broccoli-persistent-filter:Babel > [Babel: secondproject] [Babel: secondproject#3162 -> derivePatches#3163] found 0 files invalidated due to dependency changes. +13ms
  fs-tree-diff: [Babel: secondproject#3162 -> derivePatches#3163] invalidation reason: 
  fs-tree-diff: before Entry { relativePath: 'secondproject/components/upload-fi/component.js', basePath: '/tmp/broccoli-2028251l6a6zVNzKjEG/out-266-analyzer_ember_auto_import_analyzer', mode: 33204, size: 176, mtime: 1648093444681 }
  fs-tree-diff:  entryB Entry { relativePath: 'secondproject/components/upload-fi/component.js', basePath: '/tmp/broccoli-2028251l6a6zVNzKjEG/out-266-analyzer_ember_auto_import_analyzer', mode: 33204, size: 179, mtime: 1648093517521 } +0ms
  broccoli-persistent-filter:Babel > [Babel: secondproject] [Babel: secondproject#3162 -> derivePatches#3163] derivePatches duration: 2.03 ms {"patches":1,"entries":54,"invalidations":{"dependencies":0,"count":0,"duration":"0.16 ms"},"walk":{"entries":54,"duration":"1.35 ms"}} +0ms
  async-promise-queue: started, with concurrency=3 +1ms
  async-disk-cache get: /tmp/khaled/if-you-need-to-delete-this-open-an-issue-async-disk-cache/60752e0420d2d76e324ee36db6a8377a3f7bb400/37c1f9418ee002127298279720a594fd329cf087 +1ms
⠙ building...   broccoli-persistent-filter:babel:parallel-api [Babel: secondproject#3162 -> applyPatches#3164] transformString is parallelizable +1ms
2022-03-24T03:45:17.555Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/babel-plugin-htmlbars-inline-precompile/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/ember-cli-htmlbars/lib/colocated-babel-plugin.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/plugin-proposal-decorators/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/plugin-proposal-private-property-in-object/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/plugin-proposal-private-methods/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/plugin-proposal-class-properties/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/babel-plugin-debug-macros/src/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.556Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/babel-plugin-debug-macros/src/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.557Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/babel-plugin-module-resolver/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.557Z babel:config:loading:files:plugins Loaded plugin '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/plugin-transform-modules-amd/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
2022-03-24T03:45:17.557Z babel:config:loading:files:plugins Loaded preset '/home/khaled/projects/thisIsMy/secondproject/node_modules/@babel/preset-env/lib/index.js' from '/home/khaled/projects/thisIsMy/secondproject'.
```

**Comment by benedikt** [comment] 2022-03-24 07:27
I'm running into the same problem. The only thing that works is killing the process, figuring out what the syntax error might be, and then starting the server again.

**Comment by Windvis** [comment] 2022-03-24 22:04
We also started seeing this issue since a couple of days ago after updating our app. It doesn't seems to be related to the Ember update itself since I can reproduce it in any app that I generate today (tested 3.24 - 4.2). So it must be caused by some transitive dependency change. 

I did some debugging and I think it's related to the `@babel/parser` [v7.17.7](https://github.com/babel/babel/blob/main/CHANGELOG.md#v7177-2022-03-14) release which was released a bit more than a week ago. If I force the version to be 7.17.3 the process doesn't hang and I see an error message about the syntax error in the console again. The issue is also present in the `v7.17.8` release.

So for now I think you can try pinning you version until we figure out what causes the  issue in `@babel/parser`.

**Comment by khaled-s** [comment] 2022-03-25 02:00
yes the main problem is `@babel/parser` 
`npm instal` is updating all the packages with respecting semver, thus it's updating `@babel/parser` 

I solved this by using overrides for npm >= 8
```
"overrides": {
    "@babel/parser": "7.16.4"
  }
```
this will replace all versions of `@babel/parser` to "7.16.4"

or by using tag flag `npm install --tag`, this will keep all packages at the same version specified in the `package.json` without update

for both ways `package-lock.json` should be deleted with `npm_modules` folder

**Comment by chbonser** [comment] 2022-03-25 12:05
For the yarn users out there, just a reminder that overrides are handled

**Comment by rwjblue** [comment] 2022-03-30 20:11
Can someone provide some steps to reproduce the issue?

**Comment by rwjblue** [comment] 2022-03-30 20:17
Another thing to try, would be:

```js
CI=true JOBS=0 ember s
```

This would prevent the build pipeline from spawning child processes and to report errors directly to the console. I _suspect_ what is happening is that we are throwing an error in a spawned child process and our `workerpool`ing system doesn't do a ton to report those failures to the parent process. Using `JOBS=0` would cause that (possible) failure to actually fail in the main process, making the real problem clearer...

**Comment by benedikt** [comment] 2022-03-31 07:55
Running the server with `CI=true JOBS=0 ember s` doesn't really change anything. There are no error messages, it just hangs at "building..." until hitting CTRL+C when it changes to "cleaning up..." but still hangs indefinitely.

The only way to recover is killing the process, fixing the syntax error, and starting the server again.

**Comment by Windvis** [comment] 2022-03-31 08:04
@rwjblue To reproduce:

1. Generate a new Ember app. The version doesn't matter I tried versions between 3.24 and 4.3.
2. Start the app
3. Add a syntax error to a .js file and save it (I used `app/app.js`)
4. The process hangs on `building... [Babel: project > applyPatches]`

It also hangs when starting the app if it already has a syntax error somewhere so it's not limited to rebuilds only.

Forcing the version of `@babel/parser` to be lower than 7.17.7 "fixes" the problem.

**Comment by machty** [comment] 2022-04-05 18:06
I am modernizing my ember-navigator addon and I'm encountering this hanging behavior on `applyPatches` step.

Here is the branch that's hanging: https://github.com/machty/ember-navigator/tree/modernize-hang

You can repro with

```
yarn
ember s
```

The funny thing is if you check out the commit prior to this one, it'll build; the only difference is I deleted some test files and modified one.

**Comment by Windvis** [comment] 2022-04-08 11:33
It seems this has been fixed with the latest [broccoli-babel-transpiler release](https://github.com/babel/broccoli-babel-transpiler/releases/tag/v7.8.1). After updating I can't reproduce the issue anymore so you can safely unpin your `@babel/parser` dependency again.

Thanks @rwjblue!

**Comment by locks** [comment] 2022-04-20 00:33
Closing as solved according to last comment in the thread. Let us know if you're still encountering the problem even with the latest broccoli-babel-transpiler.

**Closed by locks** 2022-04-20 00:33 UTC
