### ISSUE TITLE
Illegal Operation on a Directory with Unknown Broccoli Plugin

### ISSUE THREAD

**Issue by li-xinyang** [ember-cli/ember-cli#6981] opened 2017-04-23 22:50 UTC
Output from `ember version --verbose && npm --version`:

```
ember-cli: 2.12.1
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
```

When I try `ember s` I have the following error,

```
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [object Object] failed with:
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:732:19)
    at tryReadSync (fs.js:487:20)
    at Object.fs.readFileSync (fs.js:535:19)
    at /Users/li-xinyang/Desktop/XX_MemoCycle_Firebase/node_modules/broccoli-flatiron/index.js:33:16
    at Array.forEach (native)
    at readDirectory (/Users/li-xinyang/Desktop/XX_MemoCycle_Firebase/node_modules/broccoli-flatiron/index.js:28:31)
    at /Users/li-xinyang/Desktop/XX_MemoCycle_Firebase/node_modules/broccoli-flatiron/index.js:21:15
    at tryCatch (/Users/li-xinyang/Desktop/XX_MemoCycle_Firebase/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/li-xinyang/Desktop/XX_MemoCycle_Firebase/node_modules/rsvp/dist/rsvp.js:554:13)

The broccoli plugin was instantiated at:
undefined
```

Below is a list of `devDependencies` (click to expand),

<details>
  <summary>package.json File</summary>
<pre><code>
{
  "name": "memo-cycle",
  "version": "0.0.0",
  "description": "A study tool for serious learner",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.12.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-gravatar": "^3.8.1",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^3.1.0",
    "ember-cli-sass": "^6.1.2",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-export-application-global": "^1.0.5",
    "ember-in-viewport": "^2.1.1",
    "ember-inline-svg": "^0.1.10",
    "ember-load-initializers": "^0.6.0",
    "ember-paper": "^1.0.0-alpha.19",
    "ember-power-select": "^1.6.1",
    "ember-power-select-with-create": "^0.3.1",
    "ember-resolver": "^2.0.3",
    "ember-route-action-helper": "^2.0.2",
    "ember-simple-auth": "^1.2.2",
    "ember-source": "~2.12.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": ">= 4"
  },
  "private": true
}
</code></pre>
</details>

<br>

It was working fine before my last to commit. What I have done in the last two commits are I remove all `.DS_Store` files in the last commit and added Firebase deploy config files and install cloud function dependencies via Yarn in the last second commit.

What I have tried to resolve the issues, but the issue persists.

1) Delete all node modules via `rm -rf node_modules` and re-install them `npm install` (dependencies were installed via Yarn)

2) Remove the project and clone from the origin

3) Revert back to early commit (issue persists even I revert back to the `initial commit` and re-install all the dependencies of course)

4) Restart Mac 😅 

5) Update `.ember-cli` file

<details>
  <summary>.ember-cli File</summary>
<pre><code>
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": false,
  "liveReload" : true,
  "environment" : "mock-development"
}
</code></pre>
</details>

<br>

**Comment by hjdivad** [comment] 2017-04-24 10:54
@li-xinyang this looks like a problem in https://github.com/buschtoens/broccoli-flatiron

That plugin looks like it was built for an older version of broccoli, but the basic problem seems that its `write` function doesn't handle symlinks to directories.

Check out the body of the loop within [readDirectory](https://github.com/buschtoens/broccoli-flatiron/blob/master/index.js#L29-L33).  Note that `isDirectory()` will be false for a symlink to a directory, after which this code assumes it will be safe to `readFileSync`.

You may well be able to get away with just changing `lstatSync` to `statSync` to fix up that plugin.

**Comment by hjdivad** [comment] 2017-04-24 10:54
I'm going to close this as I'm fairly confident the problem is with broccoli-flatiron but @li-xinyang please reopen if you find that not to be the case.

**Closed by hjdivad** 2017-04-24 10:54 UTC
