### ISSUE TITLE
Attempting to inject an unknown injection: `service:xyz` with Ember 2.12.*

### ISSUE THREAD

**Issue by gnanavelum** [ember-cli/ember-cli#6945] opened 2017-04-07 01:04 UTC
>Ember test
fails with Attempting to inject an unknown injection: `service:xyz`

After 2.12 upgrade, i am upgrading from 2.8.

The actual page rendering all works fine, but tests fail...

**Comment by harpcio** [comment] 2017-04-10 15:11
We noticed 3 days ago strange behaviour on our Ember-cli 1.13.15. 
Multiple tests previously passed now ends with the error ie.: 
Attempting to inject an unknown injection: `router:main`

I tested it already both on Chrome with xvfb and PhantomJS.

**Comment by harpcio** [comment] 2017-04-10 15:44
Ok, we have npm list diff:
https://www.diffchecker.com/pbUyBoJ4

We think the problem is with ember-qunit@0.4.23

**Comment by Kuzirashi** [comment] 2017-04-10 16:04
With @harpcio we've found that ember-qunit@0.4.23 is source of problem.

Using npm shrinkwrap to lock ember-qunit at 0.4.22 fixed the issue.

**Comment by gnanavelum** [comment] 2017-04-10 16:54
I noticed that, if i specify all the services that the test component users should be specified in the 'needs' attribute, when i do that it works. I stayed on the same version of ember-qunit @ "0.4.16".

should i upgrade to 0.4.22?

**Comment by Kuzirashi** [comment] 2017-04-10 17:07
@gnanavelum 
What's the output of `npm list ember-qunit` for you? Maybe it's other package. I've pushed whole npm-shrinkwrap.json to teamcity and tests passed.

**Comment by gnanavelum** [comment] 2017-04-10 17:16
@Kuzirashi 
`-- ember-cli-qunit@3.1.2
  `-- ember-qunit@2.1.0

I did explicitly upgrade ember-cli-qunit to 3.1.1 from 2.1.0... part of my upgrade.

**Comment by stefanpenner** [comment] 2017-04-11 01:32
Is there a reproduction available?

**Comment by Kuzirashi** [comment] 2017-04-11 08:33
@gnanavelum 
I have rechecked and moved in shrinkwrap between ember-qunit 0.4.22 and 0.4.23 and now I'm sure that 0.4.23 was reason for our application to throw errors in 377 tests that router:main injection isn't defined and other dependencies for test modules also failed.

However, 14 hours ago ember-qunit released new version 0.4.24 which fixed the problem. Seems like this PR can tell more about the issue: https://github.com/emberjs/ember-qunit/pull/263.

@stefanpenner 
This issue probably can be closed as it shouldn't be no longer reproducible. At least for me after release of new ember-qunit.

**Closed** 2017-04-11 15:25 UTC

**Comment by devinrhode2** [comment] 2018-01-21 21:31
For some reason, in my application route, it seems I don't necessarily have to include certain services with the `serviceName: Ember.inject.service(),` syntax. I was getting this error (`Error: Assertion Failed: Attempting to inject an unknown injection: 'service:logr'`) only when running `ember test`. Other services I need to include, I'm not sure why but if I don't have the `serviceName: Ember.inject.service(),` the `get` will fail. My `logr` service (created when setting up ember-cli-sentry) and the i18n service I do not need to include this `inject.service()` line. I do need to include the `moment` service in order for that `get` to succeed.

PS:`ember test -f "Unit | Route | application"` and `ember test -m "Unit | Route | application"` worked well for isolating the test.

**Comment by Balaji4** [comment] 2018-06-14 07:36
I just added the required service "service:xyz" to the `needs` of my tests.

```
moduleFor('your-test', 'Unit | Controller | your-test', {
  needs: ['service:xyz']
});
```

**Comment by TheLooseCannon** [comment] 2020-04-02 13:35
@Balaji4 im confused where im supposed to add my needs in 

```
import { module, test } from "qunit";
import { setupTest } from "ember-qunit";

module("Unit | Route | xyz", function(hooks) {
    setupTest(hooks);

    test("it exists", function(assert) {
        let route = this.owner.lookup("route:xyz");
        assert.ok(route);
    });
});
```

and in this case...the issue is with my engine tests

**Comment by gouravtiwari** [comment] 2020-10-27 05:42
+1 to @TheLooseCannon I am also looking for a solution for module() function.

**Comment by rwjblue** [comment] 2020-10-27 12:43
Needs is dead. https://github.com/emberjs/rfcs/blob/master/text/0229-deprecate-testing-restricted-resolver.md
