### ISSUE TITLE
Tests failing on PhantomJS but not Chrome in 2.13.0 (that all passed in prior versions)

### ISSUE THREAD

**Issue by rstudner** [ember-cli/ember-cli#7001] opened 2017-04-30 20:24 UTC
```
ember version --verbose && npm --version && yarn --version
ember-cli: 2.13.0
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
0.23.2
```
PhantomJS is 2.1.1

Any component(model, etc) that does import _ from 'lodash'; now fails under testing only in PhantomJS.
Example failure:
```
not ok 326 PhantomJS 2.1 - Unit | Serializer | vendor device: it serializes records
    ---
        actual: >
            null
        expected: >
            null
        stack: >
            http://localhost:7357/assets/vendor.js:150785:50
            http://localhost:7357/assets/vendor.js:155188:24
            baseRest@http://localhost:7357/assets/vendor.js:150678:47
            createAssigner@http://localhost:7357/assets/vendor.js:152018:44
            http://localhost:7357/assets/vendor.js:156262:54
            exports@http://localhost:7357/assets/vendor.js:119:37
            _reify@http://localhost:7357/assets/vendor.js:153:66
            reify@http://localhost:7357/assets/vendor.js:140:33
            exports@http://localhost:7357/assets/vendor.js:117:15
            _reify@http://localhost:7357/assets/vendor.js:153:66
            reify@http://localhost:7357/assets/vendor.js:140:33
            exports@http://localhost:7357/assets/vendor.js:117:15
            requireModule@http://localhost:7357/assets/vendor.js:34:25
            _extractDefaultExport@http://localhost:7357/assets/vendor.js:139015:27
            resolveOther@http://localhost:7357/assets/vendor.js:138731:53
            superWrapper@http://localhost:7357/assets/vendor.js:65861:27
            resolve@http://localhost:7357/assets/vendor.js:30213:47
            _setupIsolatedContainer@http://localhost:7357/assets/test-support.js:10157:66
            setupContainer@http://localhost:7357/assets/test-support.js:9989:39
            http://localhost:7357/assets/test-support.js:8550:32
            initializePromise@http://localhost:7357/assets/vendor.js:73244:15
            Promise@http://localhost:7357/assets/vendor.js:73732:50
            nextStep@http://localhost:7357/assets/test-support.js:8549:51
            invokeSteps@http://localhost:7357/assets/test-support.js:8556:24
            setup@http://localhost:7357/assets/test-support.js:8503:32
            beforeEach@http://localhost:7357/assets/test-support.js:8311:46
            callHook@http://localhost:7357/assets/test-support.js:3331:26
            runHook@http://localhost:7357/assets/test-support.js:3325:15
            advance@http://localhost:7357/assets/test-support.js:2957:26
            begin@http://localhost:7357/assets/test-support.js:4648:27
            http://localhost:7357/assets/test-support.js:3842:11
        message: >
            Promise rejected before "it serializes records": Object is not a constructor (evaluating '(0, _lodash_defineProperty['default'])')
        Log: |
```

Bonus Weirdness:
Also -- I can alternate between ember test (always fails) followed by an ember test -s and get the phantomjs tests to pass (chrome always pass)
There are exactly 0 Ember.run's etc in the codebase :)  (and again, they all pass on my 2.12.2 and 2.12.3 branches)

<img width="426" alt="screen shot 2017-04-30 at 4 04 07 pm" src="https://cloud.githubusercontent.com/assets/209970/25567692/892dffd0-2dc1-11e7-8e55-bb6fec694196.png">
<img width="273" alt="screen shot 2017-04-30 at 4 02 37 pm" src="https://cloud.githubusercontent.com/assets/209970/25567693/8931f0d6-2dc1-11e7-9962-23bf02051bc7.png">

**Comment by stefanpenner** [comment] 2017-05-01 17:21
My guess is something is not being compiled correctly. Could you provide a reproduction?

**Comment by fusion2004** [comment] 2017-05-02 03:49
I'm seeing the exact same issue, though I think we're importing lodash differently than @rstudner. We use ember-browserify to import it, and I think this is the output it is not liking:
```javascript
  /**
   * The base implementation of `assignValue` and `assignMergeValue` without
   * value checks.
   *
   * @private
   * @param {Object} object The object to modify.
   * @param {string} key The key of the property to assign.
   * @param {*} value The value to assign.
   */
  function baseAssignValue(object, key, value) {
    if (key == '__proto__' && _lodash_defineProperty['default']) {
      (0, _lodash_defineProperty['default'])(object, key, {
        'configurable': true,
        'enumerable': true,
        'value': value,
        'writable': true
      });
    } else {
      object[key] = value;
    }
  }
```

I will try to make a repo with a reproduction.

**Comment by fusion2004** [comment] 2017-05-02 04:23
I tried to make a simple repo to reproduce (https://github.com/fusion2004/lodash-compilation-phantomjs), but I wasn't able to reproduce the issue!

From what I can see, the repo I just linked has the baseAssignValue function in the vendor.js defined once:
```javascript
/**
 * The base implementation of `assignValue` and `assignMergeValue` without
 * value checks.
 *
 * @private
 * @param {Object} object The object to modify.
 * @param {string} key The key of the property to assign.
 * @param {*} value The value to assign.
 */
function baseAssignValue(object, key, value) {
  if (key == '__proto__' && defineProperty) {
    defineProperty(object, key, {
      'configurable': true,
      'enumerable': true,
      'value': value,
      'writable': true
    });
  } else {
    object[key] = value;
  }
}
```

The output from the project that is being problematic has it defined in two places, one looks like the less problematic output from just above & the other looks like the more problematic code in my previous comment.

**Comment by josemarluedke** [comment] 2017-05-02 22:20
I'm also having this issue with our application when upgrading to Ember CLI 2.13 and ember-cli-babel 6.1.0.

**Comment by rwjblue** [comment] 2017-05-02 22:31
Just to echo what @stefanpenner mentioned above, a reproduction app would help us understand the underlying issue and solve this much faster...

**Comment by josemarluedke** [comment] 2017-05-02 22:58
@rwjblue I managed to get a reproduction app here: https://github.com/josemarluedke/ember-lodash-define-property-babel-polyfill

It seems that it starts breaking when adding the babel polyfill with:

```js
'ember-cli-babel': {
  includePolyfill: true
}
```

**Comment by rstudner** [comment] 2017-05-07 12:03
@josemarluedke - Did you ever figure out how to get around this?  (or was it as simple as: "do not includePolyfill: true anymore and everything worked going forward?)

**Comment by josemarluedke** [comment] 2017-05-07 19:18
@rstudner No, I didn't figure out how to keep the polyfill. I started working towards removing the need for our polyfill in our application, so that will solve my issue.

**Comment by simonihmig** [comment] 2017-05-08 09:37
Crosslinking this issue: https://github.com/mike-north/ember-lodash/issues/103

I think it is the same, whatever/wherever the root cause of this lies. I tracked it down as far as I could, would be nice if someone could have a look, maybe that helps. I am also using the polyfill in the app having these test failures, btw!

Is maybe the polyfill of Babel6 fiddling with the global `Object`, so it causes these exceptions I tracked down?

**Comment by simonihmig** [comment] 2017-05-08 09:43
I can confirm @josemarluedke's observations: I was not able to reproduce this in a minimal app as mentioned in the other issue (https://github.com/mike-north/ember-lodash/issues/103). As soon as I add the polyfill, it starts to fail!

**Comment by jrr** [comment] 2017-05-08 15:26
@josemarluedke 's repro presents the same symptom as my web app: `Object is not a constructor (evaluating '(0, _lodash_defineProperty['default'])')`

@rwjblue (ping) we have a repro now!

**Comment by john-griffin** [comment] 2017-05-10 12:11
Also just hit this upgrading to 2.13. It doesn't always fail in my app - tests pass about 10% of the time. Removing the `includePolyfill` setting causes the tests to hang.

**Comment by rwjblue** [comment] 2017-05-12 15:48
Going to try and poke more at this today with @rondale-sc...

**Comment by fotinakis** [comment] 2017-05-12 17:59
@rwjblue also just hit this in our app upgrading to 2.13 this morning, let me know if you need another app to poke at.

**Comment by simonihmig** [comment] 2017-05-12 20:33
@rwjblue just to make sure my hours are not lost, and you don't loose too much time as well, please have a look at my comment in the other issue: https://github.com/mike-north/ember-lodash/issues/103#issuecomment-299591281. I *guess* lodash's `isMasked` function returns true because of some modifications of the global `Object` caused by Babel's polyfill (core-js).

**Comment by rwjblue** [comment] 2017-05-12 23:06
Will be fixed by https://github.com/mike-north/ember-lodash/pull/104.  Many hours have been spent on this 😭 .

**Comment by eturino** [comment] 2017-05-15 09:41
I now see
```
Object is not a constructor (evaluating '(0, _defineProperty.default)')
```

**Comment by rwjblue** [comment] 2017-05-15 13:37
@eturino - Can you double check that things are linked up properly?  The reproduction that @josemarluedke provided is working when installing from master branch (checkout https://github.com/josemarluedke/ember-lodash-define-property-babel-polyfill/pull/1 locally to confirm). You might also want to `npm ls ember-lodash` to see if you have multiple versions hanging around (one of which might not be linked).  If those things don't shed light on the problem I'll need another reproduction to dig into...

**Comment by simonihmig** [comment] 2017-05-15 16:20
Cross linking https://github.com/mike-north/ember-lodash/pull/105

**Comment by eturino** [comment] 2017-05-15 17:04
mike-north/ember-lodash#105 fixed my issue! //cc @rwjblue @simonihmig

**Comment by jrr** [comment] 2017-05-17 16:13
FYI everyone ember-lodash released v4.17.3 today with the fixes discussed in this thread. It's working for us!

**Comment by rstudner** [comment] 2017-05-17 16:15
Huge thanks to @rwjblue @simonihmig @josemarluedke and anyone else who solved this. It must have been a bear to track down.

**Comment by rwjblue** [comment] 2017-05-17 17:14
Glad thats behind us 😩

**Closed** 2017-05-17 17:14 UTC
Labels: On-going investigation
