### ISSUE TITLE
ember new fails on commit when signing commits with GPG

### ISSUE THREAD

**Issue by daniel-archer-hs** [ember-cli/ember-cli#6920] opened 2017-03-29 02:29 UTC
Running `ember new ember-app` when global commit signing is enabled fails the ember new process..

Here's the issue in the output:

```
Error creating new application. Removing generated directory `./ember-app`
Command failed: git commit -m "Initial Commit from Ember CLI v2.12.1

                                                        _...,
                                                     ,:^;,...;
              -+===;.         ,,--++====++-,,,     .:  /.....,
            :::::~+++++#:,+#++++++++++++++++++#*..:   /,......
           (,,,,,,::=+++##++++++++++++++++++++++#.   :....../
            ...,,,,,::++++++++++++++++++++++++++++++*..,...:
            *..+...,#@@@@@@@@@++++++++++++++++++++++#*....*
              @#,;##############@@@+*+#@@@@@@@@@@#*++#..<
              *@##@@+,-*^^^*-+@####@@@######@@@#####@@,,,+
                @#@*            @#@@@@#@@+--*^^*--#@@@@@@#
                @#@.    @#      @##+++@#,           .@@#@@
                 #@#    @@     +@@++++#@@     @@     :@@
                 :@#*         @#@++++++@#*    #@     @@+
                :*+@@#;,.__.+@#@+,-^^.++@#          @@++
               ;*  :*@@@##@@@@;++r._j^.+@##@+,.__,,@@++.
              /*    ........+++++++++++++#@@@@@###@@#++++,
            ,:       ...,@@@#++===----==@@@####,,....+++++
           .:       ......@@##@\   ;   :@####@,,...... +++.
           ;       .........@###,   ;  ;xx#@;,,.....   *;+,
           |       ........,*;xxxx--^--=xxx,........   :+#;
           ;         ......,,;xxxxxxxxxxxxx;,.....     *+#
            ;          ......,::xxxx;.     ......       +.   .
             *;            .........  +###  ....       / ,. /:| ,.
               .+:             ...  ;##++##, .      ,#. (..v..;*./
                  **                ##  ###*    .:*&&&+. \.,....<,
                   #&+**==-..,,__  ;##  ###  :,*+&&&&&&&v+#&,,.._/
                  #&&&&*...,::,,.  ##; ,##* .*****;:&&&&&&&&&
                 ,+*+;~*..*** *.* ### ###* *******    *+#&;*
                                  ##,;##    ****    :,  **
         #####    ##   ###  ###,  ########       .#####   ;##  ##
        #######  ;##  #### ,###.  ##########    ########  ### ####
       ###  ###  ### ##########   ####  ####   ,##   ###  #######*
      ### ,###  ##############:   ##     ###  #### ,##   :#### ###  ##;
  ##########    ########### ##   .##    ,###  #######    ##### :######
    ######    .###### ####  ##   ###    ### ######*    :#####   ####
       #############  ####  ################    ######## ###
        #####*  *#*    #:   :###   *###*         *####    #*
"
error: gpg failed to sign the data
fatal: failed to write commit object

Error: Command failed: git commit -m "Initial Commit from Ember CLI v2.12.1

                                                        _...,
                                                     ,:^;,...;
              -+===;.         ,,--++====++-,,,     .:  /.....,
            :::::~+++++#:,+#++++++++++++++++++#*..:   /,......
           (,,,,,,::=+++##++++++++++++++++++++++#.   :....../
            ...,,,,,::++++++++++++++++++++++++++++++*..,...:
            *..+...,#@@@@@@@@@++++++++++++++++++++++#*....*
              @#,;##############@@@+*+#@@@@@@@@@@#*++#..<
              *@##@@+,-*^^^*-+@####@@@######@@@#####@@,,,+
                @#@*            @#@@@@#@@+--*^^*--#@@@@@@#
                @#@.    @#      @##+++@#,           .@@#@@
                 #@#    @@     +@@++++#@@     @@     :@@
                 :@#*         @#@++++++@#*    #@     @@+
                :*+@@#;,.__.+@#@+,-^^.++@#          @@++
               ;*  :*@@@##@@@@;++r._j^.+@##@+,.__,,@@++.
              /*    ........+++++++++++++#@@@@@###@@#++++,
            ,:       ...,@@@#++===----==@@@####,,....+++++
           .:       ......@@##@\   ;   :@####@,,...... +++.
           ;       .........@###,   ;  ;xx#@;,,.....   *;+,
           |       ........,*;xxxx--^--=xxx,........   :+#;
           ;         ......,,;xxxxxxxxxxxxx;,.....     *+#
            ;          ......,::xxxx;.     ......       +.   .
             *;            .........  +###  ....       / ,. /:| ,.
               .+:             ...  ;##++##, .      ,#. (..v..;*./
                  **                ##  ###*    .:*&&&+. \.,....<,
                   #&+**==-..,,__  ;##  ###  :,*+&&&&&&&v+#&,,.._/
                  #&&&&*...,::,,.  ##; ,##* .*****;:&&&&&&&&&
                 ,+*+;~*..*** *.* ### ###* *******    *+#&;*
                                  ##,;##    ****    :,  **
         #####    ##   ###  ###,  ########       .#####   ;##  ##
        #######  ;##  #### ,###.  ##########    ########  ### ####
       ###  ###  ### ##########   ####  ####   ,##   ###  #######*
      ### ,###  ##############:   ##     ###  #### ,##   :#### ###  ##;
  ##########    ########### ##   .##    ,###  #######    ##### :######
    ######    .###### ####  ##   ###    ### ######*    :#####   ####
       #############  ####  ################    ######## ###
        #####*  *#*    #:   :###   *###*         *####    #*
"
error: gpg failed to sign the data
fatal: failed to write commit object

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Turbo87** [comment] 2017-03-29 17:29
@daniel-archer-hs what do you expect to happen instead?

**Comment by merwan** [comment] 2017-03-30 10:55
I encounter the same issue as I configured git to sign all my commits using `gpgsign = true` on my global git config file.
I would expect that this first commit is not signed as it's done automatically by a tool. I suggest passing the `--no-gpg-sign` option to `git commit`. I can provide a PR for this.

**Comment by Turbo87** [comment] 2017-03-30 15:31
Does that option work fine if gpg has not been configured too? If so then a PR for that would be very welcome! Thanks for looking into this!

**Comment by topaxi** [comment] 2017-03-30 16:11
I've enabled signing too and it works flawlessly for me.

**Comment by merwan** [comment] 2017-03-30 20:08
Actually, I cannot reproduce the issue on my other machine. I will investigate the root cause and will let you know my findings.

**Comment by merwan** [comment] 2017-04-02 19:00
I identified the cause of this issue.
The first git commit is done with the email `GIT_COMMITTER_EMAIL='tomster@emberjs.com'` (https://github.com/ember-cli/ember-cli/blob/v2.12.1/lib/tasks/git-init.js#L58). If the git configuration setting `user.signingkey` is not set, then git tries to find a signing key for `tomster@emberjs.com`which result in an error as no key correspond to this email.
To avoid this error, the user has to explicitly set `user.signingkey` to a valid key in the gitconfig file.

I don't know if we should change something in ember-cli code - for example disabling signing for the first commit - or if it should be considered as a user misconfiguration of the git client.

**Comment by Turbo87** [comment] 2017-04-02 19:09
I think disabling signing for that initial commit seems fine

**Comment by kellyselden** [comment] 2017-04-03 01:12
Or using the user's git email. Would that be better than disabling signing?

**Comment by rwjblue** [comment] 2017-04-03 03:29
Is there a way (via command line) to disable signing? I vaguely thought there was (and if so we can add that arg to avoid this issue)...

**Comment by twokul** [comment] 2017-04-03 03:37
@rwjblue `git -c commit.gpgsign false init <repo-name>` should do the trick I think

**Comment by merwan** [comment] 2017-04-03 09:27
I would rather change the committer info so that the initial commit is still authored by emberjs but it is committed by the user.
@Turbo87 What would you prefer? Disabling signing with the `git --no-gpg-sign` parameter or removing the `GIT_COMMITTER_*` environment variables when doing the initial commit? I will provide a PR for any of those two suggestions.

**Comment by Turbo87** [comment] 2017-04-03 09:51
I wouldn't want to decide this alone, but I think I'd prefer the second solution (committing as correct user)

**Closed** 2017-05-02 17:01 UTC
Labels: Bug
