### ISSUE TITLE
Adding support for proxy for ember test

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3227] opened 2015-02-08 06:11 UTC
Testem supports proxies however when using ember test there is no way to specify a proxy location.

Would it be possible to allow configuration of tests to allow communications through a proxy?

Providing this feature would vastly speed up the ability to test communications to other systems (I was tempted to write a quick plugin to spin up and pull down a dev server at the same time as the tests)

**Comment by joostdevries** [comment] 2015-02-08 13:50
@jonathanKingston can't you just use `testem.json` for this?

**Comment by jonathanKingston** [comment] 2015-02-08 15:00
@joostdevries I should have explained, I tried this and it didn't work. Has anyone had look doing this?

I tried both:
```
  "proxies": {
    "/modelname": {
      "target": "http://localhost:8000"
    }
  }
```

and

**Comment by joostdevries** [comment] 2015-02-08 15:36
@jonathanKingston could you please be a bit more specific: what didn't work? Did you get an error? What is your test code?

**Comment by jonathanKingston** [comment] 2015-02-08 17:09
So I mocked up a quick example as what I was testing was much more lengthy.

app/models/thing.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string')
});
```

tests/unit/models/thing-test.js
```
import startApp from '../../helpers/start-app';
import {
  moduleForModel,
  test
} from 'ember-qunit';

var App;

moduleForModel('thing', 'Thing', {
  // Specify the other units that are required for this test.
  setup: function() {
    App = startApp();
  },
  teardown: function() {
    Ember.run(App, 'destroy');
  }
});

test('it exists', function() {
  Ember.run(function () {
    var store = App.__container__.lookup('store:main');

    var me = store.find('thing');
    console.log(me);
    ok(!!me);
  });
});
```

testem.json
```
{
  "framework": "qunit",
  "test_page": "tests/index.html",
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ],
  "proxies": {
    "/": {
      "target": "http://localhost:8000"
    }
  }
}
```


Running `ember test --serve` and in the network panel checking the message to: `http://localhost:7357/things` with and without proxy:
```
Error: ENOENT, stat '/home/jonathan/tinkering/emberSample/tmp/class-tests_dist-DUsqQ84n.tmp/things'
    at Error (native)
```


Sample app:
```
var http = require('http');

var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/json"});
  response.end('{"Response": true}');
});

server.listen(8000);
```

Opening the browser to `localhost:8000/things` returns the expected result.

---

I previously tried and failed to track down through the testem codebase where it was picking up the config for the proxy and checking if it was, I might try doing that again; I can confirm however it is picking up the correct config file in the testem npm.

**Comment by joostdevries** [comment] 2015-02-08 20:22
@jonathanKingston I cannot reproduce (it works fine here except for a small change to testem because they broke proxying in their last release. But since that gave me a big nasty error I'm assuming that's not the problem here).  What version of testem + Ember CLI are you using?

**Comment by jonathanKingston** [comment] 2015-02-08 22:44
@joostdevries sorry for the delay.

Eslint:
```
version: 0.1.2
node: 0.11.15
npm: 2.1.4

```

Testem is installed in this path: `node_modules/ember-cli/node_modules/testem/package.json`
0.6.22

---

Will update to the latest ESLint now and globally install testem (This should be the same as the setup on my other machine but will check now)

**Comment by jonathanKingston** [comment] 2015-02-08 22:48
I'm using Ubuntu 14.10 and 14.04 both produce the same results.

**Comment by jonathanKingston** [comment] 2015-02-08 23:10
Ah yes as my other computer was getting with 0.1.12:

The request gets a 404 with:
```
Not found: /things
```

**Comment by joostdevries** [comment] 2015-02-09 06:33
Ok so this turns out to be an issue with testem which is fixed in `v0.6.38`. Could you manually install v0.6.38 and verify that it works?

**Comment by jonathanKingston** [comment] 2015-02-09 21:17
So there was no error before as referenced in the testem bug referenced in #3232.

Running:
`cd node_modules/ember-cli/; npm install testem@0.6.38`

Then rerunning the test again the testem server interface in the browser returns the server output instead of the test interface, eg: http://localhost:7357/7718
`{"Response": true}`

Surely it should not be that the whole interface gets proxied?

**Comment by johanneswuerbach** [comment] 2015-02-10 14:24
Proxing `/` does not make really sense for me and is not supported at the moment. Could you explain me your use-case?

A config to proxy all requests starting with `/api` (e.g. `/api/users`, etc.) to your backend, would look like this:
```json
{
  "proxies": {
    "/api": {
      "target": "http://localhost:8000"
    }
  }
}
```

In `0.6.38` only get request were proxied, `0.6.39` proxies all requests again (sorry about that).

**Comment by jonathanKingston** [comment] 2015-02-10 23:28
The use case is having a server that doesn't have a set prefix like that.

For example I have server paths that are out of my control but all served from the same routing server, paths similar to:
```
'user/create'
'client/create'
'payment/pay'
```

Ember allows for the same style proxy behaviour so the application is shaped around having a series of API points at the base of the URL. Content negotiation will be used to serve on live the API vs the HTML of the Ember.

The main advantage for me really is that we can use REST style URLS with content negotiation to have a consistent interface for the application. So `/user/create` via HTML returns the ember app for the representation of the API request `/user/create`.

Sure the API could be rerouted to come from a subpath but that is how it currently operates. Surely Ember applications shouldn't dictate the behaviour of applications API's, there is already a big enough hurdle of making an adapter and serializer that match the API requests.

**Comment by johanneswuerbach** [comment] 2015-02-11 06:30
@jonathanKingston thank you. Makes sense to me. Could you create an issue at the https://github.com/airportyh/testem I'll look into this as soon as possible.

**Comment by jonathanKingston** [comment] 2015-02-11 19:40
@johanneswuerbach - Closing in favour of this ticket: https://github.com/airportyh/testem/issues/496

Thanks both for your help with this.

**Closed** 2015-02-11 19:41 UTC
