### ISSUE TITLE
`addBowerPackages` is useless for some bower-packages as bower's programmatic API seems broken

### ISSUE THREAD

**Issue by fpauser** [ember-cli/ember-cli#6419] opened 2016-11-08 09:41 UTC
Bower issue: https://github.com/bower/bower/issues/2387

This is a very annoying bower-bug which breaks the otherwise great 'ember-addon-user experience'. Maybe we can work around this by changing `addBowerPackagesToProject` to use bowers CLI interface?

**Comment by stefanpenner** [comment] 2016-11-08 19:17
> to use bowers CLI interface?

I suspect it will be more constructive / good use of our time to address this upstream.

**Comment by locks** [comment] 2020-03-28 22:19
Closing as the issue is no longer relevant due to the deprecation of Bower.

**Closed by locks** 2020-03-28 22:19 UTC
