### ISSUE TITLE
Newly generated addon with one component won't compile

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4436] opened 2015-07-13 12:04 UTC
Running `ember addon test-addon --skip-git && cd test-addon && ember g component test-component && ember test` on a windows system fails with _Addon templates were detected, but there are no template compilers registered_.

```
C:\Users\adminjfi.TESTUM\Desktop\Ember-Projekte>ember addon test-addon --skip-gi
t && cd test-addon && ember g component test-component && ember test
version: 1.13.1
installing addon
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create tests\dummy\app\app.js
  create tests\dummy\app\components\.gitkeep
  create tests\dummy\app\controllers\.gitkeep
  create tests\dummy\app\helpers\.gitkeep
  create tests\dummy\app\index.html
  create tests\dummy\app\models\.gitkeep
  create tests\dummy\app\router.js
  create tests\dummy\app\routes\.gitkeep
  create tests\dummy\app\styles\app.css
  create tests\dummy\app\templates\application.hbs
  create tests\dummy\app\templates\components\.gitkeep
  create bower.json
  create tests\dummy\config\environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create tests\dummy\public\crossdomain.xml
  create tests\dummy\public\robots.txt
  create testem.json
  create tests\.jshintrc
  create tests\helpers\resolver.js
  create tests\helpers\start-app.js
  create tests\index.html
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep
  create LICENSE.md
  create addon\.gitkeep
  create config\ember-try.js
  create config\environment.js
  create app\.gitkeep
  create index.js
  create .npmignore
Installing packages for tooling via npm...
C:\Users\adminjfi.TESTUM\Desktop\Ember-Projekte\test-addon\node_modules\ember-cl
i\node_modules\testem\node_modules\socket.io\node_modules\engine.io\node_modules
\ws>if not defined npm_config_node_gyp (node "C:\Users\adminjfi.TESTUM\AppData\R
oaming\npm\node_modules\ember-cli\node_modules\npm\bin\node-gyp-bin\\..\..\node_
modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Installing packages for tooling via npm
C:\Users\adminjfi.TESTUM\Desktop\Ember-Projekte\test-addon\node_modules\ember-cl
i\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_
modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (nod
e "C:\Users\adminjfi.TESTUM\AppData\Roaming\npm\node_modules\ember-cli\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Installed packages for tooling via npm.
Installed browser packages via Bower.
version: 1.13.1
installing component
  create addon\components\test-component.js
  create addon\templates\components\test-component.hbs
installing component-test
  create tests\integration\components\test-component-test.js
installing component-addon
  create app\components\test-component.js
version: 1.13.1
Building...
Addon templates were detected, but there are no template compilers registered fo
r `test-addon`. Please make sure your template precompiler (commonly `ember-cli-
htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `test-addon`'s
 `package.json`.
```

**Comment by rwjblue** [comment] 2015-07-13 13:07
We do not add ember-cli-htmlbars to the packages deps section intentionally, but we definitely should move it after generating anything with a template (a component in this case)...

**Comment by stefanpenner** [comment] 2015-07-13 14:57
cc @trabus

**Comment by trabus** [comment] 2015-07-13 15:17
I was just talking to someone on slack about this last week, and I know it's a tripping point for a lot of new addon developers. I'm definitely down to add this if it's blessed.

**Comment by rwjblue** [comment] 2015-07-13 15:18
:+1:

**Comment by stefanpenner** [comment] 2015-07-13 15:40
> I'm definitely down to add this if it's blessed.

:+1:

**Comment by trabus** [comment] 2015-07-13 17:07
Will try and get this done tomorrow, got a full day of work and a wedding this afternoon.

**Comment by stefanpenner** [comment] 2015-07-13 17:08
> Will try and get this done tomorrow, got a full day of work and a wedding this afternoon.

have fun at the wedding!

**Comment by trabus** [comment] 2015-07-15 16:03
I've got a good start on this, just need to account for corner cases and get some tests added. Will be making a PR this afternoon.

**Comment by pavloo** [comment] 2015-12-10 05:25
I have a similar issue, but even after adding `ember-cli-htmlbars` to dependencies in `package.json`, I still get template compilation error. I'm using `ember-cli` 1.13.13, my steps are:

1. created addon
2. generated component
3. ran `ember test`, and got an error
4. added `ember-cli-htmlbars` as it was said in error message
5. after running `ember test` still get template compilation error

**Comment by Turbo87** [comment] 2016-04-13 13:43
@trabus has this been solved at some point?

**Comment by nathanhammond** [comment] 2016-04-17 16:47
If anybody wants to bring home this functionality start from here:
https://github.com/ember-cli/ember-cli/compare/master...trabus:add-template-compiler-on-generate

It's close, but needs a rebase and tests.

**Comment by trabus** [comment] 2016-04-17 18:25
This needs to be fixed on ember-cli-legacy-blueprints if it hasn't already been fixed. I should have an hour to look at it tonight.

**Comment by trabus** [comment] 2016-04-17 18:29
Quickly looking at the error, it looks like the addon needs the htmlbars compiler moved to dependencies in the package.json

**Comment by nathanhammond** [comment] 2016-04-17 18:38
Yep, and that's something we want to automate upon generation of a template.

**Comment by trabus** [comment] 2016-04-17 23:13
Was trying to steal a moment to respond from my phone and I misread the (my) previous comments. Sorry for any confusion.

**Comment by stefanpenner** [comment] 2016-06-10 20:47
confirmed, this is still an issue with 2.6

**Comment by rennomarcus** [comment] 2017-10-18 18:08
Should this functionality still be here or in ember-source? From what I saw in the code, the Blueprint model in ember-cli calls the blueprint from ember-source. Over there, at the index.js of the component blueprint, one could add the `afterInstall()` hook.  Is this right?

**Comment by rwjblue** [comment] 2017-10-19 11:20
Yes

**Comment by rdhelms** [comment] 2018-05-24 18:37
Is this still in process? Looks like it hasn't been touched in a while, but still seeing this error in 3.1. Would really like to see that automatic movement of `ember-cli-htmlbars` to a dependency after `ember g component ... `

**Comment by Turbo87** [comment] 2018-05-24 18:39
@rdhelms would you like to work on this? happy to mentor you through it :)

**Comment by rdhelms** [comment] 2018-05-24 19:33
Haha I would be interested, to be honest - but would probably be a slow process as I have very little free time these days...but yeah if you can point me in the right direction I'd be happy to take a look.

**Comment by Turbo87** [comment] 2018-05-24 19:38
if I understand correctly the fix would have to be done in https://github.com/emberjs/ember.js/blob/master/blueprints/component-addon/index.js, where you could use an API like https://ember-cli.com/api/classes/Blueprint.html#method_addPackagesToProject to add the dependency to the package.json file.

**Comment by rdhelms** [comment] 2020-01-08 13:25
In case anyone else ever comes across this - just want to point out that I'm definitely not working on this nor have any plans to ever work on it 🙂Ran across this looking through old GitHub activity and wanted to make sure others knew it was fair game.

**Comment by snewcomer** [comment] 2020-09-04 22:44
This issue looks to be fixed!  Looks to come by default.

https://github.com/ember-cli/ember-cli/blob/0e4e318498aeb12da704c8a51bfc085cba0f1a15/blueprints/addon/index.js#L59

**Comment by rwjblue** [comment] 2020-09-16 14:17
Thanks for circling back to this @snewcomer!

**Closed** 2020-09-16 14:17 UTC
Labels: enhancement, good first issue
