### ISSUE TITLE
SyntaxError: illegal character on production deploy

### ISSUE THREAD

**Issue by ahmadqarshi** [ember-cli/ember-cli#6923] opened 2017-03-30 11:22 UTC
Couple of months ago I built and deployed my Ember application on the web server and it worked without any issue. However, today after executing `ember deploy production` when I deployed it I started getting 

_SyntaxError: illegal character_

There is no code change. However, few days ago I did upgrade npm and ember versions.

![image](https://cloud.githubusercontent.com/assets/5607132/24501819/149bb4f0-1543-11e7-9a58-52f5603273e9.png)

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.0
http_parser: 2.7.0
node: 6.9.5
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2k
os: win32 x64
npm: 3.10.10
```

**Comment by Turbo87** [comment] 2017-03-31 06:18
can you provide a repository that reproduces this issue? otherwise this will be hard/impossible to fix

**Comment by leondmello** [comment] 2019-08-11 19:40
Could this because of `nginx` (of whatever web server you are using) not serving `gzipped` files properly?
I followed [this post ](https://medium.com/@selvaganesh93/how-to-serve-webpack-gzipped-file-in-production-using-nginx-692eadbb9f1c) to ensure the `content-enconding` response header mentioned `gzip`h
I'm still seeing the same error thoug

**Comment by leondmello** [comment] 2019-08-11 20:02
ok, I was able to get it working by changing the file names to end with `.gz` so that the browser could decompress them properly.
Now I don't why `ember-cli-deploy-simply-ssh`/`ember-cli-deploy-gzip` aren't doig that automatically

**Comment by leondmello** [comment] 2019-08-17 01:02
Figured it out, had to change the keep property of the `gzip` plugin to be true and it all works now :smiley:

**Comment by locks** [comment] 2020-04-12 20:37
Closing as the issue seems resolved!

**Closed by locks** 2020-04-12 20:37 UTC
