### ISSUE TITLE
Tests in firefox failing

### ISSUE THREAD

**Issue by anehx** [ember-cli/ember-cli#6200] opened 2016-08-22 08:35 UTC
Output from `ember version --verbose`:
```
ember-cli: 2.8.0-beta.2
http_parser: 2.5.2
node: 4.4.5
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: linux x64
```

I have problems testing my ember app in firefox. I could manage to reproduce the issue creating a fresh ember app with the current beta version (stable results in the same error).

Steps to reproduce:

- `ember new test-app`
- `cd test-app`
- `ember generate route foo`
- Change `testem.js` to:
```javascript
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Firefox"
  ],
  "launch_in_dev": [
    "Firefox"
  ]
};
```
- Remove `ember-cli-jshint` in `package.json`
- `ember test`

This command should fail and print an error like this:
```
Built project successfully. Stored in "********/test-app/tmp/core_object-tests_dist-8jNshODi.tmp".
not ok 1 Firefox 48.0 - Browser "firefox -profile /tmp/testem-9253 http://localhost:7357/9253/tests/index.html?hidepassed" exited unexpectedly with exit code 0.

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (********/test-app/node_modules/ember-cli/node_modules/testem/lib/app.js:402:15)
    at EventEmitter.App.exit (********/test-app/node_modules/ember-cli/node_modules/testem/lib/app.js:163:23)
    at ********/test-app/node_modules/ember-cli/node_modules/testem/lib/app.js:157:14
    at tryCatcher (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (********/test-app/node_modules/ember-cli/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
(I replaced my home directory path with ********)

I have some other ember projects with older versions (2.3.0) which are working perfectly with firefox. I already tried to use the testem version of those projects (1.3.0) but it didn't change anything.

Thanks for watching into it..

**Comment by nathanhammond** [comment] 2016-08-22 17:43
@anehx [This test works for me](https://github.com/nathanhammond/issue-6200) following your instructions precisely. Can you try using that to reproduce?

I'm closing this issue as likely not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you have more questions.

**Closed by nathanhammond** 2016-08-22 17:43 UTC
Labels: Bug
