### ISSUE TITLE
kill <base href='smth'> or use it properly as in <base href='smth' />

### ISSUE THREAD

**Issue by zigotica** [ember-cli/ember-cli#4277] opened 2015-06-10 19:32 UTC
hi,

can we change the code for base tag (closing the element as in <base href='smth' /> would fix many issues at least for IE) or kill it anytime soon-ish with fire?

is there an easy way I can modify that base markup locally while there is no final killing of this?

thank you :D

**Comment by stefanpenner** [comment] 2015-06-10 20:17
If you search this repo. The code for this is in a single place. Fix it and if the tests stay green it will be merged. That way you fix it for all

**Comment by stefanpenner** [comment] 2015-06-13 19:02
can you elaborate on which IE issues this causes?

**Comment by stefanpenner** [comment] 2015-06-13 19:12
killing base is a duplicate of: https://github.com/ember-cli/ember-cli/issues/2633

Im closing this, as I am not aware of non XHTML issues with HTML5 void elements. If someone can demonstrate and issue, please share and I will open up.

**Closed by stefanpenner** 2015-06-13 19:12 UTC
