### ISSUE TITLE
ember-cli failing using citgm

### ISSUE THREAD

**Issue by GeorgeAdams95** [ember-cli/ember-cli#6382] opened 2016-10-24 09:11 UTC
I am getting the following failure on all our linux machines when running 
`citgm -v verbose -q error ember-cli`

```
Error: foo
# at Context.<anonymous> (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/tests/unit/cli/cli-test.js:563:48)
# at callFn (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runnable.js:326:21)
# at Test.Runnable.run (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runnable.js:319:7)
# at Runner.runTest (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:422:10)
# at /tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:528:12
# at next (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:342:14)
# at /tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:352:7
# at next (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:284:14)
# at Immediate.<anonymous> (/tmp/db6b2285-b063-44f0-b198-dae4258e23ad/ember-cli/node_modules/mocha/lib/runner.js:320:5)
# at runCallback (timers.js:637:20)
# The specified command fake-command is invalid. For available options, see `ember help`.
# The specified command fake-command is invalid. For available options, see `ember help`.
# The specified command fake-command is invalid. For available options, see `ember help`.
```

**Comment by nathanhammond** [comment] 2016-10-24 15:38
Hey @GeorgeAdams95! This seems likely due to the way `citgm` sets everything up or it could even be a legitimate failure in the most recent Node.js. As it stands this isn't a workflow that we have presently tried to support in any way and so it doesn't surprise me that it isn't working.

Properly setting expectations: support for `citgm` is not on our list of priorities and we won't be addressing this at all without your participation in the process. However, if it's important to you that this function, it's something that we would be willing to consider a PR for if you're willing to investigate and address. We'll happily help you through that process.

So, with that, I'm closing this issue as not a bug but _please feel encouraged to open a PR_ or continue discussion here. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

And if you wish to discuss further we all hang out in [#dev-ember-cli](https://embercommunity.slack.com/messages/dev-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and we can discuss your findings!

**Closed by nathanhammond** 2016-10-24 15:38 UTC
