### ISSUE TITLE
Failing test after generating Application serializer

### ISSUE THREAD

**Issue by leondmello** [ember-cli/ember-cli#5778] opened 2016-04-12 01:39 UTC
I generated an application serializer for a vanilla ember-cli generated app with the command,
```
ember g serializer application
```
When you run `ember test`, the auto generated test for the application serializer fails
```
Promise rejected before it serializes records: Attempting to register an unknown factory: `model:application`
```
I have generated [an example repository](https://github.com/leondmello/embercli_issue_4879)
This issue was previously mentioned in #4879

**Comment by nathanhammond** [comment] 2016-04-12 03:20
@leondmello Thank you so much for this report, and the reproduction.

We generate a `moduleForModel` test when creating an `ApplicationSerializer` which is actually a special case. This blueprint is coming from Ember Data itself now, so, my apologies for giving you the runaround, but can you post this issue there?

[This is the file that will need adjusting.](https://github.com/emberjs/data/blob/master/blueprints/serializer/index.js) If you'd like to take a swing at fixing it the problem is that we're blindly generating a test assuming there will be a model. In most cases that's a reasonable assumption, but in the `ApplicationSerializer` case that isn't true. We would need to use a different test template.

So, I'm closing this one, but if you can pop open a new issue over on Ember Data, that's where this one should land. Thank you so much for your time so far, and I would love to help you take a swing at patching this yourself. Find me on Slack if you want help!

**Closed by nathanhammond** 2016-04-12 03:20 UTC
Labels: Bug

**Comment by nathanhammond** [comment] 2016-04-12 03:23
See also: https://github.com/emberjs/data/commit/b6c2c7c25dface19bb0ff9f78f36848f17284740
