### ISSUE TITLE
On Node 15, errors during build are not recoverable

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#9404] opened 2020-12-03 18:32 UTC
On Node 15, something that causes a build error (such as a syntax error in hbs or js) causes `ember s` to exit 1 when a request is made.

For example, you type part of a line of code, your editor saves, the build error displays in your log, livereload is triggered and a request is made, then the server exits 1. 

<details>
<summary>Output</summary>

```bash
file changed components/selected-item.hbs.hbs
Build Error (broccoli-persistent-filter:Babel > [Babel: my-app]) in my-app/components/my-component.js

/Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:
...           @extra={{(hash driveTime=@dri
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'


Stack Trace and Error Report: /var/folders/wq/_yzzcnwn3wlfm5x_6gg5d8vm0000gn/T/error.dump.64eb8cc3228b3c62aa5d1e0a7a89a0e7.log
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

BuildError: /Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:
...           @extra={{(hash driveTime=@dri
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'
    at Parser.parseError (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13397:15)
    at Parser.parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13472:20)
    at parseWithoutProcessing (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14657:26)
    at parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14662:15)
    at preprocess (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:8885:35)
    at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:6103:38)
    at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:11500:37)
    at compileTemplate (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:66:26)
    at PluginPass.CallExpression (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:226:26)
    at newFn (/Users/katie/dev/my-app/node_modules/@babel/traverse/lib/visitors.js:175:21) {
  isBuilderError: true,
  isSilent: undefined,
  isCancellation: undefined,
  broccoliPayload: {
    originalError: Error: /Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:
    ...           @extra={{(hash driveTime=@dri
    -----------------------^
    Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'
        at Parser.parseError (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13397:15)
        at Parser.parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13472:20)
        at parseWithoutProcessing (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14657:26)
        at parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14662:15)
        at preprocess (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:8885:35)
        at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:6103:38)
        at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:11500:37)
        at compileTemplate (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:66:26)
        at PluginPass.CallExpression (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:226:26)
        at newFn (/Users/katie/dev/my-app/node_modules/@babel/traverse/lib/visitors.js:175:21) {
      code: 'BABEL_TRANSFORM_ERROR',
      file: 'my-app/components/my-component.js',
      treeDir: '/var/folders/wq/_yzzcnwn3wlfm5x_6gg5d8vm0000gn/T/broccoli-22626Xituejlbzweg/out-549-analyzer_ember_auto_import_analyzer'
    },
    originalMessage: '/Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:\n' +
      '...           @extra={{(hash driveTime=@dri\n' +
      '-----------------------^\n' +
      "Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'",
    nodeId: 550,
    nodeLabel: 'broccoli-persistent-filter:Babel > [Babel: my-app] (Babel: my-app)',
    nodeName: 'broccoli-persistent-filter:Babel > [Babel: my-app]',
    nodeAnnotation: 'Babel: my-app',
    instantiationStack: '    at Babel.Plugin (/Users/katie/dev/my-app/node_modules/broccoli-plugin/index.js:7:31)\n' +
      '    at Babel.Filter [as constructor] (/Users/katie/dev/my-app/node_modules/broccoli-persistent-filter/index.js:87:10)\n' +
      '    at new Babel (/Users/katie/dev/my-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:58:10)\n' +
      '    at Class.transpileTree (/Users/katie/dev/my-app/node_modules/ember-cli-babel/index.js:63:16)\n' +
      '    at Object.toTree (/Users/katie/dev/my-app/node_modules/ember-cli-babel/index.js:73:30)\n' +
      '    at /Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at processPlugins (/Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)\n' +
      '    at module.exports.preprocessJs (/Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:179:10)\n' +
      '    at DefaultPackager.processJavascript (/Users/katie/dev/my-app/node_modules/ember-cli/lib/broccoli/default-packager.js:503:29)',
    location: {
      file: 'my-app/components/my-component.js',
      treeDir: '/var/folders/wq/_yzzcnwn3wlfm5x_6gg5d8vm0000gn/T/broccoli-22626Xituejlbzweg/out-549-analyzer_ember_auto_import_analyzer',
      line: undefined,
      column: undefined
    },
    error: {
      message: '/Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:\n' +
        '...           @extra={{(hash driveTime=@dri\n' +
        '-----------------------^\n' +
        "Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'",
      stack: 'Error: /Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:\n' +
        '...           @extra={{(hash driveTime=@dri\n' +
        '-----------------------^\n' +
        "Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'\n" +
        '    at Parser.parseError (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13397:15)\n' +
        '    at Parser.parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:13472:20)\n' +
        '    at parseWithoutProcessing (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14657:26)\n' +
        '    at parse (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:14662:15)\n' +
        '    at preprocess (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:8885:35)\n' +
        '    at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:6103:38)\n' +
        '    at precompile (/Users/katie/dev/my-app/node_modules/ember-source/dist/ember-template-compiler.js:11500:37)\n' +
        '    at compileTemplate (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:66:26)\n' +
        '    at PluginPass.CallExpression (/Users/katie/dev/my-app/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:226:26)\n' +
        '    at newFn (/Users/katie/dev/my-app/node_modules/@babel/traverse/lib/visitors.js:175:21)',
      errorType: 'Build Error',
      codeFrame: '/Users/katie/dev/my-app/my-app/components/my-component.js: Parse error on line 79:\n' +
        '...           @extra={{(hash driveTime=@dri\n' +
        '-----------------------^\n' +
        "Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'",
      location: {
        file: 'my-app/components/my-component.js',
        treeDir: '/var/folders/wq/_yzzcnwn3wlfm5x_6gg5d8vm0000gn/T/broccoli-22626Xituejlbzweg/out-549-analyzer_ember_auto_import_analyzer',
        line: undefined,
        column: undefined
      }
    },
    broccoliNode: {
      nodeName: 'broccoli-persistent-filter:Babel > [Babel: my-app]',
      nodeAnnotation: 'Babel: my-app',
      instantiationStack: '    at Babel.Plugin (/Users/katie/dev/my-app/node_modules/broccoli-plugin/index.js:7:31)\n' +
        '    at Babel.Filter [as constructor] (/Users/katie/dev/my-app/node_modules/broccoli-persistent-filter/index.js:87:10)\n' +
        '    at new Babel (/Users/katie/dev/my-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:58:10)\n' +
        '    at Class.transpileTree (/Users/katie/dev/my-app/node_modules/ember-cli-babel/index.js:63:16)\n' +
        '    at Object.toTree (/Users/katie/dev/my-app/node_modules/ember-cli-babel/index.js:73:30)\n' +
        '    at /Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26\n' +
        '    at Array.forEach (<anonymous>)\n' +
        '    at processPlugins (/Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)\n' +
        '    at module.exports.preprocessJs (/Users/katie/dev/my-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:179:10)\n' +
        '    at DefaultPackager.processJavascript (/Users/katie/dev/my-app/node_modules/ember-cli/lib/broccoli/default-packager.js:503:29)'
    },
    versions: { 'broccoli-builder': '3.4.2', node: 'v15.2.1' }
  }
}
```
</details>

**Comment by rwjblue** [comment] 2020-12-04 13:49
We need to catch (and not rethrow) the recoverable build errors. 

/cc @stefanpenner

**Comment by bardzusny** [comment] 2021-02-25 08:06
For those who must use Node 15, a workaround is adding a global exception handler:

```js
process.on('uncaughtException', function(err) {
  console.error(err.stack);
  console.log('Node NOT Exiting...');
});
```

to your `ember-cli-build.js` (or any other file ran through Node on build).

**Comment by 12finger** [comment] 2021-03-06 14:59
@bardzusny which ember version are you on and reporting the success with M1-arm-Node15 for ?

@rwjblue testing the ember example app 'super-rentals' against a M1-arm-Node15 won't fly, too. error in initial build step.

**Comment by bardzusny** [comment] 2021-03-07 19:09
@12finger it's 3.24, so like current [`super-rentals` repo](https://github.com/ember-learn/super-rentals/).

What I posted fixes issue discussed here, but indeed isn't the whole story to get a real Ember project running with Node 15. On a `super-rentals` app example, the error you've probably got is:

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:716:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/Users/bardzusny/code/super-rentals/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/Users/bardzusny/code/super-rentals/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:378:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

To fix it, I backported this piece of code from latest `workerpool` package release. Save the following diff to some file, e.g. `fix-workerpool.patch`:
```
diff --git a/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js b/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js
index 02f748a..bdcc0c6 100644
--- a/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js
+++ b/node_modules/ember-inflector/node_modules/workerpool/lib/WorkerHandler.js
@@ -171,8 +171,9 @@ function WorkerHandler(script, options) {
   // send all queued requests to worker
   function dispatchQueuedRequests()
   {
-    me.requestQueue.forEach(me.worker.send.bind(me.worker));
-    me.requestQueue = [];
+    for (const request of me.requestQueue.splice(0)) {
+      me.worker.send(request);
+    }
   }

   // listen for worker messages error and exit
```

And then apply it to your project:
```bash
git apply .../fix-workerpool.patch
```

You'll need to repeat this call after each `npm install`.

I consider those typical early adopter pains. Expecting them to get fixed once Node 16 (next LTS) is out, `ember-cli` starts supporting it.

**Comment by 12finger** [comment] 2021-03-08 22:47
@bardzusny good too see other brave hearts experimenting with the new arm64 Platform!
Would be nice to collect all knowledge around "Apple Silicon + Node" somewhere central, right?

Waiting for Node16 is a long wait .. Active LTS start is 2021-10-26!

Meanwhile I am using my zsh terminal natively in arm64, just the node12 binary was installed via nvm as intel-binary.
Works like a charm for now. Nice coexistence.

**Comment by bardzusny** [comment] 2021-06-09 12:14
FWIW: I've dumped the solution posted before, patching local `ember-cli-build.js` and `workerpool` package above.

Now I'm preloading the following script with required monkey-patches, using `NODE_OPTIONS` env. var:

```javascript
// For Ember on Node.js 15+, set in NODE_OPTIONS:
// export NODE_OPTIONS="--require /Users/bardzusny/node-15-for-ember-monkeypatching.js"

// 1. Don't exit Node process on uncaught exceptions, keeping Node 14 behaviour. Required to not crash Ember server on type errors thrown by ember-cli-typescript
process.on("uncaughtException", function (err) {
  console.error(err.stack);
  console.log("Node NOT Exiting...");
});

// 2. Monkey-patching Array.prototype.forEach: to detect specific build step call from a specific file, based on a stack trace - and add special sauce for it to work OK with Node 15+:
//
// Error
// at Array.forEach (/Users/bardzusny/this-file.js:24:17)
// at dispatchQueuedRequests (/Users/bardzusny/code/fly-components/node_modules/workerpool/lib/WorkerHandler.js:240:21)
// ...

let specialForEachRegexp = new RegExp(
  "at dispatchQueuedRequests.*node_modules/workerpool/lib/WorkerHandler.js"
);

let origForEach = Array.prototype.forEach;

Array.prototype.forEach = function () {
  if (specialForEachRegexp.test(new Error().stack.split("\n")[2])) {
    let sendFunc = arguments[0];
    return origForEach.bind(this)((req) => sendFunc(req)); // sendFunc must receive only one argument, otherwise it errors out
  }

  return origForEach.bind(this)(...arguments);
};
```

And that's it -> now Ember server should work all right with Node 15/16. (3.24 here, with plenty of legacy addons.)

**Comment by rwjblue** [comment] 2021-06-11 13:09
FYI - We are working toward a solution RE: ember-cli-babel@6 users (the workerpool issue) over in https://github.com/babel/broccoli-babel-transpiler/pull/203.

**Comment by rwjblue** [comment] 2021-06-11 19:31
I was just chatting with @stefanpenner about this (over in https://github.com/embroider-build/embroider/pull/843). We think that the broad changes in https://github.com/broccolijs/broccoli/pull/458/ should fix the issue. He was gonna try to dust that off and get it landed sometime next week.

**Comment by NullVoxPopuli** [comment] 2021-07-12 13:14
Related?: 
https://github.com/typed-ember/ember-cli-typescript/issues/1439
https://github.com/ember-cli/ember-cli/issues/9584
https://github.com/ember-cli/ember-cli/issues/9534

**Comment by NullVoxPopuli** [comment] 2021-11-10 11:51
@rwjblue any progress on those issues?

For some reason half my team started running in to these issues. 🤔

**Comment by marceloandrader** [comment] 2021-12-06 12:26
Same error with node 16.13.1 my deployments started to fail when GitHub rolled out nodejs 16 on their GitHub action images for runners.

**Comment by chasegiunta** [comment] 2021-12-16 16:27
same error as @bardzusny above with node 15:
```
⠸ building... [Babel: ember-raf-scheduler > applyPatches]node:internal/validators:164
      throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:716:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/Users/chasegiunta/repos/dochub/frontend/node_modules/ember-raf-scheduler/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/Users/chasegiunta/repos/dochub/frontend/node_modules/ember-raf-scheduler/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:369:20)
    at ChildProcess.emit (node:domain:470:12)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_ARG_TYPE'
  ```

**Comment by mileslane** [comment] 2022-01-05 18:16
With node 16.13.1:
`TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:713:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/Users/mileslane/Projects/clear_value_plus/ember/reference-ui/node_modules/ember-cli-airbrake/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/Users/mileslane/Projects/clear_value_plus/ember/reference-ui/node_modules/ember-cli-airbrake/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'`

**Comment by FinlayDaG33k** [comment] 2022-05-03 21:13
Node `16.15.0` also is affected:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:733:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (F:\repos\FinlayDaG33k\dashboard\node_modules\ember-cli-test-loader\node_modules\workerpool\lib\WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (F:\repos\FinlayDaG33k\dashboard\node_modules\ember-cli-test-loader\node_modules\workerpool\lib\WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by ef4** [comment] 2022-08-10 17:58
I can't reproduce this particular failure on ember-cli 4.6, for any node version from 14 through 18.

Syntax errors in hbs files don't process.exit, and the next build recovers as it should. 

I also tried patching an exception directly into ember-template-compiler but it's all handled correctly.

I *do* think we still have a bug with postBuild() hooks blowing up, which is tracked in https://github.com/ember-cli/ember-cli/issues/9584. Perhaps to reproduce this specific bug you need some addon that is relying on a valid parse from within postBuild?

**Comment by ef4** [comment] 2022-08-10 18:05
Nevermind, I figured out the reproduction. I was missing the part where it's not the rebuild that crashes, it's the HTTP request after the rebuild.

**Comment by ef4** [comment] 2022-08-10 18:34
I think people have been getting trolled by the stack trace. The HTTP server is re-throwing an older build error to cause this process.exit. So the stack trace you see has nothing to do with the code that is doing the re-throwing, which is the code that needs to be fixed. I am digging in.

**Comment by bertdeblock** [comment] 2022-08-11 07:54
This should be fixed by https://github.com/ember-cli/ember-cli/pull/9987.

**Closed by bertdeblock** 2022-08-11 07:54 UTC
