### ISSUE TITLE
Intermittent build failures that require computer reboot

### ISSUE THREAD

**Issue by timiyay** [ember-cli/ember-cli#8436] opened 2019-02-15 01:01 UTC
Our company uses Ember for multiple apps, and we have a common development environment configured on all of our developer machines.

A couple of months ago, we upgraded all of our apps from Ember 2.18 to Ember 3.5.1.

Since then, we intermittently encounter build failures that usually go along the lines of:

```
Could not find module `my-package/my-module` imported from `my-app/file`
```

The missing module varies, though `ember-resolver` has been one of the common ones.

Our usual method to fix this is remove `node_modules` and run `yarn install`. In some cases this doesn't work, and the only solution is to reboot your machine.

I couldn't find an existing issue for this, but the [Jan 2019 coversation in this merged PR](https://github.com/ember-cli/ember-cli/pull/8068) for ember-cli 3.5.0 indicates the use of system temp may be related.

I appreciate this issue is a bit vague, and hard to repro. We aim to collect more info about it, and will update this issue whenever we can. It has happened enough times now to be a Thing, so we'll be more observant when it happens in future.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
$ ember version --verbose
ember-cli: 3.5.1
http_parser: 2.7.0
node: 6.9.2
v8: 5.1.281.88
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64

$ npm --version
6.4.1

$ yarn --version
1.12.3
```

**Comment by oligriffiths** [comment] 2019-02-15 01:34
@timiyay so it appears not to be related to the Broccoli 2 update as it does it for Broccoli 0.18 per the info in that related PR. Have you tried the steps outlined to see if the issue persists for you?

**Comment by timiyay** [comment] 2019-02-15 01:51
@oligriffiths Thanks for the quick reply.

We haven't tried those steps yet, but we will next time we encounter the issue.

**Comment by sdhull** [comment] 2019-02-15 05:01
I'm also happy to try more things, but this error still surfaced for me (eventually) even after updating from node 8x to 10x, then disabling system temp / disabling Broccoli 2 so I'm kind of at a loss as to what to try next.

My team's only observation is that this error _only_ occurs after waking a machine up from sleep (however not reliably).

**Comment by sdhull** [comment] 2019-02-15 22:49
Came back from lunch, woke computer up, started working aaaaand:
<img width="668" alt="screen shot 2019-02-15 at 2 47 38 pm" src="https://user-images.githubusercontent.com/50039/52888536-e1eb5b80-3130-11e9-9f2c-d2d16d892351.png">

**Comment by stefanpenner** [comment] 2019-02-15 23:52
Does removing the folder located at  ‘$TMPDIR/$USERNAME’ also fix the problem?

Is there a way I can reproduce this or get access to your app?

**Comment by stefanpenner** [comment] 2019-02-15 23:54
Can you share how you import the file found at http://client.localhost/assets/node_modules/lodash.merge/index.js ?

**Comment by sdhull** [comment] 2019-02-16 05:17
@stefanpenner unfortunately our codebase is closed source. One thing that might be strange (I just noticed) is we have both `ember-lodash` and `ember-auto-import` as dependencies. Not sure if this is really a _problem_ per say...  I should probably remove `ember-lodash` and switch our imports to import from `lodash-es`

I'm very much looking forward to seeing this issue again and trying `rm -rf "$TMPDIR/$USERNAME"`. I'll let you know how it goes!

The offending file varies, however the one constant is the `ember-resolver` bit.

As for how we import lodash.merge, it's nothing special, just `import { merge } from 'lodash';`

**Comment by stefanpenner** [comment] 2019-02-16 17:27
> @stefanpenner unfortunately our codebase is closed source.

ya understood, but if we get stuck debugging this way maybe we can setup a screenshare session?

> I should probably remove `ember-lodash` and switch our imports to import from `lodash-es`

Yes. Once you have done this, if the problem persists let us know.

> The offending file varies, however the one constant is the `ember-resolver` bit.

This is due to the `ember-resolver` bit being more of a catch-all error.  If anything prevents the `ember-resolver` module from being loaded, such as an error in `vendor.js` before `define('ember-resolve', [], ....)` is executed, will subsequently cause your app's boot to fail due to a missing `ember-resolver`

**Comment by stefanpenner** [comment] 2019-02-16 17:32
@sdhull / @timiyay can you guys also be sure to share all browser console output each time the issue occurs? My hope is that it will help us narrow down a consistent source of those proceeding errors.

**Comment by stefanpenner** [comment] 2019-02-16 17:35
Also, based on the issues reported so far. My current guess is that:

The offending state is being stored in a persistent manner, most likely in `$TMPDIR`. A restart purges `$TMPDIR` which would then explain why a restart corrects this issue.

I mentioned deleting `rm -rf $TMPDIR/$USER` as this is typically were `async-disk-cache` and `sync-disk-cache`, common libraries for broccoli plugins to store "warm build caches" stores, stores it's persistent caches.  If deleting it addresses the issue, it may help narrow down whats causing the issue.

**Comment by stefanpenner** [comment] 2019-02-16 17:58
Ok after some more thinking:

The following error, suggests this may be related to `ember-auto-import`, as:

* that filepath follows the same source-mapping as something produced by ember-auto-import
* `module` not existing, suggests something has gone sideways when converting `lodash.merge`

```
the `module is not defined` from index.js is actually from
`http://client.localhost/assets/node_modules/lodash.merge/index.js`
```

**Comment by stefanpenner** [comment] 2019-02-16 18:00
> As for how we import lodash.merge, it's nothing special, just `import { merge } from 'lodash';`

@sdhull I don't believe that is correct, the error message suggests that is coming directly from `lodash.merge` module not `lodash`. Specifically it is most likely `import merge from 'lodash.merge'` and is being pulled in via ember-auto-import.

**Comment by stefanpenner** [comment] 2019-02-16 18:04
Given that a functioning `lodash.merge/index.js` via `ember-auto-import` starts with:
```js
(function(global, module) {

```

and the one of the error messages is:

```
the 'module is not defined' from index.js is actually from
'http://client.localhost/assets/node_modules/lodash.merge/index.js'
```

It may be that post `sleep` the `(define(global, module` is being lost of some reason.
Although you app is close source, could an offending `vendor.js` be provided? (Feel free to DM me on discord, or send it to me via email). This will help me verify some hypothesis.

**Comment by sdhull** [comment] 2019-02-21 08:17
@stefanpenner yeah I see no reason why I couldn't send you the `vendor.js` file when I get the error again!

If someone is importing `merge` like you say (`import merge from 'lodash.merge'`) , it must be in an addon. I've grepped our codebase and we don't import it like that anywhere. 🤔

Welp I'm actually looking forward to getting this error again -- I hope we're able to make some progress figuring it out! I'll hit you up on discord and save a copy of the vendor.js file regardless.

**Comment by stefanpenner** [comment] 2019-02-21 08:35
@sdhull  keep me posted

**Comment by oakho** [comment] 2019-02-21 14:24
We are also experiencing this issue since a bunch of months and I'm going to list what we tried so far.

At first, this issue was only happening when we were deploying our app in production through ember-cli-deloy so we thought it was something linked with it. As it happened randomly and not so often in the beginning we didn't bother that much and just trashed our node_modules and redeployed and it was working again.

Then It started to happen more often and so we narrowed that It was happening because of lodash import. We tried to load lodash with ember-lodash, ember-browserify, ember-cli-cjs-transform everytime I thought I was done then it was happening again. I finally removed completely lodash from our application and the issue was still happening.

So we thought there might be something with ember-cli and then upgraded to 3.6.0 in hope of a fix but that it just did move the bug somewhere else. We were only experiencing this error while deploying via ember-cli-deploy but the issue moved in development, when we restart our servers and still happening randomly though.

At the moment, we have completely removed lodash in our app but we still have addons or node modules that rely on it and gets compiled in the vendor.js file.

@stefanpenner I'm currently getting the issue so I gathered all you asked and I'm going to send it to you. I kept a copy of the dist folder so let me know if you need something else.

**Comment by stefanpenner** [comment] 2019-02-21 14:35
@oakho thank you for sharing, ideally access to your app would let me diagnose and fix. But the dist alone may be helpful.

Could you also include clear scenarios when this problem occurs and exact/complete logs and errors.

It may also be useful to get a list of all places and addons lodash is being used from.

**Comment by oakho** [comment] 2019-02-21 15:08
@stefanpenner I just gave you access to a fork of our repository.

It always happen after a server restart and we mostly do that to install or update addons, modules. 

Today It happened after : 
- I pulled a coworker code changes on a git branch
- There was an addon added so I killed my server to install it with a yarn install then restarted the server
- The server successfully started my got a blank page with the error

There is only these browser errors : 
```
14:08:23.715 index.js:1963 Uncaught ReferenceError: module is not defined
    at index.js:1963
(anonymous) @ index.js:1963
14:08:24.068 loader.js:247 Uncaught Error: Could not find module `ember-resolver` imported from `idol/resolver`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at app-boot.js:3
missingModule @ loader.js:247
findModule @ loader.js:258
Module.findDeps @ loader.js:168
findModule @ loader.js:262
Module.findDeps @ loader.js:168
findModule @ loader.js:262
requireModule @ loader.js:24
(anonymous) @ app-boot.js:3
```

The first error happen at the end of node modules `lodash.merge`

You should be able to list it with the repository I shared with you.

**Comment by stefanpenner** [comment] 2019-02-21 15:26
@oakho awesome thanks.

It does in-fact seem like the CJS is not being wrapped correctly.

Also the source of lodash.merge are:

```
yarn why lodash.merge                                                   (%1)
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "lodash.merge"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "foundation-sites@6.2.4" is incompatible with requested version "foundation-sites@^6.3.1"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lodash.merge@4.6.1"
info Reasons this module exists
   - "ember-custom-actions" depends on it
   - Hoisted from "ember-custom-actions#lodash.merge"
   - Hoisted from "ember-cli-template-lint#broccoli-concat#lodash.merge"
   - Hoisted from "ember-svg-jar#cheerio#lodash.merge"
   - Hoisted from "ember-cli#yam#lodash.merge"
   - Hoisted from "ember-cli#markdown-it-terminal#lodash.merge"
   - Hoisted from "ember-cli-notifications#ember-css-modules#lodash.merge"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "64KB"
info Disk size with transitive dependencies: "64KB"
info Number of shared dependencies: 0
✨  Done in 1.38s.
```

**Comment by stefanpenner** [comment] 2019-02-21 15:36
@oakho poking around, it seem thats lodash.merge is coming in to the browser build via ember-custom-actions via.

I'm going to confirm ^ and then also investigate https://github.com/rwjblue/ember-cli-cjs-transform/blob/master/src/cjs-transform.js which is suspicious .

**Comment by oakho** [comment] 2019-02-21 15:42
@stefanpenner Alright, thank you Stefan, hope we'll sort that out soon !

**Comment by stefanpenner** [comment] 2019-02-21 15:56
I think we have narrowed down the issue to https://github.com/rwjblue/ember-cli-cjs-transform/blob/master/src/cjs-transform.js

A quick work-around while I investigate a fix, is to search `$TMPDIR` for a folder named `cjs-transform` and delete it.

**Comment by stefanpenner** [comment] 2019-02-21 16:01
I believe the issue is the cache existence check in ember-cli-cjs-transform is for the folders folder, not the contents of the folder. So if the contents become malformed or removed, the build incorrectly assumes the cache is populated

**Comment by oakho** [comment] 2019-02-21 16:11
And just found https://github.com/rwjblue/ember-cli-cjs-transform/issues/91 that seems to look like our exact same issue here !

**Comment by stefanpenner** [comment] 2019-02-21 17:04
I think i have a fix, at-least for @oakho's issue: https://github.com/rwjblue/ember-cli-cjs-transform/pull/143

**Comment by oakho** [comment] 2019-02-21 17:15
Thanks @stefanpenner, I'll update our app with the fix !

**Comment by rwjblue** [comment] 2019-02-21 17:34
ember-cli-cjs-transform@1.3.1 released with the fix @stefanpenner mentioned above

**Comment by sdhull** [comment] 2019-02-21 20:46
OMG @stefanpenner @rwjblue & everyone else who helped, you rock the most!

**Comment by sdhull** [comment] 2019-02-22 00:52
(For those of you who haven't upgraded cjs-transform yet, I found `rm -rf $TMPDIR/$USER/cjs-transform` fixes this issue without a restart)

**Comment by stefanpenner** [comment] 2019-02-22 02:23
Closing this

**Closed by stefanpenner** 2019-02-22 02:23 UTC

**Comment by timiyay** [comment] 2019-03-18 01:04
Thanks for the fix @stefanpenner. We were consuming `ember-cli-cjs-transform` via `ember-rollbar-client`, and have updated to the latest to get the fix.

No recurrences of the issue for a couple of weeks, so it looks like it's squashed.

**Comment by stefanpenner** [comment] 2019-03-18 05:23
@tomiyay sorry for the bug, glad to see it is now resolved. (Honestly it was kinda fun to debug...)
