### ISSUE TITLE
inputTree/inputTrees set on tree: CoreObject

### ISSUE THREAD

**Issue by sebyx07** [ember-cli/ember-cli#4724] opened 2015-08-21 12:29 UTC
ember-cli version: 1.13.7
node: 0.12.7

I get when i try to run ember s
```SH
  No inputTree/inputTrees set on tree: CoreObject
  Error: No inputTree/inputTrees set on tree: CoreObject
```

**Comment by artych** [comment] 2015-08-21 12:32
This might be caused by last ember-browserify 1.0.4 and could be fixed by downgrading to 1.0.3.
See https://github.com/ef4/ember-browserify/issues/44#issuecomment-133405760

**Comment by chrisvdp** [comment] 2015-08-21 17:41
Also ran into this. downgrading to 1.0.3 fixed it.

**Comment by stefanpenner** [comment] 2015-08-21 18:16
v1.0.5 has been released

**Closed** 2015-08-21 18:16 UTC
Labels: pending-dependency-fix

**Comment by knownasilya** [comment] 2015-08-21 18:48
:+1: love the turn around.
