### ISSUE TITLE
Production build of brand new app includes a QUnit

### ISSUE THREAD

**Issue by HeroicEric** [ember-cli/ember-cli#9915] opened 2022-05-24 20:51 UTC
I generated a brand new app using `ember-cli@4.3.0` and generated a production build and noticed that the generated assets seem to be including QUnit, which seems like a bug.

I uploaded a repo that contains the brand new app and the build result in `./dist`:

https://github.com/HeroicEric/default-ember-application-production-build-bug/

### Steps to reproduce

```
# Install ember-cli v4.3.0
npm install -g ember-cli@4.3.0`

# Generate a new ember app
ember new foo-app`

# Change into the Ember app's directory
cd foo-app/

# Create a production build of the app
ember build --environment=production
```

After generating the production build, the contents of `your-app/dist/` will look something like this:

```
dist/
├── assets
│   ├── chunk.143.933eb1b04ba9aa5d682d.js
│   ├── chunk.178.c9175ed872be1d7e9130.js
│   ├── chunk.916.681660d2aa2df2335264.js <---- Copy of QUnit?
│   ├── chunk.916.681660d2aa2df2335264.js.LICENSE.txt <---- QUnit license?
│   ├── default-ember-app-production-build-bug-c23f4317a720e8bb060ad2f360c52a6c.js
│   ├── default-ember-app-production-build-bug-d41d8cd98f00b204e9800998ecf8427e.css
│   ├── vendor-d41d8cd98f00b204e9800998ecf8427e.css
│   └── vendor-fa36ddbb160fbb52af633362777140ef.js
├── index.html
└── robots.txt
```

The following files seem to be for QUnit.js

- [assets/chunk.916.681660d2aa2df2335264.js](https://github.com/HeroicEric/default-ember-application-production-build-bug/blob/main/dist/assets/chunk.916.681660d2aa2df2335264.js)
- [assets/chunk.916.681660d2aa2df2335264.js.LICENSE.txt](https://github.com/HeroicEric/default-ember-application-production-build-bug/blob/main/dist/assets/chunk.916.681660d2aa2df2335264.js.LICENSE.txt)

See https://github.com/HeroicEric/default-ember-application-production-build-bug for an example of the what I'm talking about.

**Comment by bertdeblock** [comment] 2022-05-25 08:30
Hi, thanks for opening!

If I create a fresh v3.28 app, then I don't see this issue.
If I create a fresh v3.28 app, bump `ember-auto-import` to v2 and install `webpack` v5, then I _do_ see this issue as well.

So I'm guessing this is related to `ember-auto-import` v2.
Would you mind creating an issue there as well?

**Comment by bertdeblock** [comment] 2022-06-18 09:11
I don't think the issue is with `ember-cli` itself, so I'm going to close this in favour of the issue over in `ember-auto-import`: https://github.com/ef4/ember-auto-import/issues/525.

**Closed by bertdeblock** 2022-06-18 09:11 UTC

**Comment by runspired** [comment] 2022-07-29 11:38
This seems like correct behavior. Production builds include test assets. With ember-auto-import v2 qunit is now included via it vs via the old test-assets file, but test fils should still be built.
