### ISSUE TITLE
Ember-CLI with Sublime Text 3 collisions..

### ISSUE THREAD

**Issue by pcjpcj2** [ember-cli/ember-cli#3451] opened 2015-03-07 03:10 UTC
Hello I use OS X yosemite contains Ember-CLI 0.2.0-beta.1 with Sublme Text 3.

I just create new emberjs project and add ember-paper addon.

I write some code 
```
<h1>Lorem Ipsum</h1>
```

I refresh my browser when sublime text on, terminal alert for me belows..
```
EEXIST, file already exists '/Users/ChangJooPark/Development/EmberJs/EP_TEST/tmp/class-tmp_cache_dir-V8qPFkap.tmp'
Error: EEXIST, file already exists '/Users/ChangJooPark/Development/EmberJs/EP_TEST/tmp/class-tmp_cache_dir-V8qPFkap.tmp'
    at Object.fs.symlinkSync (fs.js:742:18)
    at symlink (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)
    at Function.symlinkOrCopySync [as sync] (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at /Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:103:21
    at lib$rsvp$$internal$$tryCatch (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/ChangJooPark/Development/EmberJs/EP_TEST/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Why I can't use `ember serve` with `Sublime Text 3`?

**Comment by zjrosen1** [comment] 2015-03-07 04:10
Please see #3413 and d4ec617

**Comment by rwjblue** [comment] 2015-03-07 05:49
Duplicate of #3413

**Closed by rwjblue** 2015-03-07 05:49 UTC
