### ISSUE TITLE
ember-template-lint enabled by default

### ISSUE THREAD

**Issue by mfeckie** [ember-cli/ember-cli#8131] opened 2018-10-16 06:10 UTC
Going through the process of upgrading and am surprised that template linting is now turned on be default and has no support for auto fixing.

I feel like this is a premature inclusion and wonder if y'all could shed some light on the the thought process for it being part of the default even for those upgrading using `ember-cli-update`.

**Comment by rwjblue** [comment] 2018-10-16 13:13
We followed the normal RFC process for this (https://github.com/ember-cli/rfcs/pull/114). I think the larger issue is with the default inclusion of some more noisy/difficult to fix rules (e.g. `attribute-indentation`).

> I feel like this is a premature inclusion and wonder if y'all could shed some light on the the thought process for it being part of the default even for those upgrading using ember-cli-update.

FWIW, I think this is an interesting point and one that we don't really have the infrastructure to handle at the moment. Specifically, that there are some blueprint changes that are perfectly fine for "new apps" but probably aren't quite as simple/nice for existing apps.

**Comment by tavosansal** [comment] 2018-10-16 14:34
So is there a way to turn this off in the mean time? I dont have the time to fix all of the indentation of all of my template files (there are 100s of template files in our app).

**Comment by kellyselden** [comment] 2018-10-16 14:57
@tavosansal Remove it from your package.json until you want it back.

**Comment by locks** [comment] 2020-03-28 21:22
Thank you for expressing your concern! I believe some auto-fixing capabilities are being introduced to ember-template-lint at the moment.
Since this is not a bug per se, and the feature followed the expected RFC path, I will be closing this. Check out the ember-template-lint for more information on the current status and for contribution opportunities if you have some cycles to help out 🙏

**Closed by locks** 2020-03-28 21:22 UTC
