### ISSUE TITLE
Import from node_modules (package.json) from 2.11 (beta), bower.json removed.

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#6612] opened 2016-12-25 19:43 UTC
Now that we have removed bower.json standard dependencies from 2.11 (beta) how can we import packages, libraries from node_modules (packages in package.json)?

For example bootstrap, tether, moment, others...

**Comment by yads** [comment] 2017-01-03 21:11
Could you not just reference the files from node_modules rather than bower_components?

`app.import('node_modules/bootstrap/dist/js/bootstrap.js');`

**Comment by johnunclesam** [comment] 2017-01-03 21:20
No way, it doesn't work.

**Comment by btecu** [comment] 2017-01-03 21:41
@johnunclesam not yet. Meanwhile, you can use something like https://github.com/kellyselden/ember-cli-node-modules-to-vendor.

**Comment by nathanhammond** [comment] 2017-01-04 00:28
That is our official recommendation for now: use the other addons or handle it yourself manually. It's an imperfect situation we want to make a bit better, but we also don't want to watch all of `node_modules` for performance reasons.

I'm closing this issue as not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. Please also consider stopping by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) as that's a better venue for questions like this.

**Closed by nathanhammond** 2017-01-04 00:28 UTC
