### ISSUE TITLE
Include .less files in vendor for addon

### ISSUE THREAD

**Issue by TayHobbs** [ember-cli/ember-cli#3033] opened 2015-01-19 21:00 UTC
I have been trying to use less in an addon that I am working on, and can't seem to include the files. I receive a `Path or pattern "app.less" did not match any files` error. Using this code inside the index.js file :   
`included: function(app) {
    app.import(path.join('vendor', 'app.less'));
  }`

If I try the same thing with .css files everything works as expected.
I also do have ember-cli-less installed in the addon.

**Comment by krisselden** [comment] 2015-01-19 22:53
Currently there is an outstanding issue with style preprocessors in addons.  I have a series of PRs coming shortly to address the issues, first of which is #3030

**Comment by jakecraige** [comment] 2015-01-20 02:53
This is a duplicate of #2872

**Closed by jakecraige** 2015-01-20 02:53 UTC
