### ISSUE TITLE
a11y: Set the default generated index.html lang attribute to "en"

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/ember-cli#9033] opened 2020-02-12 13:01 UTC
As per https://guides.emberjs.com/release/accessibility/application-considerations/#toc_language-attribute

> Until Ember provides this by default, developers should edit the index.html file of the generated Ember application with the default language declaration.

Raising an issue to generate the index.html file with `lang` attribute set by default.

**Comment by kellyselden** [comment] 2020-02-12 13:16
Duplicate of https://github.com/ember-cli/ember-cli/issues/8599

**Closed** 2020-02-12 15:01 UTC
