### ISSUE TITLE
ember new my-app created in wrong directory

### ISSUE THREAD

**Issue by bradly** [ember-cli/ember-cli#3792] opened 2015-04-04 19:00 UTC
When running ```ember new my-app``` as specified in the getting started guide, the app is creating in my user's home directory instead of in my current working directory

```shell
cd ~/code

ember new wheres-waldo
# lots of stuff

ls | grep waldo
# nothing found

cd ~

ls | grep waldo
# wheres-waldo found

ember --version
Future versions of Ember CLI will not support v0.10.30. Please update to Node 0.12 or io.js.
version: 0.2.2
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.10.30
npm: 2.7.4
```

Here is the gist of my actual console output: https://gist.github.com/bradly/cf46abac718dab8533db

**Comment by visualjeff** [comment] 2015-04-04 19:14
I saw this happy too.  Changed node version to iojs and the issue disappeared for me.

**Comment by stefanpenner** [comment] 2015-04-04 21:16
@bradly can you try iojs or node 0.12 ?

**Comment by jpalmer1026** [comment] 2015-04-20 15:10
I'm using node 0.12 and the same issue is happening to me.

**Comment by abuiles** [comment] 2015-04-20 15:30
@jpalmer1026 @bradly can you check if maybe you have a `package.json` in the same directory where you are running the command, that is known to cause this kind of issue too.

**Comment by jpalmer1026** [comment] 2015-04-20 15:39
@abuiles There was a `package.json` file in my root directory. Even though it's not the directory I was running the new command in, deleting it from the root directory solved the problem. Thanks.

**Comment by abuiles** [comment] 2015-04-20 15:40
Closing, as I'm almost sure the problem is the one which @jpalmer1026 was having. I'll re-open if that's not the case.

**Closed** 2015-04-20 15:40 UTC
Labels: pending-submitter-response

**Comment by bradly** [comment] 2015-04-20 15:45
@abuiles @jpalmer1026 There was a package.json in my home directory, although I was in ~/code so I guess running ember new looks for the most parent package.json. Do you think that is a bug or at least unintuitive enough that a warning should be displayed if running ember new is going to create the app in a different directory than the one you are currently in?
