### ISSUE TITLE
outputPaths always send the app css : Asset compilation #4948

### ISSUE THREAD

**Issue by datasc123** [ember-cli/ember-cli#6185] opened 2016-08-17 09:53 UTC
I want to use custom themed css files instead of app.scss, I did this in ember-cli-build.js:

```
 outputPaths: { 
      app: { 
        scss: {
          'app': null,
          'dark-theme': '/assets/dark-theme.css',
          'normal-theme': '/assets/normal-theme.css',
          'highcontrast-theme': '/assets/test-support.css'
        }
      }
    },
```

@dukex : Did you get any workaround to fix this?

**Comment by nathanhammond** [comment] 2016-08-17 15:09
Hey @datasc123! This looks like you're trying to work through a problem. It's not really an Ember CLI issue. My recommendation is that you have your "normal-theme" be the content which appears in the "app" slot. Further, this is a configuration that you need to work out within `broccoli-sass` as that addon is (likely) who is responsible for the `scss` property on `outputPaths`.

I'm closing this issue as not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and pick the brains of the wonderful people in our community if you have additional questions!

**Closed by nathanhammond** 2016-08-17 15:09 UTC
