### ISSUE TITLE
ember-cli is slow with > 100,000 files in bower_components

### ISSUE THREAD

**Issue by borisding1994** [ember-cli/ember-cli#4460] opened 2015-07-15 17:35 UTC
```

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SourcemapConcat                               | 2559ms              
SourcemapConcat                               | 2486ms              
SourcemapConcat                               | 2277ms              
SourcemapConcat                               | 2166ms              
SassCompiler                                  | 1953ms              
Funnel: App JS Files                          | 814ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SourcemapConcat (8)                           | 9517ms (1189 ms)    
SassCompiler (1)                              | 1953ms              
Funnel: App JS Files (1)                      | 814ms    
```

package.json:
```json
 "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.15",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "3.3.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-document-title": "1.13.0",
    "ember-export-application-global": "^1.0.2"
  }
```

ember-cli-build.js:
```js
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: false,
      sourceMap: false
    }
  });

  //import material design lite
  app.import('bower_components/material-design-lite-src/dist/material.js');
  app.import('bower_components/material-design-icons/iconfont/MaterialIcons-Regular.woff2',{
    destDir: 'assets/fonts'
  });
  app.import('bower_components/material-design-icons/iconfont/MaterialIcons-Regular.woff',{
    destDir: 'assets/fonts'
  });
  app.import('bower_components/material-design-icons/iconfont/MaterialIcons-Regular.ttf',{
    destDir: 'assets/fonts'
  });
  app.import('bower_components/material-design-icons/iconfont/MaterialIcons-Regular.eot',{
    destDir: 'assets/fonts'
  });

  return app.toTree();
};
```

and, my hrad disk is SSD.

help me,please. thanks very much.

**Comment by stefanpenner** [comment] 2015-07-15 17:38
1. is this initial build or incremental
2. what are the times in 10.10 ?

**Comment by poyueh** [comment] 2015-07-16 04:25
@stefanpenner 
is incremental.
app/* have 20 files.

this is source code: https://github.com/poyueh/slow-ember-cli-project

thanks very much.

And, in OS X 10.10:
```
Build successful - 12866ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SourcemapConcat                               | 2606ms              
SourcemapConcat                               | 2437ms              
SourcemapConcat                               | 2257ms              
SourcemapConcat                               | 2217ms              
SassCompiler                                  | 2084ms              
Funnel: App JS Files                          | 951ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SourcemapConcat (8)                           | 9550ms (1193 ms)    
SassCompiler (1)                              | 2084ms              
Funnel: App JS Files (1)                      | 951ms
```

**Comment by stefanpenner** [comment] 2015-07-16 04:57
Something seems strange. I'm building 100kloc app in way less time then that

**Comment by stefanpenner** [comment] 2015-07-16 05:02
holy crap the MaterialDesign stuff is > 100MB

**Comment by runspired** [comment] 2015-07-16 05:30
o.O yikes

**Comment by stefanpenner** [comment] 2015-07-16 05:31
We still shouldn't be pulling everything in, so something is likely sideways.

Also, i  have no idea why ember-cli-sass is being configured from config/environment.js this file is strictly for runtime configuration

**Comment by stefanpenner** [comment] 2015-07-16 05:33
The fact the sourceMapConcat is showing up in the slowTrees, and removing the icons fixes the perf problem, would seem to indicate that sourceMapConcat is likely accidentally trying to concat the icons...

**Comment by poyueh** [comment] 2015-07-16 07:36
@stefanpenner 
yep. this problem about  app.import webfonts.

when I use google fonts.it's work. :
```
file deleted styles/app.scss___jb_bak___
file deleted styles/app.scss___jb_old___
file changed styles/app.scss

Build successful - 934ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
TreeMerger (vendor)                           | 167ms               
SourcemapConcat                               | 132ms               
SassCompiler                                  | 59ms                
SourcemapConcat                               | 54ms                
SourcemapConcat                               | 53ms                
Funnel: App JS Files                          | 51ms                
SourcemapConcat                               | 49ms                

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SourcemapConcat (8)                           | 325ms (40 ms)       
TreeMerger (vendor) (1)                       | 167ms               
Funnel (33)                                   | 83ms (2 ms)         
TreeMerger (161)                              | 70ms (0 ms)         
SassCompiler (1)                              | 59ms                
Funnel: App JS Files (1)                      | 51ms           
```

**Comment by joshuairl** [comment] 2015-07-17 23:14
I'm getting 113% CPU usage with latest ember-cli for some reason?
Same thing with sourcemapConcat sometimes 50,000ms-70000ms

**Comment by joshuairl** [comment] 2015-07-17 23:36
![image](https://cloud.githubusercontent.com/assets/171077/8759065/0ee6196e-2cbb-11e5-9694-f8bd1642d789.png)

OUCH :(

**Comment by stefanpenner** [comment] 2015-07-17 23:37
Ya something is funky. It seems to pull in far to much. I've been adding additional instrumentation to allow us to track down exactly what. I"ll hopefully land that this weekend.

**Comment by joshuairl** [comment] 2015-07-18 00:19
@stefanpenner You rock brother.
Thanks for all you do.

**Comment by stefanpenner** [comment] 2015-07-18 00:24
thanks, we will fix this. It might take a little elbow grease.

**Comment by joshuairl** [comment] 2015-07-18 16:04
@stefanpenner Love it.  Do what you do. :dancer:

**Comment by bjornstar** [comment] 2015-07-21 01:49
Any workarounds? `ember-cli` is absolutely useless on our developers' macbooks at the moment.

**Comment by stefanpenner** [comment] 2015-07-21 02:29
> Any workarounds?

move only stuff you need to vendor, and import from there.

**Comment by bjornstar** [comment] 2015-07-21 02:49
![screen shot 2015-07-21 at 11 47 40 am](https://cloud.githubusercontent.com/assets/20630/8792129/84e56d78-2f9e-11e5-9012-deddfe6796a6.png)

Two minute rebuild time. Something is horribly wrong here.

**Comment by stefanpenner** [comment] 2015-07-21 02:57
> Two minute rebuild time. Something is horribly wrong here.

yup, do you have any new information to add? I will continue to work on this later this week.

**Comment by brandonjmckay** [comment] 2015-07-23 01:36
subscribing

**Comment by kennethkalmer** [comment] 2015-07-23 17:41
@stefanpenner I might have an easy way for you to reproduce the issue. I was experiencing the same slow down when I upgraded [ember-paper](https://github.com/miguelcobain/ember-paper/) from 0.1.1 to 0.2.6. Build time shot up to more than 30 seconds. Out of desperation I switched to [ember-cli-materialize](http://mike.works/ember-cli-materialize) and my build times dropped to less than 2 seconds again...

I then tested it on two blank ember apps and you can clearly see the difference in build times:

Run `ember new ember-sample-paper && cd ember-sample-paper && ember install ember-paper`, accept all the overwrites from the blueprint and start a server, you'll get something like this:

```
Build successful - 27814ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Concat: Vendor                                | 11012ms
SourcemapConcat                               | 3554ms
SassCompiler                                  | 3292ms
Concat: Test Support JS                       | 3201ms
SourcemapConcat                               | 3121ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Concat: Vendor (1)                            | 11012ms
SourcemapConcat (3)                           | 6694ms (2231 ms)
SassCompiler (1)                              | 3292ms
Concat: Test Support JS (1)                   | 3201ms
```

The do the same for ember-cli-materialize, `ember new ember-sample-cli-materializer && cd ember-sample-cli-materialize && ember install ember-cli-materialize`. Accept blueprint conflicts and go for jQuery ^1.11.3 when bower complains. Running `ember server` will give you something like this:

```
Build successful - 7983ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Concat: Vendor                                | 4149ms
Babel                                         | 703ms
Babel                                         | 654ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Concat: Vendor (1)                            | 4149ms
Babel (7)                                     | 1770ms (252 ms)
```

_Note my machine was performing time machine backups and other crap, so performance was greatly impacted_...

28 seconds vs 8 seconds, huge difference between the two projects. So something in ember-paper might help diagnose what is going on. Maybe @miguelcobain could help provide info on what changed in later ember-paper versions. I did a quick scan and couldn't find any references to importing web fonts as mentioned in earlier comments, so I'm stuck.

More background info:

```
$ node -v                                                                                                                                                                                          
v0.12.7
$ npm -v
2.11.3
$ uname -a
Darwin Kenneths-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

**Comment by stefanpenner** [comment] 2015-07-23 17:42
@kennethkalmer awesome thanks!

Just an update, i have some local spikes that mitigate the majority of this slow down. Still noodling on the exact solution (that I can roll out, with minimal / no pain upgrading, and does't regression the fixes that introduced the issue). Its a fun puzzle.

**Comment by miguelcobain** [comment] 2015-07-23 18:10
@kennethkalmer @stefanpenner 

v0.1.1 and v0.2.6 diff: https://github.com/miguelcobain/ember-paper/compare/v0.1.1...v0.2.6

Main differences between ember-paper 0.1.1 and 0.2.6 are the ember-cli version and that the material icons are now being loaded from google.
However, there is this new large [scss file](https://github.com/miguelcobain/ember-paper/blob/47fe537018979b78a12df4ebb6de1b14ed939958/app/styles/paper-icon.scss#L97) with every icon definition. Don't know if sass is having a hard time on that (unlikely).

Also, we're now loading a file directly from `/vendor`: https://github.com/miguelcobain/ember-paper/blob/master/index.js#L16

Besides this, there are more scss and component files in the newer version.

I've never had such long times building ember-paper (or anything else). I'm on linux.

**Comment by stefanpenner** [comment] 2015-07-23 20:00
@miguelcobain thanks for the detailed report. I just need to carve out some time to address this.

**Comment by kennethkalmer** [comment] 2015-07-23 20:21
@stefanpenner @miguelcobain thanks! I'll definitely help test if and when needed!

**Comment by bucaran** [comment] 2015-07-24 05:57
@stefanpenner 

> Just an update, i have some local spikes that mitigate the majority of this slow down. Still noodling on the exact solution (that I can roll out, with minimal / no pain upgrading, and does't regression the fixes that introduced the issue). Its a fun puzzle.

Do you mind describing exactly where you think the problem is? Other people, myself included, could use that to help you. I am going through `ember-cli` massive ~1500 LOC base hopelessly trying to find a crack of light.

**Comment by joshuairl** [comment] 2015-07-24 14:11
Want to confirm that sourceMapConcat line stayed in my compilation until I removed google material design icons and hammerjs from bower_components directory.

Also, should be noted that it was loading them even though I didn't have them in Brocfile or bower.json... what's that about?

Also, I'm using ember-cli 0.2.7 so it's not isolated to 1.13.x.

If sourcemap concat is involved what so ever it seems to have the slowdown.

Once I deleted hammerjs and google material design icons form bower_components the slowness went away.

:-/  That's all I have for now!

**Comment by raytiley** [comment] 2015-07-24 14:18
I was talking with @rwjblue about this last night. I was noticing the same thing with the list-view addon that has a bunch of images in the dummy test app public folder. I thought I heard someone mention that things that shouldn't be (images, svgs, etc) are running through source maps. Haven't had time to investigate.

**Comment by stefanpenner** [comment] 2015-07-24 14:37
Yes @raytiley more is getting pulled in then expected, and also there exist some invalidations upstream that need to be fixed. Like broccoli-config-replacer.

For those interested in helping my time is extremely limited. But high level tasks are as follows. I plan on working on this again after I get the next cli release out. I'll follow up with more details.

* migrate out broccoli plugins to the new broccoli-plugin baseclass
* help finish broccoli-cauliflower as a broccoli-plugin upgrade (I think just tests need porting) 
* introduce invalidation logging (like I added to broccoli-caching-writer) to broccoli-cauliflower 
* merge Broccoli-cauliflower into broccoli-filter (just think of the former as an experimental branch of the later, that should now be merged)
* upgrade usages of merge-trees to the one that is stable (I believe the most recent version is)

* make broccoli-config-replacer stable (by migrating to the new filter, or if not possible moving to a strategy that is stable)

**Comment by bucaran** [comment] 2015-07-24 14:45
@stefan How come you are the only person working on this? ember-cli has gone out of control… This is just a wrapper for broccoli, but there is more source code in this project than in broccoli and grunt combined. And roughly 10 times more than in [Fly](http://git.io/fly).

**Comment by stefanpenner** [comment] 2015-07-24 16:07
> @stefan How come you are the only person working on this?

I'm not, many contributors -> https://github.com/ember-cli/ember-cli/graphs/contributors just everyone has different time

> ember-cli has gone out of control… This is just a wrapper for broccoli,

Sure, if you have suggestions to reduce entropy that would be valuable. But I don't believe `ember-cli` is "just a wrapper for broccoli"

**Comment by bucaran** [comment] 2015-07-24 16:37
@stefanpenner And that was trying to be constructive. Well, there is always deprecate and use your energy on more _ambitious_ enterprises. Advice noted.

**Comment by stefanpenner** [comment] 2015-07-24 16:39
> Well, there is always deprecate and use your energy on more ambitious enterprises.

maybe our definitions of constructive differ...

**Comment by bucaran** [comment] 2015-07-24 16:45
@stefanpenner I know you are really busy on this project, and although I can see there are quite a number of contributors (after this is what ember users are, for better or worse, stuck with), you seem to be the only one trying to fix bugs and answering to issues. I asked in a couple other open issues regarding specific places where one could help you, but only got the list you posted above. Unfortunately that is not good enough.

I have started to think the slow builds my team is experiencing has to do more with Broccoli's hard disk abuse and rampant IO dynamics than with `ember-cli` itself.

> if it perceived as just a "Wrapper" around broccoli.

Please help understand this better. If this is not just a Broccoli wrapper for Ember On Rails :wink: , what is it exactly?

**Comment by stefanpenner** [comment] 2015-07-24 17:11
> @stefanpenner I know you are really busy on this project,

Then please be mindful of my time.

I feel you are demanding I teach you the system, in-order for you to provide a hand. Based on this conversation I am dubious if this investment is at all in my (or the larger communities) favor.

> I have started to think the slow builds my team is experiencing have to do more with Broccoli's hard disk abuse and rampant IO dynamics than with ember-cli itself.

It is accurate that the build performance issues are during broccoli.rebuild system, but it is actually not broccoli nor IO that is the problem. For some reason, IO keeps coming up, but the system isn't at all bottlenecked on IO.

And in-fact the only time the system is CPU bottlenecked, is when a misbehaving plugin or two are causing invalidations or accidentally interacting with to many files.

Good news is these are totally solvable problems, just requires some elbow grease.

> I want to know what happens between task1 and task2, because I am experienced "black holes". Instrumentation shows the ms times for each task (concat, babel, merge, etc) but why does stuff stuck in between?

As mentioned above, adding invalidation logging to cauliflower-filter and then merging cauliflower-filter into mainline will help illuminate this for you. Now that I am on my laptop, I [can share a recent improvement](https://github.com/ember-cli/broccoli-caching-writer/pull/44) to the logging of broccoli-caching-writer. 

If you want to be helpful, please start with that.

**Comment by stefanpenner** [comment] 2015-07-27 17:23
quick update:

> introduce invalidation logging (like I added to broccoli-caching-writer) to broccoli-cauliflower

this task is done, pending review -> https://github.com/caitp/cauliflower-filter/pull/16

**Comment by jerel** [comment] 2015-07-28 01:05
In case it helps anyone:

I'm on Linux and an empty Ember project builds in 7 seconds on my machine. Installing `ember-paper` jumped that to 30+ seconds and a second file save while it was building would sometimes freeze the whole thing and require a `kill -9`. I found that it was entirely due to material-design-icons and since I wasn't using any icons this was a nice workaround:

* remove `material-design-icons` line from bower.json
* `rm -rf bower_components/material-design-icons`
* `pkill watchman` due to some sort of IN_Q_OVERFLOW watch error
* `ember serve`

Builds are back to 7 seconds.

**Comment by cah-danmonroe** [comment] 2015-07-28 03:11
FWIW, on my MacBook, I tried to remove material-design-icons from `ember-paper` as well and my rebuilds went down to under a second.

**Comment by miguelcobain** [comment] 2015-07-28 08:47
@jerel @cah-danmonroe I'm not getting this. ember-paper never had `material-design-icons` as a bower dependency. :confused:

**Comment by stefanpenner** [comment] 2015-07-31 15:18
So in addition to the above invalidations the are causing spurious cache purges.

broccoli-sourcemap-concat are broccoli-caching-writer are mis-aligned

BCW is not made aware when BSC has only specific files to deal with, resulting in BCW stating and iterator potentially massive trees. A quick local test showed that making [BCW aware](https://github.com/ember-cli/broccoli-caching-writer/blob/master/index.js#L76-L84) of [BSC's inputFiles](https://github.com/ef4/broccoli-sourcemap-concat/blob/master/simple-concat.js#L97) results in in nice improvement. Not the whole perf story, but a nice step in the right direction. I suspect combined with my above diagnosis will result in quite a nice boost.

@bucaran ^

**Comment by stefanpenner** [comment] 2015-08-06 21:35
https://github.com/ember-cli/broccoli-caching-writer/pull/53 reduces @borisding1994's example apps incremental time from 12s -> 2.5s for me, and initial from 20s -> 3.5s.

remaining chunks of time:

* 1.7s ember-cli-sass 
  * which apparently doesn't use any caching and just always rebuilds
  * i may take a look sometime soon
* 800ms funnel
  * this is twofold, actually a bug in ember-cli causing the funnel to need to deal with more files then it should – will be addressed sometime soon
  * an algorithmic change to funnels walkSync will allow for it to work performently in-light of the above issue - will be addressed next.

**Comment by david-duncan** [comment] 2015-08-06 21:39
fwiw its not just ember-cli-sass rebuilding every time, the issue exists over in ember-cli-less as well

There were several tickets opened in ember-cli-less but each was closed..

**Comment by runspired** [comment] 2015-08-06 22:10
Which very likely means it's in ember-cli-stylus as well which still hasn't added addon support.

**Comment by stefanpenner** [comment] 2015-08-07 23:30
> 800ms funnel – up next for me

https://github.com/joliss/node-walk-sync/pull/5 mitigates the funnel cost nearly entirely.

I have a local WIP that integrates it with `Funnel` but the code needs some cleanup. I'll be cleaning it up tonight, with a release planned this weekend.

**Comment by stefanpenner** [comment] 2015-08-08 04:52
updated #'s

initial build:

```
Build successful - 3078ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 2060ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 2060ms
Babel (3)     
```

incremental build:

```
Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 1457ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 1457ms
```

A quick look at SassCompiler reveals another relatively straight-forward set of fixes. I may limit external imports to ones explicitly added to the load-path. Although the ergonomics of that aren't the best, the perf outcome is fantastic. A local prototype reveals with that change the SassCompiler times drop to negligible if no sass files changed.

**Comment by brandonjmckay** [comment] 2015-08-10 15:56
The dude is a machine. Thank you so much stefanpenner.

**Comment by stefanpenner** [comment] 2015-08-10 19:35
v1.13.8 now includes the fixes the ember-cli related the original author reported. The Sass issue is still out-standing, and I will likely investigate that later this week.

updated numbers:

```
➜  slow-ember-cli-project git:(master) ✗ ember s
version: 1.13.8
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 8510ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 7378ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 7378ms

Job 1, 'ember s' has stopped
➜  slow-ember-cli-project git:(master) ✗ bg
Send job 1 'ember s' to background
➜  slow-ember-cli-project git:(master) ✗ touch app/app.js
➜  slow-ember-cli-project git:(master) ✗ file changed app.js

Build successful - 1877ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 1531ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 1531ms
```

As you can note: Sass(and other CSS preprocessors) still suffer a similar issue, but will be addressed soon.

There is more performance work outstanding, but the issue the original reporter described here should be addressed.

some more focused perf related tracking issues i have opened:

* https://github.com/ember-cli/ember-cli/issues/4645
* https://github.com/ember-cli/ember-cli/issues/4645
* https://github.com/ember-cli/ember-cli/issues/4644

**Closed by stefanpenner** 2015-08-10 19:35 UTC
Labels: bug, performance

**Comment by kennethkalmer** [comment] 2015-08-11 13:31
@stefanpenner thanks so much, the initial work you (and everyone else we don't know of) did made a huge difference already!

**Comment by kingpin2k** [comment] 2015-08-21 17:53
Looking good dropped from 20 seconds down to 3 seconds, as an FYI for anyone else who comes here, if you are running ember-cli in windows, make sure you are enabling symlinks ;)  http://www.ember-cli.com/user-guide/#symlinks-on-windows
