### ISSUE TITLE
Safari 10: "The network connection was lost."

### ISSUE THREAD

**Issue by workmanw** [ember-cli/ember-cli#6257] opened 2016-09-13 14:06 UTC
One of our developers (@lepolt) has upgraded to macOS Sierra and Safari 10. Shortly thereafter he noticed that he would get "network connection was lost" errors on ajax requests. It seems to happen about 2-3 times in the span of 40 ajax requests.

Here is a screenshot from his console:

![pasted image at 2016_09_13 10_01 am](https://cloud.githubusercontent.com/assets/825487/18476770/54f05722-7999-11e6-85e3-2c434e47be55.png)

Additionally, he connected to the server directly (bypassing the ember-cli proxy) and did not see this issue.

It is worth pointing out that we are also using a self signed SSL cert configured via `.ember-cli`. We have been doing so for a while and had no trouble with previous versions of Safari or other browsers, but wanted to point it out as it might be necessary to reproduce.
---

Output from `ember version --verbose && npm --version`:

```
ember-cli: 2.7.0
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: darwin x64

npm: 3.9.5
```

**Comment by nathanhammond** [comment] 2016-09-14 08:57
1. No other configuration change other than the upgrade?
2. No new `npm install`? Nothing?
3. Do the issues appear in non-Safari browsers?

Goals:
- Identify the set of changes.
- Deduce the set of possible culprits.

If this is a Safari + Sierra-specific bug I'm not going to be able to reproduce for a while, but maybe somebody else will be able to.

@workmanw Can you upgrade to the most-recent version of Safari on your box and see if that triggers the failure?

**Comment by workmanw** [comment] 2016-09-14 11:53
> 1. No other configuration change other than the upgrade?
No

> 2.  No new npm install? Nothing?
No

> 3. Do the issues appear in non-Safari browsers?
Nope, just Safari 10 (12602.1.50.0.8). He also used Chrome 53 (53.0.2785.113) and Firefox 48 (48.0.2) w/ Sierra and it had no issues.

What's weirder is that I upgraded my Safari to 10 (12602.1.50.0.5), staying on El Capitan and I had no issues. 

I will upgrade to Sierra GM and report back.

**Comment by workmanw** [comment] 2016-09-14 13:42
I can very easily reproduce this issue after upgrading to Sierra GM and Safari 10 (12602.1.50.0.8). 😢 

It seems like maybe this could just be a regression with that specific version of Safari 10. Seeing as how it's only the GM, maybe we should just hold for the time being and check after Sierra releases.

**Comment by nathanhammond** [comment] 2016-09-14 15:59
Okay, so Safari + Sierra = network issues. I have no clue what's going on. I'm going to leave this open for a week for awareness, but generally we don't keep tracking issues open on Ember CLI for things which we may not have control over. At that point I'm going to close it or hope somebody figured out what the underlying problem is that combination triggered.

So, people, thoughts?

**Comment by markschmid** [comment] 2016-10-14 13:55
Just as a quick note: I have exactly the same problem.
It happens on Safari Version 10.0 (12602.1.50.0.10) since upgrade to mac OS Sierra. I've never seen this error before. The error happens quite often, but only to localhost.

We're connecting via nginx as reverse proxy to our node stack (HTTPS, self-signed cert). We're not using anything ember-related at all though, I've found this discussion via a google search.

Tried to pinpoint it to anything, but no success so far. It might be related to Safari/mac OS Sierra.

**Comment by nathanhammond** [comment] 2016-10-31 06:38
Okay, y'all, I'm closing this as it's unlikely we are going to be able to do anything about it. @markschmid reports that this happens as well without Ember in the stack, which implies to me that it's an upstream issue in either https://github.com/nodejitsu/node-http-proxy or Safari + Sierra.

If people who encounter this can please continue to comment with your setups that would be fantastic. (Please also upgrade to the newest version of Sierra/Safari.)

**Closed by nathanhammond** 2016-10-31 06:38 UTC

**Comment by workmanw** [comment] 2016-10-31 11:06
Sounds good to me! I tried to build a reproduction, and while I was successful it was very convoluted. Despite getting all of the HTTP headers to match exactly, the reproduction still only worked when the end destination for proxy was Google App Engine. So ¯\\\_(ツ)_/¯. I agree this is not ember-cli's bug. Thank you.
