### ISSUE TITLE
"ember build" fails on Windows for newly created app

### ISSUE THREAD

**Issue by e-domnenko** [ember-cli/ember-cli#2974] opened 2015-01-13 16:09 UTC
Tested on versions 0.1.3, 0.1.4, 0.1.5 and 0.1.6, Windows 7 and Windows 8, using GitBash

After installing one of the versions above run
ember new app5
cd app5

Then trying to build app get next error:

```
$ ember build
version: 0.1.3
Could not find watchman, falling back to NodeWatcher for file system events
Build failed.
File: app5/app.js
false == true
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (d:\tmp\app5\node_modules\ember-cli-esnext\
node_modules\broccoli-esnext\node_modules\esnext\node_modules\recast\node_module
s\ast-types\lib\path-visitor.js:135:12)
    at Visitor.PVp.visit (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules
\broccoli-esnext\node_modules\esnext\node_modules\recast\node_modules\ast-types\
lib\path-visitor.js:117:21)
    at Function.transform (d:\tmp\app5\node_modules\ember-cli-esnext\node_module
s\broccoli-esnext\node_modules\esnext\node_modules\regenerator\lib\visit.js:31:1
8)
    at transform (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules\broccol
i-esnext\node_modules\esnext\lib\index.js:86:23)
    at compile (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules\broccoli-
esnext\node_modules\esnext\lib\index.js:33:9)
    at EsnextFilter.processString (d:\tmp\app5\node_modules\ember-cli-esnext\nod
e_modules\broccoli-esnext\index.js:41:16)
    at EsnextFilter.Filter.processFile (d:\tmp\app5\node_modules\ember-cli-esnex
t\node_modules\broccoli-esnext\node_modules\broccoli-filter\index.js:136:31)
    at Promise.resolve.then.catch.err.file (d:\tmp\app5\node_modules\ember-cli-e
snext\node_modules\broccoli-esnext\node_modules\broccoli-filter\index.js:82:21)
    at $$$internal$$tryCatch (d:\tmp\app5\node_modules\ember-cli-esnext\node_mod
ules\broccoli-esnext\node_modules\broccoli-filter\node_modules\rsvp\dist\rsvp.js
:490:16)
    at $$$internal$$invokeCallback (d:\tmp\app5\node_modules\ember-cli-esnext\no
de_modules\broccoli-esnext\node_modules\broccoli-filter\node_modules\rsvp\dist\r
svp.js:502:17)
```

**Comment by wayne-o** [comment] 2015-01-13 16:13
What's this? false == true

Is that something you added? Seems a bit cray cray to me...

On Tue, Jan 13, 2015 at 4:09 PM, Evgen Domnenko <notifications@github.com>
wrote:

> Tested on versions 0.1.3, 0.1.4, 0.1.5 and 0.1.6, Windows 7, using GitBash
>
> After installing one of the versions above run
> ember new app5
> cd app5
>
> Then trying to build app get next error:
>
> $ ember build
> version: 0.1.3
> Could not find watchman, falling back to NodeWatcher for file system events
> Build failed.
> File: app5/app.js
> false == true
> AssertionError: false == true
> at Visitor.PVp.visitWithoutReset
> (d:\tmp\app5\node_modules\ember-cli-esnext\
>
> node_modules\broccoli-esnext\node_modules\esnext\node_modules\recast\node_module
> s\ast-types\lib\path-visitor.js:135:12)
> at Visitor.PVp.visit
> (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules
>
> \broccoli-esnext\node_modules\esnext\node_modules\recast\node_modules\ast-types\
> lib\path-visitor.js:117:21)
> at Function.transform
> (d:\tmp\app5\node_modules\ember-cli-esnext\node_module
>
> s\broccoli-esnext\node_modules\esnext\node_modules\regenerator\lib\visit.js:31:1
> 8)
> at transform
> (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules\broccol
> i-esnext\node_modules\esnext\lib\index.js:86:23)
> at compile
> (d:\tmp\app5\node_modules\ember-cli-esnext\node_modules\broccoli-
> esnext\node_modules\esnext\lib\index.js:33:9)
> at EsnextFilter.processString
> (d:\tmp\app5\node_modules\ember-cli-esnext\nod
> e_modules\broccoli-esnext\index.js:41:16)
> at EsnextFilter.Filter.processFile
> (d:\tmp\app5\node_modules\ember-cli-esnex
>
> t\node_modules\broccoli-esnext\node_modules\broccoli-filter\index.js:136:31)
> at Promise.resolve.then.catch.err.file
> (d:\tmp\app5\node_modules\ember-cli-e
>
> snext\node_modules\broccoli-esnext\node_modules\broccoli-filter\index.js:82:21)
> at $$$internal$$tryCatch
> (d:\tmp\app5\node_modules\ember-cli-esnext\node_mod
>
> ules\broccoli-esnext\node_modules\broccoli-filter\node_modules\rsvp\dist\rsvp.js
> :490:16)
> at $$$internal$$invokeCallback
> (d:\tmp\app5\node_modules\ember-cli-esnext\no
>
> de_modules\broccoli-esnext\node_modules\broccoli-filter\node_modules\rsvp\dist\r
> svp.js:502:17)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/2974>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by stefanpenner** [comment] 2015-01-13 16:13
hey, sorry about this one.

Turns out an upstream dependency (ast-types) broke something. Anyways, this is a duplicate of: https://github.com/ember-cli/ember-cli/issues/2968 please be sure to search existing issues before posted.

quickfix: remove ember-cli-esnext and replace it with ember-cli-6to5

**Closed by stefanpenner** 2015-01-13 16:13 UTC
