### ISSUE TITLE
baseURL & rootURL - Ember CLI server inconsistency

### ISSUE THREAD

**Issue by williamhector** [ember-cli/ember-cli#4883] opened 2015-09-21 23:31 UTC
I understand there is some confusion around the use of baseURL and rootURL, however this is an issue that seems to be a bug in the Ember server.

The bug is that the ember server will sometimes serve up the assets and sometimes return 404s for the assets, depending on the baseURL config when it is launched.

Versions: 
Ember cli: 1.13.8
Ember: 1.13.7
OS: Windows 7

Steps to reproduce:
1. Make a new ember cli project
2. In app/index.html, change the 4 assets paths from "assets/file.ext" to "/dir/assets/file.ext"
3. In router.js, set rootURL to "/dir/"
4. Start the ember server and navigate to http://localhost:4200/dir/
5. In a network inspector, you should see that all the assets are being loaded from the correct urls, but the server is returning 404s for all of them
6. Kill the server
7. In config/environment.js, change the baseURL to "/dir" then restart the ember server
8. The assets are loaded, however the page urls will be incorrect, eg localhost:4200/dir/dir/
9. While the ember server is still running, change the baseURL back to "/" and try naving to localhost:4200/dir/ again. This time all the assets should be loaded, and the only difference is whether the desired config is set before launching the ember server or while it is currently running.

Extra info:
When our main project was still on ember-cli 0.2.7 and ember 1.12.0, we had the baseURL set to "/dir" but after upgrading to the version listed above, we had to change baseURL to "/" in order to maintain the previous routing behaviour, which includes supporting url hashes for IE9.

**Comment by stefanpenner** [comment] 2015-09-21 23:32
i suspect this is a duplicate: https://github.com/ember-cli/ember-cli/search?q=baseURL&type=Issues&utf8=%E2%9C%93 (i apologies for these issues, hopefully soon we can sort it out)

**Comment by williamhector** [comment] 2015-09-21 23:34
Cheers. I did have a look over the recent baseURL issues. None of the ones I looked at had similar symptoms, but you're probably right that the root cause is common.

**Comment by Turbo87** [comment] 2016-04-13 14:35
I agree that this is a duplicate of all the other baseURL/rootURL issues.

@williamhector what scenario are you trying to achieve in the end?

**Closed by Turbo87** 2016-04-13 14:35 UTC
Labels: Bug
