### ISSUE TITLE
Node 4 & Ember CLI 2.12.0 builds are failing

### ISSUE THREAD

**Issue by hayesmaker** [ember-cli/ember-cli#6866] opened 2017-03-17 16:48 UTC
[npm-debug.txt](https://github.com/ember-cli/ember-cli/files/851235/npm-debug.txt)

Seems like Node 4 builds are breaking when using Ember CLI (2.12.0)

---

Output from `ember version --verbose && npm --version`:
```
DEPRECATION: Node v4.0.0 is no longer supported by Ember CLI. We recommend that you use the most-recent "Active LTS" version of Node.js.
ember-cli: 2.12.0
http_parser: 2.5.0
node: 4.0.0
v8: 4.5.103.30
uv: 1.7.3
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 46
openssl: 1.0.2d
os: darwin x64
2.14.2
```

npm debug log attached

**Comment by rwjblue** [comment] 2017-03-17 16:54
Can you please share the commands used to cause the error? Also, a demo repo with steps to reproduce the issue would be massively helpful...

**Comment by hayesmaker** [comment] 2017-03-17 16:55
the command was npm i (post install: bower install && ember g ember-commons (a private addon) can't really share the code since it's locked behind private repos

**Comment by stefanpenner** [comment] 2017-03-17 17:55
The above gist is suggesting the error is within

`help-and-support@1.6.5` npm module, which does not appear to be a public module.

---

More details will need to be provided, or a reproduction. As is, not sure what we can do.

Also, worth pointing out: ember-cli's own tests are passing on node 4 https://travis-ci.org/ember-cli/ember-cli/jobs/212172981

**Comment by stefanpenner** [comment] 2017-03-17 17:56
stack provided isn't really helpful. (nor does it suggest ember-cli is an issue).

```
52719 info install help-and-support@1.6.5
352720 info postinstall help-and-support@1.6.5
352721 verbose unsafe-perm in lifecycle true
352722 info help-and-support@1.6.5 Failed to exec postinstall script
352723 verbose stack Error: help-and-support@1.6.5 postinstall: `bower install && ember g ember-commons && ember g ember-cli-es5-shim`
352723 verbose stack Exit status 1
352723 verbose stack     at EventEmitter.<anonymous> (/Users/hayesmaker/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
352723 verbose stack     at emitTwo (events.js:87:13)
352723 verbose stack     at EventEmitter.emit (events.js:172:7)
352723 verbose stack     at ChildProcess.<anonymous> (/Users/hayesmaker/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
352723 verbose stack     at emitTwo (events.js:87:13)
352723 verbose stack     at ChildProcess.emit (events.js:172:7)
352723 verbose stack     at maybeClose (internal/child_process.js:817:16)
352723 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
352724 verbose pkgid help-and-support@1.6.5
352725 verbose cwd /Users/hayesmaker/Workspace/island/help-and-support
352726 error Darwin 16.4.0
352727 error argv "/Users/hayesmaker/.nvm/versions/node/v4.0.0/bin/node" "/Users/hayesmaker/.nvm/versions/node/v4.0.0/bin/npm" "i"
352728 error node v4.0.0
352729 error npm  v2.14.2
352730 error code ELIFECYCLE
352731 error help-and-support@1.6.5 postinstall: `bower install && ember g ember-commons && ember g ember-cli-es5-shim`
352731 error Exit status 1
352732 error Failed at the help-and-support@1.6.5 postinstall script 'bower install && ember g ember-commons && ember g ember-cli-es5-shim'.
352732 error This is most likely a problem with the help-and-support package,
352732 error not with npm itself.
352732 error Tell the author that this fails on your system:
352732 error     bower install && ember g ember-commons && ember g ember-cli-es5-shim
352732 error You can get their info via:
352732 error     npm owner ls help-and-support
352732 error There is likely additional logging output above.
352733 verbose exit [ 1, true ]
```

**Comment by hayesmaker** [comment] 2017-03-18 10:35
sorry i thought the npm debug log would show the actual error.  It was something like: `Ember-CLI uses a newer version of npm, please update npm with npm install -g npm` shortly after a deprecation warning saying Node 4 was not supported by NPM.   

you'll have to wait til Monday if you need the exaxct messages since it's on a work machine.

**Comment by twokul** [comment] 2017-03-31 01:28
@hayesmaker any news on this?

**Comment by stefanpenner** [comment] 2017-04-03 20:00
Closing for now, will gladly reopen when additional information is provided. But as it stands this does not appear actionable (nor is it clear, the issue is with ember-cli).

**Closed by stefanpenner** 2017-04-03 20:00 UTC
Labels: Needs Submitter Response
