### ISSUE TITLE
ember serve fails when ipv6 disabled

### ISSUE THREAD

**Issue by wealth** [ember-cli/ember-cli#5602] opened 2016-03-11 05:54 UTC
Here's log:
```
[user@workstation work]$ ember serve
version: 2.4.2
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
listen EAFNOSUPPORT ::1:49152
Error: listen EAFNOSUPPORT ::1:49152
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at nextTickCallbackWith3Args (node.js:485:9)
    at process._tickCallback (node.js:391:17)
```
IPv6 is probably disabled on this machine. Is there a way to bind only IPv4 adress?

**Comment by wealth** [comment] 2016-03-11 06:35
Managed to get it working by removing '::1' here:
`/node_modules/ember-cli/node_modules/portfinder/lib/portfinder.js:79`
change
`var hosts = ['::1', '127.0.0.1', '0.0.0.0'];`
to
`var hosts = ['127.0.0.1', '0.0.0.0'];`

**Comment by stefanpenner** [comment] 2016-03-11 07:27
--host should allow it to be configured

**Comment by stefanpenner** [comment] 2016-03-11 07:28
Also please provide the information that yellow banner you saw when submitting the issue linked you to read suggested. OS/node versions etc

**Comment by wealth** [comment] 2016-03-11 07:40
--host and --live-reload-host not really helping, maybe some misconfiguration with node
```
[user@workstation25 qr-ember-frontend]$ cat /etc/issue && uname -a
Fedora release 21 (Twenty One)
Linux workstation25 3.18.7-200.fc21.x86_64 #1 SMP Wed Feb 11 21:53:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[user@workstation25 qr-ember-frontend]$ npm --version
3.3.12
[user@workstation25 qr-ember-frontend]$ ember --version
version: 2.4.2
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 5.5.0
os: linux x64
[user@workstation25 qr-ember-frontend]$ ember serve
version: 2.4.2
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
listen EAFNOSUPPORT ::1:49152
Error: listen EAFNOSUPPORT ::1:49152
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at nextTickCallbackWith3Args (node.js:485:9)
    at process._tickCallback (node.js:391:17)
[user@workstation25 qr-ember-frontend]$ ember serve -lrh 127.0.0.1 -H 127.0.0.1
version: 2.4.2
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
listen EAFNOSUPPORT ::1:49152
Error: listen EAFNOSUPPORT ::1:49152
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at nextTickCallbackWith3Args (node.js:485:9)
    at process._tickCallback (node.js:391:17)
[user@workstation25 qr-ember-frontend]$ 
```
steps to reproduce:
1. ember new test_app
2. cd test_app
3. ember serve

**Comment by stefanpenner** [comment] 2016-03-11 17:06
Hmm it might be the port finder code. Any recommendations for reproducing this?

**Comment by wealth** [comment] 2016-03-12 02:15
Basically, you need to disable ipv6 support systemwide, probably in kernel, by removing ipv6-related mods. I've done it a while ago, because our corporate network doesnt handle it well.
Also looks like it's a common issue across node packages, e.g. https://github.com/Jalle19/node-ffmpeg-mpegts-proxy/issues/5

**Comment by Turbo87** [comment] 2016-03-14 15:42
has this been reported to https://github.com/indexzero/node-portfinder yet?

**Comment by Soliah** [comment] 2016-03-17 07:25
Not sure if this is related, but we're also getting failed serve on CircleCI with 2.4.2. Here's a demo repo https://circleci.com/gh/Soliah/ember-docker-test/2

```
$ ember server
version: 2.4.2
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
listen EADDRNOTAVAIL ::1:49152
Error: listen EADDRNOTAVAIL ::1:49152
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:463:9)

at process._tickCallback (node.js:369:17) ember server returned exit code 1
```

2.3.0 has been fine: https://circleci.com/gh/Soliah/ember-docker-test23/2

**Comment by stefanpenner** [comment] 2016-03-17 16:10
2.3 has an older version of port finder i believe, we are pending a port-finder release now.

**Comment by Soliah** [comment] 2016-03-18 01:17
@stefanpenner Anyway we can workaround this in the meantime?

**Comment by kellyselden** [comment] 2016-03-18 13:47
> Anyway we can workaround this in the meantime?

cc @eriktrom

**Comment by eriktrom** [comment] 2016-03-18 13:57
sorry I didn't see this - @kellyselden - sure - i froze portfinder at the sha where this was fixed(current master) - and wrapped the failing windows only test in an if block with a comment - if we merge #5391 this will be fixed (and close)

**Comment by eriktrom** [comment] 2016-03-18 14:03
fwiw - this is the exact upstream error that has been fixed, fyi

**Comment by ajgordo** [comment] 2016-07-01 00:23
Running under ember-cli 2.4+ we are still seeing this issue. I have confirmed that portfinder 1.0.3 is being used, and that the changes made with 2e22f95d831428b5cf6ce63e8681533a02daa034 commit of portfinder is definitely in there.
The workaround of updating `/node_modules/ember-cli/node_modules/portfinder/lib/portfinder.js` does fix this so it seems perhaps to be related?
Any thoughts?

**Comment by eriktrom** [comment] 2016-07-01 00:31
@ajgordo - can you run this:

```bash
netstat -an | grep THE_PORT_IT_TRIED_TO_START_ON
```

My guess is that the interface its trying to start on is `::0` or `::2` which will happen if you run from a vm like parallels.

See the discussion at the bottom (closed issue) https://github.com/indexzero/node-portfinder/issues/21 which became an open issue on portfinder https://github.com/indexzero/node-portfinder/issues/32

I need to add some more interfaces and would be happy too do so. Let me know what interface you need.

**Comment by eriktrom** [comment] 2016-07-09 05:16
There does seem to be a regression somewhere - I'm pairing with someone tonight and they had the same issue. I will take a look at what the deal is. Thanks @ajgordo for reporting the issue.

**Comment by eriktrom** [comment] 2016-07-09 14:08
@ajgordo - can you test out https://github.com/indexzero/node-portfinder/pull/33 - it should fix the issue

Will make pr for portfinder bump upon confirmation. 

Thanks again @ajgordo for finding this. MacOS seems to have changed the interfaces you can bind to substantially in a recent update. :shrugs:

**Comment by mnannola** [comment] 2016-07-15 15:50
@eriktrom 
I am seeing this issue with ember-cli 2.4.3 and portfinder 1.0.4.  This is on a new ember addon.  OsX 10.11.5.

    Error: listen EADDRNOTAVAIL
        at exports._errnoException (util.js:746:11)
        at Server._listen2 (net.js:1112:19)
        at listen (net.js:1155:10)
        at net.js:1253:9
        at dns.js:85:18
        at process._tickCallback (node.js:355:11)

The problem I think is that portfinder.js line 114 is looking for err.address, but the error object does not include an address property.  Since I know the address that is causing the error, I worked around this issue by adding this:

    err.address = 'fe80::1';
    var idx = exports._defaultHosts.indexOf(err.address);

Not sure why that address property doesn't exist on the error object.  Let me know if you need any more info.

**Comment by eriktrom** [comment] 2016-07-15 19:44
@mnannola - thanks for reporting the issue - I'm not sure of the exact answer at the moment, it'll hopefully come to me, this interface stuff is all a bit odd. I'll debug this weekend. 

In the meantime do you mind giving me two pieces of information (you can put it in a gist, the output may be long):

1.  `netstat -an | grep THE_PORT_IT_TRIED_TO_START_ON`
2. open up a node console and run: `os.networkInterfaces()` - also what what version of node are you running.

Your right that sometimes there is no `err.address` on the error object. Below line 114 I was handling this prior to the commit merged last night. The interesting thing is that if there is no `err.address` property it may be difficult to auto-lookup a free port on all machines auto-magically, I have to recall all the scenarios, which I'll think about. If you see anything that could help answer this question while printing the previous output on your machine - just anything that might be different on your machine than normal - your feedback is greatly appreciated. 

Thanks again a bunch for reporting the issue and for your help.

**Comment by mnannola** [comment] 2016-07-15 20:11
@eriktrom 
1.  Running that command with a port of 4200 does not bring back anything.  I also tried starting the ember server on different ports that I know are free, and would receive the same error.  It doesn't seem to matter which port I choose.
2. [os.networkInterface gist](https://gist.github.com/mnannola/d836949faa3c3b4794b46078a5701705)
Node: v0.12.0

I am also using nvm 0.23.3 to manage my node versions.   If I think of anything else that is different I will let you know.

**Comment by eriktrom** [comment] 2016-07-15 20:17
@mnannola - hmm - `netmask: '255.255.254.0',` - portfinder is not looking for this - it looks for `netmask: '255.255.255.0'`. Also `fe80::1` does not bind on my machine. So technically there are 2 differences. The fact that the netmask is different or that the port is un-bindable (the inverse problem basically of what you see) both become hard to catch without `err.address`.

I'll figure it out :) 

Thanks a bunch for that output

**Comment by stefanpenner** [comment] 2016-07-15 20:46
@eriktrom looks like some co-workers have also run into this. I'm currently a-bit busy to dig in though...

**Comment by eriktrom** [comment] 2016-07-15 20:57
@stefanpenner - I have to figure out what to do about the lack of `err.address` - currently the options I have in my head are:

a) (cheap hack, likely to break again) - add another netmask to the list, like `255.255.254.0`
b) if there is no `err.address` dont provide portfinder functionality, basically throw and say put in a host manually
c) roll back and think about this all a bit more, but lose any more bug reports that may come in and help solve the issue
d) leave it and fix

I won't have time to make a real commit (with deep thought) until tomorrow afternoon as I am about to leave but I would make a rollback commit if u think its necessary - also curious about the release cycle - merging last nite put this on master only correct? (in which case its okay there are some bugs b/c we kinda need the bug reports to help us)

are we choosing d) for today, thanks :)

(that list is a little jumbled as the first 2 options I dont think are really good options, thus really its d or c for today)

**Comment by stefanpenner** [comment] 2016-07-15 21:02
lets track this in a fresh issue https://github.com/ember-cli/ember-cli/issues/6083 it looks like the original issue isn't quite correct.

@eriktrom mind transfering over what you to feel to be the most important bits from here?

**Closed by stefanpenner** 2016-07-15 21:02 UTC
Labels: Bug, Needs Dependency Fix
