### ISSUE TITLE
Ember test hangs forever on browser failure

### ISSUE THREAD

**Issue by orf** [ember-cli/ember-cli#5798] opened 2016-04-14 14:49 UTC
Hello, we're having intermittent failures on our CI server with the following output:

`not ok 1 Browser "chromium-browser --user-data-dir=/tmp/testem-8694.chromium --no-default-browser-check --no-first-run --ignore-certificate-errors --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/8694/tests/index.html?hidepassed" failed to connect. testem.js not loaded?`

We're launching the tests like so:
`xvfb-run -e ~/xvfb_out -a --server-args='-screen 0, 1024x768x16' ember test -l chromium,firefox -r tap`

This issue isn't regarding the failure to start the browsers, but if this does happen `ember test` just hangs forever. Is it possible to detect this and either skip to the next browser in the sequence, or abort completely?

Output from ember version --verbose:
```
ember-cli: 2.4.3
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: linux x64

```

**Comment by stefanpenner** [comment] 2016-04-14 15:28
this is most likely a testem.js issue

cc @johanneswuerbach

**Comment by orf** [comment] 2016-04-15 12:21
The browser exists, it's just for some unknown reason the browser (always Chrome, but this is always first in our runs) seems to hang/fail to start occasionally. We're running it through a `xvfb-run` so it's hard to debug, but when testem.js fails to connect it errors to stdout, but the `ember` process just sits there forever until it is forcibly killed.

I think `ember test` should detect when this happens and abort the testing, if possible.

You can reproduce this by replacing `chromium-browser` in `/usr/bin/` this script:

```
#!/bin/bash
sleep 100000
```

Then running `ember test -l chromium`.

**Comment by johanneswuerbach** [comment] 2016-04-15 12:28
Strange, I'll try to find time to investigate. Looks like testem is not able / not trying to nuke the process probably and then just hangs.

**Comment by orf** [comment] 2016-04-15 12:32
Awesome, thanks :+1: 

One other thing we've noticed with testem is that our `/tmp` directory fills up with profiles pretty quickly. Does testem not attempt to clean them up?

**Comment by rwjblue** [comment] 2016-04-15 14:26
Cleaning the project local tmp dir is the responsibility of ember-cli (not testem).  Most likely the folders are not getting cleaned because of the original issue reported (depending on how you kill the process our on exit cleanup handlers may not be executing).

**Comment by stefanpenner** [comment] 2016-04-15 14:34
i thought we fixed most of the testem <-> ember-cli tmp dir leaking issues. Maybe there are more.

**Comment by rwjblue** [comment] 2016-04-15 14:36
@stefanpenner - Ya, same.  This is the first report of that in a while.  I suspect that when the process is `kill -9` that we don't cleanup (since our exit hooks aren't called).  We may want to implement that locking system we discussed previously...

**Comment by johanneswuerbach** [comment] 2016-04-15 14:36
I think @orf was talking about browser profiles not being cleaned after `ember test`, which might be caused by testem not cleaning them.

**Comment by orf** [comment] 2016-04-15 15:00
Yep, it's the browser profiles. They are never cleaned as far as I can tell, which is not a huge deal because it's `/tmp` after all.

```
➜  ~ ls /tmp | grep "testem-" | wc -l
33
```
That's since I reported this issue and did a clean of `/tmp`, we normally have thousands of the buggers.

**Comment by stefanpenner** [comment] 2016-04-15 16:09
> Yep, it's the browser profiles.

ah ok.

**Comment by nathanhammond** [comment] 2016-08-28 01:54
@orf @johanneswuerbach Has this been addressed? Or do you have a tracking issue over at the https://github.com/testem/testem repository? This isn't actionable over here on the Ember CLI side of things so rather than hold open an issue for it I'm going to close it.

**Closed by nathanhammond** 2016-08-28 01:54 UTC
Labels: Needs Dependency Fix, Needs Reproduction

**Comment by johanneswuerbach** [comment] 2016-08-28 06:30
@nathanhammond the should have been fixed inside testem
