### ISSUE TITLE
server blocks during rebuilds

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#8011] opened 2018-09-04 21:13 UTC
### Background

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.8.0
node: 8.11.4
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.6.0
1.6.0
```

### Problem

`ember server` accepts, but blocks HTTP requests during rebuilds. Under most circumstances, this is a good experience. I start up the server, switch to my browser, navigate to `http://localhost:4200/`, and the browser waits for ember-cli to serve the HTML.

In my development environment, however, we use a reverse proxy to route requests among a number of ember (and non-ember) applications. The blocking causes the reverse proxy's health checks to fail.

### Workaround

Simply make the health checks longer. Ten seconds tends to be enough time for most rebuilds, but they still fail every so often.

### Attempted solution

My first hypothesis was that the blocking was in an express middleware or endpoint that waits for a rebuild and then serves files. So I build the following in-repo addon to circumvent that:

```js
lib/ember-cli-healthcheck/index.js

/* eslint-env node */
'use strict'

function healthcheck(req, res) {
  res.status(204).end()
}

module.exports = {
  name: 'ember-cli-healthcheck',

  isDevelopingAddon() {
    return true
  },

  serverMiddleware(config) {
    const { app, options } = config
    const healthcheckPath = options.healthcheckPath || '/healthcheck'
    // > The app.get() function is automatically called for the HTTP HEAD method
    // > in addition to the GET method if app.head() was not called for the path before app.get().
    // - https://expressjs.com/en/api.html#app.METHOD
    app.get(healthcheckPath, healthcheck)
  }
}
```

The healthcheck definitely gets called:
```bash
$ curl -svo /dev/null http://localhost:4200/healthcheck 2>&1 | grep HTTP/1.1
> GET /healthcheck HTTP/1.1
< HTTP/1.1 204 No Content
```

But if I call it during a rebuild, it still blocks:

```bash
file changed styles/overrides/_style-guide.scss
file changed overrides/_style-guide.scss
$ curl -svo /dev/null http://localhost:4200/healthcheck 2>&1 | grep HTTP/1.1
> GET /healthcheck HTTP/1.1
Build successful (10654ms) – Serving on http://localhost:4200/
< HTTP/1.1 204 No Content
```

It seems that whatever is causing the blocking happens before my express handler gets invoked.

**Comment by stefanpenner** [comment] 2018-09-05 21:48
So we explicitly do block all requests, in the broccoli-watcher middleware, is this what you mean? Or do you mean that the process itself is blocked for periods longer then 10s?

**Comment by jamesarosen** [comment] 2018-09-05 21:54
> So we explicitly do block all requests during build to avoid stale reads, in the broccoli-watcher middleware, is this what you mean?

It might be. What I don't understand is why that would affect my custom middleware that just immediately responds with a 204.

**Comment by rwjblue** [comment] 2018-09-05 22:52
Likely because we can’t know that that path isn’t a static file result of the build, and therefore have to wait to confirm...

**Comment by jamesarosen** [comment] 2018-09-05 23:10
I suspect the real problem is that I don't understand what's actually happening. Here's my mental model:

```
↓ request from HTTP
various express middleware
express endpoint that serves files from ember builds
```

In that mental model, only requests that get to the "files" endpoint would block while the app rebuilds. Anything mounted above that in the stack would still respond immediately. So what seems to be happening is that when I call `app.use` in my `addon/index.js`, it's getting added after the blocking endpoint.

Of course, I could be totally wrong. The true model might be

```
↓ request from HTTP
thing that queues requests, watches for changes, rebuilds app, then restarts the server
  express server
    various express middleware
    endpoint that serves from the now-definitively-built app
```

**Comment by Turbo87** [comment] 2018-09-22 17:16
maybe I'm missing something, but why are you running healthchecks on your dev server?!

**Comment by jamesarosen** [comment] 2018-09-26 18:44
> why are you running healthchecks on your dev server?

It's a great question. I admit it's a somewhat unusual use-case. We have multiple Ember applications that run on the same domain. We use Varnish as a reverse-proxy to route among them (and do caching). That way, we can have a page on `http://dev.local/app-1/a/thing` that links to `/app-2/another/type-of-thing`.

Healthchecks aren't strictly required for Varnish to work. If `app-2` were down and you clicked that link, you would just get an error page after a long timeout.

But we actually use the healthchecks to make it a little easier to develop. One of the apps does session management. Most people don't develop it, but do need to have it running in order to sign in to their other apps. Instead of requiring the developer to run the Session app and their own app(s), we actually bundle a precompiled version of the session app into the dev environment. We use Varnish healthchecks to fall back to that if the developer isn't running `ember serve` for the Session app localy.

**Comment by evrowe** [comment] 2018-10-01 17:30
Having also recently experimented with this, it turns out the solution to making sure that a healthcheck URL is to add the following to our addon's `package.json`:

```json
"ember-addon": {
    "before": "broccoli-watcher"
}
```

This ensures that the healthcheck route mounts to the express app before the code in `broccoli-watcher` that handles serving 500 errors for all (other) requests. The error handling behavior then still works as intended, but allows our healthcheck URL to still be available and respond with a `200` even when the build is broken so that our dev environment knows that the ember server is running.

**Comment by locks** [comment] 2022-02-10 00:15
I'm closing this issue under the assumption that the latest comment is an acceptable workaround. Thanks for the discussion everyone :)

**Closed by locks** 2022-02-10 00:15 UTC
