### ISSUE TITLE
Livereload is not working, when SSL is on

### ISSUE THREAD

**Issue by JohnnyBushy** [ember-cli/ember-cli#8041] opened 2018-09-12 17:38 UTC
Hi, we updated to `3.4.2` and found some problem.

It seems like after `v3.4.0-beta.2` release, livereload became broken, in case when `ssl` option is set to `true`.
I see that request to `GET https://localhost:4200/_lr/livereload.js?host=localhost&port=4200` produces `404` response. 
If I turn `ssl` off, then it works properly.

**Comment by rwjblue** [comment] 2018-09-12 17:52
Thanks for reporting! Looks like I missed this one:

 https://github.com/ember-cli/ember-cli/blob/4eabec478936a1fd5247701b9cd3bb401bc35f33/lib/tasks/server/livereload-server.js#L122 

In #8038.

**Comment by ryanhollister** [comment] 2018-09-12 19:45
I dont know, for me 3.4.2's live reloading is broken ssl or not. the livereload.js file just 404s. If i bypass the cleanBaseUrl func and just statically pass '/' to 

`this.liveReloadServer = new Server({
          app: this.app,
          dashboard: 'false',
          prefix: '/',
          port: options.port,
        });`

and 

`this.app.use('/', this.liveReloadServer.handler.bind(this.liveReloadServer));`

it works fine. The value that comes out of cleanBaseUrl is /_lr/ ... is that expected?

**Comment by rwjblue** [comment] 2018-09-12 20:29
@ryanhollister - Some questions for you:

* Are you using a root url?
* How are you launching the server?
* Do you have any other live reload options set in the command line or `.ember-cli` file?
* Can you reproduce in a new app?

**Comment by ryanhollister** [comment] 2018-09-12 20:45
Are you using a root url?
 - rootURL: '',
How are you launching the server?
just 'ember s' but it is in a lerna monorepo. So ember s is being run from the ember app's folder inside the packages directory.
Do you have any other live reload options set in the command line or .ember-cli file?
no
Can you reproduce in a new app?
no i cannot, so maybe it is something with the lerna structure then

**Comment by rwjblue** [comment] 2018-09-19 12:47
Fixed by https://github.com/ember-cli/ember-cli/pull/8044 and queued up for release as 3.4.3 soon...

**Comment by rwjblue** [comment] 2018-09-20 21:56
fix released in v3.4.3

**Closed by rwjblue** 2018-09-20 21:56 UTC
