### ISSUE TITLE
With bower gone, upgrading older apps breaks

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#6993] opened 2017-04-29 21:07 UTC
This isn't a plea to bring bower back. However, when an older app has duplicate dependencies like `ember-cli-shims`, because bower.json is completely gone from the `init` process it doesn't overwrite `bower.json` to remove any potential duplicate dependencies.

Perhaps the app blueprint should continue to try to delete `bower.json` until 3.x ?

**Comment by rwjblue** [comment] 2017-04-29 23:02
Yeah, this is a pain point.  Until the very end of the 2.13 beta cycle we actually deleted `bower.json` during `ember init`.  Unfortunately, that was done without prompting the user so it was very unexpected.  

We fully intend to bring back deleting `bower.json` and `.bowerrc` with a proper prompt...

**Comment by Turbo87** [comment] 2017-05-02 07:08
closing as duplicate of https://github.com/ember-cli/ember-cli/issues/6976

**Closed by Turbo87** 2017-05-02 07:08 UTC
