### ISSUE TITLE
Test timed out

### ISSUE THREAD

**Issue by andrei-sheina** [ember-cli/ember-cli#6289] opened 2016-09-21 11:13 UTC
I have an Ember app and using standard ember testing configuration (testem, phantom, qunit). I am trying to launch the simplest test, here is the code (simply modified from ember-cli guides):
```
import Ember from "ember";
import { module, test } from 'qunit';
import startApp from '../helpers/start-app';
var App;

module('An Integration test', {
  beforeEach: function() {
    App = startApp();
  },
  afterEach: function() {
    Ember.run(App, App.destroy);
  }
});

test("Page contents", function(assert) {
  visit('/sign-in')
  .then(function() {
    assert.equal(Ember.$('div.brand').length, 1, "I am on sign in page");
    fillIn('input#login', 'blabla@mail.com');
    fillIn('input#password', 'qwerty');
    click('button.btn')
    .then(() => {
      assert.equal(Ember.$('li.breadcrumb-item:contains("Weekly Imports")').length, 1, "I am on weekly imports page");
    })
  });
});
```

And i'm getting the following error in terminal:
```
not ok 1 PhantomJS 2.1 - An Integration test: Page contents
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:434:15)
    at EventEmitter.App.exit (/home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:189:23)
    at /home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:103:14
    at tryCatcher (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
Obviously problem with promises (simple test without using promises works fine).
How can i fix that?

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
os: linux x64
3.3.6
```

**Comment by nathanhammond** [comment] 2016-09-21 16:15
You shouldn't directly chain off of any of these promises. You'll note that [in the guides](https://guides.emberjs.com/v2.8.0/testing/acceptance/#toc_wait-helpers) we use the `andThen` helper.

```javascript
andThen(function() {
  assert.equal(currentURL(), '/login');
});
```

Change that and I bet it works.

I'm closing this issue as likely not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. Please stop by [#-help](https://embercommunity.slack.com/messages/-help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) as that's a better forum for learning.

**Closed by nathanhammond** 2016-09-21 16:15 UTC

**Comment by emilenriquez** [comment] 2017-05-22 05:28
Hi in my case I have a simple test code using andThen but it also gives me a timeout error even after increasing the timeout duration.

Here's my code

```
import { test } from 'qunit';
// import Ember from 'ember';
import moduleForAcceptance from 'rates-ui/tests/helpers/module-for-acceptance';

moduleForAcceptance('Acceptance | root');

test('visiting /filter-management', function(assert) {	
	visit('/filter-management');

  andThen(function() {
  	console.log('and then');

    assert.equal(currentURL(), '/filter-management');
    console.log('asserted');
    console.log(currentURL());    
  });
});
```

**Comment by emilenriquez** [comment] 2017-05-22 05:29
@nathanhammond
