### ISSUE TITLE
Newest published version of Heimdalljs is suddenly breaking ember-cli

### ISSUE THREAD

**Issue by chrisccerami** [ember-cli/ember-cli#6435] opened 2016-11-15 23:07 UTC
It looks like a new version of [Heimdalljs](https://www.npmjs.com/package/heimdalljs) was just published (0.2.2), and all of a sudden I can't run the ember server or use any other ember-cli commands.

```
➜  cpc git:(development) ember s --proxy=http://localhost:3000
/Users/ccerami/dev/cpc/node_modules/heimdalljs-fs-monitor/index.js:59
  var metrics = heimdall.statsFor('fs');
                         ^

TypeError: heimdall.statsFor is not a function
    at FSMonitor._measure (/Users/ccerami/dev/cpc/node_modules/heimdalljs-fs-monitor/index.js:59:26)
    at Object.realpathSync (/Users/ccerami/dev/cpc/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryPackage (module.js:93:10)
    at Function.Module._findPath (module.js:151:20)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

---

Output from `ember version --verbose && npm --version`:
Can't produce the output from `ember version` due to the aforementioned issue, but we're using Ember 2.9.1 and npm 3.8.6

**Comment by nathanhammond** [comment] 2016-11-15 23:08
Closing as duplicate of https://github.com/ember-cli/ember-cli/issues/6434

**Closed by nathanhammond** 2016-11-15 23:08 UTC
