### ISSUE TITLE
Build error in v2.3.0 (loader.js related)

### ISSUE THREAD

**Issue by oliverwilkie** [ember-cli/ember-cli#5478] opened 2016-02-16 18:40 UTC
Unable to run ember server after bumping to the recently released v2.3.0

Reproducable Dummy App: https://github.com/oliverwilkie/dummy

Build error
Merge error: conflicting file types: loader.js is a directory in /Users/oliverw/projects/dispatcher/tmp/broccoli_merge_trees-input_base_path-28kqcRDc.tmp/18 but a file in /Users/oliverw/projects/dispatcher/tmp/broccoli_merge_trees-input_base_path-28kqcRDc.tmp/33
Remove or rename either of those.

**Comment by rwjblue** [comment] 2016-02-16 23:54
This is being caused by ember-cli-timecop's `treeFor` hook.  I opened an issue over there with a suggestion on how to fix: https://github.com/matteodepalo/ember-cli-timecop/issues/2.

I am also updating `loader.js` to prevent this sort of issue (which should mean that ember-cli-timecop changes shouldn't be required, but they should still happen).

loader.js updated in https://github.com/ember-cli/loader.js/pull/68, and released as loader.js@4.0.1.

**Closed by rwjblue** 2016-02-16 23:54 UTC

**Comment by oliverwilkie** [comment] 2016-02-18 01:59
Thanks @rwjblue! For next time, do you have any protips for identifying the culprit dependency?

**Comment by rwjblue** [comment] 2016-02-18 02:04
I deleted them from `package.json` one at a time, until I got a different error :stuck_out_tongue_winking_eye:.  Overall, took less than 5 minutes to identify which addon, then a few more to figure out why (it wasn't immediately obvious).
