### ISSUE TITLE
Custom blueprint creates mismatched paths for addons/apps

### ISSUE THREAD

**Issue by briarsweetbriar** [ember-cli/ember-cli#5908] opened 2016-05-20 00:22 UTC
I've got an example of this [here](https://github.com/null-null-null/blueprint-example).

Steps to reproduce:

1) Create an addon: `ember addon my-addon`
2) Create a custom blueprint: `ember g blueprint my-blueprint`
3) Have the blueprint populate folders other than it's name:

```
  blueprints/my-blueprint
  ├── files
  │   └── __root__
  │       └── some
  │           └── random-director
  │              └── __name__.js
  └── index.js
```

4) Use the blueprint: `ember g my-blueprint foo`
5) Note the mismatch:

```
  addon
  │   └── some
  │        └── random-director
  │           └── foo.js

  app
  │   └── my-blueprints
  │        └── foo.js
```

6) Checkout `app/my-blueprints/foo.js`:

```
export { default } from 'my-addon/my-blueprints/foo';
```

I would expect the paths in `addon` and `app` to match, as well as for the `app` file to correctly point to its corresponding `addon` source.

Would be happy to look into this, if it seems like a good problem for someone new to the project to tackle.

**Comment by null-null-null** [comment] 2016-05-20 19:18
Looks like [this](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon-import/index.js#L26) is the first half of the problem: creating the wrong folder structure. But to resolve it, we'll need to get access to the correct folder structure through the options, and I'm not sure how that's done.

The second half of the problem is [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon-import/index.js#L41): providing the correct import path in `foo.js`. Basically, resolving it begs the same question. How do we get the correct path?

**Comment by locks** [comment] 2023-07-24 23:46
Closing as stale. Thanks for reporting!

**Closed by locks** 2023-07-24 23:46 UTC
Labels: bug, needs reproduction, help wanted
