### ISSUE TITLE
Using Ember CLI addons on fiddle services

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli#3050] opened 2015-01-21 11:26 UTC
Hi!

It is hard to underestimate the importance of fiddle services, namely https://emberjs.jsbin.com/, to the Ember community. Fiddle services allow effortlessly code and share live Ember apps, allowing Ember users to evaluate and exchange ideas, debug issues, request and provide help. When asking a question on StackOverflow, users are encouraged to provide an executable JSBin/JSFiddle demo, so that others can quickly get their hands into the issue.

More and more essential libraries that extend Ember are being released as Ember CLI addons. They are distributed via npm which makes it impossible to use them on fiddle services. I consider this a serious (and growing!) problem. With Ember 2 migrating to Ember CLI, an ability to run Ember demos on fiddle sites might die out completely.

I can think of two approaches to solving this problem.

* * *

## a. Encouraging addon creators to split their addons

It is technically possible to release an addon that works both in globals and Ember CLI environments.

And Example of such an addon is Simple Auth. It has three repositories:

* Main source code: [ember-simple-auth](https://github.com/simplabs/ember-simple-auth).
* Precompiled bower package: [ember-simple-auth-component](https://github.com/simplabs/ember-simple-auth-component), containing both globals and AMD versions.
* Ember CLI wrapper: [ember-cli-simple-auth](https://github.com/simplabs/ember-cli-simple-auth).

Apparently, it requires much more effort to organize an addon in such a way. It's not a trivial thing to do, i personally don't understand a number of things. I've asked a [question](http://stackoverflow.com/questions/27999488/how-do-i-split-my-ember-cli-addon-into-a-vanilla-ember-library-and-an-ember-cli) on StackOverflow and it remains unanswered despite a humble bounty.

Solving the subj issue this way would require writing a thorough guide to organizing addons and developing tools that simplify addon creation and releasing.

## b. Developing an Ember CLI-capable fiddle service

There should be a fiddle service that allows effortlessly importing Ember CLI addons and running live Ember apps with them.

For this task to be feasible, there should be a way to run Ember CLI completely client-side. Then the app could be hosted on Github Pages and use Github Gists as a backend.

* * *

I hope to start a discussion of the matter for the community to decide on an acceptable solution and start its implementation.

**Comment by joostdevries** [comment] 2015-01-21 12:36
@lolmaus I agree that this is something that would make asking for and providing help a whole lot easier.  I know @stefanpenner has a [basic version](https://twitter.com/stefanpenner/status/530403279898177537) for JSBin and there was some discussion on this earlier (#840). 

Right now, I think that what's proposed in #840 still sounds like the most feasible solution. Allow an easy export of your project which you can use in JSBin. 

Completely mimicking Ember CLI in JSBin would mean getting all the stuff from package.json/bower.json, transpiling, running filters etc etc etc. which would make JSBin an extremely heavy application which is probably outside or their scope.

I don't think anyone has built the addon proposed in #840 yet. Would this be something you could work on?

**Comment by lolmaus** [comment] 2015-01-21 13:16
Quoting #840:

> it would be awesome if we can have something like `ember build debug-build` that reads from a "config" file a list of folders/files (controllers/templates/models etc.) that will be extracted from es6-modules and generate a file that can be copy/pasted into jsbin. 

This does not allow creating new jsbins from Ember CLI addons. To set up a jsbin with an Ember CLI addon, you would have to `ember new`, `ember install:addon`, `ember build debug-build` on your machine, then copy-paste the output to JSBin.

It will be very hard to debug the result, because instead of a concise, self-explanatory Ember-globals app you will have a bloat of precompiled Ember CLI lumber.

I am talking about a solution that would keep the simplicity of JSBin. You should be able to fix up a new online Ember app demo with little effort and without reverting to your machine's command line. This can be achieved by either:

* Encouraging addon developers to refactor their addons to be compilable to both globals and AMD, serving the compiled files from a separate repo, and extracting the Ember CLI addon into a third repo (see Simple Auth example in top post).
* Creating own fiddle service that would allow importing addons from npm. Just imagine, you press "Include addon" and see an interface similar to http://emberaddons.com/ .

**Comment by stefanpenner** [comment] 2015-01-21 13:32
Globals are fundamentally broken, although they might work in some cases they are too low fidelity to actually work for ember cli users.

I agree with the idea of having either jsbin improved or creating a similar service but that embraces ember cli.

My poc is a good starting point for those interested, but what you propose is a large amount of effort. Although it will be valuable it is unlikely to happen soon unless someone is able to invest considerable time and energy. As we are all extremely busy, I have my doubts

Nevertheless I have been keeping the above requirements in my mind as I begin to rethink how our addon system works.

**Comment by lolmaus** [comment] 2015-01-21 13:44
I've thought of one more alternative: cloud coding platforms like https://koding.com/ and https://c9.io/ .

They are able to import a Github Project, run Ember CLI in a virtual machine and even have Ember CLI serve a page to a public URL.

This is the only branch that i'm capable to investigate. I'm too novice to develop an Ember CLI-driven JSBin fork/alternative, but i'll explore and report the capabilities of cloud coding services to replace JSBin.

**Comment by joostdevries** [comment] 2015-01-21 14:06
@lolmaus @stefanpenner We wouldn't need to actually create the complete jsbin but just an API which you can feed a couple of params and returns a compiled file. 

I think the following should actually be reasonably doable:
- Paste your package.json
- Get back a URL to a JS file with your deps (including addons)
- Use Stefs JSBin to provide additional app structure.

**Comment by jakecraige** [comment] 2015-01-21 14:14
@joostdevries Rather than requiring package.json we could just have a local command that takes the compiled assets and uploads them to a hosting service that the jsbin can reference. We would need to merge the addon's "app tree" into the vendor file though since we wouldn't include the compiled app itself. 

A command could look something like:

```sh
ember jsbin:create
```

It would

- compile vendor js and addon's into a file and upload them to a hosting service
- create a jsbin that includes that asset 
- inline the 6to5 scripts of your app from stefan's addon

One of the things I see breaking is any extra app tree build steps. Coffeescript, emberscript, etc.

**Comment by lolmaus** [comment] 2015-01-21 14:27
@jakecraige @joostdevries This approach will not allow creating Ember CLI-driven JSBins from JSBin web interface, i. e. without a command line and a locally installed npm. :(

**Comment by joostdevries** [comment] 2015-01-21 14:29
@lolmaus I understand. I think we need to get a clear list of what are important requirements for a JSBin first. Either way I'm pretty sure that this will have to be done as an Addon or external service.

**Comment by lolmaus** [comment] 2015-01-21 14:34
@joostdevries A JSBin is a fiddle service. It lets you code a demo online and live, then share it with other collaborators who can read and edit the code.

What you and @jakecraige and #840 suggest is not a way of fiddling online, but rather a way to quickly deploy your local Ember CLI project to a free hosting.

**Comment by stefanpenner** [comment] 2015-01-21 15:00
@lolmaus no i think you are incorrect, addon + vendor code just needs to be a big blob, then the app code needs to be in individual modules similar to what i did already. Cleary we also need a mechanism various app transpile steps, but i suspect we can doit.

It is likely worth exploring how far we can push addons so they are "isometric" (i really hate the word)

**Comment by jakecraige** [comment] 2015-01-21 18:45
@lolmaus it seems like other than app transpile steps, the main thing missing would be adding dependencies in the jsbin. Setting up a default one so you don't need to run one locally would be pretty straightforward. You just wouldn't be able to add any addons to it

**Comment by lolmaus** [comment] 2015-01-21 19:11
> You just wouldn't be able to add any addons to it

This ruins the whole concept of a fiddle service.

**Comment by lolmaus** [comment] 2015-01-21 19:23
I've tried [C9.io](https://c9.io) and i have mixed feelings.

Pros:

* It's fully capable of running Ember CLI.
* Full control of the environment. Install Watchman, run `ember serve`, etc.
* Can create workspaces off Github projects.
* Has a free account.

Cons:

* It's way more heavy than JSBin, can hardly be considered a fiddle service. Difficult to use for people not already familiar with it.
* Can not clone workspaces. Starting another fiddle is a burden, you have to do a lot of routine steps.
* You can't run/edit other person's project until the owner gives you write permissions. And you can't fork it.
* Limited to one workspace per account. :( Paid accounts have very few workspaces either.

Overall, it's not a JSBin replacement, though it has limited applications.

* * *

I have a feeling that when Ember migrates to Ember CLI, we will lose the ability to do live Ember fiddles. This is a huge pitfall, don't you think?

**Comment by stravid** [comment] 2015-01-21 23:11
@lolmaus It sure is a pitfall, but even if Ember CLI is a step back in this regard it is at least two steps forward for developing Ember.js applications in general. A tradeoff I will happily make.

I agree that we should look for solutions but not on the expense of Ember CLI.

**Comment by stefanpenner** [comment] 2015-01-22 04:31
not a bug with ember-cli. But something that would be cool to solve. 

please keep the discussion going, but i am closing this as it is not a bug with ember-cli.

**Closed by stefanpenner** 2015-01-22 04:31 UTC

**Comment by joostdevries** [comment] 2015-01-23 07:11
@lolmaus C9 is amazing but not for this usecase, I agree. Losing the ability to play around with addons/apps and quickly demo them is also not an option so there are two basic direction IMO:

- Develop a service which lets you load addons into jsbin (no change in the addon required). Developing a jsbin/jsfiddle alternative for Ember CLI is not really an option I think.
- Create a way to package Addons as single JS file.

I have some time to play around with these ideas this weekend and maybe I can get a POC of one of the two. 
What do you think?

**Comment by lolmaus** [comment] 2015-02-12 06:38
The fact is that when Ember drops globals it will become impossible to use JSBin/JSFiddle to demonstrate examples, problems and solutions.

I consider this to be a HUGE issue and i'm perplexed that no Ember/Ember-CLI maintainers recognize the importance of the issue.

**Comment by joostdevries** [comment] 2015-02-12 07:08
@lolmaus #3228

**Comment by runspired** [comment] 2015-03-04 21:31
This is definitely a big issue, I'm thinking of producing a globals build of my addons to go with the ember-cli builds just so user's can produce bug reports with fiddles.  Something ember-cli could do to make addon fiddling easier is to provide a built in mechanism for producing a globals based version of addon code when needed.  There are addons that want both anyway.

**Comment by lolmaus** [comment] 2015-03-10 12:22
Hey @runspired, can you please share your recipe of building for both globals and ember-cli?

**Comment by joostdevries** [comment] 2015-03-10 12:27
@lolmaus to give you a brief status update: I'm working on ember-gist.joostdvrs.com and @alexspeller is working on alexspeller.com/ember-twiddle. Adding support for addons is on my list but will likely require the option to pre-build addons (so that they can ship with a `dist` directory included)

**Comment by lolmaus** [comment] 2015-03-10 12:42
That's awesome, @joostdevries!

**Comment by runspired** [comment] 2015-03-11 21:04
@lolmaus I'm working on extracting liquid-fire's method into an addon any addon can use to produce a globals build. see: https://github.com/ef4/liquid-fire/tree/master/packaging

Nothing public / published but I might be able to push an unstable master up tonight.

**Comment by knownasilya** [comment] 2015-03-17 17:17
Koding worked best for me. I tried Runnable, and that didn't like `npm install -g`.

**Comment by alexspeller** [comment] 2015-03-17 19:07
I really don't like the idea of hosting the CLI on a server side environement, however it's probably the easiest to implement. Just using docker and setting up a base cli install would work pretty good, but the issue is hosting it and providing that infrastrucuture. I believe it's possible to abstract out the cli parts so that the relevant stuff can run in the browser, but it's certainly a way bigger task.

**Comment by runspired** [comment] 2015-03-18 01:41
I really think being able to produce a globals build is a better approach than hosting cli in order to get jsbin-like functionality.  Not only do globals builds work in any existing service, it ensures that the ecosystem is available to those who might need a few addons and ember for a small app on a page but not a whole workflow.

I started extracting liquid-fire's approach to generating a globals build here https://github.com/runspired/ember-cli-export-addon.  The trouble I'm having with this approach is that anything that's dependent on importing `config/environment` gets in trouble.

**Comment by stefanpenner** [comment] 2015-03-21 15:55
@joostdevries & @alexspeller is there a place/issue/repo we can point people too who are interested in your current adventure?

**Comment by alexspeller** [comment] 2015-03-21 23:01
@stefanpenner http://alexspeller.com/ember-twiddle/ http://github.com/alexspeller/ember-twiddle
