### ISSUE TITLE
Module Unification: Blueprints

### ISSUE THREAD

**Issue by GavinJoyce** [ember-cli/ember-cli#7530] opened 2018-01-02 12:10 UTC
🔼 Part of [[QUEST] Module Unification: Final Cut](https://github.com/emberjs/ember.js/issues/16373)

---

This issue is part of the [Module Unification Quest](https://github.com/emberjs/ember.js/issues/16373) and will serve as a list of remaining tasks to land blueprint support for module unification apps.

## Interested in helping?

Great! Comment on the issue to take on one of these blueprints. They are mostly pretty straightforward, see the [service blueprint](https://github.com/emberjs/ember.js/pull/16397) for example. Anything without a 🔒 is up for grabs.

If you have any questions, you can ask them in the `#st-module-unification` channel on the [Ember community slack](https://emberjs.com/community/) or you can ask me directly `@gavinjoyce`.

## Creating a new module unification app

Install Ember CLI master:

```
npm install -g https://github.com/ember-cli/ember-cli.git
```

Generate a new app with the module unification env variables:

```
MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true ember new my-mu-app
```

Generate a component:

```
EMBER_CLI_MODULE_UNIFICATION=true ember g component x-button
```

Run the app:

```
EMBER_CLI_MODULE_UNIFICATION=true ember serve
```

### `ember-cli/ember-cli` ([blueprints](https://github.com/ember-cli/ember-cli/tree/master/blueprints)):

 * ~~`addon-import`~~ (not applicable)
 * [x] [`MODULE_UNIFICATION=true ember addon my-addon`](https://github.com/ember-cli/ember-cli/pull/7658)
 * [x] [`MODULE_UNIFICATION=true ember new my-app`](https://github.com/ember-cli/ember-cli/pull/7488)
 * ~~`ember generate blueprint`~~ (not applicable)
 * ~~`ember generate http-mock`~~ (not applicable)
 * ~~`ember generate http-proxy`~~ (not applicable)
 * [x] [`ember generate in-repo-addon`](https://github.com/ember-cli/ember-cli/pull/7783)
   * [ ] remove `.jshintrc` and `.eslintrc` (see [discussion](https://github.com/ember-cli/ember-cli/pull/7783#discussion_r188061985))
 *  ~~`ember generate lib`~~
 * ~~`ember generate server`~~ (not applicable)
 * ~~`ember generate vendor-shim`~~ (not applicable)

### `emberjs/ember.js` ([blueprints](https://github.com/emberjs/ember.js/tree/master/blueprints)):

 * [ ] `ember generate acceptance-test`
 * [x] [`ember generate component`](https://github.com/emberjs/ember.js/pull/16043)
 * [x] [`ember generate controller`](https://github.com/emberjs/ember.js/pull/16656)  🍻 @dexturr @kevinansfield
 * [ ] `ember generate helper` 🆓 [this incomplete PR might help](https://github.com/emberjs/ember.js/pull/16492)   
 * [x] [`ember generate initializer`](https://github.com/emberjs/ember.js/pull/16489) 🔒@sduquej
 * [ ] `ember generate instance-initializer` 🆓 [this incomplete PR might help](https://github.com/emberjs/ember.js/pull/16491) 
 * [x] [`ember generate mixin`](https://github.com/emberjs/ember.js/pull/16524) 🍻@jackbeegan
 * [x] [`ember generate route`](https://github.com/emberjs/ember.js/pull/16663) 🍻 @kevinansfield 
 * [x] [`ember generate service`](https://github.com/emberjs/ember.js/pull/16397)
 * [x] [`ember generate template`](https://github.com/emberjs/ember.js/pull/16651) 🍻@Willibaur @pablobm 
 * [x] [`ember generate util`](https://github.com/emberjs/ember.js/pull/16490) 🍻@daibhin 
 
#### running emberjs blueprint tests

`yarn run test:blueprints`

### `emberjs/data` ([blueprints](https://github.com/emberjs/data/tree/master/blueprints)):

 * [x] [`ember generate adapter`](https://github.com/emberjs/data/pull/5476) 🔒 @kevinansfield 
 * [x] [`ember generate model`](https://github.com/emberjs/data/pull/5491) 🔒@dcyriller
 * [x] [`ember generate serializer`](https://github.com/emberjs/data/pull/5494) 🔒@dcyriller
 * [x] [`ember generate transform`](https://github.com/emberjs/data/pull/5495) 🔒@dcyriller

### other items

* [ ] replace {{welcome-page}} addon with component example
 * [x] remove bower and user ember canary in package.json (https://github.com/ember-cli/ember-cli/pull/7533)
 * [ ] support init command (and any other commands which MU affects)
 * [ ] reduce the duplication between classic and MU blueprints @ro0gr (WIP https://github.com/ember-cli/ember-cli/pull/7595) 
 * [x] create a mini module unification blueprint quest issue (once we've migrated a few)
 * [ ] document new blueprint usage
 * [ ] [don't use `ember-resolver/resolvers/fallback` resolver by default](https://github.com/ember-cli/ember-cli/pull/7531)
 * [ ] fix travis-ci build failure on app output (`config/environment.js` : `51:37  error  Empty block statement  no-empty`)
 * [x] [allow MU app/addon to be created using `ember-cli-blueprint-test-helpers` and `emberNew`](https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/153) (we currently just create an empty `src` directory, which means we have to do [things like this](https://github.com/emberjs/ember.js/pull/16663/files#diff-7b356d860fa1783b996c6a9d9ce2faa6R514)) 🔒@dcyriller
 * [ ] ...

**Comment by rwjblue** [comment] 2018-01-02 14:54
I submitted https://github.com/ember-cli/ember-cli/pull/7533 to tackle:

>  remove bower and user ember canary in package.json

**Comment by alexander-alvarez** [comment] 2018-01-04 18:41
Should we have a `ember-new-module-unification-output` repo also?

**Comment by ro0gr** [comment] 2018-01-14 21:36
I've started working on 
> reduce the duplication between classic and MU blueprints

I think the first necessary step is to improve testing of the `new` and `addon` command output https://github.com/ember-cli/ember-cli/pull/7557

**Comment by jackbeegan** [comment] 2018-04-11 17:29
Hey! I'll take the mixin blueprint!

**Comment by kevinansfield** [comment] 2018-05-19 18:26
I'm taking a stab at the routes blueprint :)

**Comment by kevinansfield** [comment] 2018-05-23 08:20
I've made a start on the Ember Data adapter blueprint, I'll try and get that finished off tonight

**Comment by dcyriller** [comment] 2018-06-14 17:37
Hello! I just did the model blueprint https://github.com/emberjs/data/pull/5491 (based on @kevinansfield 's https://github.com/emberjs/data/pull/5476)

**Comment by dcyriller** [comment] 2018-06-16 08:07
@GavinJoyce acceptance blueprint should remain unchanged according to MU RFC or am I wrong?

**Comment by GavinJoyce** [comment] 2018-06-18 13:54
@dcyriller hey, sorry I haven't had time to look into your PR yet. I have little time this week, if no one else has reviewed your PR or answered your question by then I'll get to it early next week when I have more time.

> acceptance blueprint should remain unchanged according to MU RFC or am I wrong?

I don't have the answer of the top of my head, perhaps you could ask in the #st-module-unification slack channel?

**Comment by runspired** [comment] 2018-06-21 05:43
@thoov and I discovered today that there is poor testing interop between old world and new world blueprints due to the inability to configure the state of the `EMBER_CLI_MODULE_UNIFICATION` feature flag for the test. We had to skip the `adapter` tests for MU due to this.  We propose something like the following being possible:

```
emberNew({
   cliOptions: {
     EMBER_CLI_MODULE_UNIFICATION: true
   }
});
```

cc @GavinJoyce @rwjblue

**Comment by dcyriller** [comment] 2018-07-26 14:30
@GavinJoyce may you update the emberjs/data part with a 🔒?

Also some work is in progress on ember-cli test helpers https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/153

**Comment by GavinJoyce** [comment] 2018-07-26 15:53
@dcyriller sure, what needs to be updated? (I've been busy on other projects so haven't been following MU progress)

**Comment by dcyriller** [comment] 2018-07-26 17:34
Thanks :)

A 🔒 should be added on ember-data blueprints. @NullVoxPopuli do you agree we should keep the PRs https://github.com/emberjs/data/pull/5491, https://github.com/emberjs/data/pull/5494, https://github.com/emberjs/data/pull/5542 (as they contain tests)?

The last item `allow MU app/addon to be created using ember-cli-blueprint-test-helpers and emberNew (we currently just create an empty src directory, which means we have to do things like this)` is also in progress (ember-cli/ember-cli-blueprint-test-helpers#153).

**Comment by NullVoxPopuli** [comment] 2018-07-26 18:43
@dcyriller yeah, your code is pretty much the same as mine, but yours has tests.

**Comment by GavinJoyce** [comment] 2018-07-26 19:38
@dcyriller updated, thanks!

**Comment by NullVoxPopuli** [comment] 2018-10-03 09:43
the ember-data blueprints look like they're all implemented. (just confirmed they all work)

**Comment by GavinJoyce** [comment] 2018-10-03 09:47
Nice work @dcyriller! I've updated the todo list

**Comment by dcyriller** [comment] 2018-10-03 11:57
Thank you @GavinJoyce! You can also tick the last item (the blueprint thing) which is merged.  :)

**Comment by GavinJoyce** [comment] 2018-10-06 19:46
@abhilashlr I seem to recall that @locks was proposing that we implement a `welcome-page` component in the blueprint, possibly so that there is an example component in the app. @locks, perhaps you recall and can confirm?

**Comment by gossi** [comment] 2018-10-08 09:11
Can we have two blueprints instead? One for beginners, that has two routes and a component on one of them and one for people that are already familiar with ember, they receive a blank ember setup to get started without remove the "bloat" for beginners? I can put a screenshot from ember-cli-create later that gives makes this one more understandable from a consumers pov.

**Comment by locks** [comment] 2018-10-08 09:31
@gossi `ember new my-project --no-welcome`

**Comment by gossi** [comment] 2018-10-08 12:02
@locks true but I think we can do better by offering two blueprints instead: `ember new my-project -b beginner-app` (with route and component) and `ember new my-project -b regular-app` (blank app) I made passing the blueprint explicit in this scenario. Should be handled by cli instead, like I do in `ember-cli-create`. Can provide a screenshot in the evening.

**Comment by abhilashlr** [comment] 2018-10-17 15:57
@GavinJoyce @Turbo87 Here it is for ember-welcome-page: https://github.com/ember-cli/ember-cli/pull/8139

**Comment by ppcano** [comment] 2018-11-09 23:40
`remove .jshintrc and .eslintrc` ->  #8179 

Next, I will try to complete the `helper` and `instance-initializer` generators.

**Comment by ppcano** [comment] 2018-11-15 05:15
`acceptance-test` -> emberjs/ember.js#17209

**Comment by ppcano** [comment] 2018-11-15 06:58
#8194 stops adding `tests/{unit,integration}` folders on the `ember new` blueprint  (#7488)

**Comment by ppcano** [comment] 2018-11-15 09:53
#8195 adds tests for the `--no-welcome` option of the`new MU app` blueprint.

I think, `replace {{welcome-page}} addon with component example` can be removed from the list. Read the #8139 discussion.

**Comment by ppcano** [comment] 2018-11-27 10:55
@GavinJoyce Please, could you update the task list status.

### ember-cli/ember-cli

- [x] MODULE_UNIFICATION=true ember new my-app
  - [ ] Generate `tests/acceptance` folder  #8194 


- [x] `remove .jshintrc and .eslintrc`

### emberjs


- [x] [ember generate acceptance-test](https://github.com/emberjs/ember.js/pull/17209)
- [ ] `ember generate helper` . (emberjs/ember.js#17211)
- [ ] `ember generate instance-initializer` @ppcano (blocked by emberjs/ember.js#17212)

### other items
- [ ] ~~replace {{welcome-page}} addon with component example~~. It may be removed based on the #8139 discussion.

- [ ] adds tests for the --no-welcome option of the new MU app. #8195 


- [ ] Fix blueprint tests for MU addons when using `ember-cli@3.5`  ember-cli/ember-cli-blueprint-test-helpers#185 @dcyriller

**Comment by Turbo87** [comment] 2019-12-01 17:52
closing due to https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html

**Closed by Turbo87** 2019-12-01 17:52 UTC
Labels: Quest
