### ISSUE TITLE
Deprecation warning for locationType=auto

### ISSUE THREAD

**Issue by denik1981** [ember-cli/ember-cli#9765] opened 2022-01-23 17:58 UTC
**What did happen?**

A fresh installation using `ember-cli` throws a deprecation warning from ember.js for using `locationType="auto"`.
```
DEPRECATION: Router location 'auto' is deprecated. 
Most users will want to set `locationType` to 'history' in config/environment.js for no change in behavior. 
See deprecation docs for details. 
[deprecation id: deprecate-auto-location] 
See https://emberjs.com/deprecations/v4.x#toc_deprecate-auto-location for more details.
```

**What should happen?**

New apps generated with ember-cli should stay in sync with ember.js LTS list of deprecations. 
The deprecation warning came in ember 4.x.
    
**Steps to reproduce the issue**

- `ember new my-new-ember-app`
-  `cd my-new-ember-app`
- `ember serve`
- Navigate to [http://localshost:4200](http://localshost:4200)
- Check the console in your browser devtools.

**References:**
[ember-v4-deprecate-auto-location](https://emberjs.com/deprecations/v4.x#toc_deprecate-auto-location)

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 4.1.0
node: 16.13.2
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: linux x64
8.1.2
1.22.17
```

**Comment by denik1981** [comment] 2022-01-23 18:17
I have submitted PR #9766 to address this issue

**Comment by bertdeblock** [comment] 2022-01-23 18:33
It seems you've created the same issue twice. Also, I think this should already be addressed by https://github.com/ember-cli/ember-cli/pull/9739.

**Comment by denik1981** [comment] 2022-01-23 18:44
GH sent me to an error page the first time I submitted the issue so I created it again. 
I didn't though it was created. I will close it.

> Also, I think this should already be addressed by #9739.
Seems so. It was looking for this in the pool of issues (not in the PRs).
Double-check for #9739 because I'm not seeing in there the code needed to adapt CI tests.

**Comment by denik1981** [comment] 2022-01-23 18:56
From I found in the merged code, this twot test utilities are still referencing `locationType:auto` in the release branch.

https://github.com/ember-cli/ember-cli/blob/release/tests/unit/utilities/ember-app-utils-test.js
https://github.com/ember-cli/ember-cli/blob/release/tests/unit/tasks/server/middleware/history-support-test.js

It might be good to adapt for `locationType:history` in these test utilities as well. What do you think?

**Comment by bertdeblock** [comment] 2022-01-23 19:02
I could be wrong (someone from the core team should verify), but I don't think those test changes are needed in https://github.com/ember-cli/ember-cli/pull/9766? We still wan't to verify that locationType `auto` works as intended as long as it's not fully removed, so it seems those tests should remain the same?

**Comment by denik1981** [comment] 2022-01-23 19:54
@bertdeblock That's a good answer. It's always a gray area if deprecated code should fail in tests while still delivered. 
In any case, if the team behind **ember-cli** needs me to update the code related to the test utilities include in my PR, just ask me to modify it and I will commit those 2 files only.

**Comment by kategengler** [comment] 2022-01-24 20:54
We should keep the tests for locationType: `auto` until the deprecation is removed.

**Comment by locks** [comment] 2022-01-27 01:33
Seems like the issue originally reported has been addressed. Thanks everyone for the discussion!

**Closed by locks** 2022-01-27 01:33 UTC
