### ISSUE TITLE
The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with

### ISSUE THREAD

**Issue by BenjaminHorn** [ember-cli/ember-cli#5636] opened 2016-03-18 10:51 UTC
I try to update Ember CLI from 2.4.0 to 2.4.2
After clearing the folders
`rm -rf node_modules bower_components dist tmp`

I updated my package.json 

```
    -"ember-cli": "2.4.0",
    +"ember-cli": "^2.4.0",
```
then
` npm install && bower install`

I went trough file by file  the 

> [?] Overwrite

 questions after `ember init`.
Now I am getting:

> The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
> Error: Merge error: file my-project-name/templates/components/bs-form.hbs exists in /home/me/projects/my-project-name/tmp/broccoli_merge_trees-input_base_path-wRxD0KUG.tmp/0 and /home/me/projects/my-project-name/tmp/broccoli_merge_trees-input_base_path-wRxD0KUG.tmp/1
> Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
>     at BroccoliMergeTrees._mergeRelativePath (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:212:17)
>     at BroccoliMergeTrees._mergeRelativePath (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:238:31)
>     at BroccoliMergeTrees._mergeRelativePath (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:238:31)
>     at BroccoliMergeTrees._mergeRelativePath (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:238:31)
>     at BroccoliMergeTrees.build (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:50:24)
>     at /home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-plugin/read_compat.js:61:34
>     at lib$rsvp$$internal$$tryCatch (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
>     at lib$rsvp$$internal$$invokeCallback (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
>     at lib$rsvp$$internal$$publish (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
>     at lib$rsvp$asap$$flush (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
> 
> The broccoli plugin was instantiated at: 
>     at BroccoliMergeTrees.Plugin (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-plugin/index.js:7:31)
>     at new BroccoliMergeTrees (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:29:10)
>     at BroccoliMergeTrees (/home/me/projects/my-project-name/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:53)
>     at module.exports (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
>     at EmberApp._processedTemplatesTree (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/ember-app.js:775:56)
>     at EmberApp.appAndDependencies (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/ember-app.js:1011:24)
>     at EmberApp.javascript (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/ember-app.js:1137:34)
>     at EmberApp.toArray (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/ember-app.js:1542:10)
>     at EmberApp.toTree (/home/me/projects/my-project-name/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
>     at module.exports (/home/me/projects/my-project-name/ember-cli-build.js:23:14)

**Comment by rwjblue** [comment] 2016-03-18 13:46
I made a mistake in a refactor that landed in 2.4.2. The issue is that an apps templates will not override an addons templates.

There is an open pull request fixing, but I need to add some tests to ensure no regressions happen in the future.

**Comment by marcemira** [comment] 2016-03-18 20:19
@rwjblue sorry for the ping >_< . I got stuck on a deploy with this same issue. Is there any update? can you refer me to that pull request? Thanks :+1:

**Comment by stefanpenner** [comment] 2016-03-19 20:41
https://github.com/ember-cli/ember-cli/pull/5591

**Closed** 2016-04-13 15:35 UTC
Labels: Bug
