### ISSUE TITLE
Error: Addon templates were detected, but there are no template compilers registered

### ISSUE THREAD

**Issue by tsteuwer** [ember-cli/ember-cli#5306] opened 2016-01-05 15:20 UTC
After trying to create an addon using ``ember addon my-addon``, I started working on creating some components, controllers, and routes that I could share in a couple of projects. However, after generating the components and updating them, I tried to use ``ember test`` and it results in the following:

```
troy:/$ ember test
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingAddon templates were detected, but there are no template compilers registered for `my-addon`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `my-addon`'s `package.json`.

troy:/$ ember -v
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.13.0-pre
npm: 2.14.10
os: linux x64
```

**Comment by tsteuwer** [comment] 2016-01-05 15:22
Additional information:

``package.json``

```
{
  "name": "my-addon",
  "version": "0.0.0",
  "description": "The default blueprint for ember-cli addons.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember try:testall"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.13",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.15",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-disable-prototype-extensions": "^1.0.0",
    "ember-try": "~0.0.8"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^5.1.5"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by gmurphey** [comment] 2016-01-05 15:23
This is expected. You can move `ember-cli-htmlbars` from `devDependencies` to `dependencies` in your addon's `package.json` and everything should work.

**Comment by tsteuwer** [comment] 2016-01-05 15:24
Why would this be expected and why would we want this to happen? I feel like this would be a hinderance to new users (esp those who've never done command-line).

**Comment by gmurphey** [comment] 2016-01-05 15:37
I agree that it might be made a little friendlier. I suppose we could move the dependency in the `afterInstall` hook in the `component` blueprint?

**Comment by stefanpenner** [comment] 2016-01-05 17:05
> I suppose we could move the dependency in the afterInstall hook in the component blueprint?

sorta, we would want the component generation operation to ensure (based on where the component is being generated, e.g. dummy app doesn't care, app or addon does) the compiler is correct.

**Comment by gmurphey** [comment] 2016-01-05 17:09
I have a WIP branch with some of this fleshed out. I'll try to put together a PR tonight.

**Comment by stefanpenner** [comment] 2016-01-05 17:27
> I have a WIP branch with some of this fleshed out. I'll try to put together a PR tonight.

:+1:

**Comment by stefanpenner** [comment] 2016-01-09 19:38
> I have a WIP branch with some of this fleshed out. I'll try to put together a PR tonight.

can you share your WIP?

**Comment by misteroh** [comment] 2016-04-12 16:00
sorry, i realize that this is a little old but can you elaborate on why creating the add-on puts ember-cli-htmlbars inside devDependencies by default? I have to manually move it from devDependencies to dependencies every time I create an add-on?

**Comment by Turbo87** [comment] 2016-04-13 15:03
@misteroh it does that because not every addon has templates and so not every addon needs that dependency

**Comment by Turbo87** [comment] 2016-04-13 15:03
closing because this seems to be a duplicate of https://github.com/ember-cli/ember-cli/issues/4436

**Closed by Turbo87** 2016-04-13 15:03 UTC
Labels: Enhancement
