### ISSUE TITLE
Ember init while upgrading to v3.0.0 fails with `Cannot find module 'mout/lang'`

### ISSUE THREAD

**Issue by Alonski** [ember-cli/ember-cli#7638] opened 2018-02-21 16:00 UTC
Output from `ember version --verbose && npm --version && yarn --version`:
```
$ ember version --verbose
ember-cli: 3.0.0
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: win32 x64
$ npm -v
3.10.10
$ yarn -v
1.3.2
```

I am currently upgrading my v2.12.2 Ember app to v3.0.0
While upgrading after following the instructions in the [releases page](https://github.com/ember-cli/ember-cli/releases/tag/v3.0.0) I got a weird error.
I did Ember Init.
Chose which files I wanted to override and which I didn't.
```
ember init
installing app
? Overwrite .ember-cli? No, skip
? Overwrite README.md? No, skip
? Overwrite app\templates\application.hbs? No, skip
  identical .editorconfig
  skip .ember-cli
  identical .eslintrc.js
  identical .travis.yml
  identical .watchmanconfig
  skip README.md
  identical app\app.js
  identical app\index.html
  identical app\resolver.js
  identical app\router.js
  skip app\templates\application.hbs
  identical config\environment.js
  identical config\targets.js
  identical ember-cli-build.js
  identical .gitignore
  identical package.json
  identical public\robots.txt
  identical testem.js
  identical tests\index.html
  identical tests\test-helper.js
Yarn: Installed dependencies
Cannot find module 'mout/lang'


Stack Trace and Error Report: C:\Users\Alon\AppData\Local\Temp/error.dump.524d89d3eb185c31511a1288dc133e89.log
```

I ended up `fixing` this by doing a `yarn add mout` and then running Ember Init again.

This somehow fixed the error but I don't understand why it happened in the first place.

Keep up the good work guys!

Here is the error dump from npm:
```
=================================================================================

ENV Summary:

  TIME: Wed Feb 21 2018 17:48:07 GMT+0200 (Jerusalem Standard Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Program Files\nodejs\node_modules\ember-cli\bin\ember
  - init
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\Alon\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \ProgramData\Oracle\Java\javapath;C
  - \Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C
  - \Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Program Files\SlikSvn\bin;C
  - \Program Files\Microsoft SQL Server\110\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files\Microsoft\Web Platform Installer\;C
  - \Program Files\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files\dotnet\;C
  - \Program Files\SourceGear\Common\DiffMerge\;C
  - \Program Files (x86)\Android\android-sdk\platform-tools;C
  - \Program Files\PuTTY\;C
  - \Program Files\Geth;C
  - \Users\Alon\AppData\Roaming\nvm;C
  - \Program Files\nodejs;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
  - \Program Files\TortoiseSVN\bin;C
  - \Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C
  - \Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE;C
  - \Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C
  - \Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files (x86)\Yarn\bin;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\Git\cmd;C
  - \Users\Alon\AppData\Local\Microsoft\WindowsApps;C
  - \Users\Alon\AppData\Roaming\npm;C
  - \Users\Alon\.lein\bin;D
  - \IPFS\go-ipfs;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Program Files\MySQL\MySQL Server 5.7\bin;D
  - \Music\DL;C
  - \Program Files (x86)\Android\android-sdk;C
  - \Program Files (x86)\Android\android-sdk\tools;D
  - \Projects\webplatform\landing_pages_head\CamilyoConsole\bin\Debug;D
  - \mobart\deploy;C
  - \Program Files (x86)\Rico Suter\NSwagStudio\full;C
  - \Users\Alon\AppData\Local\Yarn\bin
  PLATFORM: win32 x64
  FREEMEM: 7292063744
  TOTALMEM: 17079775232
  UPTIME: 502438.827463
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz - 2394
  - Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz - 2394
  - Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz - 2394
  - Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz - 2394
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.7.0
  - icu: 58.2
  - modules: 48
  - node: 6.11.0
  - openssl: 1.0.2k
  - uv: 1.11.0
  - v8: 5.1.281.102
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'mout/lang'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'mout/lang'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'mout/lang'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Projects\webplatform\landing_pages_head_14.7\cache\camilyo\node_modules\bower-config\lib\Config.js:1:74)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

=================================================================================
```

**Comment by Turbo87** [comment] 2018-02-23 22:51
can you reproduce this in a fresh `ember new` app? I'm afraid without reproduction instructions this will be quite hard to fix.

**Comment by Nippius** [comment] 2018-05-01 21:48
@Alonski  @Turbo87 

Alright I managed to find a way to fix it but I have no idea what the problem is!
I can't reproduce this using `ember new` but if you grab my repo ([commit](https://github.com/Nippius/digitalillusion-frontend/commit/672e72e7d42641467c473f5c337c1b9720617efa))
you can reproduce it.

So here it goes. The trick is to install the global ember-cli, call npm install and then update package.json

Here are my actual commands:

1. `npm uninstall -g ember-cli` // Make sure we start from zero
 
2. `npm install -g ember-cli@3.1.3` // Install global cli
 
3. `rm -rf node_modules dist tmp`

4. `npm install` // Here is the "trick". Call this first
 
5. `npm install --save-dev ember-cli@3.1.3`
 
6. `ember init -no-welcome`

And thats it.

Lastly, you only need to do this once. Although I used version 3.1.3 in the commands above, what I actualy did was execute them for version 3.1.0 and then followed the standard instructions for upgrading to version 3.1.3 (as defined in the releases [page](https://github.com/ember-cli/ember-cli/releases) )

**Comment by rwjblue** [comment] 2018-05-01 23:30
This seems likely to be an npm bug. I suspect that running `npm install —save-dev ember-cli@3.1.3` ends up pruning and deleting the rest of the `node_modules/` contents. 

:(

**Comment by Turbo87** [comment] 2018-06-19 17:54
I'll go ahead and close this issue as we've traced this down to an issue with `npm`

**Closed by Turbo87** 2018-06-19 17:54 UTC
Labels: Needs Reproduction
