### ISSUE TITLE
Use rootURL instead of baseURL

### ISSUE THREAD

**Issue by michaelrkn** [ember-cli/ember-cli#4905] opened 2015-09-29 02:08 UTC
Long story short: they should have the same values so they shouldn't be set in different places, and the `<base>` tag causes problems, so let's get rid of baseURL.

Long story medium: @HeroicEric did a nice little writeup about how confusing the current situation is in an [issue on the Guides](https://github.com/emberjs/guides/issues/612#issue-101730315). @SaladFork had a conversation with @rwjblue about the current state of things and how to un-confuse the situation. He's going to clean up his notes and add them here shortly.

In the meantime, I'm closing out the issue on the Guides, since we don't want to encourage people to use a soon-to-be-deprecated feature of Ember CLI.

**Comment by SaladFork** [comment] 2015-10-07 18:11
The below is based on a conversation with @rwjblue, who will hopefully offer a correction if I misquote or otherwise misstate something below.

#### Background Information

Originally, before Ember CLI and when ember-app-kit was first seeing use, there was a requirement of having to support an Ember app running on a different domain or in a subdirectory of a domain. This would work as-is, but the Ember router uses the browser history API through `pushState` and `popState`, and thus needs to know what it's "root directory" is. To address this, a `rootURL` option was added to the router.

Later on, Ember CLI gained popularity and yet had its own requirements for how it serves (through `ember server`) an Ember application. It needs to take into account not just where the app and its assets will end up being deployed, but also how it runs in development and testing. The latter is particularly important, as testem (when run as a server) runs independent of Ember CLI. Since `rootURL` didn't fulfill all the needs, a new `baseURL` as introduced, despite some initial concerns.

This option serves as a way to tell Ember CLI where it will eventually be deployed so that it can properly point to application assets. It results in the addition of a `<base>` tag to `index.html` which affects all relative URLs on the page.  This way, the same app will work both in development and production, but also in testing both when accessed via `/tests` on an ember server and via a testem server (which serves the test index as root).

However, `baseURL` causes much confusion, as is highlighted by the [linked Guides issue](https://github.com/emberjs/guides/issues/612#issue-101730315). Furthermore, using a `<base>` tag can cause issues with SVGs and some CSS.

Today, `rootURL` is only used in Ember ([when location type is not `'hash'`](https://github.com/ember-cli/ember-cli/blob/25642e20b97638052694f0fb6acb539f0fa2f451/lib/broccoli/ember-app.js#L1510-L1523)), and `baseURL` is only used in Ember CLI.

---

#### The Way Forward

Ultimately, we just want to have `rootURL` as it doesn't make sense to have two mechanisms for the same end-goal that interoperate in weird ways. However, we still need to support all the use-cases that `baseURL` supported, specifically the two test environments (`/tests` and testem server). We would like to do this while completely eliminating `baseURL` and the `<base>` tag.

One suggested approach for doing this is to reuse `ember-asset-rewrite` (which is used today by `broccoli-asset-rev` to fingerprint assets) to rewrite the URLs to assets in our app to what is configured by `rootURL` and makes sense for the current environment. Compared to `<base>`, this would eliminate browser quirks, be static after being built, and be much more testable.

We may need to make changes to the Ember CLI blueprints to automatically pass `rootURL` forward as needed, and deprecate the approach of using `<base>`. As an intermediate step we can have the blueprint for `router.js` import the environment and set `rootURL` to the `baseURL` option. We may also need a way to opt out of creating the `<base>` tag entirely (the current approach of setting it to an empty string is not intuitive).

To get testem server to work, we might be able to take advantage of a relatively new (compared to when `baseURL` was implemented) testem feature of [custom routes](https://github.com/airportyh/testem#custom-routes) for rerouting asset requests. We might have to introduce some middleware.

The guides should only discuss `rootURL`. It's supported by Ember, is thought through, and is not going away as we always need a way to tell the history API what the root URL is.

As a checklist, all of the following scenarios should work with `rootURL`:
 * Serving an Ember application with `ember s`
 * Deploying an Ember application after building it with `ember b`
 * Testing by visiting `/tests` after running `ember s`
 * Testing by visiting `/tests` after running deploying an Ember application built with `ember b`
 * Testing by running `ember test`
 * Testing by running `ember test --server`

---

#### An Additional Idea

One idea that @rwjblue mentioned that we might want to do as part of this is to have the `dist/` output folder reflect the folder structure of the deploy target. That is, if the app is being served from `/my-app`, you would find the output in `dist/my-app/`. This is a breaking change, but might make the express server easier, and allows flexibility for putting things in the domain root (such as `.htaccess` or other root files).

**Comment by locks** [comment] 2015-11-11 09:22
Any progress?

**Comment by constantm** [comment] 2015-11-11 09:25
Just ran into this issue as well with hosting a built Ember app in a subfolder. Would love some clarification.

**Comment by rwjblue** [comment] 2015-11-11 14:23
The write up by @SaladFork in https://github.com/ember-cli/ember-cli/issues/4905#issuecomment-146281529 summarizes the real issues here, and mostly lays out the path forward.

Someone just needs to execute the plan...

**Comment by kongeor** [comment] 2016-04-14 10:36
Is the issue @constantm [mentions](https://github.com/ember-cli/ember-cli/issues/4905#issuecomment-155713312) above going to be fixed with this?

**Comment by rwjblue** [comment] 2016-04-14 11:32
There isn't enough info in @constantm's comment to be able to answer. The WIP PR above does remove the need for <base> in general. We will need to ensure the checklist of scenarios that @SaladFork laid out above is confirmed to be working with the new setup. 

//cc @Turbo87

**Comment by kongeor** [comment] 2016-04-14 13:25
It turns out that our `router.js` was misconfigured:

```
const Router = Ember.Router.extend({
  rootURL: config.baseURL
  ...
```

removing this line resolves our issue. Maybe @constantm had something similar.

**Comment by rwjblue** [comment] 2016-04-14 13:29
Confirm, using baseURL + rootURL is going to do what was reported.

**Closed** 2016-04-27 13:03 UTC
Labels: Bug, Ready for PR
