### ISSUE TITLE
CITGM failures

### ISSUE THREAD

**Issue by TheAlphaNerd** [ember-cli/ember-cli#6454] opened 2016-11-22 23:54 UTC
Hey All.

Started getting failures on citgm. This is for all versions of Node for ember-cli 2.9.1

We submitted a PR to skip `ember-cli` for now, please feel free to let us know when things are working again 

https://github.com/nodejs/citgm/pull/233

```
error:   failure             | The canary is dead:
error:   failing module(s)   |
error:   module name:        | ember-cli
error:   version:            | 2.9.1
error:   error:              | The canary is dead:
error:   error:              | undefined
error:                       | > ember-cli@2.9.1 test /private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq40000gn/T/fdecf523-58fa-4aa2-895f-5831fe621b1d/ember-cli
error:                       | > node tests/runner
error:                       |
error:                       | info: Scanning for yuidoc.json file.
error:                       | info: Loading package.json data from: /private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq40000gn/T/fdecf523-58fa-4aa2-895f-5831fe621b1d/ember-cli/package.json
error:                       | info: Loading yuidoc.json data from: /private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq40000gn/T/fdecf523-58fa-4aa2-895f-5831fe621b1d/ember-cli/docs/yuidoc.json
error:                       |
error:                       | warn: Skipping node_modules directory while scanning for yuidoc.json
error:                       | { Error: Cannot find module 'ember-cli-internal-test-helpers/lib/helpers/conf'
error:                       | at Function.Module._resolveFilename (module.js:469:15)
error:                       | at Function.Module._load (module.js:417:25)
error:                       | at Module.require (module.js:497:17)
error:                       | at require (internal/module.js:20:19)
error:                       | at Object.<anonymous> (/private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq40000gn/T/fdecf523-58fa-4aa2-895f-5831fe621b1d/ember-cli/tests/acceptance/addon-dummy-generate-test.js:4:28)
error:                       | at Module._compile (module.js:570:32)
error:                       | at Object.Module._extensions..js (module.js:579:10)
error:                       | at Module.load (module.js:487:32)
error:                       | at tryModuleLoad (module.js:446:12)
error:                       | at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
error:                       | Error: Cannot find module 'ember-cli-internal-test-helpers/lib/helpers/conf'
error:                       | at Function.Module._resolveFilename (module.js:469:15)
error:                       | at Function.Module._load (module.js:417:25)
error:                       | at Module.require (module.js:497:17)
error:                       | at require (internal/module.js:20:19)
error:                       | at Object.<anonymous> (/private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq40000gn/T/fdecf523-58fa-4aa2-895f-5831fe621b1d/ember-cli/tests/acceptance/addon-dummy-generate-test.js:4:28)
error:                       | at Module._compile (module.js:570:32)
error:                       | at Object.Module._extensions..js (module.js:579:10)
error:                       | at Module.load (module.js:487:32)
error:                       | at tryModuleLoad (module.js:446:12)
error:                       | at Function.Module._load (module.js:438:3)
error:                       | npm ERR! Test failed.  See above for more details.
error:   done                | The smoke test has failed.
```

**Comment by TheAlphaNerd** [comment] 2016-11-22 23:57
It is also worth mentioning that the following test on master is failing on v4, v6, and v7

```
  1) models/builder.js ._enableFSMonitorIfVizEnabled if VIZ is enabled, monitor:

      AssertionError: expected 'idle' to deeply equal 'active'
      + expected - actual

      -idle
      +active
```

**Comment by stefanpenner** [comment] 2016-11-23 00:17
> It is also worth mentioning that the following test on master is failing on v4, v6, and v7

I think i broke that today, although CI thought it was green..

**Comment by stefanpenner** [comment] 2016-11-23 00:18
@TheAlphaNerd this is awesome, we will see whatsup and sort it out!

**Comment by TheAlphaNerd** [comment] 2016-11-23 00:23
@stefanpenner the system is working :smile: 

Let me know if there is anything we can do to help.

**Comment by nathanhammond** [comment] 2016-11-23 02:57
I closed the original reported issue with a flurry of reverts and releases upstream. I can't reproduce https://github.com/ember-cli/ember-cli/issues/6454#issuecomment-262401891 as it is passing on our CI runs: https://travis-ci.org/ember-cli/ember-cli/builds/178169251

If that is actually an issue it exists in CITGM. Closing the loop on this end.

I'M SUPER GRATEFUL FOR THIS @TheAlphaNerd!

**Closed by nathanhammond** 2016-11-23 02:57 UTC
Labels: Bug
