### ISSUE TITLE
[PROPOSAL] Alternate default pod structure

### ISSUE THREAD

**Issue by nathanpalmer** [ember-cli/ember-cli#3234] opened 2015-02-09 15:30 UTC
We love the pod structure (and have followed variations of this previously in other languages/frameworks) and are really looking forward to the completion of #2646. During our recent conversion to use ember-cli though I've noticed that the folder conventions for pods were different than how we've used them. I thought I would take a moment to describe what we consider a pod and how it's used so we can start a discussion here. 

Related: #2653 (_which blueprints are best suited to the pod structure?_)

Ember.js has a very powerful router that maps wonderfully to urls. This leads to great discoverability by allowing us to look at the route/resource in the url and find the corresponding code by those conventions. _This is what pods are to us_. They are the navigable resources within our application. For our team it makes it super simple to reason about where to look for things.

```
pods/user/login/template.hbs             
pods/user/login/controller.js
pods/user/login/route.js

pods/dashboard/template.hbs
pods/dashboard/route.js
```

That means: [Routes](http://emberjs.com/guides/routing/), [Controllers](http://emberjs.com/guides/controllers/), [Views](http://emberjs.com/guides/views/) and Templates are all part of our route. Potentially for the same reason that @knownasilya mentioned in #3012. Everything else we've left in a non-pod format. Their existence inside the pods directory in our minds crosses concerns and starts to make it harder to clearly see what is happening within the application. For example the root of the treeview could look like this. Only 2 of these coorespond with a route and a url. The others are things that could be used within any part of our application. Similar to a mixin or a helper (by where in the app they are used, not by how.)

```
pods/user/* (resource/route)
pods/project/
pods/projects/* (resource/route)
pods/cookie/
pods/array/
```

Which expands into this

```
pods/user/model.js

pods/user/login/template.hbs             
pods/user/login/controller.js
pods/user/login/route.js

pods/project/model.js
pods/project/serializer.js
pods/project/adapter.js

pods/projects/template.hbs
pods/projects/controller.js
pods/projects/route.js

pods/cookie/store.js

pods/array/transform.js
```

We have several things going on here. We're dealing with models, adapters, serializers, session storage and transformations. Things like _pods/array_ and _pods/cookie_ are global, outside the route, concerns and, in our mind, belong outside the route folder. I like the idea of keeping model/serializer/adapter together but they also fall into a category of "global" beyond the route concern so we keep them out.

This is the structure that has been ideal for us. I'd like to hear from others if they agree or disagree. I'd propose that we update the generators to follow this and introduce some official documentation for the folder structure itself.

## Pod structure proposal
Route specific pod structure.

```
# Global application usage
adapters/
authenticators/
components/
helpers/
initializers/
mixins/
models/
serializers/
stores/
transforms/
utils/

# Route specific code
pods/
pods/project/template.hbs
pods/project/controller.js
pods/project/route.js
```

**Comment by lolmaus** [comment] 2015-02-09 16:02
I see your pain, but with this proposal we end up in most of the stuff not podified.

We can't keep a component's logic, template and style ([soon](https://github.com/ember-cli/ember-cli/issues/2561)) in one place.

We can't keep an entity's model, adapter and serializer in one place.

If you want your proposal implemented, you should come up with a suggestion how to combine current pods structure with your route-based structure.

Also... I'm still an Ember newbie, but don't components technically not belong to routes? You [can request](http://emberjs.com/guides/controllers/dependencies-between-controllers/) controller `foo` from controller `bar`, and how would Ember know under which route to look for `bar`? What will happen when you have identically named controllers under different routes?

**Comment by knownasilya** [comment] 2015-02-09 16:15
@lolmaus Some of your concerns will soon go away, as Ember 2.0 removes controllers and replaces them with components.

**Comment by samselikoff** [comment] 2015-02-09 16:36
One trick will be sane namespacing/lookup of components. My apps are mostly components now, I have very little route-controller/route-view/route-template code now. So the pods that are only associated with the routes are actually a pretty small part for me. 

One thing I want is to be able to separate components that I'm using to build specific parts of the UI (e.g. `QuestionList`) from library components (e.g. `CollapsiblePanel`).

**Comment by lolmaus** [comment] 2015-02-09 16:43
> @knownasilya:
> @lolmaus Some of your concerns will soon go away, as Ember 2.0 removes controllers and replaces them with components.

So does the need in the proposed feature... unless, as @samselikoff suggests, namespacing is not limited to pre-CLI route stuff.

**Comment by nathanpalmer** [comment] 2015-02-09 16:48
> @lolmaus We can't keep a component's logic, template and style (soon) in one place.

I should mention that we use the pod format in components. They just don't live under pods/

```
components/file-upload/component.js
components/file-upload/template.hbs
components/file-upload/style.scss
```

I wouldn't mind using the same idea for models either. This puts all these related concepts together and follows the same "easy to find" methodology.

```
models/project/model.js
models/project/adapter.js
models/project/serializer.js
```

> @lolmaus don't components technically not belong to routes

Components are global. I wouldn't mind route scoped components and in that scenario they could exist under a specific pods/*/components directory.

**Comment by nathanpalmer** [comment] 2015-02-09 16:50
> @samselikoff One thing I want is to be able to separate components that I'm using to build specific parts of the UI

We would love this too. I see it as a different feature of _scoped components_ and as mentioned above would exist under a specific pods directory. We see the same thing and generally prefix the component if it's scoped versus a global library.

**Comment by lolmaus** [comment] 2015-02-09 16:55
The questions are how Ember (and the user) should understand which entity belongs to which route/scope/namespace and how to handle name collisions (e. g. what does `bar` resolve to if you have `foo/bar` and `baz/bar`).

**Comment by samselikoff** [comment] 2015-02-09 16:56
It'd be sweet if we could import components and assign them local names, the same way we do with modules...

**Comment by samselikoff** [comment] 2015-02-09 16:56
@nathanpalmer that `component/style.scss`, how are you getting that into your build? this is something I've wanted for a while but haven't had time to work on

**Comment by nathanpalmer** [comment] 2015-02-09 18:19
@lolmaus I'm not sure I understand your question. Nothing changes in terms of model or component resolution.

@samselikoff Right now we're just importing it directly in styles/app.scss until we get the time to look into glob support. We import 1 level deep. So app.scss will import a style.scss for each component.

```sass
// Components
@import "../../components/question-product-configuration/style";
@import "../../components/question-variant/style";
```

**Comment by samselikoff** [comment] 2015-02-09 18:26
@nathanpalmer gotcha. I really want to make an addon that automatically imports any style.scss file found in a component's folder.

**Comment by trabus** [comment] 2015-02-09 18:30
@nathanpalmer I'd love your input on [this rfc](https://github.com/ember-cli/rfcs/pull/5). Structures were something I came up with as a way to make the project structure more flexible (and pluggable) when you are generating or destroying blueprints. While we don't necessarily want to encourage a wild west of project structures, I do recognize that different teams have different needs for their code organization. 

The one problem is that we don't want to break the "convention over configuration" principle, and by allowing custom structures, it kind of does. The only reason I think that it's actually okay at this point in time is that ember-cli is new and as teams find pain points, we should be able to adapt and adjust to reduce them. I do think that there isn't just one way to use ember, and with that in mind I think we could develop multiple conventions regarding file organization that fit those use cases.

**Comment by trabus** [comment] 2015-02-09 18:35
The other thing is that with modules, we have so much more flexibility than globals, and it's important to recognize that not everyone thinks the same when reasoning about a project. I think allowing some level of flexibility and customization within some defined conventions could fill a need we're seeing in the community.

**Comment by nathanpalmer** [comment] 2015-02-09 20:11
@trabus My goal here was to start a discussion about the default folder structure because I would like to keep that "convention over configuration" that we've come to enjoy with Ember. My hope was, since I didn't previously see the structure noted, that we could define and refine it here and then hopefully all be on the same page. I'll checkout [the rfc](https://github.com/ember-cli/rfcs/pull/5).

**Comment by EndangeredMassa** [comment] 2015-02-09 21:29
The primary reason I want to use pods is so that I can group code of any type by entity, such as a `user`, `post`, `comment`, whatever. Splitting the structure so that you have `components/<component-pods>`, `pods/<route-pods>`, `models/<model-pods` doesn't do that for me. They are still necessarily grouped by type of file, not by entity.

**Comment by aaronbhansen** [comment] 2015-02-09 21:37
@EndangeredMassa it seems to me that ember has two separation groups. Things that are global and things that are route based. You have to have some top global items and the remaining should be route based. Personally I think a pod structure like this would work best
```
# Global application usage
components/  # Global
helpers/
initializers/
mixins/
models/ 
  /model_name/model.js
  /model_name/adapter.js
  /model_name/serializer.js
stores/
transforms/
utils/

# Route specific code
pods/
pods/project/template.hbs
pods/project/controller.js
pods/project/route.js
# While components are currently scoped globally, 
# I find I often have resource or route based components that aren't shared anywhere else
pods/project/components/project-row/template.hbs
pods/project/components/project-row/component.js
```

**Comment by nathanpalmer** [comment] 2015-02-09 21:50
@EndangeredMassa We aren't grouping by file-type but rather by feature. There are a few things that are used globally and so they stay global such as components and models. I would like to see route specific components underneath the specific route as well as I mentioned earlier and just recently mentioned by @aaronbhansen.

Models are a little trickier. Since it's possible that you define and use your user model within the pods/user/ folder I also use that user model in many other places outside of that route. We run into that often. We started out keeping them in the pod folder but very quickly refactored it back out because it led to a lot of extra files and folders that weren't directly related to our feature.

**Comment by samselikoff** [comment] 2015-02-09 22:51
I think saying everything either belongs within a specific route or a global dir is painting too broadly. I've worked on apps that have tons on a single route, by design.

In these cases, I would have liked to split up the route into many features, features that have nothing to do with the URL. Some features had related components, others had one-offs. Ideally my dir structure would have looked like

```
--creator
    |
    |-- modules
    |      |
    |      |-- lib
    |      |    |
    |      |    |--exclude-module
    |      |          |
    |      |          |-- component.js
    |      |          |-- template.js
    |      |
    |      -- questions-module
    |      |     |
    |      |     |-- component.js
    |      |     |-- template.js
    |      |     |
    |      |     |-- question-list
    |      |            |
    |      |            |-- component.js
    |      |            |-- template.js
    |      |
    |      |-- discussions-module
    |            |
    |            |-- component.js
    |            |-- template.js
    |            |
    |            |-- discussion-list
    |                   |
    |                   |-- component.js
    |                   |-- template.js
    |
    |-- settings
           |
           -- component.js
           -- template.hbs
```

and of course styles and tests at every level. The `lib` dir gives me a place to put components that are shared across all modules. But I can also namespace components at any arbitrary dir level, if that's where they belong.

Abstraction levels of an app's various pieces change during development as design changes. Ember CLI's dir structure should acknowledge this, and be flexible enough to let developers structure their apps as best they see fit according to the domain of their application.

**Comment by aaronbhansen** [comment] 2015-02-09 23:59
@samselikoff, I feel that when you are trying to create a convention that the majority of ember users will use, you need to keep it board and relatively simple. Your same example could be put in the proposed pod system and is much easier to understand.
```
components/exclude-module/component.js
components/exclude-module/template.hbs
pods/creator/route.js
pods/creator/template.hbs
pods/creator/components/questions-module/component.js
pods/creator/components/questions-module/template.hbs
pods/creator/components/question-list/component.js
pods/creator/components/question-list/template.js
etc
```

You can still test each of the components individually, and they are separated under a single route. 

If in your example above, if creator isn't a route, I think you are moving outside the ember guidelines and creating your own conventions. In that case, you could build your own resolver and structure your folders however you would like.

With one of Embers main focuses being routes, I think it makes perfect sense to separate files into global or route/resource based conventions.

**Comment by samselikoff** [comment] 2015-02-10 00:38
I agree it makes sense some of the time, but not always. In my case `creator` is essentially the index route.

The reason I wouldn't want `exclude-module` in a top-level `components` folder is, it only applies to modules. It doesn't make sense in any other context.

Say I put `exclude-module` in a top-level dir. Then I want to add a separate `settings` and `admin` route (or maybe, non-route). You can imagine this top-level dir growing very quickly, for these generic things. The point is, I want to be able to create components to keep my app modular and to encourage reuse; that's the point, after all. But if I'm going to make a component that only applies to some portion of my UI, I should be able to "scope" it there, somehow, whether that portion represents a route, doesn't represent a route, or represents only a small portion of a route.

Remember that `route` is going to just become a `component`, so we really need to start encouraging everyone to think of their apps as trees of components. With this comes more and smaller components, and I think the ability to organize them in this way.

**Comment by trabus** [comment] 2015-02-10 01:04
>Abstraction levels of an app's various pieces change during development as design changes. Ember CLI's dir structure should acknowledge this, and be flexible enough to let developers structure their apps as best they see fit according to the domain of their application.

@samselikoff this is one of the things I've been struggling with while coming up with the [Structures RFC](https://github.com/ember-cli/rfcs/pull/5). We absolutely could allow people to create their own custom structures and resolver rules to match. But would it cause more confusion because we weren't all following one convention?

I think this thread is touching on some really key points that we could derive a unified structure from. I think we could probably pick out some of what we like and come up with some rules for pods. I think we also need to work out some way to register namespaces, that aren't necessarily routecentric.

One of the things that Structures would provide is a way to easily experiment with different project organization structures so we can test out what works and what doesn't. Obviously the current pod structure is lacking and won't work in the long run.

**Comment by nathanpalmer** [comment] 2015-02-10 18:56
@samselikoff I don't see what the use-case for nested components would be. I could simply be missing something. I can see having a set of components that relate to a single route (just not one of those components having another component as a child.)

> @trabus would it cause more confusion because we weren't all following one convention?

I agree and I want to be careful about this. It's really easy to know where things are at in an ember project right now and I don't want to lose that. What I'm looking for is to better define the ember standard format.

> @trabus I think we also need to work out some way to register namespaces, that aren't necessarily routecentric

I like the idea of namespacing. From the "standard" layout I mentioned above I see 6 high-level namespaces provided by ember.

## ember

```
-- app/
   |-- components/
   |-- helpers/
   |-- initializers/
   |-- mixins/
   |-- utils/
   |-- pods/
```

These are all global for the ember app. Then we have a couple provided by things outside of main ember.js. 

## external

```
-- app/
   |-- data/  # ember-data namespace
   |-- auth/  # simple-auth namespace
```

Each of these folders themselves are together in a pod format

### ember-data
```
  |--data/
  |  |
  |  |--name/
  |  |  |
  |  |  |-- model.js
  |  |  |-- serializer.js
  |  |  |-- adapter.js
  |  | 
  |  |--name/
  |     |
  |     |-- transform.js
```

### simple-auth
```
  |--auth/
     |
     |--name/ # devise, for example
        |
        |-- authenticator.js
        |-- store.js 
```

## full preview
```
--app/
  |
  |--components/
  |  |
  |  |--name/
  |  |  |
  |  |  |-- component.js
  |  |  |-- template.hbs
  |  |  |-- style.scss
  |  |
  |
  |--helpers/
  |  |
  |  |-- name-helper.js
  |
  |--initializers/
  |  |
  |  |-- name.js
  |
  |--mixins/
  |  |
  |  |-- name.js
  |
  |--utils/
  |  |
  |  |-- name.js
  |
  |--pods/
  |  |
  |  |--name/
  |     |
  |     |-- controller.js
  |     |-- route.js
  |     |-- template.hbs
  |     |-- style.scss
  |     |
  |     |--nested-route/
  |        |
  |        |-- controller.js
  |        |-- route.js
  |        |-- template.hbs
  |        |-- style.scss
  |
  |--data/
  |  |
  |  |--name/
  |  |  |
  |  |  |-- model.js
  |  |  |-- serializer.js
  |  |  |-- adapter.js
  |  | 
  |  |--name/
  |     |
  |     |-- transform.js
  |       
  |--auth/
     |
     |--name/
        |
        |-- authenticator.js
        |-- store.js 
```

**Comment by ulisesrmzroche** [comment] 2015-02-10 19:00
ᐧ
I don't like the data or auth folders. Too much coupling.

On Tue, Feb 10, 2015 at 12:56 PM, Nathan Palmer <notifications@github.com>
wrote:

> @samselikoff <https://github.com/samselikoff> I don't see what the
> use-case for nested components would be. I could simply be missing
> something. I can see having a set of components that relate to a single
> route (just not one of those components having another component as a
> child.)
>
> @trabus <https://github.com/trabus> would it cause more confusion because
> we weren't all following one convention?
>
> I agree and I want to be careful about this. It's really easy to know
> where things are at in an ember project right now and I don't want to lose
> that. What I'm looking for is to better define the ember standard format.
>
> @trabus <https://github.com/trabus> I think we also need to work out some
> way to register namespaces, that aren't necessarily routecentric
>
> I like the idea of namespacing. From the "standard" layout I mentioned
> above I see 6 high-level namespaces provided by ember.
> ember
>
> -- app/
>    |-- components/
>    |-- helpers/
>    |-- initializers/
>    |-- mixins/
>    |-- utils/
>    |-- pods/
>
> These are all global for the ember app. Then we have a couple provided by
> things outside of main ember.js.
> external
>
> -- app/
>    |-- data/  # ember-data namespace
>    |-- auth/  # simple-auth namespace
>
> Each of these folders themselves are together in a pod format
> ember-data
>
>   |--data/
>   |  |
>   |  |--name/
>   |  |  |
>   |  |  |-- model.js
>   |  |  |-- serializer.js
>   |  |  |-- adapter.js
>   |  |
>   |  |--name/
>   |     |
>   |     |-- transform.js
>
> simple-auth
>
>   |--auth/
>      |
>      |--name/ # devise, for example
>         |
>         |-- authenticator.js
>         |-- store.js
>
> full preview
>
> --app/
>   |
>   |--components/
>   |  |
>   |  |--name/
>   |  |  |
>   |  |  |-- component.js
>   |  |  |-- template.hbs
>   |  |  |-- style.scss
>   |  |
>   |
>   |--helpers/
>   |  |
>   |  |-- name-helper.js
>   |
>   |--initializers/
>   |  |
>   |  |-- name.js
>   |
>   |--mixins/
>   |  |
>   |  |-- name.js
>   |
>   |--utils/
>   |  |
>   |  |-- name.js
>   |
>   |--pods/
>   |  |
>   |  |--name/
>   |     |
>   |     |-- controller.js
>   |     |-- route.js
>   |     |-- template.hbs
>   |     |-- style.scss
>   |     |
>   |     |--nested-route/
>   |        |
>   |        |-- controller.js
>   |        |-- route.js
>   |        |-- template.hbs
>   |        |-- style.scss
>   |
>   |--data/
>   |  |
>   |  |--name/
>   |  |  |
>   |  |  |-- model.js
>   |  |  |-- serializer.js
>   |  |  |-- adapter.js
>   |  |
>   |  |--name/
>   |     |
>   |     |-- transform.js
>   |
>   |--auth/
>      |
>      |--name/
>         |
>         |-- authenticator.js
>         |-- store.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3234#issuecomment-73759572>
> .
>

**Comment by samselikoff** [comment] 2015-02-10 19:05
The argument for nested components is, in moderately complex apps a single route/template/controller combo isn't enough, and you're going to want to split up your UI into "features" within that route. Your dir structure should mirror your UI, which is based on features (which in turn should mirror your URL structure).

Imagine some portion of your app becoming very complex, so much so that it now makes sense to extract it into its own app. My argument is, most/all of the pieces of that new "app" should live under that single dir (`admin`, for instance). Things that are shared across admin and the rest of the app should live in global dirs, but not everything falls in that category.

In general, one-child-deep pods directories make things easy to find, assuming everything related to that pod exists in that folder. When that folder becomes 20+ files, we need more structure.

**Comment by aaronbhansen** [comment] 2015-02-10 19:05
@ulisesrmzroche it seems like you either have to couple it with ember inside of pods, or you couple it with the library it belongs too. 

Namespacing actually decouples the library from ember and gives you a better pattern for setting up your external libraries inside of you app folder. Why would you not want data, auth, or external library files  grouped together in a namespace?

**Comment by samselikoff** [comment] 2015-02-10 19:07
I find this doc from Ryan Florence compelling:

https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346

**Comment by nathanpalmer** [comment] 2015-02-10 19:08
@ulisesrmzroche @aaronbhansen plus I'd expect the external library itself to register itself as a namespace and therefore ember wouldn't know or care that it existed. Less coupled than today I'd say.

**Comment by aaronbhansen** [comment] 2015-02-10 19:09
@samselikoff, in the 6 ember apps I've written, I never had a single route become that complex. If it started to get to complex, I either wasn't following the ember guidelines, or needed to break up the route into different logical routes. 

I've been doing components only in the past 6 months (no controllers other than the route controllers), and I have at most found 5-8 components live under a single route or resource. 

I can't imagine your use case is going to be common for the majority of ember users.

**Comment by trabus** [comment] 2015-02-10 19:09
> Imagine some portion of your app becoming very complex, so much so that it now makes sense to extract it into its own app. My argument is, most/all of the pieces of that new "app" should live under that single dir (admin, for instance). Things that are shared across admin and the rest of the app should live in global dirs, but not everything falls in that category.

I think as engines come around, this sort of thing would be a clear indicator that features that get this large should in fact be broken into their own apps. Addons would likely provide the path for sharing components between broken up feature apps.

**Comment by samselikoff** [comment] 2015-02-10 19:09
See Discourse's [views](https://github.com/discourse/discourse/tree/d8c616a68a98805e8f7138e7550a3478154500e5/app/assets/javascripts/discourse/views) directory for an example of the problem I'm describing.

**Comment by ulisesrmzroche** [comment] 2015-02-10 19:10
I guess I just handle auth and configuration via services and
initializers.. I don't see the point in making them first-class citizens.
ᐧ

**Comment by samselikoff** [comment] 2015-02-10 19:12
@trabus I agree something like engines would the way these pieces could get broken up into their own apps. My only point is that, prior to the decision to split up a part of an app into its own separate app, it should be as self-contained (within the current app) as possible.

**Comment by nathanpalmer** [comment] 2015-02-10 19:14
@samselikoff I can see the need for organization similar to [this](https://github.com/emberjs/ember.js/issues/10407) but what I didn't understand was why the main directory needs it's own component.js.

I'm also curious if some of what you're talking about could be broken into in-repo addons.

@ulisesrmzroche I'm not suggesting making them first-class citizens. But they exist in projects and we're allowing them to exist. It can't simply be configuration and initializers when you build out customer authorizers and stores. Those files need to go somewhere and right now they are directly off of app in `authorizers` and `stores`.

**Comment by aaronbhansen** [comment] 2015-02-10 19:15
I've looked at Discourse's views and structure before, and I personally wouldn't organize my app structure as they did. Some of the views are global, but many are route or resource specific. Taking the pod structure examples above, you could easily organize their views into global, resource, and route specific views.

**Comment by ulisesrmzroche** [comment] 2015-02-10 19:20
It shouldn't matter for adapters and serializers because those land in
their own pod

Maybe make it opt-in? I guess what I'm trying to say is that since it's an
architectural choice (simple auth is pretty heavyweight IMO) then it
shouldn't affect the default that heavily.
ᐧ

**Comment by samselikoff** [comment] 2015-02-10 19:23
@aaronbhansen perhaps, but imagine if it essentially required 0 wiring up to split up some of those pieces into multiple components? For example the [topic.js](https://github.com/discourse/discourse/blob/d8c616a68a98805e8f7138e7550a3478154500e5/app/assets/javascripts/discourse/views/topic.js.es6) view is almost 200 lines long, the [corresponding template](https://github.com/discourse/discourse/blob/d8c616a68a98805e8f7138e7550a3478154500e5/app/assets/javascripts/discourse/templates/topic.hbs) nearly 140 and [the controller](https://github.com/discourse/discourse/blob/d8c616a68a98805e8f7138e7550a3478154500e5/app/assets/javascripts/discourse/controllers/topic.js.es6) over 700.

Even if these three files were grouped together under a single parent resource directory, their complexity seems to warrant further separation. I want to make this as easy as possible. Split it up into many components to break down each task into small bite-size chunks. This `topic` combo then becomes a mini application within Discourse, and it can be broken up into whatever component structure makes the most sense for its responsibilities. This is where + why I think namespacing and sub-dir components are needed.

**Comment by samselikoff** [comment] 2015-02-10 19:29
One of the oft-touted benefits of React is the isolation of each component. Newbies can jump in and open a single component file, understand it, mess with it and be reasonably confident they won't mess up other parts of the system. Imagine being a newbie Discourse contributor and opening up that controller - it would be terrifying to change it.

I'm not saying Discourse did it a poor job architecting the code, I'm saying the primitives didn't exist in Ember yet to help guide them along. Now, those are coming - namely components as first-class citizens. Components are the way to break up UI into small, cohesive bits.

This is the path Ember is headed, and I think it is a good path. It's true that as Ember apps move away from identical top-level directory structures (like `/models`, `/views` and `/controllers`) and towards domain-specific ones, some standardization is lost. But I think the argument is that domain-specific logic is large and complex, and makes its way into your app regardless, as evidenced by the Discourse example.

So instead of pretending like this isn't true, Ember CLI could embrace it and give us the tools to structure our apps around our domains. That's basically what I'm arguing, because the alternative is single-child-level classes that have multiple responsibilities and are too complex.

**Comment by trabus** [comment] 2015-02-10 19:33
> I want to make this as easy as possible. Split it up into many components to break down each task into small bite-size chunks. This topic combo then becomes a mini application within Discourse, and it can be broken up into whatever component structure makes the most sense for its responsibilities. This is where + why I think namespacing and sub-dir components are needed.

I definitely agree with this. :+1: 

Breaking things up by namespace into smaller digestible components is definitely preferred imo. A component will always make more sense within the context of where it's used rather than lumped together with completely unrelated components. Those that do fit into a global namespace are obviously generic and have no specific context in which they are used.

**Comment by samselikoff** [comment] 2015-02-10 19:36
As a quick example here's the app I'm currently working on:

![image](https://cloud.githubusercontent.com/assets/2922250/6134812/de0be058-b131-11e4-89d5-38cec6722093.png)

This app is still relatively small (it's also not complete), but even having a `/lib` (for things like `ted-panel` and `input-range`) would be helpful. But still, for a newbie coming into this app, they shouldn't see the `new-answer-form` at the top level. It only makes sense in the context of an `answer-list`. So, I'd like to be able to nest/namespace that. (Note that we can do this right now with `/` in the name, but it quickly becomes cumbersome).

**Comment by nathanpalmer** [comment] 2015-02-10 20:06
@samselikoff I think we're getting slightly off-topic. I believe that scoped components under a route would be great (or even organized components as suggested by [Document path based component/helper names](https://github.com/emberjs/ember.js/issues/10243) and [helper names can be paths?](https://github.com/wycats/handlebars.js/issues/912)) I see it as a different proposal from this one however and it's not in any way a conflict with what I've laid out so far.

@ulisesrmzroche The auth/ directory was there was an example of a namespace. It in no way implies a change in default. Your other comments don't make sense within the context of this conversation.

**Comment by samselikoff** [comment] 2015-02-10 20:17
Gotcha, this is just about which entities get grouped into "pods" by default. I think we're on the same page there.

I guess one thing I'd like to see is the `pods` concept not applying only to top-level groupings but rather groupings at arbitrary levels. While this is also probably out of scope of this issue, the defaults we set up around the pods concept will influence how developers think about them, so I just wanted to mention it.

**Comment by runspired** [comment] 2015-02-23 22:36
My two cents: Pods is very useful, but `pods/` easily becomes cluttered.  I think what makes the most sense is a resource based structure (a combination of the separation of global/route based stuff above and to do 'resource' resets).

This is a rough sketch of what I'm thinking
```
/app
|_helpers/
|_initializers/
|_utils/
|_components/
        |_ myComponent/
            |_ component
            |_ template
|_models
    |_foo/
        |_adapter
        |_serializer
        |_model
|_pods/
    |_ myRoute
        |_ route
        |_ controller
        |_ view
        |_ template
    |_ myResource
        |_ myRoute1/
        |_ myRoute2/
        |_ myRoute3/
        |_ models/
        |_ utils/
        |_ components/
        |_ helpers/
```

**Comment by ffaubry** [comment] 2015-12-04 18:22
Just a quick feedback. I went to pods and came back from a pods structure simply because debugging was a hell. All the tabs under dev-tools were named 'component.js'. I lost the name of my component.
My dream is to take the best of both worlds:
- Use pods for organizing my components, routes, etc 
- prefix the name the files under the pods with the name of the pod
  - x-foo-component.js
  - x-foo-template.hbs

**Comment by knownasilya** [comment] 2015-12-04 18:27
This is an issue with your editor, not the structure.

**Comment by lolmaus** [comment] 2015-12-04 22:19
@ffaubry WebStorm, Sublime, Atom have this solved. File an issue against your editor.

**Comment by stefanpenner** [comment] 2015-12-04 23:33
> @ffaubry WebStorm, Sublime, Atom have this solved. File an issue against your editor.

:+1:

**Comment by ffaubry** [comment] 2015-12-07 15:58
@lolmaus Thanks. I'm using VS Code.
However, I don't think the Chrome Dev Tools support pod structure.

**Comment by stefanpenner** [comment] 2015-12-22 04:22
best revisited as a ember rfc https://github.com/emberjs/rfcs

**Closed by stefanpenner** 2015-12-22 04:22 UTC
Labels: pod, proposal
