### ISSUE TITLE
ember-cli commands hanging on macOS Sierra GM2

### ISSUE THREAD

**Issue by kpfefferle** [ember-cli/ember-cli#6275] opened 2016-09-16 22:08 UTC
Yesterday, Apple released Gold Master 2 of macOS Sierra to developers. Since updating to GM2, none of my ember-cli commands work regardless of which versions of node or ember-cli I attempt to use. They simply hang with no output.

I did a bit of remote Slack debugging today with @twokul, and we were able to narrow it down as far as this line: https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/cli/lookup-command.js#L39

The CLI commands seem to make it *to* this conditional (hitting a `debugger` placed before this line), but not *into* the conditional (not hitting a `debugger` following this line). According to the debugger repl, `command` is defined at this point but `addonCommand` is not.

I will continue to dig a bit deeper to see if I can get more precise with why this might be failing to assign a value to `addonCommand`.

---

Output from `ember version --verbose && npm --version`:
```
ember version hangs as described above
I am currently debugging using #master

npm: 3.8.6
```

**Comment by nathanhammond** [comment] 2016-09-16 22:56
Dibs on not it. 😜 Let us know what you find out @kpfefferle ... also if anybody else can reproduce this it'd be wonderful. I trust that you're seeing it; I just don't know if you're incredibly unlucky and the only person encountering it.

**Comment by corbinu** [comment] 2016-09-17 20:35
I am seeing this also I am on Public Beta 7 and I just tried to update to ember-cli@2.9.0-beta.1 and when i run ember init it simply hangs.

Node version v6.6.0
Npm version 3.10.8

**Comment by nathanhammond** [comment] 2016-09-18 03:25
For people who stumble across this issue: please please please provide as much detail as you can about the system, if it fails with a brand new project, trying to do things from scratch...

General "clean slate" debugging:

- `npm uninstall -g ember-cli`
- `npm cache clear`
- Reinstall `node` and `npm`
- Test without `watchman`
- Test with `watchman`
- Include a link to `npm ls` of your project folder.
- Reinstall Xcode command line tools.
- ...

To my knowledge none of the team is on Sierra and reproduction is inconsistent anyway. We're going to need to diagnose this on somebody else's computer.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/dev-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and see if any of us are around to help you debug once you've done all of the basic debugging steps.

**Comment by kpfefferle** [comment] 2016-09-18 05:00
@nathanhammond Thanks for the added debugging tips! I am happy to report back that uninstalling watchman allows my ember-cli commands to work properly. Reinstalling watchman causes the commands to hang again, so this clearly seems (at least on my machine) to be related to watchman.

**Comment by nathanhammond** [comment] 2016-09-18 05:42
@kpfefferle Can you try watchman@4.6.0 for me? 4.7.0 has at least one known issue.

**Comment by nathanhammond** [comment] 2016-09-18 05:44
I'm closing this issue as likely not a bug in Ember CLI. If you find yourself here via search _please_ follow the directions here: https://github.com/ember-cli/ember-cli/issues/6275#issuecomment-247822676

If after that you still have issues please leave comments here, and leave as detailed of a report as you can. We will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Closed by nathanhammond** 2016-09-18 05:44 UTC

**Comment by kpfefferle** [comment] 2016-09-18 19:24
@nathanhammond watchman@4.6.0 seems to work; watchman@4.7.0 does not

For anyone else needing to downgrade watchman to 4.6.0 via Homebrew on OS X, this method worked for me:

1. Uninstall latest watchman:

    ```
    brew uninstall watchman
    ```

1. Reinstall watchman using previous 4.6.0 formula:

    ```
    brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/5b05bf29f1327d627ddbedbf115c1d28d9fa521d/Formula/watchman.rb
    ```

1. Pin watchman to 4.6.0 to prevent updating until a fix is available:

    ```
    brew pin watchman
    ```

**Comment by kpfefferle** [comment] 2016-09-20 19:03
Today @chriskrycho shared a fix that works for me with watchman@4.7.0. After upgrading to Watchman 4.7.0, run the following command (replace `<user>` with your system user):

```
rm -r /usr/local/var/run/watchman/<user>-state
```

This was first surfaced in https://github.com/ember-cli/ember-cli/issues/6259

**Comment by chriskrycho** [comment] 2016-09-20 19:04
Note that I *believe* you can just do the even simpler:

```sh
rm /usr/local/var/run/watchman/<user>-state/sock
```

The underlying problem as I understand it is that the socket (`sock`) is holding onto some data rather than being refreshed when a new version of watchman is installed.

**Comment by wez** [comment] 2016-09-23 16:55
The correct resolution is:

```
launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist
watchman version
```
