### ISSUE TITLE
Fresh install ember stack trace on serve

### ISSUE THREAD

**Issue by anonrose** [ember-cli/ember-cli#6237] opened 2016-09-07 02:38 UTC
I've freshly cloned a repository, and ran `npm install && bower install` and received the following stack trace on `ember serve`.

➜  self-storage-search git:(master) ember build
`⠋ BuildingCould not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'`

`Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'`
    `at Function.Module._resolveFilename (module.js:325:15)`
   `at Function.Module._load (module.js:276:25)`
    `at Module.require (module.js:353:17)`
    `at require (internal/module.js:12:17)`
    `at Object.<anonymous> (/Users/anonrose/Documents/G5/Widgets/self-storage-search/ember-cli-build.js:4:16)`
    `at Module._compile (module.js:409:26)`
    `at Object.Module._extensions..js (module.js:416:10)`
    `at Module.load (module.js:343:32)`
    `at Function.Module._load (module.js:300:12)`
    `at Module.require (module.js:353:17)`
    `at require (internal/module.js:12:17)`

**Comment by nathanhammond** [comment] 2016-09-07 06:22
This is likely a broken `npm install`. Can you try `npm cache clear` and reinstalling?

I'm closing this issue as likely not a bug–we'd have tons of reports of this if it were terribly broken. If upon further investigation on your side you discover that it may in fact be a bug feel free to reopen. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

We're glad to help here or you can also find us in [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) on the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/). 😄

**Closed by nathanhammond** 2016-09-07 06:22 UTC
