### ISSUE TITLE
The `included()` hook doesn't get called in the dummy app for an addon

### ISSUE THREAD

**Issue by mansona** [ember-cli/ember-cli#8448] opened 2019-02-23 22:58 UTC
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.7.1
http_parser: 2.8.0
node: 10.12.0
v8: 6.8.275.32-node.35
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.8.0
1.13.0
```

This output may look a bit strange because I just updated my ember-cli to see if the behaviour is still the case for the addon that I'm currently working on.

The thing that originally seemed a bit odd to me was that I noticed the [included() hook](https://github.com/empress/guidemaker/blob/master/index.js#L165) from an addon that the current addon I'm working on depends on, doesn't seem to be running in the dummy app of the current addon addon. In my case I'm working on the addon `guidemaker-ember-template` which has a devDependency on `guidemaker` and guidemaker has an `included()` hook that I was expecting to run,  but it never runs. I assume this was related to https://github.com/ember-cli/ember-cli/issues/7915 to prevent issues with nested addons 🤔 

I then tried to move the `included()` hook into the same addon that I'm currently working on (`guidemaker-ember-template`) it still didn't get executed in the dummy app for the **same** addon 🤔 this is very surprising because it essentially means that the dummy app is not experiencing the same behaviour as the app that might include the addon. 

I have a feeling that this might be related to https://github.com/ember-cli/ember-cli/issues/4933 but I don't fully understand the context to know if this is the same issue. It also seems like it might be related to https://github.com/ember-cli/ember-cli/issues/6670 because that seems to have similar behaviour: 

> preprocessors only act on their direct parent, be it an app or another addon, and not any further up the dependency tree.

I know that I can easily work around this by manually adding something to the `ember-cli-build` of the addon but it seems like it is not behaving as I would expect so this is essentially working around a bug. I would love to know people's thoughts on this issue and I'm willing to help fix it if I could be given a bit of guidance.

**Comment by rwjblue** [comment] 2019-02-24 00:24
Can you help me understand the repro here? In general, these types of issues (a nested addons included hook not being called) are caused by not calling super in the thing that depends on the addon in question (quidemaker)...

**Comment by mansona** [comment] 2019-02-24 14:49
@rwjblue I'll simplify my example because I know there is a lot going on here 🙈 

The addon `guidemaker-ember-template` has ember-prism as a dependency (not a devDependency, not that it matters in this case), which requires some config in `ember-cli-build.js` to decide the default theme for Prism. As `guidemaker-ember-template` is a **theme** for guidemaker, `guidemaker-ember-template` should be providing the theme specifications for Prism and I attempted to do that in this commit: https://github.com/ember-learn/guidemaker-ember-template/pull/8/commits/ad3c359ddaa2a27e2e1a76ccb84110b659cd30e2#diff-168726dbe96b3ce427e7fedce31bb0bcR13

If you run this commit locally (npm start to run the dummy app for this addon) you will see the following: 

![screenshot 2019-02-24 at 12 05 56](https://user-images.githubusercontent.com/594890/53298957-915cb800-382c-11e9-89ea-efa1f7d6157d.png)

It looks wrong because Prism is essentially misconfigured. 

I then need to explicitly add the prism config to the ember-cli-build like this https://github.com/ember-learn/guidemaker-ember-template/pull/8/commits/43bdcbbb47925d153fe4b9a5c954d4c7e36e4629#diff-2fe2a7faee7de1e0d5d82e032498d84cR11 for it to start picking up the config. This is telling me that the `included()` hook is just not working as expected **while running the dummy app of the same addon** 

Not that it's 100% relevant to the case but here is what it looks after that change: 

![screenshot 2019-02-24 at 12 11 13](https://user-images.githubusercontent.com/594890/53299021-5d35c700-382d-11e9-8ff5-84b1e9d25314.png)

I guess it's useful to know when it's working correctly 😂

**Comment by rwjblue** [comment] 2019-02-28 22:50
> This is telling me that the `included()` hook is just not working as expected **while running the dummy app of the same addon**

I'm not sure that I agree with this conclusion. It seems to me that `guidemaker-ember-template` has at least one but possibly two issues:

* When `this._super.included.apply` is called, the `included` hook of all of your addon's `dependencies` are invoked. In the implementation from https://github.com/ember-learn/guidemaker-ember-template/commit/ad3c359ddaa2a27e2e1a76ccb84110b659cd30e2#diff-168726dbe96b3ce427e7fedce31bb0bcR13, the options are being set **after** ember-prism is trying to look for them and they therefore have no effect.  Moving the super call to be below the configuration resolves the issue.
* The argument passed to the `included` hook is _not_ always the top level `lib/broccoli/ember-app.js` instance, it is only the `EmberApp` instance that you desire here if the addon in question is a top level dependency. **IIF** you only ever expect your addon (guidemaker-ember-template) to be a top level dependency, using the argument to `included` will be fine. However, if you intend to support your addon being a nested dependency the argument to `included` will be a different thing (it would be an `lib/models/addon.js` instance). I can't tell if you intend to support the nested case, so I'm not sure if this point is an actual concern for you...

**Comment by rwjblue** [comment] 2019-02-28 22:55
See https://github.com/ember-learn/guidemaker-ember-template/pull/10 for less words, more code. 😸

**Comment by mansona** [comment] 2019-06-15 19:12
Hey sorry it took me a long time to get back to you 😂 but I can confirm that the recommended change does **not** fix the problem 😞 

I'm experimenting with it in a less high profile app than the guides so I don't break anything 🙈 

If you take a look at this PR: https://github.com/ember-learn/ember-styleguide/pull/180/files#diff-2fe2a7faee7de1e0d5d82e032498d84cR34 you will see that I need to still do the hack of updating the host addon's ember-cli-build file because the same recommended implementation doesn't work: https://github.com/empress/field-guide/blob/master/index.js#L15

Sorry if I'm not being clear enough 🙈 let me know if you have any questions

**Comment by rwjblue** [comment] 2019-06-17 13:39
The PR I sent a few months ago, absolutely fixed the issue (I tested with and without the changes to confirm the highlighting didn't work without the changes and did work with them).

Maybe you missed something in applying them to the other repo?

**Comment by rwjblue** [comment] 2019-06-17 13:55
I just uploaded images over in https://github.com/ember-learn/guidemaker-ember-template/pull/10 demonstrating that it did indeed work properly.

**Comment by locks** [comment] 2022-02-10 02:08
@mansona poke :)

**Comment by bertdeblock** [comment] 2022-08-31 19:44
Going to close this one because of https://github.com/ember-learn/guidemaker-ember-template/pull/10#issuecomment-502692156.

**Closed by bertdeblock** 2022-08-31 19:44 UTC
Labels: needs submitter response
