### ISSUE TITLE
 Issue while deploying Ember application on kubernetes | ELIFECYCLE | fatal error: node_api.h: No such file or directory  #include <node_api.h>

### ISSUE THREAD

**Issue by shyamsunder111** [ember-cli/ember-cli#9109] opened 2020-03-17 06:19 UTC
> utf-8-validate@5.0.2 install /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/utf-8-validate
> node-gyp-build

make: Entering directory '/usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/utf-8-validate/build'
  CC(target) Release/obj.target/validation/src/validation.o
[91m../src/validation.c:3:22: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
                      ^
compilation terminated.
[0mvalidation.target.mk:98: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: Leaving directory '/usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/utf-8-validate/build'
[91mmake: *** [Release/obj.target/validation/src/validation.o] Error 1
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mbuild error[0m[91m 
[0m[91mgyp ERR![0m[91m [0m[91mstack Error: `make` failed with exit code: 2
[0m[91mgyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
[0m[91mgyp ERR![0m[91m [0m[91mstack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
[0m[91mgyp ERR! System[0m[91m Linux 4.14.158-129.185.amzn2.x86_64
[0m[91mgyp ERR! command[0m[91m "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[0m[91mgyp ERR! cwd[0m[91m /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/utf-8-validate
[0m[91mgyp ERR! [0m[91mnode -v v0.12.18
[0m[91mgyp [0m[91mERR! [0m[91mnode-gyp -v[0m[91m v3.4.0
[0m[91mgyp [0m[91mERR! not ok 
[0m
> bufferutil@4.0.1 install /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/bufferutil
> node-gyp-build

make: Entering directory '/usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
[91m../src/bufferutil.c:3:22: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
                      ^
compilation terminated.
[0m[91mmake: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
[0mbufferutil.target.mk:98: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/bufferutil/build'
[91mgyp[0m[91m [0m[91mERR! [0m[91mbuild error[0m[91m 
[0m[91mgyp [0m[91mERR![0m[91m [0m[91mstack[0m[91m Error: `make` failed with exit code: 2
[0m[91mgyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
[0m[91mgyp ERR! stack     at ChildProcess.emit (events.js:110:17)
[0m[91mgyp ERR![0m[91m stack[0m[91m     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
[0m[91mgyp ERR! [0m[91mSystem[0m[91m Linux 4.14.158-129.185.amzn2.x86_64
[0m[91mgyp ERR! command[0m[91m "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp [0m[91mERR! [0m[91mcwd /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/bufferutil
[0m[91mgyp ERR! node -v v0.12.18
[0m[91mgyp ERR![0m[91m [0m[91mnode-gyp -v v3.4.0
[0m[91mgyp ERR![0m[91m not ok 
[0m
> core-js@2.6.11 postinstall /usr/local/lib/node_modules/ember-cli/node_modules/broccoli-babel-transpiler/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[91mnpm [0m[91mERR! Linux 4.14.158-129.185.amzn2.x86_64
[0m[91mnpm ERR! [0m[91margv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
[0m[91mnpm ERR! [0m[91mnode v0.12.18
[0m[91mnpm ERR![0m[91m npm  v2.15.11
[0m[91mnpm ERR! code ELIFECYCLE
[0m[91m
[0m[91mnpm ERR![0m[91m utf-8-validate@5.0.2 install: `node-gyp-build`
[0m[91mnpm ERR! Exit status 1
[0m[91mnpm[0m[91m ERR! 
[0m[91mnpm [0m[91mERR! Failed at the utf-8-validate@5.0.2 install script 'node-gyp-build'.
[0m[91mnpm ERR![0m[91m This is most likely a problem with the utf-8-validate package,
npm ERR![0m[91m not with npm itself.
npm[0m[91m ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build

**Comment by rwjblue** [comment] 2020-03-18 20:30
In general, most of these errors look like installation of some native modules are failing (that is usually what node-gyp is used for). Most of the time these native modules are optional, so I'm curious what is actually going wrong in this context.

Can you help with a reproduction? Or try to isolate the steps that are going wrong in your setup?

**Comment by locks** [comment] 2022-02-10 03:28
Closing due to lack of submitter response.

**Closed by locks** 2022-02-10 03:28 UTC
Labels: needs reproduction
