### ISSUE TITLE
Installing addons from blueprint fails: "Could not find addon"

### ISSUE THREAD

**Issue by binhums** [ember-cli/ember-cli#6318] opened 2016-10-06 12:02 UTC
When running `addAddonsToProject` in a blueprint:

```
installing ember-cli-zesty-app-base
  identical testem.js
  install addons ember-cli-eslint@^1.7.0, ember-cli-template-lint@^0.4.12, ember-concurrency@^0.7.8, ember-test-selectors@^0.0.3
Installed packages for tooling via npm.
Install failed. Could not find addon with name: ember-cli-eslint@^1.7.0
```

We have an Ember addon for installing other addons that is currently running into issues. The `afterInstall` hook in the blueprint looks a like this:

```js
  afterInstall: function() {
    var blueprint = this;
    var project = this.project;

    return blueprint.addAddonsToProject({
      packages: [
        { name: 'ember-cli-eslint', target: '^1.7.0' },
        { name: 'ember-cli-template-lint', target: '^0.4.12' },
        { name: 'ember-concurrency', target: '^0.7.8' },
        { name: 'ember-test-selectors', target: '^0.0.3' }
      ]
    }).then(function() {
      return blueprint.addPackagesToProject([
        { name: 'babel-eslint', target: '^6.1.2' },
        { name: 'ember-cli-deploy', target: '^0.6.4' },
      ])
    })
```

I can reproduce the issue with [this pared down addon](https://github.com/binhums/bug-add-addons-to-project).

This looks similar to #5880, but I believe it is distinct.

Verified against master, I have a potential fix incoming.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.5.2
node: 4.4.5
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: darwin x64
2.15.5
```

**Comment by binhums** [comment] 2016-10-06 12:15
Currently an addon maintainer will need to specify the flags explicitly to make it work. e.g.

```js
    return blueprint.addAddonsToProject({
      packages: [
        { name: 'my-little-addon', target: '^2.1.0' }
      ],
      blueprintOptions: {
        saveDev: true
      }
    })
```

**Comment by HerveSeger** [comment] 2016-10-20 17:23
I am exactly in the same situation with an addon we built to setup corporate projects with default packages/versions.

Furthermore, the default addon blueprint is not automatically executed anymore when the command `ember install https://github.com/company/addon-name.git#master` is run. ember-cli throws:
```
WARNING: Could not figure out blueprint name from: "https://github.com/company/addon-name.git#master". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
```

I  had to rollback ember-cli to a previous version to get the expected behavior.

**Comment by nathanhammond** [comment] 2016-10-20 20:17
> Furthermore, the default addon blueprint is not automatically executed anymore when the command ember install https://github.com/company/addon-name.git#master is run. ember-cli throws:
> `WARNING: Could not figure out blueprint name from: "https://github.com/company/addon-name.git#master". Please install the addon blueprint via "ember generate <addon-name>" if necessary.`

@HerveSeger that just means that you need to:

`ember install https://github.com/company/addon-name.git#master && ember g addon-name`

We don't guess at that anymore because it wasn't guaranteed to be correct.

The saving of the blueprint will be addressed by #6319 once @binhums is back.

**Comment by HerveSeger** [comment] 2016-10-20 22:23
@nathanhammond 
I knew that  a  manual install was still possible but I did not know that this behavior had changed so thanks for the info.

Thanks as well for the reference to #6319, I will wait for the fix.

**Closed** 2016-10-30 19:11 UTC

**Comment by binhums** [comment] 2016-10-31 12:01
@HerveSeger: there is a workaround whilst you're waiting for the fix to come through. You need to specify `saveDev` explicitly in a blueprintOptions param, e.g.

```js
    return blueprint.addAddonsToProject({
      packages: [
        { name: 'ember-cli-eslint', target: '^1.7.0' },
      ],
      blueprintOptions: {
        saveDev: true
      }
    })
```

We've open sourced our corporate projects repo if you want a full reference for the fix:

https://github.com/zestyzesty/ember-cli-zesty-app-base/commit/ec3743c503b745a78b21b39f5fa2ad1e067046ea#diff-03f6c07a79dd48dbe1b50ca41636c9eaR29

**Comment by HerveSeger** [comment] 2016-10-31 12:05
@binhums Thanks for the info. 
It is indeed what I have done and it has fixed the issue.
