### ISSUE TITLE
Asset host not being prepended across the tags to assets in the app?

### ISSUE THREAD

**Issue by mariogintili** [ember-cli/ember-cli#6199] opened 2016-08-20 16:31 UTC
[I'm following this article](http://emberjs.com/blog/2016/04/28/baseURL.html#toc_how-to-use-a-cdn)

And my ember-cli-build looks like this:

```js
  var assetHost = 'https://sunlight-production.s3.amazonaws.com/';

  var app = new EmberApp(defaults, {
    fingerprint: {
      prepend: assetHost,
      enabled: true
    },
  });
```

as the article suggests - shouldn't my tags that look something like this

```html
<img class="s-loginlogo" src="/public/assets/images/Sun.svg">
```

look like something like this? after I build a production distribution

```html
<img class="s-loginlogo" src="https://sunlight-production.s3.amazonaws.com/public/assets/images/Sun.svg">
```

Wether I use an absolute or relative path, the end output is the same

```html
<img class="s-loginlogo" src="/public/assets/images/Sun.svg">
```

P.S both `{{rootURL}}` and `{{baseURL}}` seem to be null

**Comment by nathanhammond** [comment] 2016-08-20 17:22
Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community.

This is likely a configuration problem with your app. Can you try it in a simple `ember new` application and test to see if it works? If that fails you can publish it to GitHub it as a simplified reproduction we will be _happy_ to dive in and help.

For now, I'm closing this issue as likely not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; _being closed doesn't mean that we're ignoring the thread_.

**Closed by nathanhammond** 2016-08-20 17:22 UTC

**Comment by mariogintili** [comment] 2016-08-20 18:37
@nathanhammond I think deferring someone to slack + replying with a template doesn't really motivate people to open an further issues if they come across things.

Then again its your project and your policy 👍

**Comment by nathanhammond** [comment] 2016-08-20 21:16
> @nathanhammond I think deferring someone to slack + replying with a template doesn't really motivate people to open an further issues if they come across things.

> Then again its your project and your policy 👍

@mariogintili You have:

- Dismissed my investigation into your filed issue (which included setting up my own quick passing test) on a Saturday morning.
- Not shown up in Slack where I've been all day available to help in a synchronous manner.
- Not included the output of `ember version --verbose`.
- Not included a full reproduction.

Your filed issue is counter to my experience. The vast majority of our incoming issues are not actually bugs but instead are support requests which are better solved in Slack. Without a reproduction we _literally can't help you_. The templates exist exactly for this scenario where I don't have enough information to do anything to help you.

Please still feel encouraged to stop by on Slack. I'm still happy to help you.

**Comment by mariogintili** [comment] 2016-08-21 08:22
@nathanhammond 

> Dismissed my investigation into your filed issue (which included setting up my own quick passing test) 

Wasn't specified on the previous comment

> Not shown up in Slack where I've been all day available to help in a synchronous manner.

A bit of a grey line between what goes on Slack and what goes here(?) Conversations happen in both...

> Not included the output of ember version --verbose.

The top of the issue has a link to an upgrade guide, in case it wasn't clear I'm upgrading to 2.7.0

```
ember version --verbose
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.4
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: darwin x64
```

> Not included a full reproduction.

I understand you want a full reproduction - but how is the information provided not enough? Or at least, how is it not reflective of someone

1) [Following this](https://ember-cli.com/user-guide/#asset-compilation)
2) [doing this change](https://github.com/mariogintili/failed-asset-host/blob/master/ember-cli-build.js#L8) and [then this one](https://github.com/mariogintili/failed-asset-host/blob/master/app/templates/show-image.hbs#L3)

and expecting the same thing as the code blocks on the guide suggests

```
<script src="assets/appname.js">
```

to

```
<script src="https://subdomain.cloudfront.net/assets/appname-342b0f87ea609e6d349c7925d86bd597.js">
```

In case ^^^ the above is only for those things using `{{content-for}}` then I apologize, but the guides are quite vague and ambiguous if thats the case

**Comment by mariogintili** [comment] 2016-08-21 14:04
found the issue now @nathanhammond - could you please link me to the repo where you host the ember-cli website? I would like to suggest a copy change on the asset compilation segment

**Comment by rwjblue** [comment] 2016-08-21 14:15
@mariogintili - https://github.com/ember-cli/ember-cli.github.io

**Comment by nathanhammond** [comment] 2016-08-21 16:56
Hokay, appreciate the context and reproduction. 😄 I prefer Slack in this scenario because I can ask about each of the things which turn out to be important as we discover that they're important instead of 1-4 hours apart.

The story so far:
- `broccoli-asset-rev` only prepends assets which it knows about.
- In order for `broccoli-asset-rev` to know about an asset it must appear in the output directory and match extensions of `['js', 'css', 'png', 'jpg', 'gif', 'map']`.
- Subsequently it will only make those replacements in files with the extensions: `['html', 'css', 'js']`.

We can see prepending working with this diff on top of a default Ember CLI 2.7.0 `init`:
```diff
diff --git a/app/templates/index.hbs b/app/templates/index.hbs
new file mode 100644
index 0000000..c3ebbe2
--- /dev/null
+++ b/app/templates/index.hbs
@@ -0,0 +1 @@
+<img src="collision.png" />
\ No newline at end of file
diff --git a/ember-cli-build.js b/ember-cli-build.js
index 2537ce2..173f481 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -5,6 +5,9 @@ var EmberApp = require('ember-cli/lib/broccoli/ember-app');
 module.exports = function(defaults) {
   var app = new EmberApp(defaults, {
     // Add options here
+    fingerprint: {
+      prepend: 'https://localhost:4200/'
+    }
   });
 
   // Use `app.import` to add additional libraries to the generated
diff --git a/public/collision.png b/public/collision.png
new file mode 100644
index 0000000..e28a4a8
Binary files /dev/null and b/public/collision.png differ
```

Prepending will _not_ occur if the asset does not appear in the build as we know nothing about that asset and it could instead be any number of other things.

Let me know if there is anything I can do to help you get additional documentation into the Ember CLI website!

**Comment by mariogintili** [comment] 2016-08-25 13:44
Thanks all for the clarification - I will submit a small amendment to the ember-cli docs after I recover from a small disease I got 😄

**Comment by mariogintili** [comment] 2016-08-30 13:07
@nathanhammond my use case was failing because `svg` files are not enabled by default. I've added a note on [this PR](https://github.com/ember-cli/ember-cli.github.io/pull/93) to make sure people like me we'll know what to refer to when this fails 😄

**Comment by nathanhammond** [comment] 2016-08-30 15:27
Thanks for following this through until the end, @mariogintili!

**Comment by mariogintili** [comment] 2016-08-30 18:16
@nathanhammond you're welcome 😄 - I've also added a small note on the ember cli guides
