### ISSUE TITLE
Cannot create new scoped addon

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#7545] opened 2018-01-10 20:30 UTC
```
~ ❯❯❯ ember addon @foo/bar --yarn
ENOENT: no such file or directory, mkdir '@foo/bar'


Stack Trace and Error Report: /var/folders/_7/8wwzqn8j1wlc91y9kgm_mq580000gp/T/error.dump.8b975c71f5b2c04aa694187c5aef0c23.log
```

**Comment by Turbo87** [comment] 2018-06-19 18:56
closing as duplicate of https://github.com/ember-cli/ember-cli/issues/4372

**Closed by Turbo87** 2018-06-19 18:56 UTC
Labels: Bug
