### ISSUE TITLE
0.2.0 "ember test" hangs when finished running all the tests

### ISSUE THREAD

**Issue by williamsbdev** [ember-cli/ember-cli#3475] opened 2015-03-09 16:37 UTC
It appears that when I upgraded to 0.2.0 and run "ember test" all the tests are passing, however, it never completes the process and hangs.

versions:

ember-cli: 0.2.0
phantomjs: 1.9.13
node: 0.10.33

It appears that this line:

https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L118

is never being fired when running "ember test". It seems to be executing the promise through the ".then" but never runs the ".finally".

I get an deprecation warning about needing to upgrade to node 0.12 or io.js for future versions of ember-cli, should I pursue that option farther?

**Comment by williamsbdev** [comment] 2015-03-09 16:50
It appears that this line:

https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L118

is never being fired when running "ember test". It seems to be executing the promise through the ".then" but never runs the ".finally".

**Comment by toranb** [comment] 2015-03-09 17:03
Nice work finding this @williamsbdev 

I'm having the same issue on fedora with node 0.10.36 and npm 1.3.6

**Comment by rwjblue** [comment] 2015-03-09 21:06
Both @abuiles and I have confirmed this issue in some scenarios. Sadly, I can't dig in until tomorrow (swamped tonight)...

**Comment by williamsbdev** [comment] 2015-03-09 21:07
Thanks for all the hard work!

On Monday, March 9, 2015, Robert Jackson <notifications@github.com> wrote:

> Both @abuiles <https://github.com/abuiles> and I have confirmed this
> issue in some scenarios. Sadly, I can't dig in until tomorrow (swamped
> tonight)...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3475#issuecomment-77942540>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abuiles** [comment] 2015-03-09 22:20
@williamsbdev @toranb is any of you use .bind somewhere in your code? that was the issue for us and now all test test are passing again and completing. 

Is weird though, because it used to work before, it looks like we were not touching that part in the test.

**Comment by williamsbdev** [comment] 2015-03-09 23:26
@abuiles I am not using bind anywhere in my code. I'm still having issues.

Thanks for responding so quickly on this!

**Comment by kellysutton** [comment] 2015-03-10 00:42
Also experiencing the issue here with a slightly different setup:

phantomjs: 1.9.8
ember-cli: 0.2.0
ember: 1.10
node: 0.12.0

(Process hangs while running `ember test` while developing an add-on.)

**Comment by williamsbdev** [comment] 2015-03-10 01:03
I should also add that my problems are also with an addon.

On Monday, March 9, 2015, Kelly Sutton <notifications@github.com> wrote:

> Also experiencing the issue here with a slightly different setup:
>
> phantomjs: 1.9.8
> ember-cli: 0.2.0
> ember: 1.10
> node: 0.12.0
>
> (Process hangs while running ember test while developing an add-on.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3475#issuecomment-77975113>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abuiles** [comment] 2015-03-10 01:12
@williamsbdev can you create a public repo where I can reproduce this issue?

**Comment by rwjblue** [comment] 2015-03-10 01:18
@abuiles https://github.com/elwayman02/ember-bug-widget demonstrates the issue for me (was using it to debug another issue earlier), also an addon.  I do not think I have had this issue in a project yet...

**Comment by williamsbdev** [comment] 2015-03-10 01:27
@abuiles @rwjblue has his example but in addition, here is the one that is currently giving me trouble.

https://github.com/williamsbdev/ember-cli-focus-input

Thanks!

**Comment by jcttrll** [comment] 2015-03-10 13:31
Here's a really simple way to reproduce this in any project I've tried. Might not be the only issue, however.

1. Use your choice of `ps`, `pgrep`, `tasklist`, or whatever process explorer you like to confirm *no* `phantomjs` instances are running.
1. Run `ember test --server`.
1. Once the tests complete, do Ctrl+C.
1. Use your choice of `ps`, `pgrep`, `tasklist`, or whatever process explorer you like to confirm an orphaned `phantomjs` process is still running (failed to be cleaned up by ember-cli when terminated with Ctrl+C).
1. Run `ember test`.
1. Watch it hang after completing the tests.

Doing Ctrl+C will also fail to clean up Chrome when running tests that way; can't confirm at this time if that also causes the next `ember test` to hang, or if only PhantomJS is a culprit for that.

Could be related to #3487, since it looks like `ember test --server` has stopped doing cleanup when Ctrl+C is hit.

**Comment by toranb** [comment] 2015-03-10 13:45
Writing to confirm my issue yesterday was due to the Ctrl+C problem @jcttrll described above. Without knowing it I had a few half dead phantom processes

**Comment by stefanpenner** [comment] 2015-03-10 15:57
we have this sort of problem, because `finally` in the async scenario does not work as `finally` in the sync scenario. More scenarios will never cause the finally.

I suspect our only solution is to do this book keeping manually, and in a signal trap kill these things...

**Comment by stefanpenner** [comment] 2015-03-24 18:10
several issues on the phantomjs side have been sorted out, closing this for now.

**Closed by stefanpenner** 2015-03-24 18:10 UTC

**Comment by Syzygy24** [comment] 2016-11-18 18:42
I'm seeing this behavior again on
ember-cli: 0.2.5
node: 0.12.10
phantomjs: 2.1.1
