### ISSUE TITLE
Make help text available for individual blueprints

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-cli#3281] opened 2015-02-13 09:25 UTC
Add the possibility to run `ember help generate <blueprint-name>` which should return the `helpText` property of the blueprint model. Alternative is to use yuidoc and extract the copy and put it online on the website.

**Comment by trabus** [comment] 2015-02-18 03:53
I [started looking into this](https://github.com/ember-cli/ember-cli/issues/2553#issuecomment-69212393), but it will require some changes to where and how the help command is called from internally by cli.

**Comment by trabus** [comment] 2015-02-19 01:30
I've started work on this again and posted progress on the other issue. Because this is technically a duplicate of [#2553](https://github.com/ember-cli/ember-cli/issues/2553), I'm going to go ahead and close it. Feel free to reopen if you'd prefer to track this here.

**Closed by trabus** 2015-02-19 01:30 UTC
