### ISSUE TITLE
rootURL deploy issues

### ISSUE THREAD

**Issue by denisnazarov** [ember-cli/ember-cli#417] opened 2014-04-22 16:00 UTC
Hey,

My use case: deploy to a directory inside an S3 bucket, say `http://s3bucket.com/foo`.

With the default rootURL of `'/'`, this wont work because it will try to resolve the assets at `http://s3bucket.com/app.js`

If I change the rootURL to `/foo/`, the assets load correctly, but now Ember's router gives double rootURL and opening your app takes you to `http://s3bucket.com/foo/foo`.

I think that for the defaults, all the paths should be relative so the above will work out of the box, and users can customize `environment.js` per their needs.

https://github.com/stefanpenner/ember-cli/issues/172

**Comment by abobwhite** [comment] 2015-02-24 22:22
After looking at the above thread, I am still confused as to what the correct approach is to use location: 'auto' or location: 'history' in a production build at a non-root URL....i.e. mydomain.com/myEmberApp/

This becomes a major issue when dealing with SEO concerns. Otherwise, no big deal to just use location: 'hash'

**Comment by catbieber** [comment] 2015-02-25 02:01
Location history should work as long as you don't need to support legacy browsers like IE9. If you need a non-root URL and support for old browsers, I think hash is currently the only option.

**Comment by johnnyoshika** [comment] 2015-03-24 08:16
It seems that this is still broken?  When setting `locationType: 'auto'` and `baseUrl: '/foo/`, I would expect the following behavior:

* In browsers that support the HTML5 history, going to `/foo/#/contact` will redirect to `/foo/contact`
* In browsers that only support hash, going to `/foo/contact` will redirect to `/foo/#/contact`

But I can't seem to get this to work as expected.  The default Ember CLI simply doesn't work for hash based browsers, as going to `/foo/contact` redirects to `/#/foo/contact`, which is incorrect.  To fix this, I added routeUrl in Router:
```
var Router = Ember.Router.extend({
    location: config.locationType,
    rootURL: config.baseURL
});
```

This solved the hash issue, and going to `/foo/contact` properly redirected to  `/foo/#/contact`.  But now, this breaks HTML5 history browsers, as we now gets double `foo` as in `/foo/foo/contact`.

**Comment by catbieber** [comment] 2015-03-24 13:38
I'd been working on a fix for this, but someone did a pretty big refactor in that part of the code, so I need to redo most of it. As far as I can tell, it's still broken and the default Ember CLI doesn't work with auto location on browsers that only support hash.

Basically, when you use 'auto' location, the history implementation respects both baseUrl and rootURL, but the hash implementation only respects rootURL and is completely unaware of baseUrl.

I believe the doubled /foo in HTML5 history browsers would go away if you remove baseUrl and use only rootURL. However, then the base tag that makes your css relative to /foo disappears and those assets fail to be included. If there's some way you can get around that (e.g. with a redirect on the server side etc) that might be a short-term fix.

**Comment by johnnyoshika** [comment] 2015-03-24 14:53
@catbieber: can you please elaborate on what you mean when you say the following?
>  remove baseUrl and use only rootURL

I believe `baseUrl` is what you specify in environment.js and `rootUrl` is what you specify in Ember.Router.  For HTML5 history, it looks like we only need `baseUrl` in environment.js, but for hash to work, we also need `rootUrl` in Ember.Router, but then that results in double `/foo`.

**Comment by catbieber** [comment] 2015-03-24 15:01
@johnnyoshika I think when I played with this months ago, I originally had left `baseUrl` as just '/' and I set `rootUrl` to '/foo' -- everything worked except my static assets (css/images). HTML5 history routing for the 'auto' location looks at `rootUrl` as well as `baseUrl` when building urls, which is why you see the double `/foo` when you set both. The hash routing for 'auto' only looks at `rootUrl` which is why it fails when you set `baseUrl` to anything other than '/'.

**Comment by johnnyoshika** [comment] 2015-03-25 01:07
@catbieber - I may be doing something wrong, but setting `baseUrl` to '/' and setting `rootUrl` to `/foo` or `/foo/` didn't work.  It works for hash, but HTML 5 history browsers throws an `Uncaught #<UnrecognizedURLError>` error.

**Comment by eddflrs** [comment] 2015-04-06 22:02
@johnnyoshika , not sure if you figured this one out. But the following seems to work in IE9:

```js
// environment.js
if (environment === 'production') {
  ENV.baseURL = '/';
  ENV.rootURL = '/foo';
}
```

and in your app router

```js
//router.js
import Ember from 'ember';
import config from './config/environment';

var Router = Ember.Router.extend({
  location: config.locationType = config.locationType,
  rootURL: config.rootURL
});
```

**Comment by mike-post** [comment] 2015-07-22 22:27
Using ember 1.13.5, that workaround doesn't work. I can't speak to whether or not it ever worked, but it definitely doesn't work now.

**Comment by peec** [comment] 2015-08-16 11:56
Just came across this today (only IE9).

Ember version: 1.13.8

Reproduce:

1. Create new ember app
2. Set root URL to e.g. `ENV.baseURL = '/ember-css-transitions'` and `locationType` to `auto` (which is default).
3. Build  app for production, put the app in a webserver with the baseUrl path.  Now when you go in the browser and open `http://localhost/ember-css-transitions` ember modifies url to this: `localhost/#/ember-css-transitions/` instead of what it should be `localhost/ember-css-transitions/`

Workaround:
- `locationType: 'hash'` which is a bad workaround since all urls are now hash based, but it will work with IE9 also.

**Closed** 2016-04-27 13:03 UTC
Labels: Documentation
