### ISSUE TITLE
Run generators without creating tests

### ISSUE THREAD

**Issue by mitchlloyd** [ember-cli/ember-cli#4310] opened 2015-06-18 21:03 UTC
I couldn't find a way to use generators without creating tests. Would anyone be opposed to this option?

**Comment by trabus** [comment] 2015-06-18 21:05
I don't have a problem with having that option.

**Comment by stefanpenner** [comment] 2015-06-18 21:07
seems like a low priority though. Why wouldn't you write tests?

Going to close this as it is not a bug.

**Comment by mitchlloyd** [comment] 2015-06-18 21:42
@stefanpenner That sounds like a [loaded question](https://en.wikipedia.org/wiki/Loaded_question) to me ;)

I'm hope I'm not alone thinking that Ember CLIs pattern of one unit test to one generated file is often not ideal. Some modules are better tested with an integration tests (e.g. adapters and serializers), some top-level components get the right coverage from acceptance tests, and some of the generated unit tests just aren't that useful (although they're getting better all the time!).

**Comment by Jinshui** [comment] 2016-04-26 02:19
Totally agree mitchlloyd, not all program needs tests, ember-cli should provide an option to disable generating tests code.

**Comment by cjtafoya** [comment] 2016-06-15 15:30
Not sure why this was totally shut down without further discussion given this would be a useful feature

**Comment by Turbo87** [comment] 2016-06-15 15:42
I think a `--skip-test` option would be reasonably easy to implement and might make sense in some scenarios as long as we don't make it the default.

**Comment by nathanhammond** [comment] 2016-06-15 16:14
@mitchlloyd @cjtafoya We try and generate an appropriate test type per generated item; integration for components for example. Part of the strength of this is that people are encouraged to follow patterns, and that people new to your project are able to immediately join in. It's imperfect but it promotes making good decisions.

> not all program needs tests - @Jinshui
I disagree with this assertion having just spent a lot of time dealing with applications without tests. This is in contrast to @mitchlloyd's more-nuanced followup describing his goals of using different types of tests per his needs. That is something I can support, but I suspect that even in that scenario there would be value in say unit-testing some portion of code in addition to (integration|acceptance) tests.

---

I'm pretty adamantly opposed to making it easy to do something like `--skip-tests`. I want the user experience of deleting a test file to feel bad enough to encourage positive behavior. Call it a "dark pattern" or something else; I don't mind having a suboptimal workflow in this one case. Since the generated test passes by default it's effectively a no-op placeholder for when you *do* want to go in and test that code.

Because I'm disagreeing with @Turbo87 I'm moving this to a discussion. Will provide update later.

**Comment by topaxi** [comment] 2016-06-15 16:49
I have several "toy" ember apps where I don't write tests, I just leave them empty. The generated tests pass by default so they don't really disturb me in any way.

**Comment by nucleartide** [comment] 2016-06-24 16:56
I'd be in favor of a `--skip-test` option, specifically for the case when it's early in the dev process and you're just prototyping component ideas, instead of writing production quality code. For example, it's often the case that you end up changing a component's template, which will break the default generated component test:

```
test('it renders', function() {
  this.render(hbs`{{some-component}}`)
  assert.equal(this.$().text().trim(), '')

  this.render(hbs`
    {{#some-component}}
      template block text
    {{/some-component}} 
  `)
  assert.equal(this.$().text().trim(), 'template block text')
})
```

All of a sudden you have a bunch of failing tests that you didn't want in the first place.

It might be just me, since I don't do TDD and instead add tests when an app's design is relatively stable. But this is something worth considering.

**Comment by stefanpenner** [comment] 2016-06-24 17:09
this should be moved over to the RFC repo, as this does not appear to be an issue. But an interesting feature to explore and fully flesh out.

**Closed by stefanpenner** 2016-06-24 17:09 UTC
Labels: Feature, Needs Team Discussion

**Comment by maxkwallace** [comment] 2016-07-19 17:42
As a workaround, if you want to prevent automatic test generation, you can override e.g. the default `component-test` blueprint, following the instructions at https://ember-cli.com/extending/. Unfortunately, this also makes it impossible (AFAIK) for anyone to generate that kind of test without first deleting your override blueprint. It might also be possible (quite a hack-- I haven't tried it) to add something to the `afterInstall` hook of your component generator to delete the auto-generated test files.

My $0.02: I'd like to see an RFC opened, but I wouldn't want this issue to devolve into a religious war over TDD. I don't think there can be any debate over whether testing makes sense (and should be encouraged) as good software engineering practice, but that's not the same thing as autogenerating all these Component tests.

I work at a small startup. We have good tests for a few critical Components, but we don't test 95% of the production Components we write, simply because the time saved from testing doesn't justify the cost of writing and maintaining those tests. We don't get any benefit from it. I have nothing against TDD. But like almost any engineer practice, it can't be universally applied. There are circumstances where it's legitimate to intentionally not write automated tests for some portion of your app.

**Comment by mitchlloyd** [comment] 2016-07-19 17:56
@maxkwallace just to echo the need to separate this functionality from testing practices: I use an outside-in TDD approach and these generated tests do not fit my workflow. See earlier comments about using integration tests for adapters, serializers and models. Also when I work on large code bases with many developers, high levels of test coverage is critical.

I'm not planning to open an RFC for this right now. At this point the projects that I work on have so much customization (using ember-shims and application-specific testing setups) that the default generators don't provide much of a starting point. I just need to bite the bullet and make custom generators on my projects.

**Comment by enterpub** [comment] 2017-01-04 18:33
@stefanpenner 
>seems like a low priority though. Why wouldn't you write tests?

For example, our team does not write client-side tests for now. In future may be we will, but now we do not need that. I'm sure I'm not along with that.
We've added "tests" folder to ignore, but there is a hidden issue: for example a developer cloned the repository and is not having "tests" folder and tests theirself. Then he runs command "ember generate component some-name". The command adds a new test automatically. But when the developer runs "ember build" the build breaks, because not all tests found (actually there is only one test for "some-name" component). The workaround is to delete the "tests" folder and run "ember build" again.
But I've spent much time while understood that! Please, do not scoff at such developers. I expect the instrument I use is flexible

**Comment by samselikoff** [comment] 2017-04-14 14:49
>  I use an outside-in TDD approach and these generated tests do not fit my workflow

I agree with this, I start with the page-level and make components to break up the structure of my pages. I see these "structural components" as implementation details of my pages, and I feel strong about the ability to rename/move/shift these components around as my pages develop.

If I have a `<image-list />` component that I use for displaying images, well I'm not going to write an integration test, mock out services, provide dummy data just to prove that image-list works... I'm going to write an acceptance test to verify the page works altogether. Only when a component does more work & has many states will I drop into an integration test.

Same for models, especially at the beginning of a project models change and are renamed, most of my models will not have unit tests since they don't contain much if any logic.

For a newbie starting with Ember, if they were writing their first TodoMVC app and they just built the ability to add a todo, I'd strongly prefer to see 1 acceptance test that verifies that behavior, rather than integration tests for each component (however they happen to split them up).

**Comment by ibraheem4** [comment] 2017-07-08 16:22
@stefanpenner @nathanhammond 

I think it's unfortunate that this framework forces me to create test files that in some cases I know I don't want or need.  Developers using frameworks such as this one have come to expect the functionality of disabling unnecessary scaffolding via `--no-test-framework`, `--skip-test-unit`, `-T`.  Yes.. ember-cli is pretty great already and I'm sure you already know this, but am adding one other vote towards implementing this feature.

**Comment by bencates** [comment] 2017-07-18 22:28
+1
