### ISSUE TITLE
./ path error introduced in 0.1.8

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#3190] opened 2015-02-03 16:33 UTC
example below this worked up to 0.1.7

```import Config from './../../config/environment';```

now i get this error on anything > 0.1.7 in the chrome console and the app is all white

```Uncaught Error: Could not find module inbox-dashboard/initializers/../config/environment```

changing this to 

```import Config from '../../config/environment';```

fixes the problem

so basically ./ got removed in 0.1.8, can't say if this was intentional or not, the odd thing is you can upgrade existing apps fine to 0.1.8 or greater as long as you don't remove tmp or dist but say if you remove those or checkout a fresh repo in an app with these you will run into these problems

**Comment by stefanpenner** [comment] 2015-02-03 18:13
> import Config from './../../config/environment';

this is wrong

**Comment by jcope2013** [comment] 2015-02-03 18:22
okay that clears it up, it was just a painful thing to fix across 100's of files but it's good now

**Comment by jcope2013** [comment] 2015-02-03 18:25
Can you elaborate more? This happened with mixins all over the app also, that was one isolated example but it seems ./ stopped working in 0.1.8 and was working fine in 0.1.7, was just wondering if this is intentional?

**Comment by stefanpenner** [comment] 2015-02-03 18:26
`import foo from './foo'` works correctly
`import foo from './../../foo'` seem pointless as it means `import foo from '../../foo'`

**Comment by jcope2013** [comment] 2015-02-03 18:32
@stefanpenner thanks

**Comment by stefanpenner** [comment] 2015-02-03 18:47
If many others report this, we can add a deprecation to loader.js  Lets see how it goes.

Sorry it hit you hard.

**Comment by Kuzirashi** [comment] 2015-02-04 00:32
Wow I tried to update ember-coffeescript-cli but now I'm running into this problem... Tried to reinstall Ember CLI 3 times but I still can't get my app to work again.

Previously I had in my router.coffee:
~~~~
`import config from './config/environment.js'`
~~~~
And everything worked. Now, I get in dev tools console:
> Uncaught Error: Could not find module my-app-name/routes/../config/environment
So I tried to change import statement to:
~~~~
`import config from '../config/environment.js'`
~~~~
But now I get:
> Uncaught Error: Could not find module config/environment
Changing that to:
~~~~
`import config from 'my-app-name/config/environment.js'`
~~~~
Solves problem in router... But then another errors are thrown from whole application, controllers, models, routes... It's going to be time consuming to refactor all :( And I had to figure it out by using chrome debugger. What has changed recently that `./` no longer works?

**Comment by jcope2013** [comment] 2015-02-04 00:40
@Kuzirashi glad to see we were not the only's one bit by this, it seemed for us just removing ./ fixed everything, hopefully most of them are easy, we had it happen completely throughout prolly 100 files between 3 apps

**Comment by Kuzirashi** [comment] 2015-02-04 00:50
@jcope2013 I managed to refactor it. But I'm left out with `import config from 'my-app-name/config/environment'` instead of relative paths. However, using relative paths for mixins etc. works. Only config has to be referenced this way. Maybe it's my fault with specyfing paths.

**Comment by stefanpenner** [comment] 2015-02-04 01:49
relative paths are tested: https://github.com/ember-cli/loader.js/blob/master/tests/all.js#L112-L145
please provide a failing example to that project, and we can fix it

**Comment by rwjblue** [comment] 2015-02-04 12:49
I believe that the issue is with Esperanto's new `abosolutePaths` option (which broccoli-es6modules uses as of https://github.com/ember-cli/broccoli-es6modules/pull/10 which was released in broccoli-es6modules@0.4.2).

I opened https://github.com/esperantojs/esperanto/issues/97 to track this issue in Esperanto.

**Comment by rwjblue** [comment] 2015-02-04 12:54
Fixed by Rich in https://github.com/esperantojs/esperanto/pull/98, and will be released (likely in esperanto@0.6.8) shortly.

**Comment by rwjblue** [comment] 2015-02-04 12:55
> import Config from './../../config/environment';

Even though this is a bug to be fixed, I still find this weird and would definitely suggest the following (which does work currently) instead:

```javascript
import Config from '../../config/environment';
```

**Comment by stefanpenner** [comment] 2015-02-04 13:15
Ah that's right this part of the loader is now mostly accomplished by the transpiler

**Comment by rwjblue** [comment] 2015-02-04 13:35
This should be fixed now, broccoli-es6modules@0.4.3 is published (https://github.com/ember-cli/ember-cli/issues/3190 updates the minimum version in our `package.json`) which includes esperanto@0.6.8.

You can get the update now however with `rm -rf node_modules && npm cache clear && npm install`.

**Closed by rwjblue** 2015-02-04 13:35 UTC

**Comment by stefanpenner** [comment] 2015-02-04 13:57
im dubious if `./.../../` shouldn't just error..

**Comment by rwjblue** [comment] 2015-02-04 16:45
@stefanpenner - IMHO, `./../` works properly in most shells, so it should work here.  I think its kinda nuts, but it should work.
