### ISSUE TITLE
Tests in Browser broken with changed baseURL

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4716] opened 2015-08-20 16:44 UTC
I've changed `baseURL` in environment.js to `/client/` to be able to get an express middleware working at some other endpoint (see https://github.com/ember-cli/ember-cli/issues/4554). 

Anyway, I've changed `baseURL`. Unfortunately this breaks test in browser (at both `http://localhost:4200/tests` (not found) and `http://localhost:4200/client/tests` (empty page)). I can reproduce this with a newly generated app or addon.

**Comment by jnfingerle** [comment] 2015-08-21 09:58
On further investigation:
 * The correct URL should be `http://localhost:4200/client/tests`.
 * The changed `baseURL` isn't properly reflected in the generated base tag.
 * Adding `<base href="/client/"/>` *before* `{{content-for 'head'}}` is currently a work around (at least in Chrome; I don't know how other browsers behave with multiple base declarations).

**Comment by laureanoarcanio** [comment] 2016-03-16 15:43
Hi, thanks for the workaround. Any ideas on how this can be workaround when running from phantomjs ?

**Comment by Turbo87** [comment] 2016-04-13 14:28
duplicate of #4507

**Closed by Turbo87** 2016-04-13 14:28 UTC
