### ISSUE TITLE
Ember server error with jquery 1.12.0

### ISSUE THREAD

**Issue by govidat** [ember-cli/ember-cli#5365] opened 2016-01-16 03:21 UTC
In ember-cli version 1.13.13
Bower.json reads as "jquery": "^1.11.3",
By default, jquery 1.12.0 gets installed. 

However, ember server throws an error as below:
Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

I made a change in Bower.json to "jquery": "^2.1.0" and installed it. 
Now the error has gone and ember server is functioning properly.

There may be an issue in reading the version range for jquery.

**Comment by szines** [comment] 2016-01-16 03:52
@govidat Yep, there was this problem, but it is already fixed and new versions are released. You can update your ember-cli version to `1.13.14` or `2.2.0-beta.6`. These new versions of ember-cli will generate proper project structure.

v1.13.14
```
npm install -g ember-cli
```
v2.2.0-beta.6
```
npm install -g ember-cli@2.2.0-beta.6
```

**Comment by kellyselden** [comment] 2016-01-16 14:25
Duplicate of #5316. Please search existing issues before filing.

**Closed by kellyselden** 2016-01-16 14:25 UTC
