### ISSUE TITLE
Missing sourcemaps after upgrading to 2.14.0

### ISSUE THREAD

**Issue by kybishop** [ember-cli/ember-cli#7212] opened 2017-07-08 18:02 UTC
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.0
http_parser: 2.7.0
node: 7.2.0
v8: 5.4.500.43
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: darwin x64
3.10.9
0.27.5
```

After upgrading to 2.14.0 from 2.13:

```zsh
➜  ember-popper git:(bump-deps) ember s
Livereload server on http://localhost:49153
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open '/Users/kybishop/github/ember/ember-popper/tmp/source_map_concat-input_base_path-PDWeZmU9.tmp/vendor/ember/ember.debug.map'
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open '/Users/kybishop/github/ember/ember-popper/tmp/source_map_concat-input_base_path-WYXOSZg9.tmp/vendor/ember/ember-testing.map'
```

**Comment by hinti** [comment] 2017-07-09 22:54
I get the same warnings.

**Comment by Samsinite** [comment] 2017-07-12 18:13
Ditto, super painful to debug now.

**Comment by siriniok** [comment] 2017-07-15 22:48
Using Ember CLI 2.14.0 with ember-cli-babeli. Same issue.

**Comment by siriniok** [comment] 2017-07-15 22:55
Related issue in the ember's tracker.
https://github.com/emberjs/ember.js/issues/15464

**Comment by simonihmig** [comment] 2017-07-15 22:59
Duplicate of https://github.com/emberjs/ember.js/issues/15464. I think the issue is with the ember-source (@2.14) addon (see my comment https://github.com/emberjs/ember.js/issues/15464#issue-240981213). I can successfully run ember-cli 2.14 and ember 2.13 without any sourcemap problems. So I think this can be closed here.

**Comment by hinti** [comment] 2017-07-18 09:59
**ember-source** 2.14 now includes source map comments. 2.13 didn't.

**fast-sourcemap-concat/lib/source-map.js:addFileSource** extracts the url from the source map comment:

``` 
if (srcURL.existsIn(source)) {
    url = srcURL.getFrom(source); // url is set in 2.14, undefined in 2.13
    source = srcURL.removeFrom(source);
}
```
and later invokes **fast-sourcemap-concat/lib/source-map.js:_resolveSourcemap** (which throws an error). 

Remove the comment `//# sourceMappingURL=ember.debug.map` from **ember-source/dist/ember.debug.js** and `//# sourceMappingURL=ember-testing.map` from **ember-source/dist/ember-testing.js** and the warnings are gone, because **addFileSource** now uses a different method to generate the map.

Hope this helps.

**Comment by Turbo87** [comment] 2017-07-23 18:45
@simonihmig is correct, this is a duplicate of emberjs/ember.js#15464

**Closed by Turbo87** 2017-07-23 18:45 UTC
