### ISSUE TITLE
Build broken because generated jshint-tests overwrite my tests

### ISSUE THREAD

**Issue by tschoartschi** [ember-cli/ember-cli#4725] opened 2015-08-21 12:39 UTC
Hi!

I'm not really sure when the problem arose and I'm also not sure if it is related to Ember-CLI but maybe I find help here.

When I start my app with ```ember serve```everything works fine. If I browse the files which are generated in Chrome Developer Tools then everything looks fine. There is a folder ```assets``` which contains a folder of my app and there are all subfolders. In the ```tests``` folders, to every test file there is a file with a ```.jshint-``` suffix.
Then when I change something in my app and save the changed file, the app is rebuilt. After that I get the exception ```Uncaught ReferenceError: describe is not defined``` in my browser console this happens because there are no ```.jshint-``` suffixed files. All my test files are overwritten by the files which which should be ```.jshint-``` prefixed. 
Because I use ember-data-factory-guy I can not start my app anymore. Ember-data-factory-guy requests every file which has not a special suffix like ```.jshint-```

I hope someone can help me fix this issue. Otherwise I can not work with my current project.

This is what I have in my package.json
```json
{
        "broccoli-asset-rev": "2.1.0",
        "broccoli-debug": "0.1.1",
        "broccoli-file-remover": "0.3.1",
        "broccoli-manifest": "0.0.6",
        "broccoli-merge-trees": "0.2.2",
        "broccoli-static-compiler": "0.2.1",
        "broccoli-string-replace": "0.0.2",
        "ember-cli": "1.13.8",
        "ember-cli-app-version": "0.5.0",
        "ember-cli-autoprefixer": "0.4.1",
        "ember-cli-babel": "5.1.3",
        "ember-cli-content-security-policy": "0.4.0",
        "ember-cli-dependency-checker": "1.0.1",
        "ember-cli-eslint": "1.0.0",
        "ember-cli-htmlbars": "0.7.9",
        "ember-cli-htmlbars-inline-precompile": "0.2.0",
        "ember-cli-ic-ajax": "0.2.1",
        "ember-cli-inject-live-reload": "1.3.1",
        "ember-cli-mocha": "0.9.2",
        "ember-cli-nouislider": "0.6.0",
        "ember-cli-page-object": "0.7.0",
        "ember-cli-sass": "4.0.1",
        "ember-cli-selectize": "0.3.9",
        "ember-cli-simple-auth": "0.8.0",
        "ember-cli-simple-auth-testing": "0.8.0",
        "ember-cli-release": "0.2.3",
        "ember-cli-uglify": "1.2.0",
        "ember-data": "1.13.8",
        "ember-data-factory-guy": "1.13.7",
        "ember-export-application-global": "1.0.3",
        "ember-i18n": "3.1.1",
        "eslint": "0.24.1",
        "eslint-plugin-ember": "1.0.1",
        "express-ls-routes": "1.0.2",
        "fs-extra": "0.22.1",
        "gulp": "3.9.0",
        "gulp-eslint": "0.15.0",
        "gulp-jshint": "1.11.2",
        "gulp-load-plugins": "1.0.0-rc.1",
        "gulp-rename": "1.2.2",
        "gulp-replace": "0.5.3",
        "gulp-shell": "0.4.2",
        "gulp-sourcemaps": "1.5.2",
        "gulp-uglify": "1.2.0",
        "js-string-escape": "1.0.0",
        "jsdoc": "3.3.2",
        "jshint-stylish": "2.0.1"
}
```
This is what I have in my bower.json
```json
{
    "ember": "1.13.8",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli/ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.8",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "0.1.15",
    "jquery": "2.1.4",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "1.18.0",
    "griddler": "0.0.9",
    "parsleyjs": "2.0.7",
    "JavaScript-MD5": "1.1.0",
    "pickadate": "3.5.5",
    "mediator-js": "0.9.9",
    "jquery-ui": "1.11.4",
    "swiper": "3.0.6",
    "roomle-editor": "git@source.roomle.local:Web/editordist.git#3.2.20",
    "roomle-webclient-assets": "git@source.roomle.local:Web/Assets.git",
    "ember-uploader": "0.3.6",
    "ember-i18n": "3.1.1",
    "modernizr": "2.8.3",
    "ember-simple-auth": "0.8.0",
    "selectize": "0.12.1",
    "ember-mocha": "~0.8.0",
    "colpick": "2.0.2",
    "jquery-mockjax": "2.0.1",
    "nouislider": "8.0.2"
}
```

**Comment by stefanpenner** [comment] 2015-08-21 13:24
Seems like a dupe. Will track this in the other issue

**Comment by stefanpenner** [comment] 2015-08-21 13:25
Appears to be Dupe of https://github.com/ember-cli/ember-cli/issues/4723. Will investigate there

**Closed by stefanpenner** 2015-08-21 13:24 UTC

**Comment by tschoartschi** [comment] 2015-08-21 13:28
@stefanpenner thanks for your quick response. Hopefully it's just a Dupe of #4723 because @amk221 reports that he misses hbs files and not the .jshint files. But I'm sure you will find the problem ;-) thanks a lot for your effort

**Comment by stefanpenner** [comment] 2015-08-21 13:32
Once the problem is known I'll circle back and confirm.

Issue appeared around the same time, I suspect I know what it is.

**Comment by stefanpenner** [comment] 2015-08-21 14:19
i'm pretty confident the route problem is the same – please see: https://github.com/ember-cli/ember-cli/issues/4723#issuecomment-133438609

**Comment by tschoartschi** [comment] 2015-08-21 21:02
The solution for #4723 also solved the problem for me
