### ISSUE TITLE
No User diff 2.18.0 to 2.18.1

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli#7593] opened 2018-02-01 08:24 UTC
Clicking on the User diff for 2.18.1 says there is nothing to compare. It appears that there is no newly generated 2.18.1 app published.

**Comment by twokul** [comment] 2018-02-01 19:06
duplicate of https://github.com/ember-cli/ember-addon-output/issues/5

**Closed by twokul** 2018-02-01 19:06 UTC

**Comment by kellyselden** [comment] 2018-02-02 00:35
fixed
