### ISSUE TITLE
Encountering error with globPattern when installing addons with a blueprint

### ISSUE THREAD

**Issue by johnotander** [ember-cli/ember-cli#3142] opened 2015-01-28 23:00 UTC
When installing an ember addon with `ember install:addon addon-name`, I encounter the following error

```
The globPattern "undefined" did not match any files, so no file updates will be made.
```

Here's an example of the error in action:

```
ember install:addon ember-cli-gravatar          
version: 0.1.11
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/blueimp/JavaScript-MD5.git#1.1.0
Installed browser packages via Bower.
Installed addon package.
```

It seems to be occurring when the generator is run. This is also reproduced with `npm i --save-dev addon-name && ember g addon-name`.

My environment:

```
ember -v
version: 0.1.11
node: 0.10.35
npm: 2.1.8
```

I've gone through installing a collection of addons to see which result in an error, and which don't. It appears that addons that have a blueprint for adding a bower dependency are the ones raising this error. What I'm not sure about is whether this is something that the addons are missing, or if it is a problem with the ember-cli. Whichever the case is, we can probably narrow it down and provide a more descriptive message. Anyone have any idea what's going on here?

I'll keep digging. Thanks for your time.

**Comment by chadhietala** [comment] 2015-01-29 23:11
Looking into this. Trying to find the root cause to avoid unnecessary branching in the code.

**Comment by johnotander** [comment] 2015-01-29 23:14
Great, thanks!

**Comment by trabus** [comment] 2015-02-10 16:48
The fix to prevent the warning was merged, thanks @chadhietala.

The ember-cli-gravatar addon blueprint doesn't install any files, it just adds a bower package. So that would explain why the addon install runs the blueprint without processing any files (the reason the warning was being thrown).

Mystery solved, this issue can be closed!

**Closed by trabus** 2015-02-10 16:48 UTC
Labels: addons
