### ISSUE TITLE
Sourcemap generation is broken for vendor.js in production

### ISSUE THREAD

**Issue by MiguelMadero** [ember-cli/ember-cli#6781] opened 2017-02-16 23:57 UTC
## Repro steps

**Summary:** To repro: create a new app, enable sourcemaps for prod, and build</summary>
  
1. Run the following commands: 
```
03:44 PM $ ember new test-sourcemap-gen-2111
DEPRECATION: Node v4.4.3 is no longer supported by Ember CLI. We recommend that you use the most-recent "Active LTS" version of Node.js.
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Successfully initialized git.
Installed packages for tooling via npm.
Installed browser packages via Bower.

~/code-tmp 
03:46 PM $ cd test-sourcemap-gen-2111/

~/code-tmp/test-sourcemap-gen-2111 [master|✔] 
03:46 PM $ vim ember-cli-build.js 
03:46 PM $ git diff
diff --git a/ember-cli-build.js b/ember-cli-build.js
index 2537ce2..523df94 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -4,7 +4,11 @@ var EmberApp = require('ember-cli/lib/broccoli/ember-app');
 
 module.exports = function(defaults) {
   var app = new EmberApp(defaults, {
-    // Add options here
+           sourcemaps: {
+      enabled: true,
+      extensions: ['js'],
+    },
+
   });
 
   // Use `app.import` to add additional libraries to the generated

~/code-tmp/test-sourcemap-gen-2111 [master|✚ 1] 
03:46 PM $ ember s --prod & open http://localhost:4200/
DEPRECATION: Node v4.4.3 is no longer supported by Ember CLI. We recommend that you use the most-recent "Active LTS" version of Node.js.
Livereload server on http://localhost:49153
Serving on http://localhost:4200/

Build successful - 12832ms.



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
UglifyWriter (1)                              | 6341ms              
Babel (8)                                     | 5871ms (733 ms)     
---
```

2. In the debugger, open the devtools and try to navigate to ember.prod or loader.js. Instead of opening the correct one, ember.prod opens the shims and loader.js opens jquery. When an exception occurs the stacktrace is all wrong. Reporting errors to sentry are broken for the same reason: 

![image](https://cloud.githubusercontent.com/assets/47388/23046797/9e30876c-f460-11e6-9bf9-f6c33d1dc981.png)

</details>

I tried this with 2.10 (ember coming from bower) and 2.11 (ember coming form npm) and I had the same problem. 

## Additional information

This may be an issue with asset-rev or uglify. I'll look into it, but since this is how ember ships by default, I wanted to raise an issue here first while I get more info. 

## Context

Output from `ember version --verbose && npm --version`:
```
 ember version --verbose && npm --version
DEPRECATION: Node v4.4.3 is no longer supported by Ember CLI. We recommend that you use the most-recent "Active LTS" version of Node.js.
ember-cli: 2.11.1
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: darwin x64

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/mmadero/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.8 /Users/mmadero/code-tmp/test-sourcemap-gen-2111/node_modules/npm
```

**Comment by MiguelMadero** [comment] 2017-02-17 01:31
Quick update: Disabling fingerprints didn't fix it.

**Comment by Turbo87** [comment] 2017-02-17 12:22
@MiguelMadero I've been meaning to look into this for quite a while. 

The sentry source map handling code is available at https://github.com/mitsuhiko/rust-sourcemap/ if that helps

**Comment by MiguelMadero** [comment] 2017-02-17 18:10
Thanks. I looked into that to repro. But, just to be clear, this is an
issue in Chrome as well and likely in other browsers.

**Comment by msalahz** [comment] 2017-02-22 15:57
I'm getting the same issue , any updates about that ?

**Comment by MiguelMadero** [comment] 2017-02-22 16:02
Not from me. I disabled fingerprinting and the error is still there, so it
is somewhere else. I had to switch gears, but I plan to investigate further
later this week

**Comment by msalahz** [comment] 2017-02-22 16:15
@MiguelMadero , Downgrade Ember-CLI from  2.11.1 to 2.11.0 fixed my issue

**Comment by Turbo87** [comment] 2017-02-22 16:24
> Downgrade Ember-CLI from 2.11.1 to 2.11.0 fixed my issue

I'm quite surprised by that as I've had that issue for a long time independent of the CLI version 🤔

**Comment by MiguelMadero** [comment] 2017-02-22 16:40
Thanks. That is good insight. I will follow that thread.

**Comment by akatov** [comment] 2017-03-01 14:06
@msalahz My sourcemaps are still broken with ember-cli 2.11.0 (never even tried v2.11.1). Are you sure you didn't change something else as well to make it work?

**Comment by jessepollak** [comment] 2017-03-10 17:39
I'm struggling with the same issue and believe it is the source of [this issue](https://github.com/damiencaselli/ember-cli-sentry/issues/73) as well.

**Comment by Turbo87** [comment] 2017-03-23 12:40
@MiguelMadero I'm currently trying to track this down. If I remove `ember-cli-uglify` from `package.json` I can't reproduce the issue anymore, so this might be an issue in uglify.

**Comment by MiguelMadero** [comment] 2017-03-23 13:58
Ill check again

**Comment by Turbo87** [comment] 2017-04-01 19:48
fixed by https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/41

**Closed by Turbo87** 2017-04-01 19:48 UTC
Labels: Bug, Needs Dependency Fix, On-going investigation
