### ISSUE TITLE
The Broccoli Plugin: [Funnel: Funnel (config)] failed with:

### ISSUE THREAD

**Issue by orgilnm11** [ember-cli/ember-cli#5818] opened 2016-04-19 17:42 UTC
after installin my app ember new myapp1. and when i try to start server this error shows.
---

ember-cli: 2.4.3
node: 4.4.3
os: win32 x64

```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [Funnel: Funnel (config)] failed with:
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at symlinkWindows (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:99:53)
    at Function.symlinkOrCopySync [as sync] (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:53:5)
    at Funnel._copy (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:398:19)
    at Funnel.build (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:167:12)
    at C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:44:10)
    at EmberApp._configTree (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\broccoli\ember-app.js:977:28)
    at EmberApp.index (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\broccoli\ember-app.js:623:40)
    at EmberApp.toArray (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\broccoli\ember-app.js:1563:10)
    at EmberApp.toTree (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\broccoli\ember-app.js:1586:30)
    at module.exports (C:\Users\owner.owner\test4\ember-cli-build.js:23:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\owner.owner\test4\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\owner.owner\test4\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)


```

**Comment by orgilnm11** [comment] 2016-04-21 14:24
what does mean ''needs reproduction', what do i have to do?

**Comment by nathanhammond** [comment] 2016-04-21 17:50
@orgilnm11 We've not seen a report like this before and as you're the only person encountering it, it seems likely that it's something about your environment in particular, not necessarily Ember CLI (I say that with more confidence having seen the other report you filed). Also working against you is that none of us actively develop on Windows, so we're not really able to dive in and see it failing consistently (a reproduction). We'll need you to do a fair amount of research to help us identify if this is actually an Ember CLI issue.

We test exactly this on our AppVeyor Windows CI tests:
```
ember new myapp1
cd myapp1
ember server
```

Can you try reinstalling literally everything (Node, NPM, ember-cli) and let us know if that helps? Also check the permissions of your user account. My suspicion is that this is a transient issue from your environment, so I'm going to close this issue. If the problem still exists for you after reinstallation please feel encouraged to reopen!

**Closed by nathanhammond** 2016-04-21 17:50 UTC
Labels: Needs Reproduction, Windows

**Comment by jgrosso** [comment] 2016-04-21 21:35
I'm having the same problem (Windows 10). Was Ember updated recently or something?

**Comment by nathanhammond** [comment] 2016-04-21 22:28
@jgrosso Thanks for identifying a workaround! This may be related to https://github.com/broccolijs/node-symlink-or-copy/issues/20

**Comment by sagar1992** [comment] 2016-04-22 17:00
This issue will be fixed by the pull request https://github.com/broccolijs/node-symlink-or-copy/pull/17. It was created because of the srcPath typo.

**Comment by tracyhyq** [comment] 2016-07-06 07:09
I have the same problem, I have reinstalled node, ember-cli, npm, node-symlink-or-copy, but the problem is not resolved. 
Now I'm just out of ideas, can someone save me ?

**Comment by nathanhammond** [comment] 2016-07-06 13:34
@tracyhyq See my comment on your other issue. Let me know what version you're running, and make sure you reinstall the full set again *without* admin privileges. (If you're on Windows I'm going to have a much more difficult time helping you, unfortunately.)

**Comment by tracyhyq** [comment] 2016-07-07 01:42
@nathanhammond Thank you very much, I resloved the problem, Change another computer.  It's strange.
