### ISSUE TITLE
Component in /addon directory is still available in the app

### ISSUE THREAD

**Issue by ctusch** [ember-cli/ember-cli#6373] opened 2016-10-21 13:40 UTC
I have an in-repo-addon. When I put a component in the /addon directory with no export in the /app directory the component is still added to the registry and can be accessed in the parent app. This is not true for services added in the /addon directory.

**Comment by nathanhammond** [comment] 2016-10-21 22:21
Cannot reproduce. Let me know if I've misunderstood you.

I'm closing this issue as likely not a bug but if you can create a simplistic reproduction we're happy to reopen. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

---

```diff
diff --git a/app/templates/application.hbs b/app/templates/application.hbs
new file mode 100644
index 0000000..34e1cd6
--- /dev/null
+++ b/app/templates/application.hbs
@@ -0,0 +1 @@
+Something component? {{some-thing}}
\ No newline at end of file
diff --git a/lib/.jshintrc b/lib/.jshintrc
new file mode 100644
index 0000000..839c191
--- /dev/null
+++ b/lib/.jshintrc
@@ -0,0 +1,4 @@
+{
+  "node": true,
+  "browser": false
+}
diff --git a/lib/foo/addon/components/some-thing.js b/lib/foo/addon/components/some-thing.js
new file mode 100644
index 0000000..aa87ed9
--- /dev/null
+++ b/lib/foo/addon/components/some-thing.js
@@ -0,0 +1,6 @@
+import Ember from 'ember';
+import layout from '../templates/components/some-thing';
+
+export default Ember.Component.extend({
+  layout
+});
diff --git a/lib/foo/addon/templates/components/some-thing.hbs b/lib/foo/addon/templates/components/some-thing.hbs
new file mode 100644
index 0000000..e47f37a
--- /dev/null
+++ b/lib/foo/addon/templates/components/some-thing.hbs
@@ -0,0 +1,2 @@
+SOMETHING
+asdfasdf
\ No newline at end of file
diff --git a/lib/foo/app/components/some-thing.js b/lib/foo/app/components/some-thing.js
new file mode 100644
index 0000000..a7ef11c
--- /dev/null
+++ b/lib/foo/app/components/some-thing.js
@@ -0,0 +1 @@
+export { default } from 'foo/components/some-thing';
\ No newline at end of file
diff --git a/lib/foo/index.js b/lib/foo/index.js
new file mode 100644
index 0000000..612322a
--- /dev/null
+++ b/lib/foo/index.js
@@ -0,0 +1,8 @@
+/*jshint node:true*/
+module.exports = {
+  name: 'foo',
+
+  isDevelopingAddon: function() {
+    return true;
+  }
+};
diff --git a/lib/foo/package.json b/lib/foo/package.json
new file mode 100644
index 0000000..81c0f8f
--- /dev/null
+++ b/lib/foo/package.json
@@ -0,0 +1,9 @@
+{
+  "name": "foo",
+  "keywords": [
+    "ember-addon"
+  ],
+  "dependencies": {
+    "ember-cli-htmlbars": "*"
+  }
+}
diff --git a/package.json b/package.json
index de6c11a..61929b2 100644
--- a/package.json
+++ b/package.json
@@ -40,5 +40,10 @@
   "engines": {
     "node": ">= 0.12.0"
   },
-  "private": true
+  "private": true,
+  "ember-addon": {
+    "paths": [
+      "lib/foo"
+    ]
+  }
 }
```

**Closed by nathanhammond** 2016-10-21 22:21 UTC

**Comment by ctusch** [comment] 2016-10-24 12:14
I'm sorry. It seems like it was a temporary issue. I can't reproduce it anymore. Sometimes the build process seems to have trouble rebuilding in-repo addons but that would be another issue. Thank you!
