### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#2991] opened 2015-01-14 12:29 UTC
We should test compatibility with io.js and set up ci to test it as well :)

**Comment by rwjblue** [comment] 2015-01-14 12:33
Agreed.

**Comment by stefanpenner** [comment] 2015-01-14 13:15
:100:

**Comment by stefanpenner** [comment] 2015-01-14 13:25
first blocking issue:

```
± % iojs $(which ember) s                                                                     !10044
version: 0.1.7
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:136:17
    at setToStringTag (/Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:88:13)
    at /Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:608:3
    at /Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:612:2
    at Object.<anonymous> (/Users/stefan/src/personal-projects/dispatch/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:2094:2)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```

Basically Symbols don't coerce to strings on their own, so code that previously polyfilled symbol like behaviour, now doesn't work.

**Comment by stefanpenner** [comment] 2015-01-14 13:46
after hacking past ^, iojs hangs after modules have transpiled, but before the server starts. That likely needs more investigation.

**Comment by stefanpenner** [comment] 2015-01-14 14:03
libsass is also currently borking

**Comment by stefanpenner** [comment] 2015-01-14 14:28
this warrants further investigation.

I updated https://github.com/ef4/broccoli-es6modules/pull/4 to use esperanto (which also gives us better module semantics) and stuff

**Comment by stefanpenner** [comment] 2015-01-22 04:33
> I updated ef4/broccoli-es6modules#4 to use esperanto (which also gives us better module semantics) and stuff

this is updated, now we have a strange "hanging" issue that needs investigation.

**Comment by ilkkao** [comment] 2015-01-22 08:59
@stefanpenner I got the same `Cannot convert a Symbol value to a string` this morning after switching to node v0.11.15:

```
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/ioksanen/git/mas/client/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/ioksanen/git/mas/client/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:136:17
    at setToStringTag (/Users/ioksanen/git/mas/client/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:88:13)
    at /Users/ioksanen/git/mas/client/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:610:3
    at /Users/ioksanen/git/mas/client/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:614:2
    at Object.<anonymous> (/Users/ioksanen/git/mas/client/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:2101:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Downgraded back to v0.11.14 and the error disappeared. Looks like this issue is becoming more visible. V8 upgrade to v8 3.28.73 in v0.11.15 must have caused the problem.

I'd like to use the latest patch version of node/io.js branch I'm using but in this case it would mean going back to 0.10 which I can't do. As a temporarily I stick with v0.11.14.

**Comment by stefanpenner** [comment] 2015-01-22 13:05
That is fixed on master

**Comment by ilkkao** [comment] 2015-01-22 13:47
Confirmed. Thanks!

**Comment by fsbdev** [comment] 2015-01-25 09:37
the hang in `ember build` sees CPU use go up to 100% on my machine

**Comment by stefanpenner** [comment] 2015-01-25 12:47
> the hang in ember build sees CPU use go up to 100% on my machine

ya, i haven't hand a chance to investigate further yet
> this is updated, now we have a strange "hanging" issue that needs investigation.

**Comment by stefanpenner** [comment] 2015-01-26 20:56
FYI: https://github.com/ember-cli/ember-cli/pull/3092 pending some MISC test helper related issue.

**Closed** 2015-01-27 16:05 UTC

**Comment by gcollazo** [comment] 2015-01-28 16:37
Live reload doesn't seem to be working with io.js + Firefox.


![node0_10_36-ff](https://cloud.githubusercontent.com/assets/61048/5941824/d4162222-a6e9-11e4-90aa-acb931789b05.png)

![iojs-ff](https://cloud.githubusercontent.com/assets/61048/5941830/df312a94-a6e9-11e4-9913-2a90f49c0cc1.png)

![iojs-chrome](https://cloud.githubusercontent.com/assets/61048/5941834/e7505b00-a6e9-11e4-8977-96f2f8319ce5.png)
