### ISSUE TITLE
TypeError: heimdall.statsFor is not a function

### ISSUE THREAD

**Issue by poteto** [ember-cli/ember-cli#6434] opened 2016-11-15 23:06 UTC
On an existing ember-cli 2.9.1 / new ember app, a clean install produces the following error when trying to serve or build the app:

```
/Users/laurent/code/hahaha/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:59
  var metrics = heimdall.statsFor('fs');
                         ^

TypeError: heimdall.statsFor is not a function
    at FSMonitor._measure (/Users/laurent/code/hahaha/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:59:26)
    at Object.realpathSync (/Users/laurent/code/hahaha/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at toRealPath (module.js:132:13)
    at tryFile (module.js:128:22)
    at tryPackage (module.js:106:10)
    at Function.Module._findPath (module.js:185:20)
    at Function.Module._resolveFilename (module.js:470:25)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```

To reproduce:

```
ember new my-app
cd my-app
ember serve
```

It appears the issue is with the latest release of `heimdalljs@0.2.2` breaking the `statsFor` API without bumping the major

cc @hjdivad

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.9.1
http_parser: 2.7.0
node: 7.1.0
v8: 5.4.500.36
uv: 1.10.0
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: darwin x64
npm: 3.10.9
```

**Comment by chrisccerami** [comment] 2016-11-15 23:09
I just opened a duplicate of this right after you haha. Same basic situation for us.

**Comment by derekdowling** [comment] 2016-11-15 23:12
Looks like `broccoli-funnel` is what's importing it: https://github.com/broccolijs/broccoli-funnel/issues/83.

**Comment by derekdowling** [comment] 2016-11-15 23:15
Hotfix: https://github.com/broccolijs/broccoli-funnel/pull/84

**Comment by hjdivad** [comment] 2016-11-15 23:25
fixed with release of heimdalljs v0.2.3

**Comment by hjdivad** [comment] 2016-11-15 23:27
@derekdowling thanks for the fast hotfix! and thanks @poteto for the prompt and detailed bug report.

If anybody has an issue with v0.2.3 please reopen and cc me.

**Closed by hjdivad** 2016-11-15 23:27 UTC

**Comment by derekdowling** [comment] 2016-11-15 23:29
Okay, not seeing `v0.2.3` in Github, should I be looking somewhere else?

**Comment by hjdivad** [comment] 2016-11-15 23:33
@derekdowling https://github.com/heimdalljs/heimdalljs-lib/tree/v0.2.3

**Comment by hjdivad** [comment] 2016-11-15 23:34
also
```
[N] ⋊> ~/s/h/heimdalljs-lib on v0.2.x ◦ npm info heimdalljs --json | jq .version
"0.2.3"
```

**Comment by derekdowling** [comment] 2016-11-15 23:35
Thanks, I refreshed and it showed up. Caching must have gotten the best of me. Thanks for the quick fix @hjdivad 👍

**Comment by hjdivad** [comment] 2016-11-15 23:40
@derekdowling no worries; as i said before please reopen and cc me if you see this issue again.  Also thanks again for your superquick hotfix.  We didn't need it in the end, but it would have been extremely useful if the actual resolution wasn't also quick!  👍
