### ISSUE TITLE
Error on vender js library minimization

### ISSUE THREAD

**Issue by jgadbois** [ember-cli/ember-cli#6347] opened 2016-10-14 16:29 UTC
I have a vendor library that is working fine on dev, but on production is throwing an error.  It looks like it's introduced during the minimization process.

```
function(e, t) {
    "use strict";
    var i = {
        "activeElement": void 0,
        // ... remove code
        "mainHandler": function(e, t) {
            // l NOT DEFINED - top level e should be l
            var n, r, s = l.location.hash.replace("#", ""), o = 0, a = [];
            // ... remove code
       }
    };
    // ... remove code
}(window, window.jQuery),
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.5.0
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
os: darwin x64
3.3.9

```

Not sure if this is a cli issue or the underlying minimizer so apologies if this is the wrong spot.

**Comment by nathanhammond** [comment] 2016-10-14 18:08
@jgadbois This is almost certainly an underlying issue: either with the library which has the error, or with the minifier itself. We can't help you diagnose without a reproduction. If you can publish a repository with the error we can take a look.

I'm closing this issue as not a bug but if upon further investigation you discover that it may in fact be a bug keep posting! We will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. 😄

**Closed by nathanhammond** 2016-10-14 18:08 UTC

**Comment by jgadbois** [comment] 2016-10-28 15:08
@nathanhammond is there a way to change or change the version the minimizer that ember-cli is using?  I'm seeing errors from Ember controllers that are related to minimization as well.

**Comment by nathanhammond** [comment] 2016-10-28 19:44
@jgadbois We use ember-cli-uglify. Being that you're the only person reporting this issue I'd be _very_ surprised if it were widespread and not something in your own code. This would break every single Ember application out there.

If you can post a simplified reproduction of the issue we can help, otherwise we're not really able to do anything about it. I'll review any reproduction you can post.

**Comment by jgadbois** [comment] 2016-10-28 19:50
Will do thanks.  Could be a rails-ember-cli issue too but I think it just delegates all Ember minification to ember build
