### ISSUE TITLE
Linting tests should run on the app directory 

### ISSUE THREAD

**Issue by kiwiupover** [ember-cli/ember-cli#6667] opened 2017-01-12 05:31 UTC
Moving this issue to ember-cli 

https://github.com/ember-fastboot/ember-cli-fastboot/issues/307

@rwjblue can you point me in the right directions to and I will open a PR 

cheers
Dave

**Comment by Turbo87** [comment] 2017-07-23 18:00
duplicate of #5839

**Closed by Turbo87** 2017-07-23 18:00 UTC
Labels: Bug

**Comment by rwjblue** [comment] 2017-10-11 14:51
Fixed by #7037 which was rebased / tweaked / landed in #7378.
