### ISSUE TITLE
ember install org-name/package-name fails running defaultBlueprint

### ISSUE THREAD

**Issue by mszoernyi** [ember-cli/ember-cli#6219] opened 2016-08-31 23:37 UTC
Running `ember install remerge/ember-remerge-blueprint` will lead to 

```
WARNING: Could not figure out blueprint name from: "remerge/ember-remerge-blueprint". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
```

Setting the `defaultBlueprint` option in my `package.json` with

```
  // package.json
  "ember-addon": {
    "configPath": "tests/dummy/config",
    "defaultBlueprint": "ember-remerge-blueprint"
  }
```

doesn't help either because [get-package-base-name](https://github.com/ember-cli/ember-cli/blob/ea866dd56d3e22501d882523cf24fc7a105fe523/lib/utilities/get-package-base-name.js#L13) doesn't set the `name` for github repositories. [npm-package-arg](https://github.com/npm/npm-package-arg/blob/master/npa.js#L141-L153) recognizes the passed in package name as github repository but doesn't set a name either. Which leads to `return null` for [findDefaultBlueprintName](https://github.com/ember-cli/ember-cli/blob/ea866dd56d3e22501d882523cf24fc7a105fe523/lib/tasks/addon-install.js#L77).

Is this considered a bug or is installing from github not supported?

We want to host our internal addons on github only but make use of the default blueprint when unsing `ember install`.

I could submit a [failing test](https://github.com/ember-cli/ember-cli/blob/ea866dd56d3e22501d882523cf24fc7a105fe523/tests/unit/utilities/get-package-base-name-test.js#L15) as a PR but wasn't able to figure out how to get the package name there.

```
  // ember-cli/tests/unit/utilities/get-package-base-name-test.js
  it('should return the full package name if hosted on github', function() {
    expect(getPackageBaseName('my-org/my-addon')).to.equal('my-addon');
  });
```

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.4.0
v8: 5.0.71.60
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
```

**Comment by davewasmer** [comment] 2016-09-08 18:32
Ran into this as well.

Seems like the problem stems from the fact that I can `npm install github:user/foo`, but the installed package isn't necessarily named `foo` (i.e. the package.json file inside my `user/foo` repo could be have `"name": "bar"`). And ember-cli needs the _package_ name, not the _repo_ name, to build the default blueprint name.

Since fetching the git repo and resolving the package name is done inside npm and doesn't seem to be exposed (i.e. there's no `npm whats-the-pkg-name-for github:user/my-foo` command), getting that information could be tricky without doing something gross like diffing the before/after state of package.json, or replicating npm functionality (i.e. going to Github to figure out the package name).

One less than perfect option might be to simply assume repo name === package name. In my experience, that's true 99% of the time. And if that's not true, resulting in ember-cli failing to find the installed `foo` package, we print the current warning ("Could not figure out blueprint name ..."). This would address the common use cases and would provide a decent warning in the failure scenarios.

The only potentially tricky part I could see here is if you have a repo name different from it's package name, and the repo name conflicts with an existing dependency. I.e. `user/alpha` contains an npm package named `something-else`, and your app separately depends on the npm package `alpha`. Running `ember install user/alpha` would end up running the default blueprint for the published `alpha` package, rather than your git repo's. But that seems like it's a rare enough edge case that it might be okay?

**Comment by nathanhammond** [comment] 2016-09-10 01:23
@mszoernyi @davewasmer Installing via `ember install` will work identically to what happens via `npm`. The _only_ caveat is that we don't support running the default blueprint because that could literally be anything, as @davewasmer noted. We are explicitly not going to guess at package name and elected the message instead given:

> repo name !== package name !== `defaultBlueprint`

A correct solution is to:

1. Stash package.json.
2. Run npm install.
3. Read package.json (pray for no race conditions)
4. `require.resolve` the new module name.
5. Grab the package.json from that path.
6. Parse out `defaultBlueprint` || `name`.

Steps 1 and 3 feel gross, so I'm hoping there's a better way to do those.

If you'd be interested in opening a PR with something that approximates this and an RFC simultaneously we can discuss whether it makes sense to do it. In the mean time I'm closing this issue because this is presently "works as intended" and you were successfully notified that it didn't do what you hoped would happen. In spite of being closed we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Closed by nathanhammond** 2016-09-10 01:23 UTC

**Comment by zen-tmq** [comment] 2016-11-16 20:39
Could we possibly pass the defaultBlueprint name in via the addBowerPackageToProject method? This is a ridiculously frustrating blocker for me rn...

**Comment by nathanhammond** [comment] 2016-11-16 21:45
@zen-tmq I've outlined a solution and a path forward if you'd like to move that forward. Working on this directly is not on our priority list, but it _is_ on my priority list to help you move forward on this if you're interested in helping.

Aside: `addBowerPackageToProject` doesn't do anything related to Ember addon installation.

**Comment by zen-tmq** [comment] 2016-11-16 22:03
Oh whoops... I don't know why I typed that. Meant addAddonsToProject. And I'd be happy to help, but I was questioning the method. Would it be easier/acceptable if I were to just include an additional property in the argument passed to that method so:
`this.addAddonToProject({packages: [{name: 'myRepo/my-addon', defaultBlueprint: 'my-addon'}]);`

thanks for the prompt reply, btw

**Comment by zen-tmq** [comment] 2016-11-16 22:04
I noticed there is an options.blueprintOptions in the code as well.. trying to trace what this does now...

**Comment by nathanhammond** [comment] 2016-11-16 22:30
We would want to solve this at the more-fundamental level, so it can't just be by passing options in.

**Comment by zen-tmq** [comment] 2016-11-17 00:34
I see, I see... do you think there would be a use case for firing different blueprints for different situations at the addAddonToProject level?

**Comment by nathanhammond** [comment] 2016-11-17 18:22
At that point I'd look into `execSync` as part of the install process of your addon though we _may_ want to provide (may have?) a simpler command to run an installed blueprint.

**Comment by jeffrey008** [comment] 2017-10-06 03:17
Hello guys, so is there any workarounds now? I use

 `this.addAddonsToProject ({packages: [{ name: 'git+ssh://my-private-repo'}]})` 

Then after installing CLI throws

`WARNING: Could not figure out blueprint name from: "git+ssh://my-private-repo". Please install the addon blueprint via "ember generate <addon-name>" if necessary.`

**Comment by kellyselden** [comment] 2017-10-11 21:38
@jeffrey008 This is a long dead issue. You might want to open a fresh issue with your problem.
