### ISSUE TITLE
Server restart needed everytime i change anything in the files

### ISSUE THREAD

**Issue by 3lackRos3** [ember-cli/ember-cli#4298] opened 2015-06-16 15:24 UTC
I'm just starting to use ember cli. My node version is 0.12.4, ember-cli version is 0.2.7, watchman's version is 3.2.0. 
I just created a new project. Changed the default markup in application.hbs but the changes doesn't take place even when i refresh the browser and the live reload also doesn't work. Only after restarting the server and refreshing the browser bring the changes made to the .hbs file

**Comment by 3lackRos3** [comment] 2015-06-16 15:27
Server Log

version: 0.2.7
Livereload server on port 35729
Serving on http://localhost:4200/

Build successful - 4936ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Concat: Vendor                                | 3876ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Concat: Vendor (1)                            | 3876ms              
Babel (2)                                     | 248ms (124 ms)      

Content Security Policy violation: {"csp-report":{"document-uri":"http://localhost:4200/","referrer":"http://localhost:4200/","violated-directive":"style-src 'self'","effective-directive":"style-src","original-policy":"default-src 'none'; script-src 'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729; font-src 'self'; connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729 http://0.0.0.0:4200/csp-report; img-src 'self'; style-src 'self'; media-src 'self'; report-uri http://0.0.0.0:4200/csp-report;","blocked-uri":"","source-file":"chrome-extension://jabopobgcpjmedljpbcaablpmlmfcogm","line-number":2,"column-number":17322,"status-code":200}}

**Comment by gmurphey** [comment] 2015-06-16 16:57
I had the same problem, but it seems to be fixed by #4290. I would try [linking ember-cli@master](https://github.com/ember-cli/ember-cli#working-with-master) and seeing if your issue is fixed.

**Comment by 3lackRos3** [comment] 2015-06-16 18:07
@gmurphey Thanks a lot. Linking Ember-cli master fixed this problem.

**Comment by 3lackRos3** [comment] 2015-06-17 14:38
It did work yesterday and now its not working. I don't understand why this is happening? Even I changed my Operating system for this

**Comment by stefanpenner** [comment] 2015-09-15 01:52
will reopen if reproduction on latest is provided

**Closed by stefanpenner** 2015-09-15 01:52 UTC
