### ISSUE TITLE
Livereload fails to load

### ISSUE THREAD

**Issue by matthewbga** [ember-cli/ember-cli#4423] opened 2015-07-10 19:09 UTC
Having followed the directions here: http://www.ember-cli.com/user-guide/#getting-started I am working to run ember server as follows, with error included.

```
# ember server
version: 1.13.1
Livereload failed on http://0.1.0.1:35729.  It is either in use or you do not have permission.
```

I have used grunt in the past, and I also use Anvil, but both appear to be inactive right now. Also, tried lost:

```
# sudo lsof -iTCP:35729
```

And no items are returned.

**Comment by stefanpenner** [comment] 2015-07-10 19:25
dupe of: https://github.com/ember-cli/ember-cli/issues/4403

**Closed by stefanpenner** 2015-07-10 19:25 UTC

**Comment by matthewbga** [comment] 2015-07-10 19:32
Thanks for the reference. I do appreciate it.

It is not a true duplicate, though, as there appears to be no workaround in this case. No way to start ember serve that actually runs.

**Comment by matthewbga** [comment] 2015-07-10 20:22
Figured this one. Embarrassed...

The server was trying to launch on IP address 0.1.0.1, and I am not sure how this IP ever works – perhaps a virtual machine setup by the test system.

At any rate, adding host and port to my .ember-cli fixed it. The entire file looks like:

```
{
  "disableAnalytics": false,
  "port": "8080",
  "watcher": "polling",
  "host": "localhost"
}
```

**Comment by stefanpenner** [comment] 2015-07-10 20:30
> The server was trying to launch on IP address 0.1.0.1, and I am not sure how this IP ever works – perhaps a virtual machine setup by the test system.

the ember-cli server?
