### ISSUE TITLE
How to use multiple CSS preprocessors in one project?

### ISSUE THREAD

**Issue by tsabolov** [ember-cli/ember-cli#2959] opened 2015-01-12 17:04 UTC
I prefer Stylus by myself to write styles. Also I use Foundation which is written in SCSS, and Selectize whose styles are in LESS. What is the correct way (if any) of using multiple preprocessors together?

**Comment by stefanpenner** [comment] 2015-01-12 17:08
specific preprocessors should detect based on the file extension

**Comment by tsabolov** [comment] 2015-01-12 18:01
But how different files should be compiled into one app.css? Maybe I missed something in docs?

**Comment by stefanpenner** [comment] 2015-01-12 18:12
hmm, i suspect they would be kept as independent trees.

**Comment by pzuraq** [comment] 2015-01-22 16:50
@stefanpenner I just ran a test case and it looks like the trees aren't merging properly. I think the expected behavior should be including both an `app.[scss/sass]` file and an `app.styl` file as entry points for the respective preprocessors (and allowing the outputPath to be specified in config as usual). Currently it fails if an app has both preprocessors and both files, I'm going to dig in and figure out why.

**Comment by tsabolov** [comment] 2015-01-23 06:01
Am I getting it right that by design both `app.[scss/sass]` and `app.styl` should be merged into one output file `app.css`? If it's the case then in what order merge will be done?

**Comment by pzuraq** [comment] 2015-01-23 06:03
@tsabolov Yes they should be merged into one file, but I was not thinking about order. Ideally you should be able to specify the order that they are merged in, as well as names of the input files.

**Closed** 2015-06-02 20:03 UTC

**Comment by knownasilya** [comment] 2015-11-14 00:13
Was this ever resolved? Related issues https://github.com/gdub22/ember-cli-less/issues/27 and https://github.com/jeffjewiss/ember-cli-postcss/issues/4

**Comment by msalahz** [comment] 2016-03-27 22:02
Any updates about this ?

**Comment by webark** [comment] 2016-06-25 00:35
@pzuraq any luck with this..?

**Comment by pzuraq** [comment] 2016-06-25 00:43
@webark If I remember correctly I had a solution working, but the core issue I came up against was if you had multiple style files with the same name and different preprocessors (e.g. `app.scss` and `app.styl`). The respective broccoli plugins would both produce an `app.css` which would cause a conflict and throw an error, so this kind of became a question of what to do in that scenario.

A lot has changed since then, I'll try to take a look at it sometime but I haven't been working on CLI stuff for a while.

**Comment by knownasilya** [comment] 2016-06-25 01:07
Postcss might be a good option, since it has plugins for sass and less. Not sure if those work together though.
