### ISSUE TITLE
addon with sass fails

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2905] opened 2015-01-06 18:31 UTC
example app: https://github.com/stefanpenner/___app-with-addon-that-has-styles

details:

* app has broccoli-sass
* addon has `addon-with-styles/addon/styles/styles.scss` & `addon-with-styles/app/styles/addon-with-sass.scss`
* app tries to import both in `app/styles/app.scss`

```sass
// should import addon-with-styles/addon/styles/styles.scss
@import 'addon-with-styles/styles';

// should import addon-with-styles/app/styles/addon-with-sass.scss
@import 'addon-with-sass';
```

```
± % ember s                                                                                                                      !10040
version: 0.1.5
Object.keys called on non-object
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at StylePlugin.toTree (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/preprocessors/style-plugin.js:24:22)
    at /Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/preprocessors.js:104:26
    at Array.forEach (native)
    at processPlugins (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/preprocessors.js:103:11)
    at module.exports.preprocessCss (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/preprocessors.js:75:10)
    at Class.Addon.compileStyles (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/models/addon.js:207:27)
    at Class.Addon.treeForAddon (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/models/addon.js:188:25)
    at Class._treeFor (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/models/addon.js:132:31)
    at Class.treeFor (/Users/stefan/tmp/app-with-addon-that-has-styles/node_modules/ember-cli/lib/models/addon.js:111:19)
```

expected behavior both import correctly, no explosions.

related issues:

* https://github.com/ember-cli/ember-cli/issues/2363
* https://github.com/ember-cli/ember-cli/issues/1949
* https://github.com/ember-cli/ember-cli/issues/2348
* https://github.com/ember-cli/ember-cli/pull/2381

maybe related: 
* https://github.com/ember-cli/ember-cli/issues/2872

**Comment by stefanpenner** [comment] 2015-01-07 19:34
cc @rwjblue

**Comment by stefanpenner** [comment] 2015-02-10 15:25
i believe https://github.com/ember-cli/ember-cli/pull/3166 will sort this out

cc @lukemelia  @rwjblue

**Comment by lukemelia** [comment] 2015-02-22 06:54
When updated to ember-cli master, @stefanpenner's example project fails with:

```
➜  ___app-with-addon-that-has-styles git:(master) ✗ ember build
Future versions of Ember CLI will not support v0.10.33. Please update to Node 0.12 or io.js.
version: 0.2.0-beta.1
Build failed.
/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/tmp/tree_merger-tmp_dest_dir-07GVgOS4.tmp/app/styles/app.scss:6: file to import not found or unreadable: 'addon-with-styles/styles'
Current dir: /Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/tmp/tree_merger-tmp_dest_dir-07GVgOS4.tmp/app/styles/
 [string exception]
Error: /Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/tmp/tree_merger-tmp_dest_dir-07GVgOS4.tmp/app/styles/app.scss:6: file to import not found or unreadable: 'addon-with-styles/styles'
Current dir: /Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/tmp/tree_merger-tmp_dest_dir-07GVgOS4.tmp/app/styles/
 [string exception]
    at /Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:35:15
    at lib$rsvp$$internal$$tryCatch (/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$$internal$$publishRejection (/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:415:7)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/lmelia/p/ember/tmp/___app-with-addon-that-has-styles/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

Not sure what the issue is as yet.

**Comment by stefanpenner** [comment] 2015-02-22 14:57
will take a look, maybe i can figure something out.

**Comment by rwjblue** [comment] 2015-02-22 16:17
I'll test this against the changes I have in https://github.com/ember-cli/ember-cli/pull/3335 as it might be related (not sure though).

**Comment by rwjblue** [comment] 2015-02-23 02:39
https://github.com/ember-cli/ember-cli/pull/3344 addresses the second scenario described (importing from the addon's `app/styles/*` path as if it were the same location as the apps `app/styles/app.scss`).

**Comment by sandstrom** [comment] 2015-09-29 17:07
Possibly this is solved now: https://github.com/ember-cli/ember-cli/pull/4825#issuecomment-144107098

**Comment by stefanpenner** [comment] 2015-09-29 17:20
will close for now, and reopen if it ends up not being.

**Comment by sandstrom** [comment] 2015-09-29 21:27
I've tried and it seems like the issue remain, unfortunately.

*The error*
```
$ ember serve
version: 1.13.8
Object.keys called on non-object
TypeError: Object.keys called on non-object
  at Function.keys (native)
  at SASSPlugin.toTree (/path/to/repo/node_modules/ember-cli-sass/index.js:20:22)
  at /path/to/repo/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:26
  at Array.forEach (native)
  at processPlugins (/path/to/repo/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:11)
  at module.exports.preprocessCss (/path/to/repo/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:154:10)
[...]
```

*Env*
```
$ ember -v
version: 1.13.8
node: 0.12.0
npm: 2.14.6
os: darwin x64

$ cat package.json | grep ember-cli\"
    "ember-cli": "git://github.com/ember-cli/ember-cli#3c90dedb0c",

$ cat package.json | grep ember-cli-sass
    "ember-cli-sass": "~4.2.1",
```

**Comment by sandstrom** [comment] 2015-10-05 16:54
@stefanpenner You can close this again. I was mistaken saying that this issue remained. I got the same error message, but for another reason.

**Closed** 2015-10-05 17:00 UTC
Labels: bug
