### ISSUE TITLE
ember-cli won't install

### ISSUE THREAD

**Issue by neophoenix123** [ember-cli/ember-cli#5188] opened 2015-12-04 21:46 UTC
Please help. 

I have been spending the better part of the week trying to just install ember-cli, dependencies and packages through BASH on my win7 machine. The problem appears to be a depreciated lodash-node version which according to BASH is no longer supported.......WONDERFUL!!! If it is, no problem! I just want to know what it does support in substitution in order for me to get ember-cli working properly. I checked for versions of npm, bower and phantom and all seem to be up and running just fine....Am I missing something? If so any assistance will help. 

Thanks all!

**Comment by stefanpenner** [comment] 2015-12-04 21:52
> I have been spending the better part of the week trying to just install ember-cli

Something seems strange, windows support should work fine. In-fact our windows CI, installs and runs In fact git-bash, cmd.exe or powershell on windows for every commit: https://github.com/ember-cli/ember-cli/blob/master/appveyor.yml#L16-L25

My suspicion is that you are using a broken version of NPM, as they have been having issues as of late.

**Comment by neophoenix123** [comment] 2015-12-04 21:54
yes indeed...I tried to reinstall an earlier version as I have been told that npm lately has been working poorly. This did not solve the issue. I am very tired of not getting any practice started I simply want to create my first todo app. That's all!

**Comment by stefanpenner** [comment] 2015-12-04 21:57
@neophoenix123 you must provide additional information. As this is known to work cross platform, and does for many users.

What version of node, npm, etc.

**Comment by neophoenix123** [comment] 2015-12-04 22:06
My apologies...
Node v4.2.2
npm v2.14.7
bower v1.6.8
phantom v2.0.0

**Comment by stefanpenner** [comment] 2015-12-04 23:33
@neophoenix123 can you also share how it is failing? What symptoms etc.

**Comment by gmurphey** [comment] 2015-12-05 19:28
Not sure if it's related, but npm-deprecate on lodash seems to have been causing Windows build failures. I haven't run into it personally, though. 

Relevant issues:
https://github.com/lodash/lodash/issues/1686
https://github.com/npm/npm/issues/10702

**Comment by jdalton** [comment] 2015-12-05 20:13
@gmurphey Ya, it's hard to pin down at the moment. Not sure if it's causing build fails (in any large number) or just folks annoyed at the message.

**Comment by DavidStrada** [comment] 2015-12-06 01:39
I can confirm new installations of `ember-cli` are not working `The lodash-node package is deprecated in favor of lodash & lodash-compat ≥ v3.0.0.`[link](https://github.com/lodash/lodash-node#deprecated)  i'm on OS X 

node -v `v5.1.1`
nmp -v `3.3.12`

After doing `ember s` getting on http://localhost:49154 >> `{"tinylr":"Welcome","version":"0.2.0"}`

**Comment by DavidStrada** [comment] 2015-12-06 01:43
some logs 
``` console
» npm i
npm WARN deprecated lodash-node@3.10.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@2.3.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

```

**Comment by gmurphey** [comment] 2015-12-06 01:48
@DavidStrada that's normal output for the livereload server. You should use http://localhost:4200 to see your Ember app.

**Comment by DavidStrada** [comment] 2015-12-06 01:53
my bad :/
Thanks,
David

**Comment by stefanpenner** [comment] 2015-12-06 01:53
@DavidStrada that doesnt sound like a bug, we are totally allowed to use something deprecated. Its merely warning us to upgrade, but will continue to work as expected without.

We should upgrade lodash, but that should not be preventing normal usage. I hope this bug isn't just confusing the warning with an actual issue.

**Comment by DavidStrada** [comment] 2015-12-06 01:57
@stefanpenner I was incorrectly using the first link provided by `ember s` `Livereload server on http://localhost:49154` instead of `Serving on http://localhost:4200/` 

Yes it's NOT a but it's a warning.
Thanks :)

**Comment by stefanpenner** [comment] 2015-12-06 02:00
@jdalton is there value in having this warning, it seems noisy, as we have `npm outdated` if we want to see whatsup.

**Comment by stefanpenner** [comment] 2015-12-06 02:04
@jdalton it is also the case, the ember-cli itself doesn't appear to depend on lodash-node, just lodash (and the semver constraint should let it update to the latest release version). Some dep of dep maybe?

As we don't use lodash-node in the project, im going to close this.

If there is actually an issue installing please provide reproducible steps, and we can reopen.

**Closed by stefanpenner** 2015-12-06 02:04 UTC
Labels: pending-submitter-response

**Comment by jdalton** [comment] 2015-12-06 04:38
@stefanpenner 
> is there value in having this warning, it seems noisy, as we have npm outdated if we want to see whatsup.

It's nudging folks to upgrade which is great. What I want to ensure though is that builds aren't breaking. So far it looks like they aren't.
