### ISSUE TITLE
minifyJS.enabled option in ember-cli-build not working

### ISSUE THREAD

**Issue by cdatehortuab** [ember-cli/ember-cli#7445] opened 2017-11-15 22:01 UTC
Hello,

I'm having an issue when build my ember project.

The problem is that ember-cli is ignoring the minifyJS.enabled option.

It only takes into account the environment, not my custom option.

If I build for 'development', using in my ember-cli-build.js file:
`
minifyJS: {
    enabled: true
},
`,
the JavaScript files should be minified but they are not.

And, if I build for 'production', using in my ember-cli-build.js file:
`
minifyJS: {
    enabled: false
},
`,
the JavaScript files should not be minified but they are.

Thanks.
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.12.0
v8: 5.1.281.108
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2m
os: linux x64
3.10.10
1.3.2
```

**Comment by twokul** [comment] 2017-11-15 22:07
@cdatehortuab just to be clear, your `ember-cli-build.js` contains:

```javascript
// ember-cli-build.js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  const app = new EmberApp(defaults, {
    minifyJS: {
      enabled: true
    }
  });

  //...
  return app.toTree();
};
```

and it doesn't minify files?

**Comment by cdatehortuab** [comment] 2017-11-15 22:25
@twokul No, it doesn't.

It is as if it was only taking into account the environment for which I'm building and not my config.

**Comment by twokul** [comment] 2017-11-15 22:41
@cdatehortuab can you put together a reproduction?

**Comment by cdatehortuab** [comment] 2017-11-16 00:33
First this is the output of `ember version --verbose && npm --version && yarn --version`
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.12.0
v8: 5.1.281.108
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2m
os: linux x64
3.10.10
1.3.2
```
I generated a new ember project with `ember new ember-test`
Then, I put in `ember-cli-build.js` file:

```javascript
// ember-cli-build.js
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    minifyJS: {
      enabled: true
    }
  });

  return app.toTree();
};
```
After that I ran `ember build --env=development` and I got that .js files in `dist` directory are not minified.

Then, I changed the `ember-cli-build.js` file to:

```javascript
// ember-cli-build.js
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    minifyJS: {
      enabled: false
    }
  });

  return app.toTree();
};
```
And when I ran `ember build --environment=production` command, I got minified .js files.

So that option is being ignored by ember-cli.

I hope it was clear.

Greetings, thanks.

**Comment by axiomabsolute** [comment] 2017-11-16 15:15
I went ahead and created a minimal example verifying the issue.

[Minimal Ember-CLI Example](https://github.com/axiomabsolute/ember-cli-issues-7445)

Clone the repo, run `ember build -prod` and note that the output is still minified, despite `minifyJS: { enabled: false }` being set in the `ember-cli-build.js` file. That is the only change I made to the basic `ember init` setup.

**Comment by axiomabsolute** [comment] 2017-11-16 17:35
I believe this is related to the following change in the `broccoli-uglify-sourcemap` plugin:

https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/49

Based on this, the `options` hash format is quite different from the one posted in the docs.  The docs currently say:

<img width="995" alt="screen shot 2017-11-16 at 12 19 00 pm" src="https://user-images.githubusercontent.com/766944/32905969-969624c2-cac9-11e7-9db9-45ce48823b4e.png">

however I believe the plugin now expects a different format. The following `ember-cli-build.js` appears to work as expected:

```js
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    /*
     * this looks to be broken!
    minifyJS: {
      enabled: false
    },
    */
    'ember-cli-uglify': {
      enabled: true,
      uglify: {
        // compress: true,
        // sourceMap: true,
        mangle: false, // defaults to true
      }
    },
  });

  return app.toTree();
};

```

**Comment by Turbo87** [comment] 2017-11-20 15:38
@axiomabsolute thanks for investigating this. could you open an issue on the https://github.com/ember-cli/broccoli-uglify-sourcemap/issues repo for this? and if you have a bit of time it would be awesome if you could come up with a failing test for it that reproduces the problem.

**Comment by c-emil** [comment] 2018-06-14 17:18
Has anyone investigated this issue further? I've run into the same issue today and it's been half year since this issue was submitted. It would be nice to update ember-cli docs, what do you think?

**Comment by ultimatemonty** [comment] 2018-10-03 21:21
another ping!

Trying to debug some issues that only occur in production and wanting to ship unminified, fingerprinted assets. ember-cli (or broccoli-uglify-sourcemaps?) is not respecting `minifyJS: { enabled: false }` when running `ember build --environment=production`

**Comment by Turbo87** [comment] 2018-10-10 13:57
@ultimatemonty have a look at https://github.com/ember-cli/ember-cli-uglify#usage. it describes how to disable the JS minification step.

**Comment by locks** [comment] 2022-02-10 02:55
Closing as no longer relevant due to the migration from uglify to terser.

**Closed by locks** 2022-02-10 02:55 UTC
