### ISSUE TITLE
Invalid mapping Error with "minifyJS" enabled.

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#3657] opened 2015-03-26 15:02 UTC
I can reproduce the following error from a fresh ember-cli project with only adding ```minifyJS: { enabled: true }``` in Brocfile.js.

```
Invalid mapping: {"generated":{"line":77238,"column":-50},"source":"vendor/ember-cli/vendor-suffix.js","original":{"line":1,"column":0},"name":null}
```

I already reviewed the following related issues but couldn't find the solution so I am creating one.
https://github.com/ember-cli/ember-cli/issues/3527
https://github.com/ember-cli/ember-cli-uglify/issues/4

My environment information is the following
```
version: 0.2.1
node: 0.12.0
npm: 2.7.3
````
and I upgraded the ember-data to ```"ember-data": "1.0.0-beta.16.1",```

This is my test repository that you can see
https://github.com/vsymguysung/ember-cli-0-2-1-bug-report

Any help would be greatly appreciated.

**Comment by vsymguysung** [comment] 2015-03-26 19:47
Is this error a intended behavior? Shouldn't I use ```minifyJS``` option in Brocfile.js for dev builds? I am just getting this error after upgrading the ember-cli to version ```0.2.1``` from ```0.2.0```, It used to work with the previous version of ember-cli.

**Comment by stefanpenner** [comment] 2015-03-26 20:58
> Is this error a intended behavior?

obviously not. This is likely broken since we added sourcemap support. This may also indicate why sometimes source-maps are not always working correctly.

> Shouldn't I use minifyJS option in Brocfile.js for dev builds?

Well, this will make your dev builds extremely slow, which is why you are likely one of the first to encounter and report this.

Production builds don't currently emit source maps (although they likely should).

This will require some further sleuthing.

**Comment by vsymguysung** [comment] 2015-03-26 21:51
Thanks much for your detailed explanation. It helps me understand what I experienced.

**Comment by stefanpenner** [comment] 2015-03-26 22:20
@vsymguysung thanks for reporting the but. Still something we should fix, although I can't promise when it will be fixed.

**Comment by vsymguysung** [comment] 2015-03-26 23:34
@stefanpenner I totally understood it, I am rather happy to help this project and always thankful for this amazing works from you guys.

**Comment by stefanpenner** [comment] 2015-03-27 01:00
Thanks :) hopefully we collectively continue to make good progress

**Comment by digitalbreed** [comment] 2015-06-29 21:34
I just encountered this, too, while I was trying to setup an EmberApp with a "staging" environment. Enabling sourcemaps for development only helped:

    var EmberApp = require('ember-cli/lib/broccoli/ember-app');
    var isDevelopment = EmberApp.env() === 'development';
    var app = new EmberApp({
    	minifyCSS: { enabled: !isDevelopment, relativeTo: 'app/styles' },
    	minifyJS: { enabled: !isDevelopment },
    	sourcemaps: { enabled: isDevelopment }
    });

**Comment by brandonjmckay** [comment] 2015-07-06 19:21
@digitalbreed nice tip! Was getting this same error doing the exact same thing.

**Comment by jamesarosen** [comment] 2015-07-10 16:56
See also #3527 and ember-cli/ember-cli-uglify#4

**Comment by stefanpenner** [comment] 2015-12-22 15:16
I have been working on improving our source-map tooling, we will likely address most obvious issues as we work through it. As for this issue, will gladly reopen if a reproduction on latest can be provided

**Closed by stefanpenner** 2015-12-22 15:16 UTC
Labels: bug
