### ISSUE TITLE
Error creating new application

### ISSUE THREAD

**Issue by afuno** [ember-cli/ember-cli#8458] opened 2019-02-27 18:47 UTC
I'm trying to create a new application:

```
ember new app1
```

As a result, I get this:

```
installing app
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/optional-features.json
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.js
  create tests/helpers/.gitkeep
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
⠋ npm: Installing dependencies ...Error creating new application. Removing generated directory `./app1`
Invalid Version: undefined


Stack Trace and Error Report: /var/folders/8y/n_lnlx7909v7tvgq5jtch1qm0000gn/T/error.dump.8043366e14bba2eb95376c7651bb3a8c.log
```

Log file contents:

```
=================================================================================

ENV Summary:

  TIME: Wed Feb 27 2019 21:45:48 GMT+0300 (MSK)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node@8/8.14.1/bin/node
  - /usr/local/bin/ember
  - new
  - app1
  EXEC_PATH: /usr/local/Cellar/node@8/8.14.1/bin/node
  TMPDIR: /var/folders/8y/n_lnlx7909v7tvgq5jtch1qm0000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/opt/icu4c/sbin
  - /usr/local/opt/icu4c/bin
  - /usr/local/opt/node@8/bin
  - /Users/afuno/.rbenv/bin
  - /Users/afuno/.rbenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/X11/bin
  PLATFORM: darwin x64
  FREEMEM: 44527616
  TOTALMEM: 8589934592
  UPTIME: 253528
  LOADAVG: 1.88232421875,2.17431640625,2.1806640625
  CPUS:
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz - 2000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.33.0
  - node: 8.14.1
  - openssl: 1.0.2q
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.2.414.75
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Invalid Version: undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Invalid Version: undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:296:11)
    at compare (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:585:10)
    at Function.gte (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:634:10)
    at findPackageManager.then (/usr/local/lib/node_modules/ember-cli/lib/tasks/npm-task.js:165:20)
    at tryCatcher (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

=================================================================================
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.8.0
http_parser: 2.8.0
node: 8.14.1
v8: 6.2.414.75
uv: 1.23.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.33.0
napi: 3
openssl: 1.0.2q
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
os: darwin x64
6.4.1
1.12.3
```

**Comment by jderr-mx** [comment] 2019-02-27 19:10
I am having the same error, same stacktrace

```
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.13.0
```

**Comment by kellyselden** [comment] 2019-02-27 20:42
@rwjblue I'm a little confused about how this was working https://github.com/ember-cli/ember-cli/search?q=npmVersion&unscoped_q=npmVersion

from https://github.com/ember-cli/ember-cli/pull/8100

**Comment by aclarembeau** [comment] 2019-02-27 22:19
Same error, worked by commenting 
on this file: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js
`// if (semver.gte(this.npmVersion, '5.0.0')) {`
I don't know why, but `this.npmVersion` is undefined in the code. 
By the way, I don't know where does this variable come from (as it's not set in the file).

**Comment by efx** [comment] 2019-02-28 17:54
Also observing this with `ember addon foo`.

**Comment by ppcano** [comment] 2019-02-28 18:38
https://github.com/ember-cli/ember-octane-blueprint/issues/52 looks the same error.

**Comment by kellyselden** [comment] 2019-02-28 19:47
Workarounds while this is getting fixed:

* `ember new my-app --yarn`
* `ember new my-app --skip-npm && cd my-app && npm install`
  * this means that you must also replace `ember install my-addon` with `npm install my-addon --save-dev && ember generate my-addon`

**Comment by Sanunez** [comment] 2019-02-28 20:10
> Workarounds while this is getting fixed:
> 
> * `ember new my-app --yarn`
> * `ember new my-app --skip-npm && cd my-app && npm install`
>   
>   * this means that you must also replace `ember install my-addon` with `npm install my-addon --save-dev && ember generate my-addon`

I was able to get the below to successfully create a new application.
`ember new my-app --skip-npm && cd my-app && npm install`

**Comment by rwjblue** [comment] 2019-02-28 20:12
Sorry about this y'all, working on a patch now...

**Comment by NullVoxPopuli** [comment] 2019-02-28 20:13
do we know what the root of the issue is?

**Comment by rwjblue** [comment] 2019-02-28 20:42
Should be fixed by https://github.com/ember-cli/ember-cli/pull/8467, once reviewed + approved I'll do a release...

**Comment by NullVoxPopuli** [comment] 2019-03-01 14:48
I confirm that the default blueprint works `npx ember-cli new my-app`

**Comment by kellyselden** [comment] 2019-03-01 14:49
Thanks everyone!

**Closed by kellyselden** 2019-03-01 14:49 UTC
