### ISSUE TITLE
Getting corrupted font assets in ember-cli 2.4.0

### ISSUE THREAD

**Issue by holandes22** [ember-cli/ember-cli#5538] opened 2016-03-01 08:38 UTC
After upgrading to 2.4.0 I started getting font errors in chrome and FF console:

```
Failed to decode downloaded font: http://localhost:4200/assets/themes/default/assets/fonts/icons.woff2

OTS parsing error: incorrect entrySelector for table directory
```
which turn into broken icons. I use semantic-ui, so those come from that library (via semantic-ui-ember addon)

A difference I spotted between 2.3 and 2.4 is in the console output of the ember server command:

2.3 prints
```
...
SourceMapConcat: Concat: Vendor               | 394ms
...
```

whereas 2.4 prints
```
...
SourceMapConcat: Concat: Vendor /assets/ve... | 289ms
...
```

I checked the file sizes of the fonts and there is difference between the source and the destination:

```
$ ls -lah bower_components/semantic-ui/dist/themes/default/assets/fonts/
total 716K
drwxr-xr-x 2 pablo users 4.0K Jan  8 06:45 .
drwxr-xr-x 4 pablo users 4.0K Mar  1 10:13 ..
-rw-r--r-- 1 pablo users  60K Jan  8 06:45 icons.eot
-rw-r--r-- 1 pablo users  92K Jan  8 06:45 icons.otf
-rw-r--r-- 1 pablo users 307K Jan  8 06:45 icons.svg
-rw-r--r-- 1 pablo users 120K Jan  8 06:45 icons.ttf
-rw-r--r-- 1 pablo users  70K Jan  8 06:45 icons.woff
-rw-r--r-- 1 pablo users  56K Jan  8 06:45 icons.woff2

$ ls -lah dist/assets/themes/default/assets/fonts/
total 996K
drwxr-xr-x 2 pablo users 4.0K Mar  1 10:15 .
drwxr-xr-x 4 pablo users 4.0K Mar  1 10:15 ..
-rw-r--r-- 1 pablo users 109K Mar  1 10:24 icons.eot
-rw-r--r-- 1 pablo users 175K Mar  1 10:24 icons.otf
-rw-r--r-- 1 pablo users 307K Mar  1 10:24 icons.svg
-rw-r--r-- 1 pablo users 154K Mar  1 10:24 icons.ttf
-rw-r--r-- 1 pablo users 130K Mar  1 10:24 icons.woff
-rw-r--r-- 1 pablo users 103K Mar  1 10:24 icons.woff2
```

You can see there is difference in the total size of 280K (bigger in dist) for some reason

**Comment by floqqi** [comment] 2016-03-01 08:55
I can confirm that issue using ember-cli-materialize (Roboto Fonts, Material Design Icons).

**Comment by charlatan154** [comment] 2016-03-01 09:54
same issue with font-awesome.
`Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.woff2?v=4.5.0
?fit=fu-0:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
?fit=fu-0:1 Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.woff?v=4.5.0
?fit=fu-0:1 OTS parsing error: incorrect file size in WOFF header
?fit=fu-0:1 Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.ttf?v=4.5.0
?fit=fu-0:1 OTS parsing error: incorrect entrySelector for table directory`

**Comment by rwjblue** [comment] 2016-03-01 12:06
Can someone please provide a reproduction repo that works in 2.3.0 but not in 2.4.0?

**Comment by holandes22** [comment] 2016-03-01 12:16
You can clone my repo.

Latest commit is the ember-cli upgrade, if you checkout to the one before that the issue goes away

https://github.com/holandes22/kube-admin

**Comment by holandes22** [comment] 2016-03-01 12:20
Actually give a few minutes, will try to set up sample repo without all the noise

**Comment by rwjblue** [comment] 2016-03-01 12:29
Thank you

**Comment by holandes22** [comment] 2016-03-01 12:37
@rwjblue please checkout https://github.com/holandes22/bad-fonts

2nd commit had the fonts working with ember-cli 2.3.0

Latest commit has broken fonts after upgrade to 2.4.0

**Comment by urbany** [comment] 2016-03-01 13:10
I'm getting the same warnings on 2.4.0 and everything was working perfectly with 2.3.0.
Using fonts from https://github.com/martndemus/ember-cli-font-awesome

**Comment by vomchik** [comment] 2016-03-01 14:08
Same problem. I use ember-cli-semantic-ui

**Comment by rwjblue** [comment] 2016-03-01 14:25
I will try to dig into this later this afternoon if someone else doesn't beat me to it. 

I'm guessing it is related to one of the two changes to app.import that we did during the 2.4 cycle (links are in the change log).

**Comment by stefanpenner** [comment] 2016-03-01 15:05
my guess is they are being merged...

**Comment by stefanpenner** [comment] 2016-03-01 15:08
i'll take a look this morning

**Comment by kpfefferle** [comment] 2016-03-01 15:58
This issue is also easily reproduced with my octicons addon (try running the dummy app):
https://github.com/kpfefferle/ember-cli-octicons

**Comment by bierdybard** [comment] 2016-03-01 16:31
Confirming. If it helps, here is a listing of dist/fonts/* as built by Ember-CLI 2.3 and then Ember-CLI 2.4:

drwxr-xr-x  8 my_user  staff     272 Mar  1 10:04 .
drwxr-xr-x  9 my_user  staff     306 Mar  1 10:04 ..
-rw-r--r--  1 my_user  staff  109688 Mar  1 10:14 FontAwesome.otf
-rw-r--r--  1 my_user  staff   70807 Mar  1 10:14 fontawesome-webfont.eot
-rw-r--r--  1 my_user  staff  365616 Mar  1 10:14 fontawesome-webfont.svg
-rw-r--r--  1 my_user  staff  142072 Mar  1 10:14 fontawesome-webfont.ttf
-rw-r--r--  1 my_user  staff   83588 Mar  1 10:14 fontawesome-webfont.woff
-rw-r--r--  1 my_user  staff   66624 Mar  1 10:14 fontawesome-webfont.woff2

drwxr-xr-x  8 my_user  staff     272 Mar  1 10:25 .
drwxr-xr-x  9 my_user  staff     306 Mar  1 10:25 ..
-rw-r--r--  1 my_user  staff  209808 Mar  1 10:25 FontAwesome.otf
-rw-r--r--  1 my_user  staff  129145 Mar  1 10:25 fontawesome-webfont.eot
-rw-r--r--  1 my_user  staff  365616 Mar  1 10:25 fontawesome-webfont.svg
-rw-r--r--  1 my_user  staff  183338 Mar  1 10:25 fontawesome-webfont.ttf
-rw-r--r--  1 my_user  staff  155862 Mar  1 10:25 fontawesome-webfont.woff
-rw-r--r--  1 my_user  staff  124092 Mar  1 10:25 fontawesome-webfont.woff2

**Comment by stefanpenner** [comment] 2016-03-01 16:38
bisect suggests 5953a319ae7afa243554561fdcdc1079a1791912

**Comment by stefanpenner** [comment] 2016-03-01 16:41
looks like something is maybe funky with `stew.map`

**Comment by stefanpenner** [comment] 2016-03-01 16:49
Ah, so it seems broccoli persistent filter is converting the binary to ascii causing this issue.

**Comment by rwjblue** [comment] 2016-03-02 01:48
The fix was merged (in #5540), this issue is fixed on master.  I'll try to release a 2.4.1 tonight or tomorrow morning...

**Closed** 2016-03-02 02:16 UTC

**Comment by holandes22** [comment] 2016-03-02 06:38
@rwjblue @stefanpenner thank you very much!

**Comment by gim-m** [comment] 2016-03-02 21:39
Awesome! I was pulling my hair out on this one. Thanks for fixing!

**Comment by crodriguez1a** [comment] 2016-03-08 13:08
:+1:

**Comment by milosb793** [comment] 2016-11-08 14:33
I got problem too on Ember Cli 2.9.1. After running these commands: 
```
1. Installed ember-font-awesome by running ember install ember-font-awesome
2. Run bower install font-awesome --save to account for issue 
3. Added {{fa-icon "camera"}} to my application.hbs file
```
I was asked somewhere which version should it install, 4.7.0 or 4.5.0, only 4.5.0 worked for me, and that solved my problem. 

reference: https://github.com/martndemus/ember-font-awesome/issues/89

**Comment by nathanhammond** [comment] 2016-11-08 17:32
@milosb793 This is unrelated to Ember CLI and this issue. Font Awesome is the library which has versions 4.5.0 and 4.7.0. If only one of them is working you should address it at `ember-font-awesome`, not here. Also, please open new issues instead of adding on to old issues. It helps keep old threads less confusing when being referenced by people who discover them via Google.

Best of luck!

**Comment by nathanhammond** [comment] 2016-11-08 17:32
@milosb793 This is unrelated to Ember CLI and this issue. Font Awesome is the library which has versions 4.5.0 and 4.7.0. If only one of them is working you should address it at `ember-font-awesome`, not here. Also, please open new issues instead of adding on to old issues. It helps keep old threads less confusing when being referenced by people who discover them via Google.

Best of luck!
