### ISSUE TITLE
Unable to use Ember Leaflet with latest Ember CLI

### ISSUE THREAD

**Issue by backspace** [ember-cli/ember-cli#8693] opened 2019-06-11 03:39 UTC
Hello, all! I’m bringing this here from Discord at the [suggestion of @rwjblue](https://discordapp.com/channels/480462759797063690/486548111221719040/587448662435823666). A few weeks ago, I started a new Octane application (very exciting, by the way, thanks to everyone who’s worked so hard) and [added Ember Leaflet](https://github.com/backspace/pole-barcodes/commit/c30356c3e67a944e0d96561a49c8fdcb229ae755) with no trouble. This past weekend, I started a different application with a fresh Octane blueprint but when I tried to use Ember Leaflet, I got this error:

```
Could not find module `ember-leaflet/templates/leaflet-map` imported from `ember-leaflet/components/leaflet-map`
```

I suspected that the culprit would be one of the Ember-related projects in the `package.json` from the newest blueprint, so I substituted them with versions from my older application until the problem went away. I found that I was able to use Ember Leaflet as expected when I switched `ember-cli` from `github:ember-cli/ember-cli#5bb062af85cebdf7dbc77132860dc2547fc7cfa4` to `github:ember-cli/ember-cli#5c9bc9b4ef3d6ff5d886fff6f2d95f7373acc7e9`.

You can see this reproduced with [this example repository](https://github.com/backspace/ember-cli-8633-ember-leaflet):

1. I added an acceptance test that looks for a string to be rendered in the application template and [it passed](https://travis-ci.com/backspace/ember-cli-8633-ember-leaflet/builds/115028090#L499).
2. After I [added Ember Leaflet and inserted the map component before the searched-for string](https://github.com/backspace/ember-cli-8633-ember-leaflet/commit/9e22895ef244d87811bc462e51afca20e9b3a90a), the [test failed](https://travis-ci.com/backspace/ember-cli-8633-ember-leaflet/jobs/206940156#L494-L513).
3. When I [changed to the older Ember CLI build](https://github.com/backspace/ember-cli-8633-ember-leaflet/commit/40890be73d1f05b361f9c46d193a5dccc8c224fe), the [test went back to passing](https://travis-ci.com/backspace/ember-cli-8633-ember-leaflet/jobs/206941324#L521).

@rwjblue suggested that it was #8633 that introduced this problem.

Let me know if I can provide any other details that might help!

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.11.0-beta.3
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.16.0
```

**Comment by rwjblue** [comment] 2019-06-11 13:39
For background context, `ember-leaflet` (and [a few other addons](https://emberobserver.com/code-search?codeQuery=treeForAddonTemplates)) are leveraging the `treeForAddonTemplates` hook which is no longer invoked as of #8633.

In `ember-leaflet`'s case, they are using `treeForAddonTestTemplates` as a way to hook into the build pipeline to provide a custom set of templates depending on the Ember version in use (they have separate templates for < Ember 2.3).

**Comment by svparijs** [comment] 2019-08-07 05:44
Hi guys, running into the same issue here. Any idea's on how to fix this. The example repo seems to work with a fixed version. Is there like a function to enable the `treeForAddonTemplates` or what  should I do to get the maps working?

**Comment by backspace** [comment] 2019-08-16 21:36
I don’t have any suggestions other than using the older Ember CLI version, is that something unworkable in your situation?

**Comment by rwjblue** [comment] 2019-08-17 01:27
We need to fix it here, and provided a useful deprecation but ultimately ember-leaflet should update (will need to anyways to fix the deprecation) to do the work it’s doing in treeForAddon.

**Comment by veebs** [comment] 2019-08-20 09:56
I think I've got a similar issue with [ember-bootstrap](https://github.com/kaliber5/ember-bootstrap/issues/881)

**Comment by rwjblue** [comment] 2019-08-20 15:34
Aye, I think at the moment any addon expecting `treeForAddonTemplates` to be called will have this issue.

**Comment by simonihmig** [comment] 2019-08-25 11:10
@veebs contributed a [PR](https://github.com/kaliber5/ember-bootstrap/pull/883) for `ember-bootstrap` to fix that problem. But that seems to require doing the template transformations we need to do both in `treeForAddonTemplates` (for older Ember CLI versions) *and* in `treeForAddon` (to fix the problem in latest Ember CLI beta). 

Is that expected? Or can we do that just in `treeForAddon` for *all* Ember CLI versions? 

Asking because there was a previous [commit](https://github.com/kaliber5/ember-bootstrap/pull/883/commits/557f84c2867a0e7b591d7f001ce858be526f4b87) doing that just in `treeForAddon`, but that was breaking the build for Ember CLI 3.11 (and probably older versions) 🤔

**Comment by rwjblue** [comment] 2019-08-25 15:05
@simonihmig - Off the cuff, I think you can do it universally in `treeForAddon` as long as you implement `treeForAddonTemplates` as `return null`, but I haven’t tested that.

**Comment by backspace** [comment] 2019-08-25 20:15
I submitted [this PR](https://github.com/miguelcobain/ember-leaflet/pull/342) to fix this in Ember Leaflet, it definitely works for me locally, hopefully it’s a proper approach!

**Comment by veebs** [comment] 2019-08-26 22:57
@rwjblue,  I've tried your suggestion

![image](https://user-images.githubusercontent.com/367073/63728883-a502dd00-c8a8-11e9-90a4-c85dbe32e56f.png)

Unfortunately that did not work.  Seems our template/component paths were not correctly found even through we did the manipulation in `treeForAddon`.

**Comment by jelhan** [comment] 2019-09-11 21:03
> We need to fix it here

Any updates on this one? Will this be considered a blocker for a stable release? Or should we expect v3.13 to be shipped with that regression? Just wondering if we should prepare a bug fix release for Ember Bootstrap or if this wouldn't be necessary.

**Comment by linearza** [comment] 2019-10-01 14:34
Just ran into this as well after upgrading to 3.13.1

**Comment by m3l1x** [comment] 2019-10-30 13:08
@rwjblue will this behavior get fixed with the stable 3.14?

**Comment by rwjblue** [comment] 2019-10-30 19:19
I don't think anyone has had time to work on it yet :(

**Comment by Yelinz** [comment] 2020-02-24 08:17
Having problems with it in [ember-a11y](https://github.com/ember-a11y/ember-a11y/blob/master/index.js#L53) some kind of information of this deprecation would be really nice.

**Comment by locks** [comment] 2023-07-24 23:40
Closing as stale. If someone is still running into this please let us know!

**Closed by locks** 2023-07-24 23:40 UTC
