### ISSUE TITLE
ember 3.22 server died when asset not present

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#9389] opened 2020-11-25 23:11 UTC
Windows 10
Project folder is on a RAM disk

```
ember version --verbose && yarn --version && node --version
ember-cli: 3.22.0
node: 12.20.0
v8: 7.8.279.23-node.45
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 72
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: win32 x64
1.22.10
v12.20.0
```

`ember serve`
Add `<img>` to template where the `src` png is missing from disk:

```
file changed templates\intro.hbs

Build successful (2499ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime >= 5%)                                                                                | Total (avg)
---------------------------------------------------------------------------------------------------------------+--------------------------------
Package /assets/vendor.js (1)                                                                                  | 313ms
BroccoliMergeTrees (19)                                                                                        | 284ms (14 ms)
Concat: Vendor Styles/assets/vendor.css (1)                                                                    | 263ms
Packaged Application Javascript (1)                                                                            | 260ms

EPERM: operation not permitted, lstat 'E:\projects\ember-presenter\public\assets\dentanomics.png'


Stack Trace and Error Report: C:\Users\Einstein\AppData\Local\Temp/error.dump.37b307bf93151b5c13718afeda1d006f.log
(node:27240) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'E:\projects\ember-presenter\public\assets\dentanomics.png'
(node:27240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

From this point on, `ember serve` does not respond to file system changes and requires restart.

**Comment by locks** [comment] 2023-08-09 03:02
Closing the issue as I couldn't reproduce the issue (v5.1). Let us know if you're still encountering this problem!

**Closed by locks** 2023-08-09 03:02 UTC
