### ISSUE TITLE
Sometimes "ember new" doesn't switch into the project directory for "npm install"

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#4175] opened 2015-05-28 13:58 UTC
Sometimes (very rarely) when running `ember new <project-name>`, ember-cli does not switch to the new project directory before trying to install the npm modules.

At least this is, how I would explain this output:

```
jan@ubuntu:~/code$ ember new citb
version: 0.2.5
0.2.5

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
ENOENT: no such file or directory, open '/home/jan/code/package.json'
Error: ENOENT: no such file or directory, open '/home/jan/code/package.json'
    at Error (native)
```

Note how the path is `/home/jan/code/package.json` and not `/home/jan/code/citb/package.json`.

Then running `rm -rf citb` and `ember new citb` works.

**Comment by stefanpenner** [comment] 2015-05-28 14:34
questions:

* which os
* which version of node
* which version of npm

**Comment by rwjblue** [comment] 2015-05-29 01:33
duplicate of https://github.com/ember-cli/ember-cli/issues/3776

**Closed by rwjblue** 2015-05-29 01:34 UTC
