### ISSUE TITLE
`ember test --server` stopped working

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#6169] opened 2016-08-10 18:18 UTC
I have a project in which ember test used to work prior to the latest ember-cli release, and now it stopped working
---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 5.12.0
v8: 4.6.85.32
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2h
os: darwin x64
```

I get this:
```
not ok 1 Browser "phantomjs /Users/rotemy/workspace/src/opensource/vmalloc/backslash/webapp/node_modules/testem/assets/phantom.js http://localhost:7357/6208/tests/index.html?hidepassed" failed to connect. testem.js not loaded?
```

To reproduce, clone https://github.com/getslash/backslash, branch *develop*, and run ember from inside the `webapp` subdirectory of the project...

**Comment by nathanhammond** [comment] 2016-08-10 19:59
Hey @vmalloc! You just need to re-init on top of your current project directory. [This is an incomplete accounting of the changes you needed to make.](https://github.com/getslash/backslash/commit/73dc211ca3de5ffe446a5e6e3a8c7e072ffa2c2f)

I'm closing this issue as likely not a bug but _please feel encouraged to reopen it_ if upon further investigation on your side you discover that it may in fact be a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you continue having issues!

**Closed by nathanhammond** 2016-08-10 19:59 UTC
