### ISSUE TITLE
ENOENT problem with spin.js

### ISSUE THREAD

**Issue by ctataryn** [ember-cli/ember-cli#6184] opened 2016-08-16 21:05 UTC
Having an issue with ember-cli on Win7, when I try to either `build` or `serve` I recieve the following error:

```
$ ember s --proxy http://localhost:8080
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to -hash`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to-hash`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to-hash`.
Proxying to http://localhost:8080
Livereload server on http://localhost:49155
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'C:\workspace\eReg_workspace\tpr-ereg-ui\tmp\source_map_concat-input_base_path-WUB8FNep.tmp\0\bower_components\spin.js\ spin.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\ind ex.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\brocco li-caching-writer\index.js:109:65)
    at C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\r ead_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_mo dules\broccoli-plugin\index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccol i-caching-writer\index.js:18:10)
    at new ConcatWithMaps (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\concat.js:24:17)
    at module.exports (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\node_modules\broccoli-concat\index.js:26:10)
    at EmberApp.concatFiles (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:346:10)
    at EmberApp.javascript (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1212:12)
    at EmberApp.toArray (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1564:10)
    at EmberApp.toTree (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\lib\broccoli\ember-app.js:1586:30)
    at module.exports (C:\workspace\eReg_workspace\tpr-ereg-ui\ember-cli-build.js:27:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\workspace\eReg_workspace\tpr-ereg-ui\node_modules\ember-cli\lib\models\builder.js:55:19)
```

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.5.0
node: 4.2.4
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
os: win32 x64
```

**Comment by ctataryn** [comment] 2016-08-16 21:43
Hmmm, appears to be a problem with an in-house addon that our project depends on. It's possible the in-house addon's blue print doesn't declare the `spin.js` dependency (which is really a transitive dependency of `ember-spin-spinner`). I'll report back.

**Comment by nathanhammond** [comment] 2016-08-17 03:07
That's a `.import` failure. Can you update to Ember CLI 2.7 and change the `spin.js` import to use `this.import` instead? Is it a nested addon? I _strongly_ suspect that this is not an issue in Ember CLI (having seen the exact stack trace a thousand times by now).

So, with that, I'm closing this issue as likely not a bug but _please feel encouraged to reopen it_ if upon further investigation on your side you discover that it may in fact be a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you'd like to pick the brains of many of the wonderful people in our community!

**Closed by nathanhammond** 2016-08-17 03:07 UTC

**Comment by ctataryn** [comment] 2016-08-17 19:35
More context: I'm building our Ember UI from a Jenkins job. Our usual build goes something like this:

```
rm -rf bower_components node_modules tmp dist 
npm install
bower install
ember build --environment="production"
```
We have an in-house addon that depends on `ember-spin-spinner`.  The app we are building uses that in-house addon and includes it as dependency in `package.json` by specifying the url of where it lives in our git repo.

The problem is, ember doesn't resolve the bower dependencies. For instance, `spin.js` is used by our in-house addon transitively has via `ember-spin-spinner`.

The only way to remedy this is to either:

1. add `spin.js` directly to our project's `bower.json` (which doesn't seem right)
1. modify our build to execute an `ember g[enerate] <our-in-house-addon>` before we execute `ember build`

Is option 2 typically what you have to do when you are using an ember addon in your project?  I guess in my heart of hearts I assumed that the `ember-cli` compiler would say "oh, that's an addon, I should now add all of the dependencies from that addon to the project" without me explicitly having to do so using `ember generate`...

**Comment by nathanhammond** [comment] 2016-08-17 20:57
Nested addons are not allowed to install bower components for themselves. The nested addon should have a blueprint matching its own name which invokes `addBowerPackageToProject` which installs it in the host application, not into the addon's scope.

This is intentional as most libraries installed via bower are globals code and that could easily end up clobbering things if included multiple times. There is an open RFC on this topic: https://github.com/ember-cli/rfcs/pull/63

**Comment by stefanpenner** [comment] 2016-08-18 01:21
> add spin.js directly to our project's bower.json (which doesn't seem right)

This doesn't seem right (and it does feel bad) but in the world of bower, this is more or less what needs to happen today. :(

@nathanhammond's recommendation for using a blueprint is how addon installations can ghetto hack install there bower dependencies in the project they are installed in. Again although not ideal, in the world of bower that is what we got.

Let me know if the above doesn't mitigate the issue for now.

**Comment by ctataryn** [comment] 2016-08-18 14:48
Thanks, I guess `ember g` is the way to go. I won't add it to my build, but I'll expect devs to do it before they commit.

**Comment by stefanpenner** [comment] 2016-08-18 15:36
@ctataryn it is on our radar to make this less crappy. Turns out fixing package managers is lots of work :P
