### ISSUE TITLE
Acceptance tests in addon are not run.

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#3934] opened 2015-04-20 16:46 UTC
The test helper start-app points to the top level directory rather than the dummy app.

```js
import Ember from 'ember';
import Application from '../../app';
import Router from '../../router';
import config from '../../config/environment';
```

Wouldn't it be better to get it to point to the dummy app as that is where I want to test my addon.

**Comment by stefanpenner** [comment] 2015-04-20 16:51
actually, it points to the right thing. Although the on-disk position for the dummy app is slightly different then the app.

**Comment by stefanpenner** [comment] 2015-04-20 16:52
```
dummy/app: Module
dummy/config/environment: Module
dummy/initializers/app-version: Module
dummy/initializers/export-application-global: Module
dummy/initializers/foo: Module
dummy/my-cool-addon/tests/modules/my-cool-addon/initializers/foo.jshint: Module
dummy/router: Module
dummy/routes/application: Module
dummy/templates/application: Module
dummy/tests/acceptance/foo-test: Module
dummy/tests/acceptance/foo-test.jshint: Module
dummy/tests/app.jshint: Module
dummy/tests/helpers/resolver: Module
dummy/tests/helpers/resolver.jshint: Module
dummy/tests/helpers/start-app: Module
dummy/tests/helpers/start-app.jshint: Module
dummy/tests/router.jshint: Module
dummy/tests/routes/application.jshint: Module
dummy/tests/test-helper: Module
dummy/tests/test-helper.jshint: Module
dummy/tests/unit/initializers/foo-test: Module
dummy/tests/unit/initializers/foo-test.jshint: Module
```

**Comment by QuantumInformation** [comment] 2015-04-20 16:54
I'm getting a not resolved error on windows for it. Using cli 0.2.2

**Comment by QuantumInformation** [comment] 2015-04-20 16:56
```
Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:7357/assets/test-support.js:5539:11)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:31:14)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:40:24)
    at http://localhost:7357/assets/test-support.js:5545:16: Could not find module `ember-cli-test-recorder/tests/helpers/start-app` imported from `dummy/tests/acceptance/test-playback-test`@ 2 ms
Source: 	
Error: Could not find module `ember-cli-test-recorder/tests/helpers/start-app` imported from `dummy/tests/acceptance/test-playback-test`
    at requireFrom (http://localhost:7357/assets/vendor.js:119:13)
    at reify (http://localhost:7357/assets/vendor.js:106:22)
    at mod.state (http://localhost:7357/assets/vendor.js:149:17)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:40:24)
    at http://localhost:7357/assets/test-support.js:5545:16
```

**Comment by stefanpenner** [comment] 2015-04-20 16:58
it seems like you code can't find `start-app` module

**Comment by QuantumInformation** [comment] 2015-04-20 17:01
Oh, right my bad.

My test is trying this:
```js
import startApp from 'ember-cli-test-recorder/tests/helpers/start-app';

```

**Comment by stefanpenner** [comment] 2015-04-20 17:12
strange, maybe a windowsism? I have an add-on here that seems to work as expected

**Comment by stefanpenner** [comment] 2015-04-20 17:12
> I'm getting a not resolved error on windows for it. Using cli 0.2.2

can you try a fresh 0.2.3 addon and report back?

**Comment by QuantumInformation** [comment] 2015-04-20 17:42
Sure will do.

**Comment by QuantumInformation** [comment] 2015-04-20 18:30
oh.. got this after running ember init:

UNKNOWN, open 'C:\Users\Laptop\AppData\Roaming\bower\cache\registry\bower.herokuapp.com\lookup\ember_98e89'

**Comment by QuantumInformation** [comment] 2015-04-20 18:31
I done these steps before:

```
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli@0.2.3
npm install ember-cli@0.2.3 --save-dev
rm -rf node_modules bower_components dist tmp
npm install
bower install
```

**Comment by QuantumInformation** [comment] 2015-04-20 18:40
Anyway I still get the same test error after the upgrade:

**Comment by stefanpenner** [comment] 2015-04-20 22:04
@QuantumInformation can you share the repo, (just zip it all up) i wanna see whats going wrong for you.

**Comment by QuantumInformation** [comment] 2015-04-21 07:42
@stefanpenner sure its this one:

https://github.com/QuantumInformation/ember-cli-test-recorder

**Comment by QuantumInformation** [comment] 2015-05-14 15:40
I just checked out my project on a mac and it still doesn't run my test:

![image](https://cloud.githubusercontent.com/assets/216566/7635276/f3fce94c-fa57-11e4-9905-b0cc69b4e23e.png)

**Comment by QuantumInformation** [comment] 2015-05-19 12:51
I still have this issue in ember cli 0.2.5.

**Comment by stefanpenner** [comment] 2015-05-19 15:03
The following just worked for me

1. git clone https://github.com/QuantumInformation/ember-cli-test-recorder
2. cd ember-cli-test-recorder
3. npm i && bower i
4. npm test

the result was several test failures, but each of the test scenarios did run

Have you nom'd ?

**Comment by QuantumInformation** [comment] 2015-05-19 15:07
The test I was trying was 'ember test'. Is that not supposed to work?

-- 

Kind regards
Nikos

**Comment by stefanpenner** [comment] 2015-05-19 15:08
just confirmed, `ember test` also works for me.

What version of phantomjs do you have?

**Comment by QuantumInformation** [comment] 2015-05-19 19:29
My apologies, I thought I had it installed but apparently it is not.

-- 

Kind regards
Nikos

**Comment by stefanpenner** [comment] 2015-05-19 20:10
> My apologies, I thought I had it installed but apparently it is not.

hmm, we should provide a better error. This is a crappy UX.
Although I believe this is something testem should do. any thoughts @johanneswuerbach ?

**Comment by johanneswuerbach** [comment] 2015-05-19 20:52
Yes, that should be handled in testem, just created an issue for that.

**Comment by stefanpenner** [comment] 2015-05-19 21:35
thanks

**Comment by QuantumInformation** [comment] 2015-05-20 16:09
Thanks guys!

**Comment by stefanpenner** [comment] 2015-05-22 00:24
going to close this, as it isn't a bug, but a "nice thing". We will eventually get it when testem gets fixed

**Comment by QuantumInformation** [comment] 2015-06-29 19:30
Sorry to drag this up again after so long, but have been busy with other projects,

Now that I have phantomJs installed I'm trying to run the test again but the import path is not working:

![image](https://cloud.githubusercontent.com/assets/216566/8416397/5bab9ebc-1e9d-11e5-83cc-92a5546a9688.png)

with error:

`Error: Could not find module `ember-cli-test-recorder/tests/helpers/start-app` imported from `dummy/tests/acceptance/test-playback-test``

**Comment by QuantumInformation** [comment] 2015-06-29 19:31
I'm on cli 0.2.5, I'll try again with 0.2.7

**Comment by QuantumInformation** [comment] 2015-06-29 19:40
I get the same error with 0.2.7

**Comment by QuantumInformation** [comment] 2015-06-29 19:41
using phantomjs -v
1.9.8

**Comment by stefanpenner** [comment] 2015-06-29 19:48
@QuantumInformation what ember/ember-data version do you have?

**Comment by QuantumInformation** [comment] 2015-06-29 19:50
Hi Stephan! I just done an upgrade:

[image: Inline images 1]

**Comment by stefanpenner** [comment] 2015-06-29 19:50
> [image: Inline images 1]

?

**Comment by QuantumInformation** [comment] 2015-06-29 19:57
Oh, its ember data beta 18 and ember 1.12.0

**Comment by stefanpenner** [comment] 2015-06-29 20:39
* are there any errors in the console?
* can you share a repo that reproduces this?

**Comment by QuantumInformation** [comment] 2015-06-29 21:05
I can't see any errors on the console. It is on my ember test recorder repo.

https://github.com/QuantumInformation/ember-cli-test-recorder

I am running this on a Mac.

The demo app runs as expected in ember server mode.

![image](https://cloud.githubusercontent.com/assets/216566/8418404/e7781ee0-1eaa-11e5-8cb2-5146d63fbf32.png)

**Comment by stefanpenner** [comment] 2015-06-29 21:40
> QuantumInformation

alright you should likely open a new issue. As this one is closed.

**Comment by stefanpenner** [comment] 2015-06-29 21:43
@QuantumInformation naviging to http://localhost:8881/tests clearly shows failures in the browser in server mode.

**Comment by stefanpenner** [comment] 2015-06-29 21:45
`Uncaught Error: Assertion Failed: calling set on destroyed object` It appears you have MutationObservers but are not cleaning them up between test runs.

**Comment by stefanpenner** [comment] 2015-06-29 21:48
the module you are looking for also doesn't exist at `<addon-name>` rather at `<dummy>

something like: `dummy/tests/helpers/start-app`

I suspect this was a bug in a old version of cli that is now fixed.

**Comment by QuantumInformation** [comment] 2015-06-29 21:51
Thank you, I thought that last error wasn't relevant, as I thought only the first one was the issue. 

The path is now fixed.

The only test I have is this below, I will investigate how to fix the issue. I havn't noticed this error in normal use of this addon.

```js
/**
 * This code inside this function has been generated from the test recorder, it is placed in here just to see if it
 * can play back what was recorded in the browser code recorder.
 */
test('Playback code', function (assert) {
//assume that the user starts  on index
  visit('inputs');
  andThen(function () {


  });

  stop();
});

```

**Comment by stefanpenner** [comment] 2015-06-29 21:59
> stop();

this is blocking the tests

https://github.com/QuantumInformation/ember-cli-test-recorder/blob/master/app/components/test-recorder.js#L231

needs to likely disconnect when the component is removed from the dom.

**Comment by stefanpenner** [comment] 2015-06-29 21:59
I believe all the ember-cli issues are dealt with, going to close this one.

**Comment by stefanpenner** [comment] 2015-06-29 22:00
If there is an ember-cli issue still, i apparently need it to be clearly explained.

**Closed by stefanpenner** 2015-06-29 21:59 UTC
Labels: pending-submitter-response

**Comment by QuantumInformation** [comment] 2015-06-29 22:17
Many thanks again for your time. I usually stop the tests running so I can have enough time to put my breakpoints in place before the browser shuts. But it doesn't work to good in this case.

**Comment by QuantumInformation** [comment] 2015-06-29 22:44
I see, the mutations must be fired when the component is removed. Hmm, theres a lot of dynamic mutationsObs set up, I'll need to maintain a reference to them all before destroy is called and then call disconnect.

**Comment by ahouchens** [comment] 2015-07-09 20:25
@stefanpenner This might already be an issue but ember g acceptance test inside of an addon has the incorrect startApp module location. It generates `import startApp from '{addon-name}/tests/helpers/start-app';` inside the acceptance test when it should be `import startApp from '../tests/helpers/start-app';
