### ISSUE TITLE
"ember new" installs npm-packages in app directory (node 6.3.1, Windows)

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#6109] opened 2016-07-26 16:37 UTC
When creating a new ember app, the packages that are supposed to go into node_modules end up in the app's main directory. This is under Windows, node 6.3.1, ember-cli 2.6.3 and ember-cli 2.7.0.

```
T:\>ember version --verbose
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64

T:\>ember new apptest
[...]
T:\>dir apptest
 Volume in Laufwerk T: hat keine Bezeichnung.
 Volumeseriennummer: 3C42-75E8

 Verzeichnis von T:\apptest

26.07.2016  18:14    <DIR>          .
26.07.2016  18:14    <DIR>          ..
26.07.2016  18:10                60 .bowerrc
26.07.2016  18:10               543 .editorconfig
26.07.2016  18:10               280 .ember-cli
26.07.2016  18:10               247 .gitignore
26.07.2016  18:10               518 .jshintrc
26.07.2016  18:10               267 .travis.yml
26.07.2016  18:10                37 .watchmanconfig
26.07.2016  18:10    <DIR>          abbrev
26.07.2016  18:12    <DIR>          accepts
26.07.2016  18:12    <DIR>          acorn
26.07.2016  18:12    <DIR>          after
26.07.2016  18:11    <DIR>          align-text
26.07.2016  18:12    <DIR>          alter
26.07.2016  18:11    <DIR>          amd-name-resolver
26.07.2016  18:11    <DIR>          amdefine
26.07.2016  18:11    <DIR>          ansi-escapes
26.07.2016  18:10    <DIR>          ansi-regex
26.07.2016  18:10    <DIR>          ansi-styles
26.07.2016  18:12    <DIR>          ansicolors
26.07.2016  18:10    <DIR>          app
26.07.2016  18:12    <DIR>          aproba
26.07.2016  18:12    <DIR>          are-we-there-yet
26.07.2016  18:12    <DIR>          argparse
26.07.2016  18:10    <DIR>          array-equal
26.07.2016  18:11    <DIR>          array-flatten
26.07.2016  18:12    <DIR>          array-to-error
26.07.2016  18:12    <DIR>          array-to-sentence
26.07.2016  18:12    <DIR>          arraybuffer.slice
26.07.2016  18:12    <DIR>          asn1
26.07.2016  18:12    <DIR>          assert-plus
26.07.2016  18:12    <DIR>          ast-traverse
26.07.2016  18:13    <DIR>          ast-types
26.07.2016  18:11    <DIR>          async
26.07.2016  18:10    <DIR>          async-disk-cache
26.07.2016  18:12    <DIR>          aws-sign2
26.07.2016  18:12    <DIR>          aws4
26.07.2016  18:10    <DIR>          babel-core
26.07.2016  18:11    <DIR>          babel-plugin-constant-folding
26.07.2016  18:11    <DIR>          babel-plugin-dead-code-elimination
26.07.2016  18:11    <DIR>          babel-plugin-eval
26.07.2016  18:11    <DIR>          babel-plugin-feature-flags
26.07.2016  18:11    <DIR>          babel-plugin-filter-imports
26.07.2016  18:10    <DIR>          babel-plugin-htmlbars-inline-precompile
26.07.2016  18:11    <DIR>          babel-plugin-inline-environment-variables
26.07.2016  18:11    <DIR>          babel-plugin-jscript
26.07.2016  18:11    <DIR>          babel-plugin-member-expression-literals
26.07.2016  18:11    <DIR>          babel-plugin-property-literals
26.07.2016  18:11    <DIR>          babel-plugin-proto-to-assign
26.07.2016  18:11    <DIR>          babel-plugin-react-constant-elements
26.07.2016  18:11    <DIR>          babel-plugin-react-display-name
26.07.2016  18:11    <DIR>          babel-plugin-remove-console
26.07.2016  18:11    <DIR>          babel-plugin-remove-debugger
26.07.2016  18:11    <DIR>          babel-plugin-runtime
26.07.2016  18:11    <DIR>          babel-plugin-undeclared-variables-check
26.07.2016  18:11    <DIR>          babel-plugin-undefined-to-void
26.07.2016  18:11    <DIR>          babylon
26.07.2016  18:12    <DIR>          backbone
26.07.2016  18:12    <DIR>          backo2
26.07.2016  18:10    <DIR>          balanced-match
26.07.2016  18:12    <DIR>          base64-arraybuffer
26.07.2016  18:12    <DIR>          base64id
26.07.2016  18:11    <DIR>          basic-auth
26.07.2016  18:12    <DIR>          benchmark
26.07.2016  18:12    <DIR>          better-assert
26.07.2016  18:10    <DIR>          binaryextensions
26.07.2016  18:12    <DIR>          bl
26.07.2016  18:10    <DIR>          blank-object
26.07.2016  18:12    <DIR>          blob
26.07.2016  18:12    <DIR>          bluebird
26.07.2016  18:11    <DIR>          body-parser
26.07.2016  18:12    <DIR>          boom
26.07.2016  18:11    <DIR>          bower
26.07.2016  18:11    <DIR>          bower-config
26.07.2016  18:11    <DIR>          bower-endpoint-parser
26.07.2016  18:10               183 bower.json
26.07.2016  18:14    <DIR>          bower_components
26.07.2016  18:10    <DIR>          brace-expansion
26.07.2016  18:12    <DIR>          breakable
26.07.2016  18:10    <DIR>          broccoli-asset-rev
26.07.2016  18:11    <DIR>          broccoli-asset-rewrite
26.07.2016  18:10    <DIR>          broccoli-babel-transpiler
26.07.2016  18:10    <DIR>          broccoli-caching-writer
26.07.2016  18:11    <DIR>          broccoli-clean-css
26.07.2016  18:10    <DIR>          broccoli-concat
26.07.2016  18:11    <DIR>          broccoli-config-loader
26.07.2016  18:11    <DIR>          broccoli-config-replace
26.07.2016  18:11    <DIR>          broccoli-file-creator
26.07.2016  18:11    <DIR>          broccoli-filter
26.07.2016  18:10    <DIR>          broccoli-funnel
26.07.2016  18:11    <DIR>          broccoli-funnel-reducer
26.07.2016  18:10    <DIR>          broccoli-jshint
26.07.2016  18:10    <DIR>          broccoli-kitchen-sink-helpers
26.07.2016  18:10    <DIR>          broccoli-merge-trees
26.07.2016  18:10    <DIR>          broccoli-persistent-filter
26.07.2016  18:10    <DIR>          broccoli-plugin
26.07.2016  18:11    <DIR>          broccoli-sane-watcher
26.07.2016  18:11    <DIR>          broccoli-slow-trees
26.07.2016  18:11    <DIR>          broccoli-source
26.07.2016  18:10    <DIR>          broccoli-sri-hash
26.07.2016  18:10    <DIR>          broccoli-uglify-sourcemap
26.07.2016  18:11    <DIR>          broccoli-viz
26.07.2016  18:11    <DIR>          broccoli-writer
26.07.2016  18:12    <DIR>          bser
26.07.2016  18:12    <DIR>          buffer-shims
26.07.2016  18:12    <DIR>          bytes
26.07.2016  18:13    <DIR>          callsite
26.07.2016  18:10    <DIR>          camelcase
26.07.2016  18:10    <DIR>          can-symlink
26.07.2016  18:11    <DIR>          cardinal
26.07.2016  18:12    <DIR>          caseless
26.07.2016  18:10    <DIR>          center-align
26.07.2016  18:10    <DIR>          chalk
26.07.2016  18:12    <DIR>          charm
26.07.2016  18:11    <DIR>          clean-base-url
26.07.2016  18:12    <DIR>          clean-css
26.07.2016  18:12    <DIR>          clean-css-promise
26.07.2016  18:10    <DIR>          cli
26.07.2016  18:11    <DIR>          cli-cursor
26.07.2016  18:11    <DIR>          cli-spinners
26.07.2016  18:11    <DIR>          cli-table
26.07.2016  18:12    <DIR>          cli-table2
26.07.2016  18:13    <DIR>          cli-usage
26.07.2016  18:11    <DIR>          cli-width
26.07.2016  18:10    <DIR>          cliui
26.07.2016  18:10    <DIR>          clone
26.07.2016  18:12    <DIR>          code-point-at
26.07.2016  18:12    <DIR>          colors
26.07.2016  18:12    <DIR>          combined-stream
26.07.2016  18:12    <DIR>          commander
26.07.2016  18:12    <DIR>          commoner
26.07.2016  18:12    <DIR>          component-bind
26.07.2016  18:12    <DIR>          component-emitter
26.07.2016  18:13    <DIR>          component-inherit
26.07.2016  18:11    <DIR>          compressible
26.07.2016  18:11    <DIR>          compression
26.07.2016  18:10    <DIR>          concat-map
26.07.2016  18:10    <DIR>          config
26.07.2016  18:11    <DIR>          configstore
26.07.2016  18:11    <DIR>          connect
26.07.2016  18:10    <DIR>          console-browserify
26.07.2016  18:12    <DIR>          console-control-strings
26.07.2016  18:12    <DIR>          consolidate
26.07.2016  18:11    <DIR>          content-disposition
26.07.2016  18:11    <DIR>          content-type
26.07.2016  18:11    <DIR>          convert-source-map
26.07.2016  18:11    <DIR>          cookie
26.07.2016  18:11    <DIR>          cookie-signature
26.07.2016  18:11    <DIR>          copy-dereference
26.07.2016  18:11    <DIR>          core-js
26.07.2016  18:12    <DIR>          core-object
26.07.2016  18:11    <DIR>          core-util-is
26.07.2016  18:12    <DIR>          cross-spawn
26.07.2016  18:12    <DIR>          cryptiles
26.07.2016  18:12    <DIR>          dashdash
26.07.2016  18:11    <DIR>          date-now
26.07.2016  18:12    <DIR>          debug
26.07.2016  18:10    <DIR>          decamelize
26.07.2016  18:12    <DIR>          defined
26.07.2016  18:12    <DIR>          defs
26.07.2016  18:12    <DIR>          delayed-stream
26.07.2016  18:12    <DIR>          delegates
26.07.2016  18:11    <DIR>          depd
26.07.2016  18:12    <DIR>          destroy
26.07.2016  18:11    <DIR>          detect-indent
26.07.2016  18:12    <DIR>          detective
26.07.2016  18:12    <DIR>          did_it_work
26.07.2016  18:11    <DIR>          diff
26.07.2016  18:11    <DIR>          dom-serializer
26.07.2016  18:11    <DIR>          domelementtype
26.07.2016  18:11    <DIR>          domhandler
26.07.2016  18:11    <DIR>          domutils
26.07.2016  18:11    <DIR>          dot-prop
26.07.2016  18:10    <DIR>          editions
26.07.2016  18:11    <DIR>          ee-first
26.07.2016  18:10    <DIR>          ember-ajax
26.07.2016  18:10    <DIR>          ember-cli
26.07.2016  18:10    <DIR>          ember-cli-app-version
26.07.2016  18:10    <DIR>          ember-cli-babel
26.07.2016  18:11    <DIR>          ember-cli-broccoli
26.07.2016  18:10               826 ember-cli-build.js
26.07.2016  18:10    <DIR>          ember-cli-dependency-checker
26.07.2016  18:11    <DIR>          ember-cli-get-component-path-option
26.07.2016  18:13    <DIR>          ember-cli-get-dependency-depth
26.07.2016  18:10    <DIR>          ember-cli-htmlbars
26.07.2016  18:10    <DIR>          ember-cli-htmlbars-inline-precompile
26.07.2016  18:10    <DIR>          ember-cli-inject-live-reload
26.07.2016  18:11    <DIR>          ember-cli-is-package-missing
26.07.2016  18:10    <DIR>          ember-cli-jshint
26.07.2016  18:11    <DIR>          ember-cli-legacy-blueprints
26.07.2016  18:11    <DIR>          ember-cli-normalize-entity-name
26.07.2016  18:11    <DIR>          ember-cli-path-utils
26.07.2016  18:11    <DIR>          ember-cli-preprocess-registry
26.07.2016  18:10    <DIR>          ember-cli-qunit
26.07.2016  18:10    <DIR>          ember-cli-release
26.07.2016  18:10    <DIR>          ember-cli-sri
26.07.2016  18:11    <DIR>          ember-cli-string-utils
26.07.2016  18:11    <DIR>          ember-cli-test-info
26.07.2016  18:10    <DIR>          ember-cli-uglify
26.07.2016  18:13    <DIR>          ember-cli-valid-component-name
26.07.2016  18:10    <DIR>          ember-cli-version-checker
26.07.2016  18:10    <DIR>          ember-data
26.07.2016  18:10    <DIR>          ember-export-application-global
26.07.2016  18:11    <DIR>          ember-inflector
26.07.2016  18:10    <DIR>          ember-load-initializers
26.07.2016  18:10    <DIR>          ember-qunit
26.07.2016  18:10    <DIR>          ember-resolver
26.07.2016  18:13    <DIR>          ember-router-generator
26.07.2016  18:10    <DIR>          ember-test-helpers
26.07.2016  18:11    <DIR>          ember-try
26.07.2016  18:12    <DIR>          ember-try-config
26.07.2016  18:10    <DIR>          ember-welcome-page
26.07.2016  18:11    <DIR>          encodeurl
26.07.2016  18:12    <DIR>          encoding
26.07.2016  18:12    <DIR>          engine.io
26.07.2016  18:12    <DIR>          engine.io-client
26.07.2016  18:12    <DIR>          engine.io-parser
26.07.2016  18:10    <DIR>          ensure-posix-path
26.07.2016  18:11    <DIR>          entities
26.07.2016  18:11    <DIR>          escape-html
26.07.2016  18:10    <DIR>          escape-string-regexp
26.07.2016  18:12    <DIR>          esprima
26.07.2016  18:12    <DIR>          esprima-fb
26.07.2016  18:11    <DIR>          esutils
26.07.2016  18:11    <DIR>          etag
26.07.2016  18:11    <DIR>          eventemitter3
26.07.2016  18:12    <DIR>          events-to-array
26.07.2016  18:11    <DIR>          exec-sh
26.07.2016  18:10    <DIR>          exists-sync
26.07.2016  18:10    <DIR>          exit
26.07.2016  18:12    <DIR>          exit-hook
26.07.2016  18:11    <DIR>          express
26.07.2016  18:12    <DIR>          extend
26.07.2016  18:12    <DIR>          extsprintf
26.07.2016  18:10    <DIR>          fast-ordered-set
26.07.2016  18:10    <DIR>          fast-sourcemap-concat
26.07.2016  18:11    <DIR>          faye-websocket
26.07.2016  18:11    <DIR>          fb-watchman
26.07.2016  18:11    <DIR>          figures
26.07.2016  18:11    <DIR>          filesize
26.07.2016  18:12    <DIR>          finalhandler
26.07.2016  18:11    <DIR>          findup
26.07.2016  18:11    <DIR>          findup-sync
26.07.2016  18:12    <DIR>          fireworm
26.07.2016  18:12    <DIR>          forever-agent
26.07.2016  18:12    <DIR>          form-data
26.07.2016  18:12    <DIR>          forwarded
26.07.2016  18:11    <DIR>          fresh
26.07.2016  18:11    <DIR>          fs-extra
26.07.2016  18:11    <DIR>          fs-monitor-stack
26.07.2016  18:11    <DIR>          fs-readdir-recursive
26.07.2016  18:11    <DIR>          fs-tree-diff
26.07.2016  18:10    <DIR>          fs.realpath
26.07.2016  18:12    <DIR>          gauge
26.07.2016  18:12    <DIR>          generate-function
26.07.2016  18:12    <DIR>          generate-object-property
26.07.2016  18:11    <DIR>          get-caller-file
26.07.2016  18:12    <DIR>          get-stdin
26.07.2016  18:12    <DIR>          getpass
26.07.2016  18:10    <DIR>          git-repo-info
26.07.2016  18:10    <DIR>          git-repo-version
26.07.2016  18:10    <DIR>          git-tools
26.07.2016  18:12    <DIR>          glob
26.07.2016  18:11    <DIR>          globals
26.07.2016  18:11    <DIR>          graceful-fs
26.07.2016  18:12    <DIR>          graceful-readlink
26.07.2016  18:13    <DIR>          growly
26.07.2016  18:11    <DIR>          handlebars
26.07.2016  18:12    <DIR>          har-validator
26.07.2016  18:10    <DIR>          has-ansi
26.07.2016  18:12    <DIR>          has-binary
26.07.2016  18:10    <DIR>          has-color
26.07.2016  18:13    <DIR>          has-cors
26.07.2016  18:12    <DIR>          has-unicode
26.07.2016  18:10    <DIR>          hash-for-dep
26.07.2016  18:12    <DIR>          hawk
26.07.2016  18:12    <DIR>          hoek
26.07.2016  18:11    <DIR>          home-or-tmp
26.07.2016  18:11    <DIR>          hosted-git-info
26.07.2016  18:10    <DIR>          htmlparser2
26.07.2016  18:12    <DIR>          http-errors
26.07.2016  18:11    <DIR>          http-proxy
26.07.2016  18:12    <DIR>          http-signature
26.07.2016  18:12    <DIR>          iconv-lite
26.07.2016  18:11    <DIR>          imurmurhash
26.07.2016  18:12    <DIR>          indexof
26.07.2016  18:11    <DIR>          inflection
26.07.2016  18:10    <DIR>          inflight
26.07.2016  18:10    <DIR>          inherits
26.07.2016  18:12    <DIR>          inline-source-map-comment
26.07.2016  18:11    <DIR>          inquirer
26.07.2016  18:13    <DIR>          invert-kv
26.07.2016  18:12    <DIR>          ipaddr.js
26.07.2016  18:11    <DIR>          is-buffer
26.07.2016  18:12    <DIR>          is-finite
26.07.2016  18:12    <DIR>          is-fullwidth-code-point
26.07.2016  18:11    <DIR>          is-git-url
26.07.2016  18:11    <DIR>          is-integer
26.07.2016  18:12    <DIR>          is-my-json-valid
26.07.2016  18:11    <DIR>          is-obj
26.07.2016  18:13    <DIR>          is-property
26.07.2016  18:12    <DIR>          is-stream
26.07.2016  18:12    <DIR>          is-type
26.07.2016  18:12    <DIR>          is-typedarray
26.07.2016  18:10    <DIR>          is-utf8
26.07.2016  18:12    <DIR>          isarray
26.07.2016  18:11    <DIR>          isbinaryfile
26.07.2016  18:12    <DIR>          isexe
26.07.2016  18:12    <DIR>          isstream
26.07.2016  18:10    <DIR>          istextorbinary
26.07.2016  18:11    <DIR>          js-tokens
26.07.2016  18:12    <DIR>          js-yaml
26.07.2016  18:12    <DIR>          jsesc
26.07.2016  18:10    <DIR>          jshint
26.07.2016  18:12    <DIR>          json-schema
26.07.2016  18:10    <DIR>          json-stable-stringify
26.07.2016  18:12    <DIR>          json-stringify-safe
26.07.2016  18:12    <DIR>          json3
26.07.2016  18:11    <DIR>          json5
26.07.2016  18:12    <DIR>          jsonfile
26.07.2016  18:10    <DIR>          jsonify
26.07.2016  18:12    <DIR>          jsonpointer
26.07.2016  18:12    <DIR>          jsprim
26.07.2016  18:11    <DIR>          kind-of
26.07.2016  18:10    <DIR>          klassy
26.07.2016  18:12    <DIR>          klaw
26.07.2016  18:11    <DIR>          lazy-cache
26.07.2016  18:13    <DIR>          lcid
26.07.2016  18:11    <DIR>          leek
26.07.2016  18:12    <DIR>          leven
26.07.2016  18:12    <DIR>          linkify-it
26.07.2016  18:11    <DIR>          livereload-js
26.07.2016  18:10    <DIR>          loader.js
26.07.2016  18:11    <DIR>          lodash
26.07.2016  18:11    <DIR>          lodash.assign
26.07.2016  18:13    <DIR>          lodash.clonedeep
26.07.2016  18:12    <DIR>          lodash.debounce
26.07.2016  18:12    <DIR>          lodash.flatten
26.07.2016  18:12    <DIR>          lodash.isarguments
26.07.2016  18:12    <DIR>          lodash.isarray
26.07.2016  18:12    <DIR>          lodash.isplainobject
26.07.2016  18:12    <DIR>          lodash.istypedarray
26.07.2016  18:12    <DIR>          lodash.keys
26.07.2016  18:12    <DIR>          lodash.keysin
26.07.2016  18:11    <DIR>          lodash.merge
26.07.2016  18:10    <DIR>          lodash.omit
26.07.2016  18:12    <DIR>          lodash.restparam
26.07.2016  18:12    <DIR>          lodash.toplainobject
26.07.2016  18:10    <DIR>          lodash.uniq
26.07.2016  18:12    <DIR>          lodash._arraycopy
26.07.2016  18:12    <DIR>          lodash._arrayeach
26.07.2016  18:12    <DIR>          lodash._baseassign
26.07.2016  18:13    <DIR>          lodash._baseclone
26.07.2016  18:12    <DIR>          lodash._basecopy
26.07.2016  18:12    <DIR>          lodash._baseflatten
26.07.2016  18:12    <DIR>          lodash._basefor
26.07.2016  18:12    <DIR>          lodash._bindcallback
26.07.2016  18:12    <DIR>          lodash._createassigner
26.07.2016  18:12    <DIR>          lodash._getnative
26.07.2016  18:12    <DIR>          lodash._isiterateecall
26.07.2016  18:11    <DIR>          longest
26.07.2016  18:12    <DIR>          lru-cache
26.07.2016  18:10    <DIR>          make-array
26.07.2016  18:12    <DIR>          makeerror
26.07.2016  18:11    <DIR>          markdown-it
26.07.2016  18:11    <DIR>          markdown-it-terminal
26.07.2016  18:13    <DIR>          marked
26.07.2016  18:13    <DIR>          marked-terminal
26.07.2016  18:10    <DIR>          matcher-collection
26.07.2016  18:10    <DIR>          md5-hex
26.07.2016  18:10    <DIR>          md5-o-matic
26.07.2016  18:12    <DIR>          mdurl
26.07.2016  18:12    <DIR>          media-typer
26.07.2016  18:11    <DIR>          memory-streams
26.07.2016  18:10    <DIR>          merge
26.07.2016  18:11    <DIR>          merge-defaults
26.07.2016  18:11    <DIR>          merge-descriptors
26.07.2016  18:11    <DIR>          methods
26.07.2016  18:11    <DIR>          mime
26.07.2016  18:13    <DIR>          mime-db
26.07.2016  18:12    <DIR>          mime-types
26.07.2016  18:11    <DIR>          minimatch
26.07.2016  18:13    <DIR>          minimist
26.07.2016  18:10    <DIR>          mkdirp
26.07.2016  18:11    <DIR>          mktemp
26.07.2016  18:10    <DIR>          moment
26.07.2016  18:10    <DIR>          moment-timezone
26.07.2016  18:11    <DIR>          morgan
26.07.2016  18:11    <DIR>          mout
26.07.2016  18:10    <DIR>          ms
26.07.2016  18:12    <DIR>          mustache
26.07.2016  18:12    <DIR>          mute-stream
26.07.2016  18:12    <DIR>          negotiator
26.07.2016  18:13    <DIR>          node-emoji
26.07.2016  18:12    <DIR>          node-fetch
26.07.2016  18:12    <DIR>          node-int64
26.07.2016  18:11    <DIR>          node-modules-path
26.07.2016  18:12    <DIR>          node-notifier
26.07.2016  18:11    <DIR>          node-uuid
26.07.2016  18:14    <DIR>          node_modules
26.07.2016  18:10    <DIR>          nopt
26.07.2016  18:11    <DIR>          npm
26.07.2016  18:11    <DIR>          npm-git-info
26.07.2016  18:11    <DIR>          npm-package-arg
26.07.2016  18:12    <DIR>          npmlog
26.07.2016  18:12    <DIR>          number-is-nan
26.07.2016  18:12    <DIR>          oauth-sign
26.07.2016  18:11    <DIR>          object-assign
26.07.2016  18:12    <DIR>          object-component
26.07.2016  18:11    <DIR>          on-finished
26.07.2016  18:11    <DIR>          on-headers
26.07.2016  18:10    <DIR>          once
26.07.2016  18:12    <DIR>          onetime
26.07.2016  18:11    <DIR>          optimist
26.07.2016  18:13    <DIR>          options
26.07.2016  18:11    <DIR>          ora
26.07.2016  18:11    <DIR>          os-homedir
26.07.2016  18:13    <DIR>          os-locale
26.07.2016  18:10    <DIR>          os-tmpdir
26.07.2016  18:11    <DIR>          osenv
26.07.2016  18:11    <DIR>          output-file-sync
26.07.2016  18:10             1.140 package.json
26.07.2016  18:13    <DIR>          parsejson
26.07.2016  18:13    <DIR>          parseqs
26.07.2016  18:12    <DIR>          parseuri
26.07.2016  18:11    <DIR>          parseurl
26.07.2016  18:11    <DIR>          path-exists
26.07.2016  18:10    <DIR>          path-is-absolute
26.07.2016  18:10    <DIR>          path-posix
26.07.2016  18:11    <DIR>          path-to-regexp
26.07.2016  18:12    <DIR>          pinkie
26.07.2016  18:12    <DIR>          pinkie-promise
26.07.2016  18:11    <DIR>          portfinder
26.07.2016  18:12    <DIR>          printf
26.07.2016  18:11    <DIR>          private
26.07.2016  18:12    <DIR>          process-nextick-args
26.07.2016  18:11    <DIR>          process-relative-require
26.07.2016  18:10    <DIR>          promise-map-series
26.07.2016  18:11    <DIR>          proxy-addr
26.07.2016  18:12    <DIR>          pseudomap
26.07.2016  18:10    <DIR>          public
26.07.2016  18:12    <DIR>          q
26.07.2016  18:12    <DIR>          qs
26.07.2016  18:10    <DIR>          quick-temp
26.07.2016  18:10    <DIR>          qunitjs
26.07.2016  18:11    <DIR>          range-parser
26.07.2016  18:12    <DIR>          raw-body
26.07.2016  18:12    <DIR>          readable-stream
26.07.2016  18:11    <DIR>          readline2
26.07.2016  18:10             1.340 README.md
26.07.2016  18:13    <DIR>          recast
26.07.2016  18:12    <DIR>          redeyed
26.07.2016  18:12    <DIR>          regenerate
26.07.2016  18:11    <DIR>          regenerator
26.07.2016  18:11    <DIR>          regexpu
26.07.2016  18:12    <DIR>          regjsgen
26.07.2016  18:12    <DIR>          regjsparser
26.07.2016  18:11    <DIR>          repeat-string
26.07.2016  18:11    <DIR>          repeating
26.07.2016  18:11    <DIR>          request
26.07.2016  18:11    <DIR>          requires-port
26.07.2016  18:10    <DIR>          resolve
26.07.2016  18:11    <DIR>          restore-cursor
26.07.2016  18:10    <DIR>          right-align
26.07.2016  18:11    <DIR>          rimraf
26.07.2016  18:11    <DIR>          rsvp
26.07.2016  18:11    <DIR>          run-async
26.07.2016  18:11    <DIR>          rx-lite
26.07.2016  18:11    <DIR>          sane
26.07.2016  18:11    <DIR>          semver
26.07.2016  18:11    <DIR>          send
26.07.2016  18:11    <DIR>          serve-static
26.07.2016  18:12    <DIR>          set-blocking
26.07.2016  18:12    <DIR>          setprototypeof
26.07.2016  18:11    <DIR>          shebang-regex
26.07.2016  18:10    <DIR>          shelljs
26.07.2016  18:13    <DIR>          shellwords
26.07.2016  18:11    <DIR>          sigmund
26.07.2016  18:12    <DIR>          signal-exit
26.07.2016  18:10    <DIR>          silent-error
26.07.2016  18:12    <DIR>          simple-fmt
26.07.2016  18:12    <DIR>          simple-is
26.07.2016  18:11    <DIR>          slash
26.07.2016  18:11    <DIR>          slide
26.07.2016  18:12    <DIR>          sntp
26.07.2016  18:12    <DIR>          socket.io
26.07.2016  18:12    <DIR>          socket.io-adapter
26.07.2016  18:12    <DIR>          socket.io-client
26.07.2016  18:12    <DIR>          socket.io-parser
26.07.2016  18:12    <DIR>          source-map
26.07.2016  18:11    <DIR>          source-map-support
26.07.2016  18:10    <DIR>          source-map-url
26.07.2016  18:10    <DIR>          spawnback
26.07.2016  18:12    <DIR>          sprintf-js
26.07.2016  18:10    <DIR>          sri-toolbox
26.07.2016  18:12    <DIR>          sshpk
26.07.2016  18:13    <DIR>          st019.testum.company_4873
26.07.2016  18:12    <DIR>          stable
26.07.2016  18:12    <DIR>          statuses
26.07.2016  18:11    <DIR>          string-width
26.07.2016  18:12    <DIR>          stringmap
26.07.2016  18:12    <DIR>          stringset
26.07.2016  18:12    <DIR>          stringstream
26.07.2016  18:11    <DIR>          string_decoder
26.07.2016  18:10    <DIR>          strip-ansi
26.07.2016  18:10    <DIR>          strip-bom
26.07.2016  18:10    <DIR>          strip-json-comments
26.07.2016  18:12    <DIR>          styled_string
26.07.2016  18:12    <DIR>          sum-up
26.07.2016  18:10    <DIR>          supports-color
26.07.2016  18:10    <DIR>          symlink-or-copy
26.07.2016  18:12    <DIR>          sync-exec
26.07.2016  18:12    <DIR>          tap-parser
26.07.2016  18:11    <DIR>          temp
26.07.2016  18:11    <DIR>          testem
26.07.2016  18:10               237 testem.js
26.07.2016  18:10    <DIR>          tests
26.07.2016  18:10    <DIR>          textextensions
26.07.2016  18:11    <DIR>          through
26.07.2016  18:11    <DIR>          tiny-lr
26.07.2016  18:10    <DIR>          tmp
26.07.2016  18:12    <DIR>          tmpl
26.07.2016  18:12    <DIR>          to-array
26.07.2016  18:11    <DIR>          to-fast-properties
26.07.2016  18:12    <DIR>          tough-cookie
26.07.2016  18:11    <DIR>          tree-sync
26.07.2016  18:11    <DIR>          trim-right
26.07.2016  18:11    <DIR>          try-resolve
26.07.2016  18:12    <DIR>          tryor
26.07.2016  18:12    <DIR>          tunnel-agent
26.07.2016  18:11    <DIR>          type-is
26.07.2016  18:12    <DIR>          uc.micro
26.07.2016  18:10    <DIR>          uglify-js
26.07.2016  18:10    <DIR>          uglify-to-browserify
26.07.2016  18:13    <DIR>          ultron
26.07.2016  18:12    <DIR>          underscore
26.07.2016  18:11    <DIR>          underscore.string
26.07.2016  18:12    <DIR>          unpipe
26.07.2016  18:11    <DIR>          untildify
26.07.2016  18:12    <DIR>          user-home
26.07.2016  18:12    <DIR>          utf8
26.07.2016  18:12    <DIR>          util-deprecate
26.07.2016  18:11    <DIR>          utils-merge
26.07.2016  18:11    <DIR>          uuid
26.07.2016  18:11    <DIR>          vary
26.07.2016  18:10    <DIR>          vendor
26.07.2016  18:12    <DIR>          verror
26.07.2016  18:10    <DIR>          walk-sync
26.07.2016  18:11    <DIR>          walker
26.07.2016  18:11    <DIR>          watch
26.07.2016  18:12    <DIR>          websocket-driver
26.07.2016  18:12    <DIR>          websocket-extensions
26.07.2016  18:12    <DIR>          which
26.07.2016  18:12    <DIR>          wide-align
26.07.2016  18:13    <DIR>          window-size
26.07.2016  18:12    <DIR>          wordwrap
26.07.2016  18:10    <DIR>          wrappy
26.07.2016  18:11    <DIR>          write-file-atomic
26.07.2016  18:12    <DIR>          ws
26.07.2016  18:11    <DIR>          xdg-basedir
26.07.2016  18:12    <DIR>          xmldom
26.07.2016  18:13    <DIR>          xmlhttprequest-ssl
26.07.2016  18:12    <DIR>          xtend
26.07.2016  18:13    <DIR>          y18n
26.07.2016  18:12    <DIR>          yallist
26.07.2016  18:11    <DIR>          yam
26.07.2016  18:12    <DIR>          yargs
26.07.2016  18:13    <DIR>          yeast
26.07.2016  18:14    <DIR>          _locks
              12 Datei(en),          5.678 Bytes
             558 Verzeichnis(se),  1.292.218.368 Bytes frei

```

... reproduced with:

```
T:\>ember version --verbose
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64
```

**Comment by nathanhammond** [comment] 2016-07-26 17:14
@jnfingerle I can't reproduce this on a Mac. Without corroborating reports for the entire lifecycle of 2.6 I have to assume that this is an issue which is unique to your machine. As a workaround you can do this:

```
ember new --skip-npm my-cool-test-project
cd my-cool-test-project
npm install
```

I'm closing this issue, but if you discover why it is failing let us know!

**Closed by nathanhammond** 2016-07-26 17:14 UTC

**Comment by kellyselden** [comment] 2016-07-26 17:42
just tried on windows ember cli 2.7.0, could not reproduce.

**Comment by jnfingerle** [comment] 2016-07-26 19:21
@kellyselden Did you use the same node.js as I did? If not, would it be possible for you to try to reproduce it on node 6.3.1?

**Comment by kellyselden** [comment] 2016-07-26 19:30
@jnfingerle yes, node 6.3.1, npm 3.10.3

**Comment by jnfingerle** [comment] 2016-07-27 10:28
Ok, I've re-installed everything, and now it works as expected. Thanks for your help.
