### ISSUE TITLE
Feature: Live reload for apps not being served with `ember serve`

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli#6367] opened 2016-10-20 13:06 UTC
I use `ember build --watch`, instead of `ember serve`

The output of which is served independently from ember-cli - it therefore lacks the injected live-reload script.

It would be great if there was a way to get this to work, it might even already be possible (but undocumented?)

Thanks

**Comment by stefanpenner** [comment] 2016-10-20 18:48
Why not just use serve?

**Comment by amk221** [comment] 2016-10-20 22:05
I didn't realise `--output-path` worked with `ember serve`. I will try that.

**Comment by nathanhammond** [comment] 2016-10-20 22:38
I'm closing this issue as not a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. Slack is _likely_ better for this type of question.

**Closed by nathanhammond** 2016-10-20 22:38 UTC
