### ISSUE TITLE
LocationType hash refreshing to root URL

### ISSUE THREAD

**Issue by wayneiny** [ember-cli/ember-cli#6130] opened 2016-07-29 17:29 UTC
Hi I set my locationType in config/environment.js to hash. 

Now it won't produce a 404 when I refresh on a non-index route. However, when I refresh, it always directs me to root URL. 

Is that the intended design? Thanks in advance.

**Comment by nathanhammond** [comment] 2016-07-29 23:39
@wayneiny Can you please provide a repository for this issue? I'm not entirely sure what you're trying to explain. If you can provide a repository and a set of instructions on how to reproduce _exactly_ what you're experiencing we will be able to tell you whether or not that is expected behavior.

I'm closing this issue as likely not a bug but _please feel encouraged to reopen it_ once you have the reproduction created. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

You can also stop by [#help](https://embercommunity.slack.com/messages/help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and see if any of the wonderful people in our community can work with you to track down the behavior.

Thank you for filing an issue!

**Closed by nathanhammond** 2016-07-29 23:39 UTC
